### ISSUE TITLE
Hide cursor on Wayland

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1019]
According to @vberger, it is possible to hide the cursor on Wayland, so the comment [here](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/linux/wayland/window.rs#L288) is not accurate anymore.

I'm not sure about other cursor features, but at least setting visibility on Wayland can be supported now, so this should be useful to track its implementation.

I'd assume that it might also be a relatively simple implementation, so this might be a good first issue? I'm not familiar with Wayland but I can't imagine this being super complicated if the APIs exist already.

**Comment by vberger** [comment]
The relevant tool in SCTK is there : https://docs.rs/smithay-client-toolkit/0.6.3/smithay_client_toolkit/pointer/index.html

It is the API used to change the cursor icon, hiding it being just assigning an empty icon.

**Comment by kchibisov** [comment]
Should be closed by  #1180
