### ISSUE TITLE
Missing platforms on docs.rs

### ISSUE THREAD

**Issue by felixrabe** [rust-windowing/winit#1028]
For some reason, https://docs.rs/winit (0.20.0-alpha1) only provides the following platforms in the "Platform" dropdown menu:

- i686-windows-pc-msvc
- x86_64-windows-pc-msvc
- x86_64-unknown-linux-gnu

Obviously, there's more missing, but I dearly miss macOS stuff.

**Comment by Osspial** [comment]
I'm unable to find the docs.rs logs for this. Does anyone know where you'd look to see what's going on here?

**Comment by ryanisaacg** [comment]
The mac logs are appearing now, and docs.rs is using a new architecture iirc. Should we close this because it affects an older alpha release?

**Comment by simlay** [comment]
Having iOS (and probably android) platform docs would also be quite useful as well I think. The mobile ecosystem is slowly growing (https://github.com/hecrj/iced/pull/57)

**Comment by Osspial** [comment]
@ryanisaacg Let's leave this open, since the docs currently aren't generated for mobile or the web.

Does anyone know of any way to have docs.rs generate docs for mobile and the web? I'm not entirely sure that's possible right now.

**Comment by ryanisaacg** [comment]
I don't think we can convince it to? Another option would be a github pages branch on winit's repo with custom-built docs, but that would be a fair bit of effort.

**Comment by simlay** [comment]
Looks like according to https://github.com/rust-lang/docs.rs/issues/343 there are currently only 6 targets supported (none of which are Android, iOS or WASM) for which docs are built. Though, it looks https://github.com/rust-lang/docs.rs/pull/346 adds support for a `extra_targets` so, that in theory would conveniently allow for mobile and web docs when it's landed and deployed.

**Comment by jyn514** [comment]
Also we have a default platform limit of 10, but we can raise that if you have a use-case for more platforms.

**Comment by simlay** [comment]
So, I looked into getting more of the docs built. Currently on docs.rs, the builds are the default (`i686-pc-windows-msvc`, `x86_64-pc-windows-msvc`, `x86_64-unknown-linux-gnu`, and `x86_64-apple-darwin`) which is everything except `i686-unknown-linux-gnu` at least according to the GUI.

Here's the [build log trace](https://gist.github.com/simlay/19e7972ca6ed35301033416c8faba9c3) for `i686-unknown-linux-gnu`. Due to the layers of docker, I'm not really sure what it's missing. 

I also looked into `aarch64-apple-ios` and `x86_64-apple-ios` targets. The error that pops up is:
```
2020/04/03 19:32:11 [INFO] rustwide::cmd: running `"docker" "start" "-a" "2618d17a6802c9bbd798be303ed78d2fd6b3a385d65a390dc1e5e4654a544fc2"`
2020/04/03 19:32:12 [INFO] rustwide::cmd: [stderr] error: failed to run `rustc` to learn about target-specific information
2020/04/03 19:32:12 [INFO] rustwide::cmd: [stderr]
2020/04/03 19:32:12 [INFO] rustwide::cmd: [stderr] Caused by:
2020/04/03 19:32:12 [INFO] rustwide::cmd: [stderr]   process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target x86_64-apple-ios --crate-type bin --crate-type rlib --crate-typ
e dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
2020/04/03 19:32:12 [INFO] rustwide::cmd: [stderr] --- stderr
2020/04/03 19:32:12 [INFO] rustwide::cmd: [stderr] error: Error loading target specification: failed to get iphonesimulator SDK path: No such file or directory (os error 2)
2020/04/03 19:32:12 [INFO] rustwide::cmd: [stderr]   |
2020/04/03 19:32:12 [INFO] rustwide::cmd: [stderr]   = help: Use `--print target-list` for a list of built-in targets
```

This is because [`rustc` needs `xcrun`](https://github.com/rust-lang/rust/blob/f6fe99c798cb65280a9a56f442b371adcb7b8aa2/src/librustc_target/spec/apple_sdk_base.rs#L70) to set the `-isysroot` for the linker. I'm guessing that `x86_64-apple-darwin` doesn't need the `-sysroot` param because that's the default but that's a different topic.

Anyway, I've gotten `wasm32-unknown-unkown` to work, so I'll submit a PR for that and add explicit targets to the list.

I'll let someone else look into android stuff.

> Also we have a default platform limit of 10, but we can raise that if you have a use-case for more platforms.

It seems that the GUI doesn't populate more than 4 for me? If I specify more than 4 targets, a random subset seems to not be there. I'll file a bug with docs.rs.

**Comment by jyn514** [comment]
> Here's the build log trace for i686-unknown-linux-gnu. Due to the layers of docker, I'm not really sure what it's missing.

The relevant error message is
```
2020/04/03 19:20:11 [INFO] rustwide::cmd: [stderr] running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m32" "-march=i686" "-Wall" "-Wextra" "-o" "/opt/rust
wide/target/i686-unknown-linux-gnu/debug/build/libloading-50b7866e56dc9b12/out/src/os/unix/global_static.o" "-c" "src/os/unix/global_static.c"
2020/04/03 19:20:11 [INFO] rustwide::cmd: [stderr] cargo:warning=In file included from /usr/include/pthread.h:21:0,
2020/04/03 19:20:11 [INFO] rustwide::cmd: [stderr] cargo:warning=                 from src/os/unix/global_static.c:1:
2020/04/03 19:20:11 [INFO] rustwide::cmd: [stderr] cargo:warning=/usr/include/features.h:424:12: fatal error: sys/cdefs.h: No such file or directory
2020/04/03 19:20:11 [INFO] rustwide::cmd: [stderr] cargo:warning= #  include <sys/cdefs.h>
2020/04/03 19:20:11 [INFO] rustwide::cmd: [stderr] cargo:warning=            ^~~~~~~~~~~~~
```
(we could probably work on trimming down how much we log)

From a quick google, it looks like docs.rs [needs to have `gcc-multilib` installed](https://askubuntu.com/questions/470796/fatal-error-sys-cdefs-h-no-such-file-or-directory) to cross-compile for x32? You could add that in a [PR to crates-build-env](https://rust-lang.github.io/rust-forge/docs-rs/add-dependencies.html).

> This is because rustc needs xcrun to set the -isysroot for the linker. I'm guessing that x86_64-apple-darwin doesn't need the -sysroot param because that's the default but that's a different topic.

It looks like xcrun is a MacOS-only tool? There's probably not a way to install it in the build environment then unfortunately, we only have packages in the Ubuntu 18.04 repository.

> It seems that the GUI doesn't populate more than 4 for me? If I specify more than 4 targets, a random subset seems to not be there. I'll file a bug with docs.rs.

Oh, that is a bug. Let me look into that.
