### ISSUE TITLE
X11: WindowEvent::Resized triggered continuously after resize

### ISSUE THREAD

**Issue by rukai** [rust-windowing/winit#1051]
WindowEvent::Resized is being triggered continuously after the user has finished resizing the window. It eventually stops sometimes but not sure whats causing it to stop.

**Comment by ZeGentzy** [comment]
https://github.com/rust-windowing/winit/issues/1041

**Comment by rukai** [comment]
The issue only occurs when drawing on the RedrawRequested event.
Redrawing on EventsCleared is fine.
Please refer to this example https://github.com/rukai/gfx/blob/winit-0.20.0/examples/colour-uniform/main.rs

**Comment by ZeGentzy** [comment]
Yeah, I'd wait till #1041 gets ironed out, and then see if this is still an issue. Appoligies, my 5 character answer from 2 days ago wasn't really helpful.

**Comment by aloucks** [comment]
I sometimes see a few `Resized` events come though while catching up, but not continuously.

I was testing `0.20.0-alpha2` using this: https://github.com/aloucks/vki/blob/master/examples/triangle_multisample.rs

**Comment by ZeGentzy** [comment]
@rukai Can you retest this against the `redraw-requested-2.0` branch? It's only been implemented for X11 so far, so Wayland should panic, but it might be resolving this issue.

**Comment by rukai** [comment]
Yep, that fixes it!
