### ISSUE TITLE
Events Loop 2.0: Why not use setjmp/longjmp?

### ISSUE THREAD

**Issue by cheako** [rust-windowing/winit#1056]
https://users.rust-lang.org/t/using-setjmp-longjmp-intrinsics-or-is-there-another-way/9350/34
```
// App
main() {
  bool running;
  while running {
    poll();
    You've seen this and know what it looks like.
  }
}

// Library
static mut App2Lib: Checkpoint;
static mut Lib2App: Checkpoint;

poll() {
  if setjmp(Lib2App) {
   return; 
  }

  static bool init = true;
  if init {
    init = false;
    Setup the event loop.
    run()
    signal that the event loop returned.  ??Emit our own event??
  } else {
    longjmp(App2Lib); /* This jumps you in and out of there OS event loop, like goto() we don;t expect to recv a return. */
    // Since we are altering the stack frame it LOOKS like we are just returning, but in fact this is virtual.
  }
}

run() {
  loop /* The system event loop */ {
    if setjmp(App2Lib) {
      gather and emit the event data that app will read.
      longjmp(Lib2App);
    }
    handle system event loop.
  }
}
```

**Comment by mickvangelderen** [comment]
Just out of curiosity, what would setjmp/longjmp allow us to do specifically? What current code could be improved?

**Comment by cheako** [comment]
It keeps the previous API intact.  The pseudo code demonstrates a wrapper around the proposed API.

I now see that winit is meant to support WASM, where it would be difficult to save/restore the frame.

**Comment by Osspial** [comment]
It's also worth noting that [using `setjmp`/`longjmp` in Windows callbacks is explicitly prohibited](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/longjmp?view=vs-2019), which makes it impossible to do on Windows. That, combined with WASM support, `Drop` handling (`setjmp`/`longjmp` are implemented via exceptions on Windows, which I believe would call `drop`s in Rust), and general coding principles makes this impossible to implement.

Given those, I'm going to close this issue. Feel free to re-open it if you think your question wasn't satisfactorily answered.

**Comment by ZeGentzy** [comment]
And then Osspial forgets to close the issue.

**Comment by cheako** [comment]
@Osspial Those would be great points to document.  I find the best comments lean more towards explaining Why.

**Comment by Osspial** [comment]
@cheako Perhaps as internal or out-of-source-tree documentation. I don't want to have that in the public API docs, since I think the exact technical details of why we *didn't* do something get in the way of understanding how the current thing we do works.
