### ISSUE TITLE
`new_user_event` should be renamed to `new_with_user_events` or something like that.

### ISSUE THREAD

**Issue by cheako** [rust-windowing/winit#1057]
new_user_event sounds like a helper to create/emit user events, not something one should call to create an event loop.

**Comment by ZeGentzy** [comment]
Yeah, `new_user_event` is a bad name.

**Comment by Osspial** [comment]
👍. If you submit a PR implementing this it should get merged pretty quickly.

**Comment by briankabiro** [comment]
I can take a look at this if that's okay with you, @cheako. Don't want to impose. :)

**Comment by cheako** [comment]
@briankabiro go ahead.

**Comment by aloucks** [comment]
`with_user_event` would be more inline with rust naming conventions.

**Comment by briankabiro** [comment]
Thanks, @cheako. 

Also updated it to `new_with_user_event` and raised a PR. #1068
