### ISSUE TITLE
run_return example always builds (and fails) for non-desktop platforms

### ISSUE THREAD

**Issue by alasher** [rust-windowing/winit#1064]
Unfortunately it looks like there isn't an easy way to fully exclude the `window_run_return` example for certain platforms, like mobile platforms that don't support EventLoop 2.0. The result is a compilation error when building all examples. I found that we can get it compiling by slapping `cfg` everywhere, but the result is a [really ugly example](https://gist.github.com/alasher/28d6b117d8a57fab478f6ba54e7097e8).

Any better ideas on what to do here? The end goal is to be able to run `cargo build --examples` for all platforms without error.

**Comment by murarth** [comment]
The `#[cfg]` attribute can be removed from the `use` item if you move it inside the body of `fn main`. Then, you only have two `#[cfg]` attributes, which is the best we can do without introducing a dependency on [`cfg_if`](https://crates.io/crates/cfg-if).

Also, the `#[cfg]` for non-desktop platforms would be better formatted as `#[cfg(not(any(target_os = "...", ...)))]`.

It may not be pretty, but it's typical for projects with platform- or feature-guarded APIs to have `#[cfg(...)]` and `#[cfg(not(...))]` pairs of definitions in numerous places.

**Comment by alasher** [comment]
@murarth Thanks for the tips. I can clean it up a little more this evening and submit a PR, any additional thoughts are appreciated as well.
