### ISSUE TITLE
When to draw?

### ISSUE THREAD

**Issue by cheako** [rust-windowing/winit#1069]
#454 #180 
Looks like the Redraw event is only sent rarely when the window should be Redrawn.  When should draw calls be dispatched, for something like a clock showing ms or s or m?

**Comment by ZeGentzy** [comment]
The planned api changes I think explain when the event will be spawned: https://github.com/rust-windowing/winit/issues/1041#issue-466467633

Are you willing to implement it for MacOS, Wayland and/or iOS?

**Comment by aloucks** [comment]
https://docs.rs/winit/0.20.0-alpha2/winit/event/enum.WindowEvent.html#variant.RedrawRequested

https://docs.rs/winit/0.20.0-alpha2/winit/window/struct.Window.html#method.request_redraw

**Comment by ryanisaacg** [comment]
Especially in light of #1529, this should be good to close. Feel free to ask follow-up questions if need be!
