### ISSUE TITLE
Link the documentation of methods in WindowBuilder to it's Window counterpart

### ISSUE THREAD

**Issue by dam4rus** [rust-windowing/winit#1070]
As discussed in #1065 to avoid duplication of documentation, the documentation of WindowBuilder should be linked to Window.

**Comment by crazcalm** [comment]
I was not exactly sure what I was suppose to do in fixing this issue. So i made an attempt based on what I thought was expected.

Let me know if I was wrong and/or if I have to change anything.

Note: I am new to contributing to Rust projects. As such, I have no idea what the standard is for Rust documentation.

**Comment by Osspial** [comment]
@crazcalm Thanks for working on this, and welcome!

#1216 certainly improves on the situation, but I think @dam4rus's intent was to link between individual `WindowBuilder::with_foo` and `Window::set_foo` functions, i.e. have [`WindowBuilder::with_inner_size`](https://docs.rs/winit/0.20.0-alpha3/winit/window/struct.WindowBuilder.html#method.with_inner_size) link to [`Window::set_inner_size`](https://docs.rs/winit/0.20.0-alpha3/winit/window/struct.Window.html#method.set_inner_size). Would you be able to add those links in?

**Comment by crazcalm** [comment]
I think I understand.

In the documentation for WindowBuilder::with_foo, we would like to add a link to Window::set_foo.

Given that my understanding is correct, my current question is:
- Is there a word and/or phrase that already exists in the documentation that I should use to create the link?

For example:
WindowBuilder::with_inner_size docs state, "Requests the window to be of specific dimensions." Should I put the hyperlink on the word "window"?

Side note: I do not have time to get to this immediately, but I should have time this weekend to do it.

**Comment by dam4rus** [comment]
The documentation for [WindowBuilder::with_fullscreen](https://docs.rs/winit/0.20.0-alpha3/winit/window/struct.WindowBuilder.html#method.with_fullscreen) and [Window::set_fullscreen](https://docs.rs/winit/0.20.0-alpha3/winit/window/struct.Window.html#method.set_fullscreen) differs by quite a lot while doing basically the same thing. @ZeGentzy suggested to me while reviewing my PR to link the documentation of one of these methods to the another to avoid confusion and missing information.

**Comment by Osspial** [comment]
@crazcalm I'd take the parts of the documentation that seem most complete, move them into `Window::set_foo`, then modify the `WindowBuilder::with_foo` docs to just be *see `Window::set_foo` for details`*.

**Comment by crazcalm** [comment]
Let me know if I got this wrong, or if there is anything else that I need to change.
