### ISSUE TITLE
Strange lockup, needs testing.

### ISSUE THREAD

**Issue by cheako** [rust-windowing/winit#1079]
I can't show this as a winit bug!  It appeared when I introduced imgui, bringing in a second Vulkan API.
https://gitlab.com/cheako/hazel-rs/commits/9955934b78f05cd31694ff811911bd763b8e4516

* Initial commit: Works, draws a colorful triangle and shows events on the console.
* Introduce imgui: This locks up.  Drawing parts are commented out, should be just the presentation, renderpass, and event logging.
* ...and This exit prevents my machine from locking up.

I have to save this, or I won't be able to keep testing.

**Comment by Osspial** [comment]
Are you sure this is a Winit bug? From what you're describing it sounds like this is an issue with the higher-level libraries you're using, not us.

I'd recommend running in a debugger to get a stack trace of where your code is freezing up. Beyond that, I don't think there's much help we can give. If this isn't a bug in our code I'd suggest closing this issue and either opening a thread in a more relevant location or asking in the Rust discord server: https://discordapp.com/invite/aVESxV8

**Comment by cheako** [comment]
@Osspial Sounds like you didn't read the first few words of my report.

I should have been more clear, by lockup I mean system hangs.  This boils down to another issue with the documentation of the event loop, that's why I think it's a winit bug because otherwise(without the event loop) I'm able to run the same code.

**Comment by ZeGentzy** [comment]
> I should have been more clear, by lockup I mean system hangs.

I mean, if your whole system is hanging, then it's not a winit issue, this is an issue with your OS. I'm sorry, but there is nothing for us to fix.

**Comment by Osspial** [comment]
@cheako I did, and I'm having a hard time figuring out what it's supposed to mean. From my perspective, it looks like you're blindly assuming that we're at fault without bothering to investigate the source of the bug and file a proper, easily digestible bug report.

> This boils down to another issue with the documentation of the event loop

That line doesn't do much to allay my first impressions. Perhaps you've got a more comprehensive explanation in your head, but I have no idea how this relates to Winit's documentation, and you've put no effort into demonstrating that connection to us. Again, it seems like you're blaming us without much concrete evidence, and there aren't a whole lot of actions I can take in that context.

**Comment by cheako** [comment]
@Osspial Blaming you?  I just don't know what to think, so I couldn't possibly come to the conclusion to blame anybody.

> I can't show this as a winit bug!

I don't know what else I can say.  I have autism and this make communicating in English difficult, from my perspective I make perfectly valid grammar that is then processed in the strangest ways.  I therefore usually let code do most of the communicating.  You'll notice my report was quite empty, I documented the code and expected that all other questions could be answered with the available information.

GH lacks a save for later feature so I was prompted to post this issue at that time, else I'd be deleted when I rebooted as a result of continuing to test.  Not that I thought it needed more work, just that I would have liked to try harder/more to solve the problem on my own.

I don't mind opening a new issue every time I have a comment on something, it is kinda useless to have threads the carry on forever over a range of different related topics.  Though if that's what I'm supposed to do then it's only reasonable that new issues will sometimes not be actionable or anyone's fault.  GH doesn't look to have a solution, there is a Wiki but it appears to lack a talk/discussion feature.  Starting up a forum or discord to discuss winit and a broader range of topics might help.

After asking about these symptoms on ```#dri-devel``` it was pointed out that this usually happens when the command buffer hasn't been ended.  Knowing that, things are working now.

**Comment by aloucks** [comment]
Please go back and read some of your prior comments:

> This boils down to another issue with the documentation of the event loop, that's why I think it's a winit bug because otherwise(without the event loop) I'm able to run the same code.

> After asking about these symptoms on #dri-devel it was pointed out that this usually happens when the command buffer hasn't been ended. Knowing that, things are working now.

The issue turned out to be unrelated to winit, which is the same the feedback that was given to you here.

Everyone gets frustrated once and a while and sometimes post things that are a little harsh. It happens. However, your behavior and demeanor has been consistently combative. Not only here, but also in the other github projects that you're posting to. 

I would recommend that you review your posts before you submit them and ask yourself a few questions:

1. Am I truly seeking a solution or am I venting my frustration?
1. Have I ruled out external sources that could contribute to the problem?
1. Have I distilled the problematic code down to the most minimal example possible?
1. Will others be able to understand the problem based on how I've described it?
1. Will others interpret my comments being respectful and polite?
