### ISSUE TITLE
Read Image from Window

### ISSUE THREAD

**Issue by nifker** [rust-windowing/winit#1091]
I'd like to read the RGB data from a Window's current displayed image - is it possible, to be implemented?

**Comment by Osspial** [comment]
This depends on the system you're using to draw to the window, and is out of scope for Winit.

If you're using OpenGL, you can [read from the default framebuffer](https://stackoverflow.com/questions/36843456/read-pixel-data-from-default-framebuffer-in-opengl-performance-of-fbo-vs-pbo). Other APIs should expose similar functionality, but I'm only familiar with OpenGL and can't comment on how it works elsewhere.

Got any followup questions?

**Comment by nifker** [comment]
Ah ok, I was thinking it would be possible to read it from the already rendered window. But I guess thats not supported for all windowing systems.
