### ISSUE TITLE
Reddit link: Success: I have a working setup of ImGui on Vulkan.

### ISSUE THREAD

**Issue by cheako** [rust-windowing/winit#1110]
https://www.reddit.com/r/rust/comments/crb7q7/success_i_have_a_working_setup_of_imgui_on_vulkan/

Please post any comments to the Reddit thread, this was opened as an issue because it's where Winit hosts all it's discussions.

**Comment by ZeGentzy** [comment]
While nice and all, kind of off topic for an issue tracker, no?

**Comment by cheako** [comment]
> While nice and all, kind of off topic for an issue tracker, no?

It would be nice if you'd have read my entire post before replying, thanks.

**Comment by vberger** [comment]
When posting such a link to winit's issue tracker, apparently to bring it to our attention, it would be nice if you could explain why and how it is relevant to winit, especially given your reddit post does not talk about winit at all.

Right now, I fail to see what you are trying to communicate to the winit developers with this link.

Also I believe the discussion of whether this issue should be closed as off-topic or not very much belongs here, and not on reddit.

**Comment by cheako** [comment]
> because it's where Winit hosts all it's discussions.
It's difficult to tell if you read my entire post or if your just ignoring key points.  As it's nice to show off what someones software can do to them, this post is mainly NOT for the developers of winit.  The main audience is ppl wanting to introduce ImGui into their Vulkan projects.

Winit is a target user-base because it's likely that Vulkan projects will target winit.

This issue could be seen as a lacking support infrastructure.  It's important for there to be a Gallery for new users to discover projects similar to their own, if the issue tracker isn't the correct place for this then that's an issue to bring to the developers attention?

As for where is best to discuss things, I still think this belongs in reddit!  For one it draws attention to the fact that this project has some connection to winit, you did complain about a lack of this in my reddit post(why not fix that your self)?  It also is a great way to demonstrate to potential users of winit the conduct of the ppl involved with winit and I think this is the most important point.

It's clear I've been using winit, given the number of issues I've opened.  If I choose something else I'm sure I'd have good reason.

Non-dictatorship ecosystem:
Gallery need not be restricted to winit or even rust, if you want to foster an open and transparent communication platform.  If there is something that competes with winit it wouldn't seem appropriate to ban those projects from using the winit Gallery as a way to compare platforms side by side.

**Comment by ZeGentzy** [comment]
> It's difficult to tell if you read my entire post or if you'r just ignoring key points. 

I can assure you I read it, as it's exactly one sentence long. The post on reddit is exactly 5 sentences long. I can assure you that I am capable of reading 6 sentences. Knowing @vberger, I think they are also capable of reading 6 sentences. Kind of insulting to think we can't read a total of 6 sentences, no? And actually, the reddit post was originally 3 sentences before the edit. So, yes, I assure you I can read 4 sentences.

> [...], this post is mainly NOT for the developers of winit. The main audience is ppl wanting to introduce ImGui into their Vulkan projects.
> [...]
> As for where is best to discuss things, I still think this belongs in reddit!

Right, so it doesn't belong on the issue tracker for winit. This belongs on some sort of blog, or wiki, or something. This is not an issue. You even seam to agree.

> For one it draws attention to the fact that this project has some connection to winit, you did complain about a lack of this in my reddit post(why not fix that your self)?

It's not our job to "fix" other people's reddit posts. We aren't even capable of "fixing" your reddit post. We don't care what you mention in the reddit post. My issue with it is that it appears to be off-topic for winit's issue tracker. Even if it did mention winit, I'd still think it's off-topic for the issue tracker.

> This issue could be seen as a lacking support infrastructure. It's important for there to be a Gallery for new users to discover projects similar to their own, if the issue tracker isn't the correct place for this then that's an issue to bring to the developers attention?

We already have one:
https://github.com/rust-windowing/winit/wiki/Software-that-uses-winit

Arguably, it could be better advertised, and I would agree, however, that is not the issue you brought up. No where did you mention wikis, or galleries, or anything. You just plopped a random link to reddit, and acted aggressive when I questioned you on it's relevance. Granted, my comment was in it self rude, and for that I apologize, but...

@cheako You have continually been off-topic, dismissive and unclear with regards to your postings here, and have been informed of this [time](https://github.com/rust-windowing/winit/issues/1054#issuecomment-516578840) after [time](https://github.com/rust-windowing/winit/issues/1079#issuecomment-516652648) after [time.](https://github.com/rust-windowing/winit/issues/1060#issuecomment-515181621) I find it frustrating tryng to forcefully pry information out of you. It shouldn't take two people posting here to learn that you want a gallery- which we already have- and I shouldn't have to deal with your attitude.

**Comment by cheako** [comment]
@ZeGentzy Again you didn't seem to respond to what I've said.  I pointed out where ppl have responded to points I've already addressed and didn't address my point, just ignoring my point as though it didn't exist.  That's the same as not reading 5 sentences, but has nothing to do with the ability to read 5 sentences.  These are not semantically different they are as different as water and oil.  Going off on a tangent discussing your abilities to read while completely ignoring my assertions that my points were ignore is AGAIN ignoring my points, though I can't tell if you read them or are just ignoring htem.

I fell no compulsion to reply to the rest of what you wrote, as it's mostly you wining about the world I see and isn't productive at all.

**Comment by kchibisov** [comment]
@cheako Unfortunately, I'm little bit dump and can't see your "point". So let's find it out together. Likely to me, your reddit post mostly consists of "oneliners", so the area of searching your point is small.

Let's start our findings (from reddit post)!

> Success: I have a working setup of ImGui on Vulkan.

Cool. Does this sentence express your point? From my point of view it's just: Hey, I did thing X and I find it cool. In case this is your point, what do you want from `winit` folks to do here:

- a) Add your project to [wiki](https://github.com/rust-windowing/winit/wiki/Software-that-uses-winit)
- b) Say that you're cool
- c) Add guide about creating such things

> A minimal example: https://gitlab.com/cheako/simulide-rs/tree/imgui_success_001

Nice, you have an example. In case this is your point, what do you want from `winit` folks to do here:

- a) Create example similar to yours
- b) Say that it's cool to have an example

> As part of a Game Engine Events Framework: https://gitlab.com/cheako/hazel-rs/blob/imgui_success_001/src/imgui.rs

Oh, some integrations. In case this is your point, what do you want from `winit` folks to do here:

- a) Add a more notes that you can use this for gaming purposes
- b) Say that it's cool

> This code makes use of a wrapper around ash(A Vulkan FFI) that is meant to call Vulkan's Destroy methods at the appropriate time: https://docs.rs/ash-tray/0.4.1/src/ash_tray/vk_helper.rs.html

WoW! `Vulkan`! I like `Vulkan`. In case this is your point, what do you want from `winit` folks to do here:

- a) Say that it's cool 
- b) Say that Vulkan is cool

> Edit: I thought these commits were important enough to have tags. I did change these a little, used latest `winit` alpha3, alphabetized something, removed trailing "s" on something that is singular.

Yeah, tagging commits and pushing changes are important nowadays. In case this is your point, what do you want from `winit` folks to do here:

- a) Says that we should do more such things
- b) Say that you're cool

I can't "group" your comments in a different way. In case I didn't covered reply to your "point" in any of the variants above please let me know, I can't read minds at the moment, but I'll develop this in a future to avoid this old style point finding technique. For now let's use "questions" (not an imperative sentences as in your reddit post).

Sorry in advance if this offends you in any way. What goes around, comes around, you know? And please be more respectful to folks here. @ZeGentzy replied to all your questions ( I'll assume that he can't read minds too), as far as I can see. And he wasn't whining, he was pointing that you're acting "bad".

**Comment by ZeGentzy** [comment]
Honestly not in the mood for typing another response. Locking this down before it gets too heated. Will unlock in 24 or 48hrs or so. Cheers!

**Comment by ryanisaacg** [comment]
I think we can close this as off-topic. Thank you for the link though!
