### ISSUE TITLE
[Wayland] Buffer resize occurs one frame after acknowledged resize

### ISSUE THREAD

**Issue by kennylevinsen** [rust-windowing/winit#1119]
During testing of Alacritty, it was observed that one could often provoke "resize glitches" when testing with Sway, where Alacritty would appear at 800x600 for what appeared to be a single frame, then resize to the appropriate size the next frame.

Running Alacritty under WAYLAND_DEBUG=1, one can observe the following behavior:
1. An xdg_surface is created, configured and acked, with no buffer yet available.
2. After initializing zwp_linux_dmabuf_v1, an 800x600 buffer is created, attached and committed.
3. A configure event is received for the xdg_surface, which results in:
    1. set_window_geometry is called with the *new* size
    2. A frame callback is registered
    3. A new buffer is created, with the *old* size (800x600)
    4. The buffer is attached and the surface is committed.
4. Then, on the *next* frame, a new buffer is created yet again, this time with the new size, which is attached and committed.

Even though we clearly acknowledge the changed size, and go through the effort of creating a new buffer, we spend time rendering an additional frame at the wrong resolution.

The issue exists with glutin_examples as well if one observes WAYLAND_DEBUG, but it does not cause the visible glitch.

**Comment by vberger** [comment]
To provide some context to whom may want to tackle it:

The general issue comes from the fact that all platforms but Wayland have a notion of "window size" independent of what is drawn in the window, while in Wayland the dimensions of a window is defined by what is drawn in it.

When a resize occurs, most platforms will thus forcibly resize the window and then notify the app about its new size. Wayland rather notifies the app of a new suggested size, but it's up to the app to actually resize itself (by adjusting the size of the content it draws).

Winit's API however matches the behavior of most platforms, so the semantics of Wayland need to be adapted, and this is likely where the bug likely lies.

What currently happens is:

- When a "configure" event is sent by the server, it is first received & processed by [SCTK](https://github.com/smithay/client-toolkit) which:
  - acks it
  - computes the associated inner size if it is drawing decorations
  - updates the decorations dimensions if necessary
  - forwards it to the downstream app (winit in out case)
- When winit then receives it, it:
  - instructs SCTK to redraw the decorations (if necessary)
  - forwards a `Resized` event to the app
  - inserts a pending `RedrawRequested`

Then, from what I see, when receiving the `Resized` event the glutin `window.rs` example immediately resize the OpenGL context, which is basically what I'd expect be the right thing to do.

But apparently something does not go exactly as it should, and after the resizing of the context, one more buffer is sent with the wrong dimension... ?

**Comment by kchibisov** [comment]
@kennylevinsen would you mind retesting it with latest winit/glutin(alacritty-0.6.0-rc1 should use it). I don't see anything related to what you describe in `WAYLAND_DEBUG=1` logs at all... I only see 800x600 buffer crated once, then I get configure, render with new buffer, drop old buffer.

**Comment by kchibisov** [comment]
During some investigation it was found out that it's sort of expected when using egl, https://gitlab.freedesktop.org/mesa/mesa/-/issues/6547.

The docs for that should likely be under glutin repos, I guess.
