### ISSUE TITLE
libdl link error on BSD

### ISSUE THREAD

**Issue by iquiw** [rust-windowing/winit#1136]
When running `cargo run --example window` on e.g. NetBSD, it throws error `ld: cannot find -ldl`.

[dlopen.rs](https://github.com/rust-windowing/winit/blob/1e7376847b4f65e4e888aa9768329550c6d26a48/src/platform_impl/linux/dlopen.rs) is built for *BSD as well as Linux.
But *BSD does not have libdl (`dlopen`, etc. is contained in libc, or no library is required for it).

Furthermore, `dlopen` seems no longer used?

**Comment by murarth** [comment]
Yes, it certainly appears that the `dlopen` module is unused. I don't know how long it's been unused, but according to [blame](https://github.com/rust-windowing/winit/blame/master/src/platform_impl/linux/dlopen.rs), the `#![allow(dead_code)]` attribute in that file is over 4 years old.

I can't see any reason to keep the module.

**Comment by iquiw** [comment]
Thanks! Works fine.
