### ISSUE TITLE
Abaqus CAE

### ISSUE THREAD

**Issue by sharanrajindia** [rust-windowing/winit#1144]
Dear All,
I have been using Abaqus CAE in my ubuntu 18.04 for the past year or so. It was working very well. Today when I tried to run Abaqus, I got the following error

> X Error: code 158 major 152 minor 6: GLXBadContext.
> [xcb] Unknown sequence number while processing queue
> [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
> [xcb] Aborting, sorry about that.
> ABQcaeK: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
> Abaqus Error: Abaqus/CAE Kernel exited with an error.

Any help to rectify this error is much appreciated.
Thank you.

**Comment by Osspial** [comment]
Hi, and thanks for the bug report! Unfortunately, I think you submitted to the wrong repository - we don't seem to be involved in the Abaqus project. As such,iI'm going to close this. 

Have you tried contacting their customer support?
