### ISSUE TITLE
Set _NET_WM_PID on X11

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1150]
I've just run into some old code in Alacritty, which is used to set the `_NET_WM_PID` attribute on X11. Since I didn't write this, I am curious if it has been discussed whether it should be included in winit or not.

The code in question can be found here:
https://github.com/jwilm/alacritty/blob/master/alacritty_terminal/src/window.rs#L423-L470

It seems like it's largely disconnected from everything else and only needs the PID which winit should have access to. So I think it might be a good addition.

I did not write this code originally, but I believe the purpose of it is to make scripting their WM easier for X11 users. So one could easily get the PID of the focused window for example.

**Comment by Osspial** [comment]
cc @murarth

**Comment by murarth** [comment]
winit already sets the `_NET_WM_PID` property for each new window: https://github.com/rust-windowing/winit/blob/bfcd85ab150d088be254f43870e7d485f6f95348/src/platform_impl/linux/x11/window.rs#L463-L464

**Comment by chrisduerr** [comment]
Oh, my bad. Looks like we've added support for this in Apr 26, 2017, while winit later introduced this in May 20, 2018. Looks like I can delete some code though, thanks!
