### ISSUE TITLE
iOS dpi panic

### ISSUE THREAD

**Issue by m4b** [rust-windowing/winit#1163]
I'm seeing this panic triggered for winit `0.20.0-alpha3` on wgpu 0.3.0 (and current top of tree master):

```
thread '<unnamed>' panicked at 'assertion failed: validate_hidpi_factor(dpi_factor)', /Users/ataraxis/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha3/src/dpi.rs:113:9
```

This only seems to occur on first touch of the iOS application (i.e., it renders fine until I touch it); I print the dpi when window is created or resized, and it returns `3.0` . I don't really know why this would trigger the panic, since I only ever use winit, and don't muck around with it after.

Original issue:
gfx-rs/wgpu#336

Note the master version of wgpu no longer has those gpu issues (but still panics) so I think this is a winit issue.

**Comment by Osspial** [comment]
Could you call the `is_sign_positive` and `is_normal` functions on the value you're passing to the function, and report the values they return? One of them has to be returning `false` to fail the check, but `3.0` shouldn't be failing either of those.

Could you also post the bitwise representation of your float that [`to_bits`](https://doc.rust-lang.org/beta/std/primitive.f64.html#method.to_bits) reports? There's a possibility that there's something fishy going on with the exact representation number that is causing one of the calls to erroneously fail, and having that data would make it easier to check that.

**Comment by m4b** [comment]
Yea, but it’ll take a while. Will have to fork and print just before the panic, etc. just to be clear, im only using functions coming from wgpu, I don’t obtain the value from some other library.

**Comment by m4b** [comment]
ok, I cannot repro this on winit master :( i don't know which commit is the release of `alpha3` (unsolicited advice: `git tag` would be super great here :) ), as I wanted to verify it was _a_ commit. Will see if i can figure out which commit it is...

**Comment by Osspial** [comment]
Looks like it's `31110be3960bb97caeacdd0a8cbad292722f94f1`. Whenever I need to find a specific release commit I usually look at the history for `Cargo.toml`

**Comment by m4b** [comment]
Ok, I can repro on 31110be3960bb97caeacdd0a8cbad292722f94f1

```
dpi_factor: 0 is_sign_positive: true, is normal: false
thread '<unnamed>' panicked at 'assertion failed: validate_hidpi_factor(dpi_factor)', /Users/ataraxis/git/winit/src/dpi.rs:114:9
```

So somehow this got fixed between 57a53bda74fa9a46e7e282d0f857d02048e64353 .. 31110be3960bb97caeacdd0a8cbad292722f94f1

🤷‍♂

**Comment by m4b** [comment]
Is there a chance we can get an alpha4 release sometime soon? No big deal if not :) and thanks for all your work here 😍

**Comment by Osspial** [comment]
@m4b We'll probably do an alpha4 release soonish. There are a few PRs waiting that I'd like to get merged first, though.

I'll close this since it seems the problem was fixed!
