### ISSUE TITLE
Cannot enter unicode characters like emojis on Windows

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1164]
When entering emojis using the Windows emoji picker or the compose sequence, the right unicode character is not sent to the application.

A `ReceivedCharacter` event is triggered, however it seems like there might be issues with UTF-16 and UTF-8 conversion, since it's received as `'\u{d83d}'` and `'\u{de00}'` which is the UTF-16 representation of the chosen emoji (see https://unicode-table.com/de/1F600/).

More details can be found in the Alacritty issue: https://github.com/jwilm/alacritty/issues/2796

**Comment by Osspial** [comment]
I've made a PR addressing this at #1165
