### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by FaultyRAM** [rust-windowing/winit#119]
Surprised nobody's tackled this one yet. We already handle keyboard and mouse input, so gamepad input seems to be the logical next step.

Anyone looking for inspiration might want to see [how SDL2 does this](https://hg.libsdl.org/SDL/file/c2b0d3d180f4/src/joystick): basically they maintain a list of controllers and map them as closely to the XInput layout as possible. That doesn't have to be the strategy we use here, and there is some legacy code in there as well (mainly deprecated Windows APIs like DirectInput), but I think it's a reasonable starting point.

**Comment by tomaka** [comment]
There was already a discussion here: https://github.com/tomaka/glutin/issues/151

Basically it's "won't fix, should be an external library".

**Comment by Osspial** [comment]
Closing in favor of #804. This *is* something we want, but we need help implementing it on other platforms.
