### ISSUE TITLE
Please add `raw-window-handle` support to 0.19 as a patch release.

### ISSUE THREAD

**Issue by Lokathor** [rust-windowing/winit#1202]
Usage of the `raw-window-handle` crate is supported in the 0.20 alpha, but a lot of people aren't using that yet since it's just alpha.

Could we get a patch release to 0.19 that adds `raw-window-handle` support?

**Comment by Osspial** [comment]
I'll see about doing this once `raw-window-handle` `0.3` is released.

**Comment by Lokathor** [comment]
@Osspial 0.3 is out
