### ISSUE TITLE
Opening an xwayland window instead of an wayland window

### ISSUE THREAD

**Issue by AustinJ235** [rust-windowing/winit#1203]
I have been giving wayland a go recently, but with it not supporting cursor grab I can't quite use it for my projects. Is there a way to create a winit window that will instead of going directly to wayland it will instead use xwayland?

**Comment by vberger** [comment]
Cursor grab has been implemented in #1180, and will be in the next alpha release.

In the meantime, you can for the use of x11 by using the `EventLoopExtUnix::new_x11()` method of the unix-specific extension trait of `EventLoop`, or by unsetting the `WAYLAND_DISPLAY` environment variable before initializing winit.

**Comment by ZeGentzy** [comment]
And #1180 was merged!
