### ISSUE TITLE
No character getting received on international keyboard on macOS.

### ISSUE THREAD

**Issue by kchibisov** [rust-windowing/winit#1208]
It was reported to Alacritty that when pressing `Control + Shift + 7` on Norwegian keyboard no characters are getting received. For the reference this keyboard has `/` on `Shift + 7`, so it assumed that it should act like `Shift + Control + 7` on `us` keyboard (I mean it should gets `/` like it gets`&` when on `us`). `Shift + 7` works just fine on this keyboard (sends `/` and getting `Slash` virtual_keycode).

alacritty bug for the reference https://github.com/jwilm/alacritty/issues/2850

**Comment by goddessfreya** [comment]
Related: https://github.com/rust-windowing/winit/issues/812 https://github.com/rust-windowing/winit/issues/753

**Comment by DorianRudolph** [comment]
This also happens in Linux/Wayland. I need to set 
```
{ key: Key7,   mods: Control|Shift, mode: Vi, action: SearchForward           }
```
