### ISSUE TITLE
Window creation hangs on X11 when another application is fullscreen

### ISSUE THREAD

**Issue by Ralith** [rust-windowing/winit#1210]
Most likely happening [here](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/linux/x11/window.rs#L883); it seems like visibility isn't guaranteed to occur at any particular time in this case. Execution resumes once fullscreen is released.

**Comment by murarth** [comment]
I'm unable to reproduce this issue. In my WM, a new window will appear on top of any existing fullscreen window (whether exclusive or borderless). I would say this is the desired behavior, as all calls to Xlib to map the window are made with `XMapRaised`.

If we set that aside, there's an unfortunate conflict: Without waiting for a `VisibilityNotify` event, winit doesn't know whether a window has become visible yet -- only that it wants to be visible. This can cause other issues, e.g. if an application tries to set a window to fullscreen before it is visible, the X server will reply with an error.

We could move the `wait_for_visibility_notify` call to `set_fullscreen` (only if winit hasn't received it already), but this would likely cause the application to hang in a different (albeit less common) situation.

**Comment by Ralith** [comment]
It occurs on i3, for example.

**Comment by OvermindDL1** [comment]
From personal experience it is pretty important to let visibility notification events through.  There are some cases where a window will not be created even though it is requested, especially in automation conditions.  The program itself needs to determine how it wants to handle things.  If a user can call something that can fail if not in the right state, then either the state needs to be encoded in the type system somehow, or those calls need to be failable (`result`?).

**Comment by Ralith** [comment]
Alternatively, perhaps calls that require visibility could have their effects implicitly deferred until visibility occurs?

**Comment by Osspial** [comment]
I'd lean towards returning `Result`. Failing when the requested operation doesn't work is better than implicitly doing something a bit different than the API says to create the illusion that everything is fine.

**Comment by Ralith** [comment]
Returning a result is likely to lead to break applications that try to
fullscreen immediately as they'll be racing with the X server, and
continuously retrying for some ill defined period of time is not a great
thing for applications to be expected to do. If a genuine error occurs,
that should probably be communicated asynchronously via the event loop.

**Comment by OvermindDL1** [comment]
> Returning a result is likely to lead to break applications that try to
fullscreen immediately as they'll be racing with the X server, and
continuously retrying for some ill defined period of time is not a great
thing for applications to be expected to do. 

That's why they should wait until the window is actually created before doing those.  In the mean time the program can be doing other setup stuff.

**Comment by Ralith** [comment]
Adding an event for a window actually becoming mapped or w/e sounds like a
good solution, yeah.

**Comment by murarth** [comment]
I would favor deferring fullscreen until `VisibilityNotify` arrives (within the normal process of event processing) over returning `Result` from `set_fullscreen`.

What would we expect an application to do with an `Err` result? Wait until later? Until when, exactly? If it's not clearly defined what to do with the `Err`, I think application developers will tend to `unwrap` it, which would be treating a temporary error as unrecoverable.

I don't feel that it is hiding an error condition from the application to have `set_fullscreen` unconditionally succeed even if winit can't yet send the fullscreen message to the X server. I feel that it falls within the design of abstracting over platform-specific details, such as the asynchronous nature of the X11 protocol.

**Comment by Ralith** [comment]
It's true that X11 is fundamentally async, and as a result most operations
can fail asynchronously, so deferring things isn't a large divergence from
the underlying semantics.

**Comment by OvermindDL1** [comment]
> What would we expect an application to do with an `Err` result?

I'd expect them to check the docs and see what causes that error, and then realize they are doing it too soon in the lifecycle and move it to the correct event.  ^.^

**Comment by OvermindDL1** [comment]
How about instead of magically deferring such things, what about a specific 'schedule' or 'defer' call, that you can then run a closure in.  There can be various kinds such as when the window is created or so.  If it already exists it runs the closure immediately, else it runs it when it does.  That would be generic over any of them then.

**Comment by Ralith** [comment]
That seems like far too much interface complexity. Either implicitly defer or expose the event that makes the operation legal to the user and let them defer it themselves.

**Comment by OvermindDL1** [comment]
> expose the event that makes the operation legal to the user and let them defer it themselves.

I'd just outright vote for this personally.  Greater control is preferred.  People can make their own helpers and wrappers if they want something more basic (a `winit-light` library for example).  But I would definitely prefer to use the proper lifecycle events as there is other stuff I could be doing to load faster during that time.

**Comment by murarth** [comment]
I've submitted PR #1248 to address this issue, using the solution I proposed above. I feel that the increased internal complexity is minimal and the behavior of the public API methods is essentially unchanged.

**Comment by goddessfreya** [comment]
Interesting, if two windows are created and then the first one becomes fullscreen, if the second window tries to become full screen two things will happen:

1- The first window will stop being fullscreen.
2- and the second window will also panic with: 
```
$ sleep 2; RUST_BACKTRACE=1 cargo run --example window_debug                
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `target/debug/examples/window_debug`
debugging keys:
  (E) Enter exclusive fullscreen
  (G) Toggle borderless fullscreen
  (Q) Quit event loop
  (V) Toggle visibility
  (X) Toggle maximized
gthread 'main' panicked at 'Failed to change window fullscreen state: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 42, minor_code: 0 }', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::expect
             at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libcore/result.rs:960
  16: winit::platform_impl::platform::x11::window::UnownedWindow::set_fullscreen
             at ./src/platform_impl/linux/x11/window.rs:694
  17: winit::platform_impl::platform::Window::set_fullscreen
             at ./src/platform_impl/linux/mod.rs:381
  18: winit::window::Window::set_fullscreen
             at ./src/window.rs:610
  19: window_debug::main::{{closure}}
             at examples/window_debug.rs:71
  20: winit::platform_impl::platform::sticky_exit_callback
             at ./src/platform_impl/linux/mod.rs:693
  21: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at ./src/platform_impl/linux/x11/mod.rs:270
  22: winit::platform_impl::platform::x11::EventLoop<T>::run
             at ./src/platform_impl/linux/x11/mod.rs:389
  23: winit::platform_impl::platform::EventLoop<T>::run
             at ./src/platform_impl/linux/mod.rs:640
  24: winit::event_loop::EventLoop<T>::run
             at ./src/event_loop.rs:148
  25: window_debug::main
             at examples/window_debug.rs:33
  26: std::rt::lang_start::{{closure}}
             at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libstd/rt.rs:61
  27: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  28: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  29: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:79
  30: std::panicking::try
             at src/libstd/panicking.rs:265
  31: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  32: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  33: std::rt::lang_start
             at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libstd/rt.rs:61
  34: main
  35: __libc_start_main
  36: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
