### ISSUE TITLE
Creating a window with platform specific or explicit size

### ISSUE THREAD

**Issue by dhardy** [rust-windowing/winit#1229]
The current winit API gives two options for the size of a created window:

-   use a platform-specific default size (from the code, 800×600 on Linux & Mac, 1024×768 on Windows and web, screen size on mobile platforms)
-   specify the size and/or bounds (currently ignored on Android but apparently used on iOS)

What I want to do is:

1.  start with a default size (platform-specific or hard-coded 800×600 is fine)
2.  if (and only if) the following hold, adjust this default size
    - it is sensible to resize windows (i.e. not mobile platforms)
    - and the UI in question has soft bounds on size

I don't believe this is possible with the current UI — at least, not on iOS, where it would not normally make sense to reduce a window size simply because less space is needed.

Possibly related: #33

**Comment by Osspial** [comment]
Could you use `#[cfg(target_os = "foo")]` to conditionally specify window size?
