### ISSUE TITLE
Application hangs even though ControlFlow::Exit was requested

### ISSUE THREAD

**Issue by cfiet** [rust-windowing/winit#1241]
Hi,

Run into this issue on `0.20.0-alpha4` while investigating [2889](https://github.com/jwilm/alacritty/issues/2889) in Alacritty.

It seem that with current implementation on Windows, there is an expectation that all Windows messages are handled before `ControlFlow` status is checked.

If the application produces messages in a separate thread faster that it can handle it, this can cause it to hang and never exit, even if it requested `ControlFlow::Exit`.

I've isolated the problem [here](https://github.com/cfiet/winit-windows-events-bug/blob/master/src/main.rs). This application should exit after about a second but it never terminates.

**Comment by Osspial** [comment]
This seems like the correct behavior. The [`ControlFlow` documentation](https://docs.rs/winit/0.20.0-alpha4/winit/event_loop/enum.ControlFlow.html) explicitly says that `ControlFlow` only gets checked once `EventsCleared` has been emitted, and if `EventsCleared` never gets emitted the event loop will never act upon the specified control flow.
