### ISSUE TITLE
macOS: run_return terminates an app instead of continuing past return 

### ISSUE THREAD

**Issue by syrel** [rust-windowing/winit#1242]
Version: 0.20.0-alpha4 (https://github.com/rust-windowing/winit/commit/05a1f4280c357c8080272f4fe55e30e9f1469eef)
OS: Catalina 10.15.1 Beta
Code: window_run_return example

Can be reproduced with `window_run_return` example. The app is terminated as a result of closing the first window, therefore the second window never appears.

The issue was introduced in https://github.com/rust-windowing/winit/pull/1234/ as an attempt to fix https://github.com/rust-windowing/winit/issues/1117
Apparently changing `stop` to `terminate` in `app_state` leads to the app termination.
Since this change breaks `run_return` feature on mac which is more critical than https://github.com/rust-windowing/winit/issues/1117 I propose to revert for now and find another solution.

**Comment by goddessfreya** [comment]
@vbogaevsky You working on this, or should you be de assigned?

**Comment by vbogaevsky** [comment]
@goddessfreya I am. I'll publish PR this week.
