### ISSUE TITLE
No window or device events after returning ControlFlow::Exit in run_return

### ISSUE THREAD

**Issue by Rua** [rust-windowing/winit#1243]
I'm working on Linux/X11, and I'm using a more traditional poll-style event loop, using `run_return`. After polling for events, the program does other logic such as drawing. In the code below, `run_return` should return control if there are no more events, or if a quit event is received. As I understand it, `ControlFlow::Exit` is used to return from the function, similar to a `break` statement.

```
loop {
	event_loop.run_return(|event, _, control_flow| {
		match event {
			Event::WindowEvent { event, window_id: _ } => {
				match event {
					WindowEvent::CloseRequested => {
						should_quit = true;
						*control_flow = ControlFlow::Exit;
					},
					_ => {},
				}
			},
			Event::EventsCleared => {
				*control_flow = ControlFlow::Exit;
			},
			_ => {},
		}
	});

	if should_quit {
		return;
	}

	// Draw and logic goes here
}
```

However, with this setup, my window never seems to receive any other events. If I print out the received events, all I get is `NewEvents(Init)`, `EventsCleared` and `LoopDestroyed`, each time `run_return` is called. There are never any other events received. If I do nothing in response to `EventsCleared` instead, then I do receive other events, but then `run_return` continues until I quit the window, so nothing ever gets drawn on it.

If I'm not receiving window or device events in subsequent polls after exiting the loop the first time, then either that seems to be a bug or I'm doing something wrong here.

**Comment by Rua** [comment]
In platform_impl/linux/x11/mod.rs, in `run_return`, if there are no events waiting, then `EventsCleared` is sent. Since my callback sends `ControlFlow::Exit` in response, it immediately breaks the loop after that point, and never has a chance to call `drain_events` at the bottom of the loop. Since this function is the only one that adds new events to `pending_events`, if it never gets called then `pending_events` stays empty and will be empty the next time `run_return` gets called, continuing the cycle.

**Comment by murarth** [comment]
@Rua You are exactly correct about the cause of this issue. I have submitted a PR to fix it.
