### ISSUE TITLE
RedrawRequested event arrives before window information available

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1246]
This is kinda related to https://github.com/rust-windowing/winit/issues/998.

To properly handle DPI and resizing it is essential to know the DPI factor of the window. Otherwise it is not possible to handle winit's events properly.

As described in #998, this DPI information is not available at startup, so as a workaround Alacritty tries to get the current DPI when the first event arrives. All other DPI changes can be handled by the HiDPIFactorChanged event.

However, since https://github.com/rust-windowing/winit/commit/2b5f9c52a6d7c35b63f6865b988735f612d7324b, an event is dispatched right at startup. However at this point the DPI information is not correct yet.

Would it be possible to delay the RedrawRequested until the DPI information is available? It seems strange to me to request a redraw when the window information can not be queried reliably yet.

Alternatively maybe it's possible to send a HiDPIFactorChanged at startup too, once the DPI is available? But I don't know why we'd then request a redraw before that information arrives.

Generally this isn't necessarily a dedicated issue unless `RedrawRequested` is supposed to arrive after the window information is available, so I have no issue with closing this as duplicate of https://github.com/rust-windowing/winit/issues/998 if there's no intention to change this. I would be curious though how an end user is supposed to work around this, should we get the initial DPI once the first resize event comes in?

**Comment by murarth** [comment]
Is this still an issue, with #998 having been solved?

**Comment by chrisduerr** [comment]
I can't reproduce this anymore, I think #998 has rendered this irrelevant.
