### ISSUE TITLE
Windows: 0.20 crashes if CoInitializeEx has been called with MULTITHREADED

### ISSUE THREAD

**Issue by hrydgard** [rust-windowing/winit#1255]
The drag/drop support for Windows use OLE drag drop, which requires that COM has been initialized with a single-threaded apartment model. [OleInitialize](https://docs.microsoft.com/en-us/windows/win32/api/ole2/nf-ole2-oleinitialize) is called and we panic if that fails.

So if someone has called CoInitialize(MULTITHREADED), which for example is currently required (for unclear reasons) when trying to use [cpal](https://github.com/RustAudio/cpal), winit just dies.

winit should handle the failure of OleInitialize better and just discard drag/drop support (or fall back to WM_DROPFILES, it's unclear to me why OLE drag/drop is used at all).

**Comment by goddessfreya** [comment]
Assigning you, since you seam to have already made the fix. :tada:

**Comment by hrydgard** [comment]
Fair enough @goddessfreya ! Let me know if there's anything more I need to do on that PR (where to add documentation maybe), or merge it I guess.

**Comment by goddessfreya** [comment]
cc @Osspial

**Comment by chemicstry** [comment]
Any updates on this? Can https://github.com/EmbarkStudios/winit/commit/7074d6ac06301f8409fdf5982bc7d36b851418f8 be merged?

**Comment by Osspial** [comment]
Closing in light of #1524.
