### ISSUE TITLE
Make `set_cursor_visible` on macOS only hide cursor within the window?

### ISSUE THREAD

**Issue by slmjkdbtl** [rust-windowing/winit#1276]
I noticed only macOS hides the cursor even when the cursor leaves the window, is there anyway to only hide within the window?

In SDL `SDL_ShowCursor(false)` hides cursor only within the window by default. I'm not sure how they did it, but a quick browse through the source and I see they only use `[NSCursor hide]` /  `[NSCursor unhide]` when switching relative mouse mode, not for `SDL_ShowCursor`.

**Comment by slmjkdbtl** [comment]
also when the mouse leaves and focus on another window, making the mouse appear, and focus on the winit window again, the mouse is not hidden anymore

**Comment by slmjkdbtl** [comment]
closed because I found it trivial to just 
```rust
match window_event {
    CursorEntered { .. } => window.set_cursor_visible(false),
    CursorLeft { .. } => window.set_cursor_visible(true),
    _ => {},
}
```

**Comment by Osspial** [comment]
I'm going to re-open this. Only hiding the cursor while it's mousing over the window is the expected behavior - just because it's easy to work around doesn't mean it shouldn't be fixed.
