### ISSUE TITLE
Consider implementing Lifecycle on controller or view.

### ISSUE THREAD

**Issue by seivan** [rust-windowing/winit#1281]
[These](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/ios/view.rs#L565-L585) could be made as notifications on either the view or the controller.

Which would make it useful in case you want to build  a Window from Rust on an existing `UIApplicationDelegate`

Necessary for https://github.com/rust-windowing/winit/issues/802

**Comment by maxammann** [comment]
This will be a requirement for the maplibre-rs project. We do not want to render maps fullscreen but in separate views.
