### ISSUE TITLE
Improve IME event handling

### ISSUE THREAD

**Issue by garasubo** [rust-windowing/winit#1293]
Reference: https://github.com/servo/servo/issues/24724

When I tried to implement compositions event handling for the browser engine, I realized that current event interface doesn't have enough information about IME events.
To implement this, we need to know what is the current content in IME when the user edit something in IME. But seems `glutin::WindowEvent::KeyboardInput` doesn't have interface to get that information. It would be nice to send more information when IME status was updated.

Currently, winit submits character information when IME edit completes. But to implement compositions event handling, those information should be available when updating the status as well. In addition, winit sends charcter information for each characters (e.g. if the content in IME was "あああ", it sends 3 `ReceiveCharacter('あ')` event) . It would be nice to have send this information as a string.

I tested this on my Linux with X11, but all other platforms might have the same issues.

**Comment by goddessfreya** [comment]
cc @murarth, I'm not familiar with how IME works, are you?

**Comment by murarth** [comment]
I'm not at all familiar with IME, but I'll read some docs and see what I can do for this issue.

**Comment by garasubo** [comment]
Thanks. I updated the description to make it clear what I want to do.

**Comment by Osspial** [comment]
#753 has a lot of good discussion on both IME handling and the broader context of how to improve the keyboard input API.

**Comment by garasubo** [comment]
That issue looks like this issue as well, but haven't updated for a while. Is there any ongoing work related to that issue?

**Comment by garasubo** [comment]
I'm not sure I fully understood the discussion on #753, but the most concern there is something how to represent pressed keys rather than IME status. I'm thinking about adding a new member into `KeyboardEvent` to have IME status corresponding to that keyboard event. What do you think? @Osspial

**Comment by garasubo** [comment]
Submitted a PR for adding new IME events for X11. Could anyone review it?

**Comment by murarth** [comment]
The X11 implementation has been merged (to the `composition-event` branch) and I've opened a tracking issue (#1497) to coordinate implementation of this API for each remaining platform. Thank you, @garasubo, for your work on this API and the X11 implementation.

I am now closing this issue. Any further discussion of this feature should take place in #1497.
