### ISSUE TITLE
Implement From/Into [T; 2] for sizes and positions in the dpi module

### ISSUE THREAD

**Issue by Rua** [rust-windowing/winit#1300]
At the moment, these implement From/Into for 2-tuples, but since both elements always have the same type, implementing them for 2-element arrays would also be useful. That way, users are more free to decide how they want to represent things in their program, without having to convert one representation to the other for the sake of winit.

**Comment by goddessfreya** [comment]
Afaik, this has been done on the dpi overhaul branch, see https://github.com/rust-windowing/winit/pull/1283

**Comment by Osspial** [comment]
I'm closing this in light of that. Thanks for raising the issue, though!
