### ISSUE TITLE
Question - Multi-Process Application Macos

### ISSUE THREAD

**Issue by chichid** [rust-windowing/winit#1311]
This is is probably not a winit problem but I wanted to ask anyway. Currently, I'm trying to experiment with multi-process apps in rust (same architecture as google chrome, one process by window) and I encoutered a problem on MacOS where it creates a new dock icon for each new forked child process. Is there any possible way to handle that? Whether at the winit level or by any other means?

**Comment by vbogaevsky** [comment]
@chichid you can start child processes with `ActivationPolicy::Accessor` or `ActivationPolicy::Prohibited` in `PlatformSpecificWindowBuilderAttributes`. 
On `ActivationPolicy` you can read more [here](https://developer.apple.com/documentation/appkit/nsapplicationactivationpolicy?language=objc)

**Comment by chichid** [comment]
Thanks @vbogaevsky! Wouldn't NSApplicationActivationPolicyAccessory break any of the existing mac user experience, ex. when I click on the dock all the windows must appear?

**Comment by Osspial** [comment]
FWIW, Chrome (or CEF, at the very least) has a single process that handles the master event loop and the top-level windows, but has separate processes for managing the resources in each particular window. I'd guess that, if you can avoid initializing the `EventLoop` in child processes, you should be able to avoid creating separate dock icons.
