### ISSUE TITLE
Window event for non-winit window on drag

### ISSUE THREAD

**Issue by worktycho** [rust-windowing/winit#1319]
When doing a drag on X11 out of a window using winit 0.20.0-alpha5 I get a WindowEvent::CursorEntered event with a window id that does not correspond to a window I have created. Is this intended behavior?

**Comment by goddessfreya** [comment]
This is unintended, right @murarth? I can't imagine any of the other platforms do this.

**Comment by murarth** [comment]
Certainly seems like unintended behavior. I've submitted PR #1320 to address this issue.
