### ISSUE TITLE
winit 0.20.0-alpha[..5] crashes my wayland window manager (sway)

### ISSUE THREAD

**Issue by Abendstolz** [rust-windowing/winit#1333]
Hello!

Ever since using `winit 0.20.0-alphaX` (0 <= X <= 5) my window-manager (sway) crashes whenever run with `wayland`.

To circumvent this I have to use `xwayland` by exporting `WINIT_UNIX_BACKEND=x11`

From checking the logs I am not sure what exactly is to blame so I am not sure whether I should file an issue on sway's side. This didn't happen for any other application so far, hence I wanted to open the issue here first.

```
Dec 22 19:34:25 manetheren systemd-coredump[10092]: Process 692 (sway) of user 1000 dumped core.
                                                    Stack trace of thread 692:
                                                    #0  0x00007fe00b136d1d n/a (libwlroots.so.3 + 0x54d1d)
                                                    #1  0x00007fe00a9e569a ffi_call_unix64 (libffi.so.6 + 0x669a)
                                                    #2  0x00007fe00a9e4fb6 ffi_call (libffi.so.6 + 0x5fb6)
                                                    #3  0x00007fe00b19b82f n/a (libwayland-server.so.0 + 0xc82f)
                                                    #4  0x00007fe00b198193 n/a (libwayland-server.so.0 + 0x9193)
                                                    #5  0x00007fe00b1997f2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xa7f2)
                                                    #6  0x00007fe00b19839c wl_display_run (libwayland-server.so.0 + 0x939c)
                                                    #7  0x000055c9be9c7592 n/a (sway + 0xe592)
                                                    #8  0x00007fe00b79b153 __libc_start_main (libc.so.6 + 0x27153)
                                                    #9  0x000055c9be9c78be n/a (sway + 0xe8be)

                                                    Stack trace of thread 694:
                                                    #0  0x00007fe00b054c45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                                                    #1  0x00007fe0042c9a5c n/a (radeonsi_dri.so + 0x8faa5c)
                                                    #2  0x00007fe0042c9658 n/a (radeonsi_dri.so + 0x8fa658)
                                                    #3  0x00007fe00b04e4cf start_thread (libpthread.so.0 + 0x94cf)
                                                    #4  0x00007fe00b8732d3 __clone (libc.so.6 + 0xff2d3)

                                                    Stack trace of thread 699:
                                                    #0  0x00007fe00b054c45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                                                    #1  0x00007fe0042c9a5c n/a (radeonsi_dri.so + 0x8faa5c)
                                                    #2  0x00007fe0042c9658 n/a (radeonsi_dri.so + 0x8fa658)
                                                    #3  0x00007fe00b04e4cf start_thread (libpthread.so.0 + 0x94cf)
                                                    #4  0x00007fe00b8732d3 __clone (libc.so.6 + 0xff2d3)

                                                    Stack trace of thread 700:
                                                    #0  0x00007fe00b054c45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                                                    #1  0x00007fe0042c9a5c n/a (radeonsi_dri.so + 0x8faa5c)
                                                    #2  0x00007fe0042c9658 n/a (radeonsi_dri.so + 0x8fa658)
                                                    #3  0x00007fe00b04e4cf start_thread (libpthread.so.0 + 0x94cf)
                                                    #4  0x00007fe00b8732d3 __clone (libc.so.6 + 0xff2d3)

                                                    Stack trace of thread 697:
                                                    #0  0x00007fe00b054c45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                                                    #1  0x00007fe0042c9a5c n/a (radeonsi_dri.so + 0x8faa5c)
                                                    #2  0x00007fe0042c9658 n/a (radeonsi_dri.so + 0x8fa658)
                                                    #3  0x00007fe00b04e4cf start_thread (libpthread.so.0 + 0x94cf)
                                                    #4  0x00007fe00b8732d3 __clone (libc.so.6 + 0xff2d3)

                                                    Stack trace of thread 704:
                                                    #0  0x00007fe00b054c45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                                                    #1  0x00007fe0042c9a5c n/a (radeonsi_dri.so + 0x8faa5c)
                                                    #2  0x00007fe0042c9658 n/a (radeonsi_dri.so + 0x8fa658)
                                                    #3  0x00007fe00b04e4cf start_thread (libpthread.so.0 + 0x94cf)
                                                    #4  0x00007fe00b8732d3 __clone (libc.so.6 + 0xff2d3)

                                                    Stack trace of thread 702:
                                                    #0  0x00007fe00b054c45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                                                    #1  0x00007fe0042c9a5c n/a (radeonsi_dri.so + 0x8faa5c)
                                                    #2  0x00007fe0042c9658 n/a (radeonsi_dri.so + 0x8fa658)
                                                    #3  0x00007fe00b04e4cf start_thread (libpthread.so.0 + 0x94cf)
                                                    #4  0x00007fe00b8732d3 __clone (libc.so.6 + 0xff2d3)

                                                    Stack trace of thread 703:
                                                    #0  0x00007fe00b054c45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                                                    #1  0x00007fe0042c9a5c n/a (radeonsi_dri.so + 0x8faa5c)
                                                    #2  0x00007fe0042c9658 n/a (radeonsi_dri.so + 0x8fa658)
                                                    #3  0x00007fe00b04e4cf start_thread (libpthread.so.0 + 0x94cf)
                                                    #4  0x00007fe00b8732d3 __clone (libc.so.6 + 0xff2d3)

                                                    Stack trace of thread 696:
                                                    #0  0x00007fe00b054c45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                                                    #1  0x00007fe0042c9a5c n/a (radeonsi_dri.so + 0x8faa5c)
                                                    #2  0x00007fe0042c9658 n/a (radeonsi_dri.so + 0x8fa658)
                                                    #3  0x00007fe00b04e4cf start_thread (libpthread.so.0 + 0x94cf)
                                                    #4  0x00007fe00b8732d3 __clone (libc.so.6 + 0xff2d3)

                                                    Stack trace of thread 701:
                                                    #0  0x00007fe00b054c45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                                                    #1  0x00007fe0042c9a5c n/a (radeonsi_dri.so + 0x8faa5c)
                                                    #2  0x00007fe0042c9658 n/a (radeonsi_dri.so + 0x8fa658)
                                                    #3  0x00007fe00b04e4cf start_thread (libpthread.so.0 + 0x94cf)
                                                    #4  0x00007fe00b8732d3 __clone (libc.so.6 + 0xff2d3)

                                                    Stack trace of thread 695:
                                                    #0  0x00007fe00b054c45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                                                    #1  0x00007fe0042c9a5c n/a (radeonsi_dri.so + 0x8faa5c)
                                                    #2  0x00007fe0042c9658 n/a (radeonsi_dri.so + 0x8fa658)
                                                    #3  0x00007fe00b04e4cf start_thread (libpthread.so.0 + 0x94cf)
                                                    #4  0x00007fe00b8732d3 __clone (libc.so.6 + 0xff2d3)

                                                    Stack trace of thread 698:
                                                    #0  0x00007fe00b054c45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                                                    #1  0x00007fe0042c9a5c n/a (radeonsi_dri.so + 0x8faa5c)
                                                    #2  0x00007fe0042c9658 n/a (radeonsi_dri.so + 0x8fa658)
                                                    #3  0x00007fe00b04e4cf start_thread (libpthread.so.0 + 0x94cf)
                                                    #4  0x00007fe00b8732d3 __clone (libc.so.6 + 0xff2d3)
Dec 22 19:34:26 manetheren systemd[1]: systemd-coredump@0-10091-0.service: Succeeded.
Dec 22 19:34:26 manetheren kernel: audit: type=1131 audit(1577039666.394:62): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-10091-0 comm="systemd" exe="/usr/lib/systemd/system>
Dec 22 19:34:26 manetheren kernel: audit: type=1130 audit(1577039666.404:63): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-10095-0 comm="systemd" exe="/usr/lib/systemd/system>
Dec 22 19:34:26 manetheren audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-10091-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? termina>
Dec 22 19:34:26 manetheren audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-10095-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? termin>
Dec 22 19:34:26 manetheren systemd[1]: Started Process Core Dump (PID 10095/UID 0).
Dec 22 19:34:26 manetheren systemd-coredump[10113]: Process 835 (ion) of user 1000 dumped core.

                                                    Stack trace of thread 835:
                                                    #0  0x00007f5b167a1f25 raise (libc.so.6 + 0x3bf25)
                                                    #1  0x00007f5b1678b897 abort (libc.so.6 + 0x25897)
                                                    #2  0x000056467c2e42f7 n/a (ion + 0x1e52f7)
                                                    #3  0x000056467c2e42e6 n/a (ion + 0x1e52e6)
                                                    #4  0x000056467c2d0a26 n/a (ion + 0x1d1a26)
                                                    #5  0x000056467c2d0952 n/a (ion + 0x1d1952)
                                                    #6  0x000056467c2d044e n/a (ion + 0x1d144e)
                                                    #7  0x000056467c2e2b96 n/a (ion + 0x1e3b96)
                                                    #8  0x000056467c2e799c n/a (ion + 0x1e899c)
                                                    #9  0x000056467c2ef91b n/a (ion + 0x1f091b)
                                                    #10 0x000056467c301174 n/a (ion + 0x202174)
                                                    #11 0x000056467c325ce0 n/a (ion + 0x226ce0)
                                                    #12 0x000056467c2f724a n/a (ion + 0x1f824a)
                                                    #13 0x000056467c304714 n/a (ion + 0x205714)
                                                    #14 0x000056467c304218 n/a (ion + 0x205218)
                                                    #15 0x000056467c33bf64 n/a (ion + 0x23cf64)
                                                    #16 0x000056467c31e3d3 n/a (ion + 0x21f3d3)
                                                    #17 0x000056467c3390c1 n/a (ion + 0x23a0c1)
                                                    #18 0x00007f5b1678d153 __libc_start_main (libc.so.6 + 0x27153)
                                                    #19 0x000056467c12d17e n/a (ion + 0x2e17e)
Dec 22 19:34:26 manetheren audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-10095-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? termina>
Dec 22 19:34:26 manetheren kernel: audit: type=1131 audit(1577039666.608:64): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-10095-0 comm="systemd" exe="/usr/lib/systemd/system>
Dec 22 19:34:26 manetheren systemd[1]: systemd-coredump@1-10095-0.service: Succeeded.
Dec 22 19:34:44 manetheren audit[10122]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 pid=10122 comm="sway" exe="/usr/bin/sway" sig=11 res=1
Dec 22 19:34:44 manetheren kernel: sway[10122]: segfault at 28 ip 00007f4440e46d1d sp 00007fff084cd8a0 error 4 in libwlroots.so.3.6.1[7f4440e17000+4e000]
```
I am out of my depth here. I see that the segfault happens in `libwlroots` and I see `radeonsi` being mentioned and `ion` crashing, but I am not sure what to make of it. 

If you need any further info, I am happy to provide whatever I can.

**Comment by goddessfreya** [comment]
What distribution are you using?

**Comment by Abendstolz** [comment]
Archlinux - `Kernel 5.4.6-arch1-1`

```
abendstolz:~# glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) RX 470 Graphics (POLARIS10, DRM 3.35.0, 5.4.6-arch1-1, LLVM 9.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.3.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.3.1
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.3.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by goddessfreya** [comment]
Can you `git bisect` winit to track down the change that broke Wayland?

**Comment by Abendstolz** [comment]
I can try, but it will take me some days.

**Comment by kchibisov** [comment]
Also if your compositor is crashing its your compositor bug, and not a client one. I mean it could be winit's bug, but compositor shouldn't crash when client misbehaves. Anyway, I suggest you to report this bug to sway.

**Comment by goddessfreya** [comment]
@Abendstolz I've taken the time to setup sway and I could not reproduce any crashes on my `AMD KAVERI (DRM 3.33.0, 5.3.18.a-1-hardened, LLVM 10.0.0)`.

In addition to providing a `git bisect` you're going to have to file a bug upstream with sway, as @kchibisov mentioned. 

Slight shameless self-plug, but, chances are the sway devs are going to request you compile stuff with debug symbols and resubmit your back trace. 

Now, running `makepkg -si` on wayland, wlroots, sway, and libffi is pretty trivial, although slightly annoying. Trying to build mesa-git, however, is an arduous task that requires a copy of llvm-git. Previously, you could get a prebuilt copy from [kerberizer's unofficial mirror,](https://repos.uni-plovdiv.net/archlinux/llvm-svn/x86_64/) however, as you may know, that mirror hasn't updated since January. Unfortunately, building a copy of llvm is pretty painful, requiring a clean chroot if you don't want many silent bugs. 

Furthermore, if you want multilib support you'll have to gather a scattering of 32-bit AUR packages off the AUR (e.g. lib32-python), a good portion of which are unmaintained/orphaned/non-existent.

Luckily, a little pet project of mine is [gabs](https://github.com/goddessfreya/gabs), a set of scripts that were explicitly made for automating this task. I've taken some time to add libffi, wayland, wlroots and sway to the list of [builtins](https://github.com/goddessfreya/gabs/tree/master/builtins) in gabs, so rebuilding everything you need should now be a trivial task:

```
$ git clone git@github.com:goddessfreya/gabs.git
$ ionice -c 2 -n 7 nice -19 ./gabs-build -ed "$(pwd)/ephemeral_dir"

<Wait ~12 hours>

$ sudo pacman -U ephemeral_dir/pkgs.chroot/*`
```

**Comment by Abendstolz** [comment]
@goddessfreya Thanks a bunch - once I have enough time on my hands, I'll be sure to follow through with this. May be a couple of days though.

On a sidenote: I wonder why I need `mesa-git` though.

**Comment by kchibisov** [comment]
@Abendstolz Hm, were you using glutin window examples or winit ones? Winit window example is useless on Wayland, since it doesn't draw anything, could you try with glutin? You should just `git clone https://github.com/rust-windowing/glutin` and do `cargo run --example window`.

Anyway for a sway part you'll likely just need a sway + wlroots with debug symbols as it was already said, llvm + mesa debug symbols feels like an optional part here. For a proper backtrace I recommend you to do the `coredumpctl gdb sway` and typing `bt full`, since it should be more useful, then pasting things from journal imho, it should attach a debugger to a last crash of sway.

IIRC on Arch you have a `sway-git` package and `wlroots-git` package which should build sway with debug symbols by default. For better debug info you can add to `CFLAGS` in `/etc/makepkg.conf` a `-ggdb` thing.

**Comment by Abendstolz** [comment]
@kchibisov Oh, I should've made it clear that I wasn't using any example, because of the reasons you mentioned.

It's an application I've been working on and off for 2 years and multiple `winit` releases :)

The `glutin window` example works just fine (Sidenote: it resizes if I move my cursor to the other screen, but that may be `wayland`)

So it may be a problem with `vulkan` in the `mesa`"stack" after all? 

Hm, I used to use `vulkano` and switched to `wgpu-rs` now. I tried to run with `BackendBit::GL` now, but that leads to an "internal error: entered unreachable code" - I haven't found the exact origin yet, but I assume that's because `wgpu-native` doesn't have an implementation for the `gl` backend yet.

Ha! That actually helped me, thanks!

**Comment by kchibisov** [comment]
>So it may be a problem with vulkan in the mesa"stack" after all?

Or vulkano/wgpu-rs, idk, but imho compositor(sway) shouldn't crash here imho.

**Comment by Abendstolz** [comment]
Finally I have some time to investigate further:

First off: `sway` doesn't crash anymore, that was fixed on their side.

I am now using `winit-0.21.0` and this is my backtrace:

`             at src/libstd/sys_common/backtrace.rs:50                                                                                                                                            [22/1508]
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::option::expect_failed
             at src/libcore/option.rs:1188
  14: core::option::Option<T>::expect
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/option.rs:348
  15: smithay_client_toolkit::surface::get_dpi_factor
             at /home/abendstolz/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.6.4/src/surface.rs:99
  16: winit::platform_impl::platform::wayland::window::Window::scale_factor
             at /home/abendstolz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/wayland/window.rs:276
  17: winit::platform_impl::platform::wayland::window::Window::inner_size
             at /home/abendstolz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/wayland/window.rs:224
  18: winit::platform_impl::platform::Window::inner_size
             at /home/abendstolz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/mod.rs:276
  19: winit::window::Window::inner_size
             at /home/abendstolz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/window.rs:478
  20: client::core::graphics::backends::wgpu::engine::WgpuEngine::get_canvas_size
             at src/core/graphics/backends/wgpu/engine.rs:144
  21: client::game::ecs::executor::Ecs::new
             at src/game/ecs/executor.rs:41
  22: client::game::states::ingame::Ingame::new
             at src/game/states/ingame.rs:23
  23: client::game::states::start_state
             at src/game/states.rs:18
  24: client::single_player::{{closure}}
             at src/lib.rs:49
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

With `RUST_BACKTRACE=full`:

`Running `target/debug/client`                                                                                                                                                               
thread '<unnamed>' panicked at 'Surface was not created with create_surface.', src/libcore/option.rs:1188:5
stack backtrace:
   0:     0x56405b8f0264 - backtrace::backtrace::libunwind::trace::heb43798aede8bd30
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x56405b8f0264 - backtrace::backtrace::trace_unsynchronized::had2ba7dec4bd2732
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x56405b8f0264 - std::sys_common::backtrace::_print_fmt::hda61f46e822731b2
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x56405b8f0264 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfe37fa5de6572965
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x56405b917c9c - core::fmt::write::h74887d18db27282c
                               at src/libcore/fmt/mod.rs:1025
   5:     0x56405b8ec527 - std::io::Write::write_fmt::h6808f3d5eceed5e5
                               at src/libstd/io/mod.rs:1426
   6:     0x56405b8f2a5e - std::sys_common::backtrace::_print::hcc0fd4b3552039ef
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x56405b8f2a5e - std::sys_common::backtrace::print::h1c9c5c1c0505592d
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x56405b8f2a5e - std::panicking::default_hook::{{closure}}::hefb6085c1ab83a59
                               at src/libstd/panicking.rs:193
   9:     0x56405b8f2751 - std::panicking::default_hook::h1b037d2bf0657ab3
                               at src/libstd/panicking.rs:210
  10:     0x56405b8f313b - std::panicking::rust_panic_with_hook::h787d7f532b084b9a
                               at src/libstd/panicking.rs:471
  11:     0x56405b8f2cee - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x56405b913bce - core::panicking::panic_fmt::h76b979c035808e69
                               at src/libcore/panicking.rs:84
  13:     0x56405b913c37 - core::option::expect_failed::h7475be656707bdc0
                               at src/libcore/option.rs:1188
  14:     0x56405b81acce - core::option::Option<T>::expect::h72991860a0fed78b
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/option.rs:348
  15:     0x56405b81acce - smithay_client_toolkit::surface::get_dpi_factor::hb4aa422c8a67bb88
                               at /home/abendstolz/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.6.4/src/surface.rs:99
  16:     0x56405b7b44e5 - winit::platform_impl::platform::wayland::window::Window::scale_factor::h3186519a375df525
                               at /home/abendstolz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/wayland/window.rs:276
  17:     0x56405b7b44e5 - winit::platform_impl::platform::wayland::window::Window::inner_size::h1ab64aefd517faab
                               at /home/abendstolz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/wayland/window.rs:224
  18:     0x56405b4a6b79 - winit::platform_impl::platform::Window::inner_size::h8c5f579ad254ee64
                               at /home/abendstolz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/mod.rs:276
  19:     0x56405b5f8026 - winit::window::Window::inner_size::h5b3684a0dab3d40a
                               at /home/abendstolz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/window.rs:478
  20:     0x56405b53405c - client::core::graphics::backends::wgpu::engine::WgpuEngine::get_canvas_size::h68f43805612234f3
                               at src/core/graphics/backends/wgpu/engine.rs:144
  21:     0x56405b663045 - client::game::ecs::executor::Ecs::new::h26732dac76bbd6b4
                               at src/game/ecs/executor.rs:41
  22:     0x56405b65c609 - client::game::states::ingame::Ingame::new::h93944cd27833e8ba
                               at src/game/states/ingame.rs:23
  23:     0x56405b64c3b7 - client::game::states::start_state::h5dc35844a5e50462
                               at src/game/states.rs:18
  24:     0x56405b6490cd - client::single_player::{{closure}}::hb5e2fb8163c0b4bf
                               at src/lib.rs:49
  25:     0x56405b5c1c63 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb88f138eebc7e8f5
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/sys_common/backtrace.rs:136
  26:     0x56405b357cc4 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::haffe1788c9d9c6cc
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/thread/mod.rs:469
  27:     0x56405b509a66 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hdd76686aeb6836b5
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/panic.rs:318
  28:     0x56405b4641c3 - std::panicking::try::do_call::h6265eced88546639
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/panicking.rs:292
  29:     0x56405b8fbafa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  30:     0x56405b463368 - std::panicking::try::hbc4e5c77f5193509
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/panicking.rs:270
  31:     0x56405b509c46 - std::panic::catch_unwind::h614e989c3dcbe12e
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/panic.rs:394
  32:     0x56405b356f9d - std::thread::Builder::spawn_unchecked::{{closure}}::h551128c91cee7eef
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/thread/mod.rs:468
  33:     0x56405b2b2bb4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haabc5b55b0e0cd4a
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/ops/function.rs:232
  34:     0x56405b8e44cf - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7bfd6e98bcf6c67e
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
  35:     0x56405b8fabc0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h9979661149bbc525
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
  36:     0x56405b8fabc0 - std::sys_common::thread::start_thread::had0bb4166c065276
                               at src/libstd/sys_common/thread.rs:13
  37:     0x56405b8fabc0 - std::sys::unix::thread::Thread::new::thread_start::hbc75223688f972da
                               at src/libstd/sys/unix/thread.rs:80
  38:     0x7f56b8db04cf - start_thread
  39:     0x7f56b8cc52d3 - clone
  40:                0x0 - <unknown>
`

**Comment by Abendstolz** [comment]
Sway doesn't crash anymore with one of their latest releases
