### ISSUE TITLE
WindowBuilderExtUnix::with_resize_increments and with_base_size should use Size, not LogicalSize

### ISSUE THREAD

**Issue by Osspial** [rust-windowing/winit#1353]
on the `dpi-overhaul` branch.

**Comment by denismaxim0v** [comment]
I could work on it if not taken

**Comment by murarth** [comment]
This issue has already been resolved. The two methods mentioned now accept any type implementing `Into<Size>` as the size parameter, which includes `Size`, `PhysicalSize`, and `LogicalSize`.

It should have been closed automatically when PR #1356 was merged. It seems GitHub somehow dropped the ball on that.
