### ISSUE TITLE
Improve Event docs

### ISSUE THREAD

**Issue by rukai** [rust-windowing/winit#1359]
I think it would be really nice if the documentation for [Event](https://docs.rs/winit/0.20.0-alpha6/winit/event/enum.Event.html) went through a few example cases. i.e. in various specific scenarios list every event that would be received.
Its currently really hard to figure out whats going on from just reading the definition of each event. 

Specifically NewEvents, MainEventsCleared, RedrawRequested, RedrawEventsCleared is what's giving me trouble.

**Comment by Osspial** [comment]
@icefoxen made a PR (#1032) that added quite a bit of docs, but it went on the backburner since the event loop model was still in flux at the time he wrote them. I'll see about polishing them up.
