### ISSUE TITLE
Activating application on macOS does not show window after set_visible(false)

### ISSUE THREAD

**Issue by nitsky** [rust-windowing/winit#1360]
On macOS, if I hide a window by calling `window.set_visible(false)`, and then attempt to show the window by activating the application, either by clicking on the application icon in the dock or using Command-Tab, the window does not show. See the example below.

I discovered this issue as a user of Alacritty. Alacritty calls `set_visible(false)` on its window to hide the application.

Alacritty Issue: https://github.com/jwilm/alacritty/issues/1465

I opened a pull request in Alacritty, but the maintainers suggested putting the relevant fix in winit instead.

Alacritty PR: https://github.com/jwilm/alacritty/pull/2973

The correct behavior can be achieved by calling `[[NSApplication sharedApplication] hide: nil]`. I will be happy to submit a PR, but I would like some guidance on what the right API should be. Perhaps we could add a method `hide_application()` method that defers to `set_visible(false)` on other platforms?

Steps to reproduce:
* Run the example below on macOS.
* Press Command-H, which calls `window.set_visible(false)`.
* Attempt to bring the window back into focus by clicking on the application icon in the dock or using Command-Tab.

```rust
use winit::{
    event::{Event, KeyboardInput, ModifiersState, VirtualKeyCode, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    let event_loop = EventLoop::new();

    let window = WindowBuilder::new()
        .with_title("A fantastic window!")
        .build(&event_loop)
        .unwrap();

    event_loop.run(move |event, _, control_flow| {
        println!("{:?}", event);

        match event {
            Event::WindowEvent {
                event:
                    WindowEvent::KeyboardInput {
                        input:
                            KeyboardInput {
                                virtual_keycode: Some(VirtualKeyCode::H),
                                modifiers:
                                    ModifiersState {
                                        shift: false,
                                        ctrl: false,
                                        alt: false,
                                        logo: true,
                                    },
                                ..
                            },
                        ..
                    },
                window_id,
            } if window_id == window.id() => {
                window.set_visible(false);
            }
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                window_id,
            } if window_id == window.id() => *control_flow = ControlFlow::Exit,
            _ => *control_flow = ControlFlow::Wait,
        }
    });
}
```

**Comment by Osspial** [comment]
This is the expected behavior, I think. The `set_visible` function is intended for completely removing the window from view of the user, rather than just minimizing it to the dock. I ran your example on Windows, and hiding the window completely removes it from the taskbar.

**Comment by Osspial** [comment]
From what I can surmise from online docs, it looks like it may be more correct to call `set_minimized(true)` on all of Alacritty's windows, rather than `set_visible(false)`. cc @chrisduerr

**Comment by nitsky** [comment]
@Osspial @chrisduerr would you be OK with a PR that adds `hide_application()` to winit, and then Alacritty can call it just on macOS?

**Comment by Osspial** [comment]
@nitsky Sure. Since it's an application-wide event instead of a window-specific event, could you add it to a new `platform::macos::EventLoopWindowsExtMacOS`?

**Comment by chrisduerr** [comment]
Is it possible to unhide through this API too? If so, it probably makes sense to do things similar to set_minimized/set_maximized/set_visible here and provide a function `set_hidden` which takes `hidden` as a `bool` parameter.

Otherwise just `hide` would work fine for Alacritty.

I'm not aware of anything like this on Windows/X11/Wayland either (I'm not even sure what the hell it does on macOS), so putting it in the macOS ext is probably the best choice.
