### ISSUE TITLE
set_minimized(true) works only with decorations on macOS

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1361]
I've just tested an Alacritty PR for adding a default minimize action bound to command + m (https://github.com/jwilm/alacritty/pull/3121) and noticed that it's not working for me.

After confirming that the winit example does work, I figured out that if I enabled decorations in my Alacritty configuration, then it would work.

So it looks like `set_minimized(true)` on macOS does not work unless decorations are enabled?

**Comment by Osspial** [comment]
cc @vbogaevsky
