### ISSUE TITLE
Semver problem with alpha versions

### ISSUE THREAD

**Issue by kvark** [rust-windowing/winit#1362]
Hi! We experience breakage from `winit` in gfx/wgpu crates. Apparently, cargo considers "xxx-alpha5" to be compatible with "xxx-alpha6", while your code actually breaks with each alpha update. This is very bad!
I suggest to change the naming scheme and potentially yank the current alpha releases.

**Comment by Osspial** [comment]
That seems like a weird call on Cargo's part - the semver spec [explicitly allows breakage in pre-release versions](https://semver.org/#spec-item-9). You should be able to lock to a specific version by setting the version string to `=xxx-alphaN`.

Fortunately, Winit `0.20` should be getting out of alpha within the next few days, and should stop getting breaking releases.

**Comment by kvark** [comment]
The call is not weird, it's just uneducated :) Well, now I see that this is the proper naming scheme.
We should therefore start using exact version requirements for `winit`. Thanks for the quick answer!

**Comment by kvark** [comment]
@Osspial this still bothers me, actually. So moving from alpha5 to alpha6 is a breaking change. Why does `cargo` then do this for us on `cargo update`? Cargo not following semver?

**Comment by Osspial** [comment]
I think Cargo is violating semver here, yeah.
