### ISSUE TITLE
Github CI actions causing spurious failure emails

### ISSUE THREAD

**Issue by murarth** [rust-windowing/winit#1370]
It seems that Github triggers the publish action on my fork of winit, resulting in my receiving a failure email any time I push new commits from upstream. Perhaps the publish action can be changed to require something akin to `repo-org == 'rust-windowing'`?

**Comment by Osspial** [comment]
It doesn't look like it. We could set publish to only run when a commit is tagged as a release, though.

**Comment by goddessfreya** [comment]
I don't seam to be experiencing anything on glutin, although I have `continue-on-error` enabled.

**Comment by murarth** [comment]
I've disabled Actions for my winit fork, which I suppose resolves this issue.
