### ISSUE TITLE
CursorMoved position is returns a PhysicalPosition with logical values inside it

### ISSUE THREAD

**Issue by aclysma** [rust-windowing/winit#1371]
I am using winit 0.20 on MacOS. I have a 13" MacBook Pro connected to a 1440p non-retina display.

Repro Steps:
 - Create a 900x600 window logically sized on a retina-scaled display.
 - Print the position field of the CursorMoved event when this event is fired
 - Move the mouse to the bottom right of the window and observe the output
 - Example code provided below

Expected:
 - When the window is on the retina display, the returned physical coordinates should be (1800, 1200) and when converted to logical coordinates should be (900, 600)

Observed
 - The PhysicalPosition returned in the CursorMoved event is returning (900, 600) and when converted to logical coordinates is (450, 300)

Notes
 - The window is sized as expected on both displays (1800x1200 on the retina display and 900x600 on the non-retina display in raw pixels)
 - When the window is moved to the non-retina display, the physical and logical coordinates from the event are the expected value of (900, 600)
 - scale_factor correctly changes to 2 on the Retina display and 1 on the non-retina display

```rust
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    simple_logger::init().unwrap();
    let event_loop = EventLoop::new();

    let window = WindowBuilder::new()
        .with_title("A fantastic window!")
        .with_inner_size(winit::dpi::LogicalSize::new(900.0, 600.0))
        .build(&event_loop)
        .unwrap();

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;
        //println!("{:?}", event);

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                window_id,
            } if window_id == window.id() => *control_flow = ControlFlow::Exit,
            Event::MainEventsCleared => {
                window.request_redraw();
            },
            Event::WindowEvent {
                event:
                    WindowEvent::CursorMoved {
                        device_id,
                        position,
                        ..
                    },
                ..
            } => {
                let logical_position = position.to_logical::<i32>(window.scale_factor());
                println!("Scale Factor: {}    Physical {:?}    Logical: {:?}", window.scale_factor(), position, logical_position);
            },
            _ => (),
        }
    });
}
```

**Comment by ilya-epifanov** [comment]
the same on Wayland
