### ISSUE TITLE
0.20 not compiling when targeting android

### ISSUE THREAD

**Issue by adrien-ben** [rust-windowing/winit#1393]
Hello,

I'm migrating my apps using winit from 0.19 to 0.20. So far it's been a rather painless process. But now I'm encountering an issue when trying to build an apk for android.

I generate the apk using [cargo apk](https://github.com/rust-windowing/android-rs-glue)'s docker image. But the process fails when trying to compile winit 0.20 because it encouters a bunch of imports that it is not able to resolve. 

You can find the build log output here : https://gist.github.com/adrien-ben/cedafcbfce1dbe2264b2f2eed005a99f and the github actions configuration here : https://github.com/adrien-ben/vulkan-triangle-rs/blob/winit020/.github/workflows/build.yml

Let me know if you need anything more.

**Comment by goddessfreya** [comment]
Dup: https://github.com/rust-windowing/winit/issues/948
