### ISSUE TITLE
Ability to set the initial background of a window

### ISSUE THREAD

**Issue by chichid** [rust-windowing/winit#1399]
Would it be possible to provide glutin with the initial background color to which a Glutin window can be set?

The feature can be very useful to handle the perceived performance of startup time where on some platforms, due to GPU problems, the window starts with an ugly white color then renders.

**Comment by goddessfreya** [comment]
In this case you would have to use platform-dependent methods to fill the windows contents before making the context. Forwarding this question to Winit, as this doesn't strike me as an issue with glutin.

It should be noted that a white window is not the standard behavior across all platforms. On X11, for example, you get a window filled with garbage, while on Wayland _no_ window shows up until you draw to it.

I believe @Osspial was hoping to solve a similar problem with [winit-blit](https://github.com/rust-windowing/winit-blit), although currently I think it only has a windows implementation.

**Comment by Osspial** [comment]
In the meanwhile, I've found that a good way to avoid showing garbage data to users is to initialize the window as hidden, and only show it after OpenGL is able to render an initial thing.

I'm going to close this issue since putting content in a window is explicitly out of scope for Winit, but thank you for asking the question!

**Comment by chichid** [comment]
@Osspial the problem with that is mainly perceived performance, as the user will click on the app icon and the window won't open immediately (which may end up with a false impression that apps developed in rust are slow :-). 

What I was hopping is to start the app with an initial background instead of garbage, and when opengl is initialized, then we render opengl.

If that's not in scope for glutin as @goddessfreya mentioned nor in the scope of winit, then I believe it has to be done using platform functions by the consumer of glutin using raw_contexts, otherwise I don't see other alternatives.

Thanks for your help!
