### ISSUE TITLE
Consider adding clippy on CI

### ISSUE THREAD

**Issue by kchibisov** [rust-windowing/winit#1402]
Right now clippy(stable branch) on `winit` (X11/Wayland backends) produces 1500 lines of warnings/errors, so I think it makes sense to at least take a look on them, since most of the time they actually make sense.

**Comment by MrGibus** [comment]
Just started working on some things on windows backend and noticed a few pointless shifts ```<< 0```. Ran clippy and it warned about a number of float comparisons and quite a bit of redundant code.
So I'd agree with this.
