### ISSUE TITLE
Redraw issue when resizing created window

### ISSUE THREAD

**Issue by EnCiprian** [rust-windowing/winit#1431]
OS = Windows 10
Rust version = 1.42.0 - nightly
winit version = 0.20.0

So i created a minimal example with winit. The example is basically the one provided in the examples in the git repository. 

`pub mod window_creation_module {

    use winit::{
        event::{Event, WindowEvent},
        event_loop::{ControlFlow, EventLoop},
        window::WindowBuilder,
    };

    pub fn create_window() {
        let event_loop = EventLoop::new();

        let window = WindowBuilder::new()
            .with_title("A fantastic window!")
            .with_inner_size(winit::dpi::LogicalSize::new(600.0, 400.0))
            .build(&event_loop)
            .unwrap();

        event_loop.run(move |event, _, control_flow| {
            *control_flow = ControlFlow::Wait;

            match event {
                Event::WindowEvent {
                    event: WindowEvent::CloseRequested,
                    window_id,
                } if window_id == window.id() => *control_flow = ControlFlow::Exit,
                Event::MainEventsCleared => {
                    window.request_redraw();
                },
                Event::RedrawRequested(_) => {
                    *control_flow = ControlFlow::Poll;
                },
                _ => (),

            }
        });
    }

}`
And the main function

`fn main() {
    rust_graphics::window_creation_module::create_window();
}`

The example works fine when creating the window. There are no issues here
![first_windows_creation](https://user-images.githubusercontent.com/51707540/73613895-b512ab80-4602-11ea-836e-ffd813887206.PNG)

The problem comes when trying to resize the window into a larger window. Then the resized area is a black screen which is not what i was expecting
![error_black_area_on_resize](https://user-images.githubusercontent.com/51707540/73613910-f2773900-4602-11ea-8809-50025b80de8d.PNG)

Can someone please help me and explain why this is the case, is this normal behaviour, is there something i am missing.

Thank you in advance.

PS: Apologies for the relative chaos of the code section, but github's insert code functionality does not seem to be working properly.

**Comment by goddessfreya** [comment]
You aren't drawing any content to the window, so what gets outputted is implementation-dependent garbage.

From: https://github.com/rust-windowing/winit/issues/1399
> It should be noted that a white window is not the standard behavior across all platforms. On X11, for example, you get a window filled with garbage, while on Wayland no window shows up until you draw to it.

**Comment by filnet** [comment]
I think we can close this issue as it is the expected behavior.

**Comment by EnCiprian** [comment]
Yes, that is correct, i will close the issue.
