### ISSUE TITLE
Wayland backend reporting incorrect window size in WindowEvent::Resized event

### ISSUE THREAD

**Issue by digitalstreamio** [rust-windowing/winit#1446]
Tested with version: winit 0.21 

I have an OpenGL app that opens a windowed context with inner size specified to some initial value (800x600).

While running on X11 backend, the size of the window reported by WindowEvent::Resized and window.inner_size() is consistent (800x600).

On Wayland backend, window height reported by Resized event is 30px less than value reported by window.inner_size(). (difference seems to be equal to window decoration height). If I use the values from the Resized event and set OpenGL's viewport, it results with a 30px black bar on top of the window, indicating that value reported by the event is incorrect and does not cover the whole inner part of the window . 

```
                WindowEvent::Resized(size) => {
                    info!("window resized {}x{}", size.width, size.height);
                    let size2 = ctx.platform.windowed_context.window().inner_size();
                    info!("window inner size {}x{}", size2.width, size2.height);
                }
```

Actual:

 Here is reported output.

> INFO [zinc64::ui::main] - window resized 800x570
> INFO [zinc64::ui::main] - window inner size 800x600

Exptected:

> INFO [zinc64::ui::main] - window resized 800x600
> INFO [zinc64::ui::main] - window inner size 800x600

**Comment by kchibisov** [comment]
Could you provide me log by applying the following diff?

```diff
diff --git a/src/platform_impl/linux/wayland/event_loop.rs b/src/platform_impl/linux/wayland/event_loop.rs
index 1ceedf19..eb22c195 100644
--- a/src/platform_impl/linux/wayland/event_loop.rs
+++ b/src/platform_impl/linux/wayland/event_loop.rs
@@ -719,10 +719,12 @@ impl<T> EventLoop<T> {
                         let physical_size = logical_size
                             .to_physical(window.new_dpi.unwrap_or(window.prev_dpi) as f64);

+                        println!("Setting inner size to a user ({},{})", w,h);
                         callback(Event::WindowEvent {
                             window_id,
                             event: WindowEvent::Resized(physical_size),
                         });
+                        println!("Applying inner size initial change ({},{})", w, h);
                         *window.size = (w, h);
                     }
                 }
diff --git a/src/platform_impl/linux/wayland/window.rs b/src/platform_impl/linux/wayland/window.rs
index 03b58b38..65ebd8f2 100644
--- a/src/platform_impl/linux/wayland/window.rs
+++ b/src/platform_impl/linux/wayland/window.rs
@@ -223,6 +223,7 @@ impl Window {
     pub fn inner_size(&self) -> PhysicalSize<u32> {
         let dpi = self.scale_factor() as f64;
         let size = LogicalSize::<f64>::from(*self.size.lock().unwrap());
+        println!("Reporting inner size of {:?}", size);
         size.to_physical(dpi)
     }

@@ -244,7 +245,9 @@ impl Window {
     pub fn set_inner_size(&self, size: Size) {
         let dpi = self.scale_factor() as f64;
         let (w, h) = size.to_logical::<u32>(dpi).into();
+        println!("Setting user requested inner size to ({},{})", w, h);
         self.frame.lock().unwrap().resize(w, h);
+        self.frame.lock().unwrap().refresh();
         *(self.size.lock().unwrap()) = (w, h);
     }

@@ -493,6 +496,7 @@ impl WindowStore {
                 wid: make_wid(&window.surface),
                 frame: opt_mutex_lock.as_mut().map(|m| &mut **m),
             });
+            println!("Setting inner size to {:?}", size);
             *window.size.lock().unwrap() = size;
             if let Some(dpi) = window.new_dpi.take() {
                 window.current_dpi = dpi;

```

**Comment by digitalstreamio** [comment]
> Setting inner size to (800, 600)
> Setting inner size to (800, 600)
> Sending inner size to a user (800,570)
> Reporting inner size of LogicalSize { width: 800.0, height: 600.0 }
> Applying inner size initial change (800,570)
> Setting inner size to (800, 570)
> Setting inner size to (800, 570)
> Setting inner size to (800, 570)

**Comment by kchibisov** [comment]
Ok, I've got an issue, you're calling inner_size on the same iteration of the event loop when you're getting resize, however inner_size will be updated only on a next tick of event_loop as far as I can see.  So the solution would be to update on the same tick of event loop.

**Comment by digitalstreamio** [comment]
I'm not sure, the window is built with initial inner_size = 800x600. Resize gets fired automatically when I go into the event_loop.run(). The problem is that the first Resized event that gets fired after opening the window reports the wrong size. I don't manually resize the window.

**Comment by digitalstreamio** [comment]
Also, I know the values in Resized event are wrong because if I use them to set GL viewport, they leave a 30px black bar on top of the window.

**Comment by kchibisov** [comment]
I mean resize is kind of correct, your inner_size is just recommendation on what to use, but your system could completely ignore it, so you can't rely on this value. You should only rely on resize events. For example tiling compositors like sway, don't mind your inner_size recommendation and just send you what to use.

**Comment by digitalstreamio** [comment]
Ok. but if I use the value from Resized event, GL viewport is messed up. See my comment above.

**Comment by kchibisov** [comment]
>I'm not sure, the window is built with initial inner_size = 800x600.

You're correct that window is built including decorations, this is a different issue. The issue is that inner_size() reporting a wrong size, since after resize we're calling back to your `run` function. so if you call `inner_size` it'll be a wrong value, and then on a next call to your `run` it'll update to a proper thing.

**Comment by digitalstreamio** [comment]
Got it. So inner size will be outdated. 

So back to my issue with values reported by Resized event. These do not seem correct as if I set up my viewport to use value reported by the event, it will span the whole inner part - 30px.

**Comment by kchibisov** [comment]
>Ok. but if I use the value from Resized event, GL viewport is messed up. See my comment above.

I wonder why you can't update it on resize and not rely on initial inner_size value? Like I don't really see a problem here and we(alacritty) are doing just fine here.

If you're interested, we're just updating viewport and our internal window size on each resize event.

A short snippet of our related GL code.

```rust
unsafe {
    gl::Viewport(
        size.padding_x as i32,
        size.padding_y as i32,
        size.width as i32 - 2 * size.padding_x as i32,
        size.height as i32 - 2 * size.padding_y as i32,
    );

    // update projection
    gl::UseProgram(self.program.id);
    self.program.update_projection(size.width, size.height, size.padding_x, size.padding_y);
    gl::UseProgram(0);
}
```

But I agree that your initial viewport could be messed up.

In theory you can mark that you need update to viewport when getting resize event and storing this size somewhere, and later on during `draw`, update viewport + draw.

**Comment by kchibisov** [comment]
Oh, wait, I've likely misunderstood your problem here. I feel like I've got a bug and the problem is likely related to decorations, etc. Since you'll be drawing correctly, but your mouse will go through the window and borders will be messed up, etc.

**Comment by digitalstreamio** [comment]
So I do update the viewport during Resized event and that's what is causing problems with not the whole inner part being used for viewport.
```
                WindowEvent::Resized(size) => {
                    self.video_renderer
                        .update_viewport(ctx, size.width as i32, size.height as i32);
                    Ok(Transition::None)
                }
```

**Comment by digitalstreamio** [comment]
If I increase the height reported by Resized event by 30 and call gl.viewport with it, then  everything works correctly.

**Comment by kchibisov** [comment]
Could you share some code to run? I'm not sure if I can repro your issue tbh.

**Comment by digitalstreamio** [comment]
Definitely. Let me put something together and I'll update this thread with the repo link.

**Comment by digitalstreamio** [comment]
Search for WindowEvent::Resized(size) in

https://github.com/digitalstreamio/zinc64/blob/wip/winit/zinc64/src/ui/main.rs

To run

> git clone https://github.com/digitalstreamio/zinc64
> git checkout wip/winit
> cargo run bin/SineAndGraphics.prg

Notice the black bar under the decorations. Now change src/ui/main.rs

from

> self.video_renderer.update_viewport(ctx, size.width as i32, size.height as i32);

to

> self.video_renderer.update_viewport(ctx, size.width as i32, size.height as i32 + 30);

Let me know if you need anything else.

**Comment by kchibisov** [comment]
Ehm, could you try without decorations? It seems like it's broken without them for me. In this case your inner_size and size from resize should be the same, so it'll be easier to trouble shoot.

**Comment by digitalstreamio** [comment]
I cannot get the Resized event to fire with decorations turned off so that could be a separate issue. I'm on Fedora 31 with Gnome 3.34.

**Comment by kchibisov** [comment]
Couldn't you start your window without decorations? It should be possible with `set_decorate(false)`.

**Comment by digitalstreamio** [comment]
Yep - did that. But it would never fire WindowEvent::Resized afterwards.

**Comment by digitalstreamio** [comment]
I changed platform.rs to do the following:

```
        let event_loop = glutin::event_loop::EventLoop::new();
        let window_builder = glutin::window::WindowBuilder::new()
            .with_title(title)
            .with_decorations(false)
            .with_resizable(true)
            .with_inner_size(glutin::dpi::LogicalSize::new(
                window_size.0 as f32,
                window_size.1 as f32,
            ));
        let windowed_context = glutin::ContextBuilder::new()
            .with_vsync(true)
            .build_windowed(window_builder, &event_loop)
            .unwrap();
````

**Comment by digitalstreamio** [comment]
It seems like surfaces used for resizing are not drawn, therefore I cannot manually resize the window. Also, the Resize event that I typically get after opening the window is no longer getting fired.

**Comment by digitalstreamio** [comment]
Keyboard may work. Just give me a sec.

**Comment by kchibisov** [comment]
GNOME has a shortcut to trigger resize for you. It's `Alt + F8` or something like that.

**Comment by digitalstreamio** [comment]
![Screenshot from 2020-02-09 19-26-56](https://user-images.githubusercontent.com/19243925/74113453-3671bd00-4b72-11ea-9b43-14d1a06e393f.png)

**Comment by digitalstreamio** [comment]
This is a bit odd.

With decorations turned off, resized event and window.inner_size() report pretty much equal values. However, when I resize the winow from 800x600 to ~950x600, the window surface is not resized, but my viewport actually tries to use the new window size.

**Comment by digitalstreamio** [comment]
![Screenshot from 2020-02-09 19-30-24](https://user-images.githubusercontent.com/19243925/74113513-a54f1600-4b72-11ea-9f81-acfc7d28356f.png)

Similarly, resizing the window down to smaller rectangle does not update the window surface, even though Resize event is fired and my viewport is updated correspondingly.

**Comment by kchibisov** [comment]
yeah, this is your issue, since inner_size and resized events are innocent and telling you correct thing. Alacritty is also handling everything with winit 0.21.0 just fine.

**Comment by digitalstreamio** [comment]
isn't winit managing window surface? i don't really do anything with it other than open window and attach gl context to it.

**Comment by digitalstreamio** [comment]
in my event loop, i only change gl.viewport to the value reported by Resized event.  how would that be wrong?

**Comment by digitalstreamio** [comment]
Ok - I think I may have found a problem with resizing. Looks like in Resized event, I need to call windowed_context.resize(physical_size).

**Comment by kchibisov** [comment]
Yeah, it fixes issue on my system and now you resize properly. Also I don't see any issue with CSD after that.

**Comment by kchibisov** [comment]
Also, you should call it before updating viewport.

**Comment by digitalstreamio** [comment]
Thanks for helping out with this. With the call to windowed_context.resize(size) in Resized event, everything else behaves properly. Cheers!

**Comment by kchibisov** [comment]
Could you open an issue about inner_size not equal to resized event? This is clearly a bug, so I won't miss it.

**Comment by kchibisov** [comment]
nvm, I've opened #1451 to track inner_size problem.
