### ISSUE TITLE
Wayland's theme close button icon color is not being picked up from custom theme.

### ISSUE THREAD

**Issue by digitalstreamio** [rust-windowing/winit#1448]
Tested version: winit 0.21

It looks like WaylandTheme's SCTKTheme impl calls the wrong function in get_close_button_icon_color(). Seems like a copy & paste error.

Actual:

> self.0.close_button_color(ButtonState::from_sctk(status))

Expected:

> self.0.close_button_icon_color(ButtonState::from_sctk(status))

```
impl<T: Theme> SCTKTheme for WaylandTheme<T> {
    fn get_close_button_color(&self, status: SCTKButtonState) -> [u8; 4] {
        self.0.close_button_color(ButtonState::from_sctk(status))
    }

    fn get_close_button_icon_color(&self, status: SCTKButtonState) -> [u8; 4] {
        self.0.close_button_color(ButtonState::from_sctk(status))
    }
}
```

**Comment by kchibisov** [comment]
Fixed one the latest master.
