### ISSUE TITLE
[wayland] title bar not receiving events

### ISSUE THREAD

**Issue by ruabmbua** [rust-windowing/winit#1455]
It seems, like the wayland title bar is currently broken in gome-shell. The title bar does not receive any focus / hover events, and clicking on it will focus the window below, and send the event to the other window.

You can also not grab the title bar, or use resize on any of the other surrounding surfaces.

```
gnome-shell --version
GNOME Shell 3.34.3

```

**Comment by kchibisov** [comment]
This is a gnome bug https://gitlab.gnome.org/GNOME/mutter/issues/1024

**Comment by kchibisov** [comment]
This bug should be fixed with gnome-shell v3.34.4, so there's no need to keep this issue around anymore . https://gitlab.gnome.org/GNOME/mutter/merge_requests/1040

**Comment by ruabmbua** [comment]
Tested on 3.34.4, seems to be fixed.
