### ISSUE TITLE
Crashes on Windows 10 1809 10.0.17763.1

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1458]
This was reported upstream in https://github.com/alacritty/alacritty/issues/3177.

It seems like on some Windows 10 systems, like Windows 10 Enterprise LTSC 1809, the new dark mode options are causing an assertion panic.

This assert is failing:
https://github.com/rust-windowing/winit/blob/83b60beba6ef53a10e3fa63eb0716372268ba199/src/platform_impl/windows/dark_mode.rs#L135-L138

**Comment by daxpedda** [comment]
Cc #1405.
