### ISSUE TITLE
How to hide mouse cursor?

### ISSUE THREAD

**Issue by nanolsn** [rust-windowing/winit#1464]
How to hide mouse cursor, and especially when the application is running?

**Comment by nanolsn** [comment]
Sorry for the question. I didn't immediately find how to get the window. Unfortunately, my IDE doesn't show all available methods.

```rust
event_loop.run(move |event, _, control_flow| {
        let w: &Window = windowed_context.window();
        w.set_cursor_visible(false);
}
```

**Comment by Osspial** [comment]
Good to know you found a solution! Since this question has been answered, I'm gonna close this issue.
