### ISSUE TITLE
No TouchPhase::Ended event on wayland

### ISSUE THREAD

**Issue by toger5** [rust-windowing/winit#1481]
There is no ended event.
Adding a print here:
https://github.com/alacritty/alacritty/blob/14dc170caafc47a46d4c040a17829b52d431bbcd/alacritty/src/event.rs#L567
`print!("{:?}", phase);` never prints Ended (only Started and Moved)

**Comment by kchibisov** [comment]
The same applies for X11 as well on my system, so I feel like it's more general problem.

**Comment by kchibisov** [comment]
I think this was long solved. But anyway the thing is that `End` may not ever appear on some systems actually, according to the Wayland protocol spec.
