### ISSUE TITLE
Window Destroyed Event Not Sent on X11

### ISSUE THREAD

**Issue by IGJoshua** [rust-windowing/winit#1486]
I copied mostly verbatim an example from the Usage section in the README and began adding on to it for my project, but I noticed that it seems like the `WindowEvent::Destroyed` event isn't triggered. Following is a minified version of the code:
```rust
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

const WINDOW_TITLE: &str = "Events Test";

fn main() -> ! {
    // Init code
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new()
        .with_title(WINDOW_TITLE)
        .build(&event_loop).unwrap();

    // Main loop
    event_loop.run(move |event, window_target, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::WindowEvent { event, window_id } if window_id == window.id() => {
                match event {
                    WindowEvent::CloseRequested => *control_flow = ControlFlow::Exit,
                    WindowEvent::Destroyed => {
                        // Cleanup resources
                        println!("Window was destroyed!");
                    }
                    _ => (),
                };
            }
            _ => (),
        }
    });
}
```
I'm aware of the LoopDestroyed event, which is functioning properly, so that's likely where I'll move deinit code to, however if I'm not misunderstanding this, I believe that `WindowEvent::Destroyed` should be sent before that occurs.

Platform is Arch Linux, with an NVIDIA Quadro M2000M graphics card, using X11, winit version is 0.21.0.

**Comment by murarth** [comment]
In my testing, `WindowEvent::Destroyed` is generated on X11 only when the `Window` instance is dropped. Therefore, if you want to trigger this event, you should change the `CloseRequested` arm to something that drops `window`; e.g. by wrapping `window` in an `Option` and setting it to `None`. Then, the `WindowEvent::Destroyed` arm could set `*control_flow = Exit;`. However, the best course of action, I think, is still to put any program deinit code in the handling of `LoopDestroyed`, as it is guaranteed to be the last event received.

Anyway, I don't believe this behavior is a bug, as I'm not seeing any guarantees in the documentation that `WindowEvent::Destroyed` will necessarily be generated before the loop ends if a `Window` instance is still alive.

**Comment by IGJoshua** [comment]
Ah, I see, so the semantics here differ from what I was expecting a bit, since setting the control flow to exit doesn't imply that the window will be closed, it's simply being automatically reclaimed when the OS sees the process exits. That makes sense to me. Thanks!
