### ISSUE TITLE
macOS: Repeated key's ReceivedCharacter cancelled by previous key's keyUp event

### ISSUE THREAD

**Issue by jayache80** [rust-windowing/winit#1488]
On macOS only, with some combinations of repeated keys, the action of releasing the first repeated key will cause the remaining repeated key to no longer call `ReceivedCharacter`.

Steps to reproduce:
1. Hold down <kbd>j</kbd> until it repeats
1. While still holding down <kbd>j</kbd>, hold down <kbd>k</kbd> until that repeats. (<kbd>j</kbd>'s `ReceivedCharacter`s will stop, superseded by <kbd>k</kbd>'s `ReceivedCharacter`s, as expected.)
1. Release <kbd>j</kbd> while still holding <kbd>k</kbd>. This causes <kbd>k</kbd>'s `ReceivedCharacter`s to stop.

Expected behavior:
1. Hold down <kbd>j</kbd> until it repeats
1. While still holding down <kbd>j</kbd>, hold down <kbd>k</kbd> until that repeats. (<kbd>j</kbd>'s `ReceivedCharacter`s will stop, superseded by <kbd>k</kbd>'s `ReceivedCharacter`s, as expected.)
1. Release <kbd>j</kbd> while still holding <kbd>k</kbd>. <kbd>k</kbd>'s `ReceivedCharacter`s should continue until <kbd>k</kbd> is released.

This causes much frustration to, say, `vim` and `less` users with "lazy fingers" while trying to scroll in a terminal emulator utilizing winit.

> Note: This happens, strangely, only with *some* key combinations. For example, trying the above steps with <kbd>a</kbd> and <kbd>s</kbd> will *not* reproduce this problem.

This is likely to be the cause of https://github.com/alacritty/alacritty/issues/2788

**Comment by kchibisov** [comment]
@chrisduerr it'll be nice if you can test it, since IIRC you don't have this issue on your macOS machine, so checking that it doesn't break anything could be a good check.

**Comment by jayache80** [comment]
I reopened https://github.com/rust-windowing/winit/pull/1489 to fix this issue. It would've also been fixed by https://github.com/rust-windowing/winit/pull/1449 but that has yet to be ironed out.
