### ISSUE TITLE
Changing window state from MainEventsCleared leads to undefined behavior

### ISSUE THREAD

**Issue by filnet** [rust-windowing/winit#1507]
This is a followup of the issue raised in this PR https://github.com/rust-windowing/winit/pull/1461#issuecomment-594669174

It is not an urgent issue as it possible to work around it.

In a nutshell changing the window state from `MainEventsCleared` is broken and hard to fix.
A user can write code like this:
```
Event::MainEventsCleared => {
    // change size
    window.set_inner_size(PhysicalSize::new(320, 240));
    // and sometimes later...
    match window.inner_size().into() {
        (320, 230) => {
            // do something...
        }
        _ => (),
    }
}
```
Note that this code expects the call to `set_inner_size` to be honored immediately. The new size must be effective upon return of the `set_inner_size` call in part because of the later call to `inner_size`.
The call to `inner_size` is perfectly legit though....
Also note that `set_inner_size` is just an example. There are other window state changing functions.

On current master for Windows, this code will behave strangely.
The expected `Event::Resized` event will not be emitted because the event loop is in the `MainEventsCleared` state. There will be a warning that his event is dropped.
On the other hand the `RedrawRequestedEvent` will be emitted right after `MainEventsCleared`.
So it sort of works. The call to `set_inner_size` is honored immediately and effective but the user code has to be aware that `Event::Resized` will not be emitted.

A more extreme case of this is changing the window state from `RedrawRequested`:
```
Event::RedrawRequested=> {
    game.renderWorld();
    window.set_inner_size(PhysicalSize::new(320, 240));
    game.renderSky();
}
```
That's really unsound but it is possible to do.

There should at least be a caveat in the documentation : https://docs.rs/winit/0.21.0/winit/event/enum.Event.html#variant.MainEventsCleared

Knowing how all other platforms behave would be great.

**Comment by filnet** [comment]
This issue is not restricted to Windows. I am pretty sure the issue discussed here applies in some form to other platforms and would like to discuss it here too.

**Comment by kchibisov** [comment]
No `MainEventsCleared` anymore.
