### ISSUE TITLE
Resized sometimes does not report the correct size on Wayland

### ISSUE THREAD

**Issue by kaimast** [rust-windowing/winit#1509]
**Steps to reproduce:**
1.Build the fullscreen example from this fork `https://github.com/kaimast/glutin`
2.Start the binary `./target/debug/examples/fullscreen`
3. Press `f` to leave fullscreen
4. Press `d` to enable window decorations. Make sure they are enabled. I sometimes need to move the window around for them to appear
5. Press `f` to enter fullscreen again.

**The result I get:**
There is a gap at the bottom of the screen (about the height of the window decorations)

**The expected result:**
The window should fill the entire screen like in the beginning

System: Ubuntu 20.04 on Wayland
Screen: 4k resolution with 2x scale factor

Can move this issue to glutin, if you think it is not winit related...

**Comment by kchibisov** [comment]
I can't repro your issue, but make sure you draw later on, glutin examples are not drawing in some cases. Also logging resize events could help us.

**Comment by kaimast** [comment]
Weird. I added a draw call to the resize handling but it does not make a different.

Also can you try to reproduce the following:
1. Exit fullscreen and enable window decorations
2. Maximize the window
3. Disable window decorations 
4. I now have a gap above the window where the window decorations where. 

One guess I have is that maybe removing the decorations does not trigger the resize event? Logging also shows that when entering fullscreen the resize event misses about 60 pixels in the report physical height of the window.

**Comment by kchibisov** [comment]
It seems like GNOME doesn't like this solution, and the order of events from it is strange tbh, while sway seems to handle everything correctly with CSD and the current code. I'll take a look at some point.

**Comment by kaimast** [comment]
Thanks! Let me know if you want me to do more debugging etc. I am pretty busy right now but I can also do some more investigation on the coding side, if needed.

**Comment by kaimast** [comment]
Not sure if this helps:

I have this issue with both wgpu and glutin. However I just tried the alacritty codebase and cannot reproduce the bug there.

**Comment by Ralith** [comment]
I've observed this issue when using `window.inner_size()` instead of the payload of a resize event.

**Comment by Ralith** [comment]
Where exactly is the wayland backend supposed to be adjusting `inner_size` to account for the decorations? `window.newsize` seems to be [set directly from an event](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/linux/wayland/window.rs#L94), which is then [passed directly to `window.size`](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/linux/wayland/event_loop.rs#L743) where [`window.inner_size()`](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/linux/wayland/window.rs#L252) fetches it, adjusting for DPI only.

**Comment by kchibisov** [comment]
Decorations are not part of winit and we shouldn't get resize events counting decorations, etc, I'll try to figure out what is causing it, but I feel like you're both using GNOME.

**Comment by Ralith** [comment]
> Decorations are not part of winit and we shouldn't get resize events counting decorations

Is this smithay-client-toolkit's bug then?

> I feel like you're both using GNOME

The behavior I observed was on GNOME, yeah, while not doing anything weird with winit (no fullscreen/decoration toggling).

**Comment by kchibisov** [comment]
I should repro and spend some time debugging it first,  but I'm not sure about this bug right now, since I can't repro it.
