### ISSUE TITLE
WindowBuilder::with_maximized does not work on Windows

### ISSUE THREAD

**Issue by yanchith** [rust-windowing/winit#1510]
Version: 0.22.0
Backend: Windows

Steps to reproduce:

1) Checkout the `v0.22.0` git tag
2) Modify `examples/window.rs` to do `WindowBuilder::with_maximized(true)` instead of `with_inner_size`
3) Observe the non-maximized window

Note that `Window::set_maximized` still works. Also other platforms I tested (X11 and macOS) seem to work.

I am willing to contribute a fix you'll have the patience with me 😄

**Comment by filnet** [comment]
I can reproduce the issue.
Problem comes from a call to `set_inner_size()` done in `platform_impl::windows::Window::init()`.
This call resets the MAXIMIZED flag after it was set.
```
    pub fn set_inner_size(&self, size: Size) {
        let scale_factor = self.scale_factor();
        let (width, height) = size.to_physical::<u32>(scale_factor).into();

        let window_state = Arc::clone(&self.window_state);
        let window = self.window.clone();
        self.thread_executor.execute_in_thread(move || {
            WindowState::set_window_flags(window_state.lock(), window.0, |f| {
                f.set(WindowFlags::MAXIMIZED, false)
            });
        });

        util::set_inner_size_physical(self.window.0, width, height);
    }
```
 Commenting out that call works around the issue.

**Comment by filnet** [comment]
@yanchith do you want to try to fix the issue ?

**Comment by yanchith** [comment]
@filnet I can try. The earliest I can get to it is the weekend.

**Comment by yanchith** [comment]
Hmm, a philosophical question I couldn't find an answer to in the docs:

`with_maximized` and `with_inner_size` are mutually exclusive. Does winit have a strategy which one wins if the caller sets both? Or is this pretty much defined by backend implementations?

**Comment by yanchith** [comment]
Oh, I see. I might have to rework the PR a bit.
