### ISSUE TITLE
WIndow Icons

### ISSUE THREAD

**Issue by frapa** [rust-windowing/winit#1527]
Hello,

I'm using winit because I'm using the Iced GUI library. I'm looking around but there seems to be no way to set window icons both in Iced and in winit. Is this correct? Does this functionality belongs to a library such as winit?

**Comment by Veykril** [comment]
If I'm not mistaken this is what you want https://docs.rs/winit/0.22.0/winit/window/struct.Window.html#method.set_window_icon?

**Comment by Osspial** [comment]
@Veykril's response is correct. I'm closing this issue since we expose methods for this.
