### ISSUE TITLE
Update core-foundation to 0.7

### ISSUE THREAD

**Issue by kvark** [rust-windowing/winit#1531]
This affects a number of other dependencies, like core-graphics, core-text, core-video, etc.
It would be useful to have WebRender's Wrench/Examples consistently using the same core-foundation dependency.

**Comment by kchibisov** [comment]
Was fixed in https://github.com/rust-windowing/winit/commit/3c38afdb4733572270805896160e8217a04051e9 and included in 0.22.2 release.
