### ISSUE TITLE
Panic when trying to buffer RedrawRequested event

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1535]
It seems like on Windows there's a chance for winit to panicking when a `RedrawRequested` event couldn't be sent without buffering.

The relevant code that is panicking is here:

https://github.com/rust-windowing/winit/blob/2f27f64cdb69978151e6b8e941658b7e742b1135/src/platform_impl/windows/event_loop/runner.rs#L107-L111

This condition has been hit by an Alacritty user:

https://github.com/alacritty/alacritty/issues/3590

**Comment by Osspial** [comment]
Thanks for the report! #1496 removes this panic so this shouldn't be an issue once that gets merged.
