### ISSUE TITLE
Using eventloop together with tokio

### ISSUE THREAD

**Issue by gzp-crey** [rust-windowing/winit#1539]
According to the documentation EventLoop::run hijacks the current thread an it acts as a blocking operation with respect to async/await infrastructure of the tokio. In tokio such function should be executed in a swap_blocking or block_in_place scope.
For swap_blocking it have to be Send, Sync and thus it cannot be use to wrapped the EventLoop::run in a swap block.
For block_in_places due to a limitation of tokio it cannot be used and panics.

So what is the correct form to keep the thread intact and integrate the two system. (I'm not trying to make the event loop async. It's just fine as it is. But I have some background loading functions those shall be async and spawned through tokio. (Ex downloading content from net). For now calling EventLoop::run from the tokio runtime (ex block_on) will stop executing my background async tasks.

Thanks.

**Comment by gzp-crey** [comment]
Never mind, an await was missing and the a task was never (a)waited, just created.

**Comment by FredrikNoren** [comment]
@gzp-crey I'm trying to do something like this as well. You wouldn't happen to have an example of how you solved it?
