### ISSUE TITLE
[Windows 10] Fullscreen does not interact well with alt-tab

### ISSUE THREAD

**Issue by alexheretic** [rust-windowing/winit#1540]
When alt-tabbing to another window while a winit window is fullscreen (either kind) the winit window keeps rendering on top.

## Steps to reproduce
* Checkout latest winit, ie d5609729cc5c23a1d74c8c25d3af9c3bc7512a6f
* `cargo run --example fullscreen`
* Select either **1** or **2**
* Select monitor _ie 0_
* Try to alt-tab into another window.

downstream: https://github.com/big-ab-games/robo-instructus/issues/235

**Comment by antonmarsden** [comment]
I have a fix for this, and will create a pull request soon, hopefully. Commenting out one line (as per below) ensures that alt-tab works correctly.

```
impl WindowFlags {
    fn mask(mut self) -> WindowFlags {
        if self.contains(WindowFlags::MARKER_FULLSCREEN) {
            self &= WindowFlags::FULLSCREEN_AND_MASK;
//            self |= WindowFlags::FULLSCREEN_OR_MASK;
        }
```

**Comment by alexheretic** [comment]
Hey guys I'm still experiencing this with 0.23. I'm mostly interested in fixing borderless fullscreen if that's easier...

**Comment by kchibisov** [comment]
If you're interested in fixing something take a look at #1542, I guess you can pick up it.
