### ISSUE TITLE
save/expose xlib visual

### ISSUE THREAD

**Issue by Slaide** [rust-windowing/winit#1545]
for vulkan compatibility, the xlib visual is needed to check for presentation support of a queue on the windows surface, this is currently impossible. according to the source code, the visual is used for window creation, and then discarded. there is no xlib function call to retrieve the visual used for creation of a given window, so this vulkan function is unusable with this library.

since the native window handles are retrieved via RawWindowHandle, please specify if the issue is related to that library, then i will open an issue there.

**Comment by murarth** [comment]
The xlib function [`XGetWindowAttributes`](https://tronche.com/gui/x/xlib/window-information/XGetWindowAttributes.html) appears to provide a `Visual` pointer to the caller. Is this not what you're looking for?

**Comment by Slaide** [comment]
I missed that one, and yes, that is what i am looking for.

I cannot figure out how to convert the Display pointer to some form of the x11 crates' Display, which is an enum, but this is not an issue of this crate, so i will close this issue.
