### ISSUE TITLE
Update Instant dependency for wasm32 target

### ISSUE THREAD

**Issue by FuriouZz** [rust-windowing/winit#1546]
Hello folks!
I tried to clone winit from the master branch and to build an example targeting `wasm32-unknown-unknown`. I fall into an error from `instant` dependency.
```
5   | pub struct Instant(f64);
    |                    ^^^ the trait `std::hash::Hash` is not implemented for `f64`
```

Few month ago, I made a [pull request](https://github.com/sebcrozet/instant/pull/10) accepted by the author. But the change is not published yet. I will crate an issue to the author's repository.

I tried the following command:
```
cargo build --target wasm32-unknown-unknown --example web --features web-sys
```

I got the same issue when building examples on `wgpu-rs`.

**Comment by ryanisaacg** [comment]
Just to confirm: this is waiting on instant updating to support Hash, yes?

**Comment by FuriouZz** [comment]
Yes! 😄

**Comment by FuriouZz** [comment]
Instant updated to 0.1.3 ! https://crates.io/crates/instant

**Comment by FuriouZz** [comment]
I did not notice, but the master branch will take all patch version of instant here https://github.com/rust-windowing/winit/blob/master/Cargo.toml#L24. I close this issue.
