### ISSUE TITLE
Windows' with_maximized(true) does not work

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1557]
This was originally reported to Alacritty in https://github.com/alacritty/alacritty/issues/2601.

When creating a window using `with_maximized(true)`, the window is not maximized but instead opened identically to `with_maximized(false)`.

It seems like this was fixed in Alacritty version 0.4.0 but since then it was introduced again. The winit fix happened during the big rework, so it got broken after that.

**Comment by Osspial** [comment]
Closing since this was addressed in #1515.
