### ISSUE TITLE
Resize event is only pushed when the user is done resizing.

### ISSUE THREAD

**Issue by VZout** [rust-windowing/winit#1559]
Currently when resizing a window the resize event is only pushed when the user lets go of the left mouse button. This prevents the application from redrawing while resizing.

A middle ground solution to this could be pushing the resize event when the user has stopped moving the mouse after x amount of time instead of after releasing the mouse button. But preferably I'd like to be able to handle this myself.

(Only tested on Windows)

**Comment by Osspial** [comment]
Can you post a code sample that reproduces this? I'm not seeing this behavior when I test it with the `window` example.

**Comment by tim-weis** [comment]
Windows uses 2 messages to communicate window resizing operations: [WM_SIZE](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-size) and [WM_SIZING](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-sizing). The former is sent to a window after the user is done resizing it, whereas the latter is sent to a window while a resize operation is in flight.

winit only appears to be [handling `WM_SIZE`](https://github.com/rust-windowing/winit/blob/b4c6cdf9a33530a2116f37a21547341c34537be1/src/platform_impl/windows/event_loop.rs#L892), which might explain the observed behavior.

There are also the related [WM_WINDOWPOSCHANGED](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-windowposchanged) and [WM_WINDOWPOSCHANGING](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-windowposchanging) messages. While winit does [handle the latter](https://github.com/rust-windowing/winit/blob/b4c6cdf9a33530a2116f37a21547341c34537be1/src/platform_impl/windows/event_loop.rs#L829), it doesn't appear to be forwarding any events from there.

**Comment by filnet** [comment]
I am using winit 0.22.1 on Windows 10 and resizing works well.

**Comment by VZout** [comment]
I believe it is a known bug after looking through the code. It happens with `run_return`

**Comment by Osspial** [comment]
It sounds like the behavior you're talking about is described in the [`run_return`](https://docs.rs/winit/0.22.1/winit/platform/desktop/trait.EventLoopExtDesktop.html#tymethod.run_return) documentation, and there's nothing we can do to fix that. I'm going to close this issue in light of that.
