### ISSUE TITLE
Inputs propagated on web, regardless of focus

### ISSUE THREAD

**Issue by AnthonyYoManz** [rust-windowing/winit#1573]
Handling keyboard inputs such as arrow keys does not stop propagation when deploying with stdweb. In the case of arrow keys and the space bar, the browser then also gets these events and responds to them by scrolling. 

In my case I am working on a game in Quicksilver which uses winit in its dependency tree, and I would like to use arrow keys for the controls. Unfortunately, if there is a scroll bar on the page hosting my game then pressing up or down scrolls away from the game view.

stdweb's `IEvent` trait includes `stop_propagation` and `stop_immediate_propagation` functions which would likely solve this problem if called after handling each event.

**Comment by ryanisaacg** [comment]
Can you try #1576 and see if that fixes the issue?

**Comment by AnthonyYoManz** [comment]
I've just tested and it doesn't appear to have fixed it, although looking at the changes it appears as if it shouldn't have been happening at all beforehand either. I'll put together a more minimal test tomorrow so it's easier + faster to reproduce the issue and test fixes than with what I'm using at the moment.

**Comment by AnthonyYoManz** [comment]
By preventing default behaviour on mouse clicks, canvases cannot gain focus and therefore can't even capture keyboard inputs. If we move `prevent_default()` calls into the closures that handle key presses and mouse wheel movements then I think we're good to go?

**Comment by ryanisaacg** [comment]
This is a bug I hadn't even anticipated! I pushed up a version with only key press and mouse wheel prevent_defaults. Let me know if *that* one works.

**Comment by AnthonyYoManz** [comment]
On account of compiler errors it does not, but once they're fixed (just needed to import the `IEvent` trait) it works as expected.
