### ISSUE TITLE
Wayland - Window has incorrect inner_size due to decorations

### ISSUE THREAD

**Issue by JMS55** [rust-windowing/winit#1575]
1. Create a window with inner_size (x, y) on wayland
2. The window actually has (x, y-30) inner_size. 30 pixels seem to be given to the decorations instead.
3. Immediately after starting, a WindowEvent::Resized event is sent, with new_size (x, y-30)

**Comment by kaimast** [comment]
Probably the same problem as #1509 ?

**Comment by kchibisov** [comment]
seems like it.
