### ISSUE TITLE
Add window.get_decorations() and window.get_maximized()

### ISSUE THREAD

**Issue by JMS55** [rust-windowing/winit#1577]
I want to listen for a button press, and then toggle maximization and window decorations. However, there is no way to get the current state, and keeping track of it myself breaks if the user maximizes the window manually.

As a side note; I feel like it should really be named `window.get_decorated()`, since it returns a bool.

**Comment by kchibisov** [comment]
Those decorations are managed by the system, unless you want that on Wayland? Some compositors don't support maximization at all and default buttons should work.

**Comment by JMS55** [comment]
Winit already has set versions of these methods for all platforms, so I assumed that getters would be possible. 

I actually wanted borderless fullscreen, and initially I didn't use set_fullscreen() because I thought it wasn't possible on wayland, but I've just read through the docs again and realized that exclusive fullscreen was not possible, but borderless should be fine. My bad on misreading it, I don't really need these setters anymore, close this issue if you don't think it's necessary.

**Comment by kchibisov** [comment]
The issue is that the decorations part won't work at least on Wayland/X11 (maybe wWndows too) I guess, since those are not managed by winit, but by system, so you're not aware of any buttons, etc. So it's not really possible to implement.
