### ISSUE TITLE
[Android] `raw_window_handle` usage requirements are inobvious

### ISSUE THREAD

**Issue by Friz64** [rust-windowing/winit#1588]
On android, when creating a window and then (pretty much) immediately requesting it's raw window handle, winit will panic at [src/platform_impl/android/mod.rs:418](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/android/mod.rs#L418): `native window null`.

This is because the code will call into [android-ndk-rs:ndk-glue/src/lib.rs:68](https://github.com/rust-windowing/android-ndk-rs/blob/867d2344d9c3aca3ce3fc45af98adb81c8ec1912/ndk-glue/src/lib.rs#L50), which then tries to read the native window, which is not yet set because it's [callback](https://github.com/rust-windowing/android-ndk-rs/blob/867d2344d9c3aca3ce3fc45af98adb81c8ec1912/ndk-glue/src/lib.rs#L230) has not arrived yet.

I can currently reliably reproduce this issue on my Google Pixel 4.

I'm not sure whether this issue should be in the winit repo or the [android-ndk-rs](https://github.com/rust-windowing/android-ndk-rs) repo, feel free to transfer it.

**Comment by TheRawMeatball** [comment]
I ran into this issue as well, and fixed it with this snippet:
```
println!("Waiting for NativeScreen");
loop {
    match ndk_glue::native_window().as_ref() {
        Some(_) => {
            println!("NativeScreen Found:{:?}", ndk_glue::native_window());
            break;
        },
        None => ()
    }
}
```

And, instead of just putting this in the documentation, wouldn't it be better to add an awaitable method so that not everyone has to implement this waiting logic?

**Comment by dvc94ch** [comment]
It's incorrect to do that. The native window will be None again. You can only use it between the resume/suspend events

**Comment by sotrh** [comment]
> ... You can only use it between the resume/suspend events

Would that mean `Event::Resumed` and `Event::Suspended` @dvc94ch ?

**Comment by dvc94ch** [comment]
Yes
