### ISSUE TITLE
[Wayland/X11] Perceived inconsistency between docs and surprising actual behaviour

### ISSUE THREAD

**Issue by Abendstolz** [rust-windowing/winit#1594]
Hello!

Today I got a little stuck with the following (trivial) problem while working on a very simple FPS style camera.

There were three things I initially wanted from `winit`:

1) `hide` the mouse_cursor, 
2) `grab` it 
3) and also `set_cursor_position` to the middle of the screen every update so that I only have to deal with the mouse position delta, but the user isn't restrained by the bounds of the window. (Else you can only turn around until the mouse cursor, albeit invisible, hits the border of the screen, so no _slow_ 360° turn)

*Issue 1*:
I found out that `set_cursor_position` isn't supported on `Wayland` [impl](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/linux/wayland/window.rs#L386).
I assume that's due to some restriction in the protocol itself? The [docs](https://docs.rs/winit/0.22.2/winit/window/struct.Window.html#method.set_cursor_position) fail to mention this btw.
I found out due to a `panic`

*Issue 2*:
At the same time the [docs](https://docs.rs/winit/0.22.2/winit/window/struct.Window.html#method.set_cursor_grab) say this, regarding `set_cursor_grab`:

> Wayland: This presently merely locks the cursor in a fixed location, which looks visually awkward."

Not only that it looks awkward (if the cursor is visible) - it also means that there is no `WindowEvent::CursorMoved` being sent anymore (although there is a `DeviceEvent::MouseMotion`) - as I am also using [winit_input_helper](https://github.com/rukai/winit_input_helper) - by the wonderful @rukai - which uses `WindowEvent::CursorMoved` internally, I couldn't move my camera on `wayland`, until I manually switched to `DeviceEvent::MouseMotion`.

Now I am aware that the docs for `WindowEvent::CursorMoved` state: 
> it should not be used to implement non-cursor-like interactions such as 3D camera control

but that is not my point. 

To clarify it:
Precondition: `set_cursor_grab(true)`

On `X11` (set via `export WINIT_UNIX_BACKEND=x11`): `WindowEvent::CursorMoved` events still fired.
On `Wayland`: `WindowEvent::CursorMoved` events _NOT_ fired.

Is this intended behaviour? If so, one could argue that the `docs` should mention this - because it's more than just a little `visually awkwardness`.

**Comment by kchibisov** [comment]
>On Wayland: WindowEvent::CursorMoved events NOT fired.

It could be an impl issue tbqh on Wayland, I really don't see any reason why are those DeviceEvents. I'll take a look once I have time.

**Comment by kchibisov** [comment]
Closing in favor of #1678
