### ISSUE TITLE
Is a custom game loop without EventLoop possible?

### ISSUE THREAD

**Issue by MarioSieg** [rust-windowing/winit#1596]
Hey,
I would like to integrate winit into an existing game engine, which currently uses glfw-rs as window library. The library looks great so far I only wonder if it is possible to just poll events without a thread freezing loop because the engine has it's own huge kernel loop. So I would just like to call something to get the events each engine tick. Is that possible?

Thanks in advance,

Mario

**Comment by kchibisov** [comment]
I guess you can do something like that with `run_return` tbqh and just process events in batches and store them into some queue, but polling on demand is not there anymore.

**Comment by MarioSieg** [comment]
Thank you for your response!
Unfortunately, we will stick to GLFW then because we do not want to change our game loop.
Thank you anyways :)
