### ISSUE TITLE
[Android] Panicked at 'native window null'

### ISSUE THREAD

**Issue by sotrh** [rust-windowing/winit#1598]
Phone used: Moto E4 Plus
Android version: 7.1.1
Dev OS: Linux Mint 19

I've created a repo with the code for this issue.
https://github.com/sotrh/wgpu-on-android

I've included the relevant LogCat entries below. I included some debug statements so you can find the line before the panic.

06-06 17:37:18.287 16307 16321 I RustStdoutStderr: src/lib.rs:169 Creating event_loop
06-06 17:37:18.287 16307 16321 I RustStdoutStderr: src/lib.rs:171 Creating window
06-06 17:37:18.288 16307 16321 I RustStdoutStderr: src/lib.rs:178 Creating state
06-06 17:37:18.288 16307 16321 I RustStdoutStderr: src/lib.rs:21 Getting window size
06-06 17:37:18.318 16307 16321 I RustStdoutStderr: src/lib.rs:24 Creating instance
06-06 17:37:18.330 16307 16321 I RustStdoutStderr: src/lib.rs:26 Creating surface
06-06 17:37:18.331 16307 16321 I RustStdoutStderr: thread '<unnamed>' panicked at 'native window null', /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/android/mod.rs:418:13
06-06 17:37:18.331 16307 16321 I RustStdoutStderr: stack backtrace:
06-06 17:37:18.331 16307 16321 I RustStdoutStderr:    0: <unknown>
06-06 17:37:18.332 16307 16321 I RustStdoutStderr:    1: <unknown>
06-06 17:37:18.332 16307 16321 I RustStdoutStderr:    2: <unknown>
06-06 17:37:18.332 16307 16321 I RustStdoutStderr:    3: <unknown>
06-06 17:37:18.333 16307 16321 I RustStdoutStderr:    4: <unknown>
06-06 17:37:18.333 16307 16321 I RustStdoutStderr:    5: <unknown>
06-06 17:37:18.333 16307 16321 I RustStdoutStderr:    6: <unknown>
06-06 17:37:18.333 16307 16321 I RustStdoutStderr:    7: <unknown>
06-06 17:37:18.333 16307 16321 I RustStdoutStderr:    8: <unknown>
06-06 17:37:18.333 16307 16321 I RustStdoutStderr:    9: <unknown>
06-06 17:37:18.334 16307 16321 I RustStdoutStderr:   10: <unknown>
06-06 17:37:18.334 16307 16321 I RustStdoutStderr:   11: <unknown>
06-06 17:37:18.334 16307 16321 I RustStdoutStderr:   12: <unknown>
06-06 17:37:18.334 16307 16321 I RustStdoutStderr:   13: <unknown>
06-06 17:37:18.334 16307 16321 I RustStdoutStderr:   14: <unknown>
06-06 17:37:18.335 16307 16321 I RustStdoutStderr:   15: <unknown>
06-06 17:37:18.335 16307 16321 I RustStdoutStderr:   16: <unknown>
06-06 17:37:18.335 16307 16321 I RustStdoutStderr:   17: <unknown>
06-06 17:37:18.335 16307 16321 I RustStdoutStderr:   18: <unknown>
06-06 17:37:18.335 16307 16321 I RustStdoutStderr:   19: <unknown>
06-06 17:37:18.335 16307 16321 I RustStdoutStderr:   20: <unknown>
06-06 17:37:18.335 16307 16321 I RustStdoutStderr:   21: <unknown>
06-06 17:37:18.336 16307 16321 I RustStdoutStderr:   22: <unknown>
06-06 17:37:18.336 16307 16321 I RustStdoutStderr:   23: <unknown>
06-06 17:37:18.336 16307 16321 I RustStdoutStderr:   24: <unknown>
06-06 17:37:18.336 16307 16321 I RustStdoutStderr:   25: <unknown>
06-06 17:37:18.336 16307 16321 I RustStdoutStderr:   26: <unknown>
06-06 17:37:18.336 16307 16321 I RustStdoutStderr:   27: <unknown>
06-06 17:37:18.337 16307 16321 I RustStdoutStderr:   28: <unknown>
06-06 17:37:18.337 16307 16321 I RustStdoutStderr:   29: <unknown>
06-06 17:37:18.337 16307 16321 I RustStdoutStderr:   30: <unknown>
06-06 17:37:18.337 16307 16321 I RustStdoutStderr:   31: <unknown>
06-06 17:37:18.337 16307 16321 I RustStdoutStderr:   32: <unknown>
06-06 17:37:18.337 16307 16321 I RustStdoutStderr:   33: <unknown>
06-06 17:37:18.338 16307 16321 I RustStdoutStderr:   34: <unknown>
06-06 17:37:18.338 16307 16321 I RustStdoutStderr:   35: <unknown>
06-06 17:37:18.338 16307 16321 I RustStdoutStderr:   36: <unknown>
06-06 17:37:18.338 16307 16321 I RustStdoutStderr:   37: <unknown>
06-06 17:37:18.338 16307 16321 I RustStdoutStderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

It seems that the stack trace isn't rendering to string correctly as well.

**Comment by francesca64** [comment]
Thanks for reporting this! To me this looks like a duplicate of #1588; do you agree?

**Comment by sotrh** [comment]
I'm inclined to agree. I'll close this for now. I'll reopen this if the fox for the other issue doesn't solve my problem.
