### ISSUE TITLE
[Windows] Dialogs and message boxes causes crash

### ISSUE THREAD

**Issue by VZout** [rust-windowing/winit#1602]
https://github.com/rust-windowing/winit/commit/b4c6cdf9a33530a2116f37a21547341c34537be1 (https://github.com/rust-windowing/winit/pull/1496) Causes message boxes and dialog to crash the application with the following error:
```
panicked at 'either event handler is re-entrant (likely), or no event handler is registered (very unlikely)', C:\Users\viktor.zoutman\.cargo\git\checkouts\winit-6811b72f73e0b798\0d0159d\src\platform_impl\windows\event_loop\runner.rs:235:37
```

This happens with `run_return` but haven't tested it with `run`. You can repro by using `msgbox` or `nfd2`

Tagging @Osspial as author and @filnet as co-author.

**Comment by VZout** [comment]
Just tested it on the `window` example. Also crashes there.

**Comment by Osspial** [comment]
Thanks for the report! Could check to see if #1615 fixes this issue for you?

**Comment by VZout** [comment]
@Osspial Sorry for the late response. I completely forgot about this issue. #1615 did indeed fix it!
