### ISSUE TITLE
On macOS, focused windows do not receive mouse events with the mouse outside of the window

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1609]
It seems like all other platforms receive mouse events when the mouse is pressed down to keep focus on the window and it is then moved outside of it. But on macOS that does not seem to be the case. Instead, no more events are received at all for mouse motion, though releasing the LMB will result in a release event.

In fact, since the events are bundled it's possible that when the mouse is moved quickly, the last mouse position before the cursor left the window is far from the border where it left. During a selection this leads to a big gap making it difficult to select until the border or to scroll using the selection.

**Comment by kchibisov** [comment]
It seems like a duplicate of #1599 to some point. However your issue is a bit more generic, but in anyway, doing things only when implicit grab is presented makes sense? Though, you're expecting that implicit grabs are a thing on macOS...

**Comment by chrisduerr** [comment]
I think we can close this as duplicate.
