### ISSUE TITLE
[Wayland] Slow keypress handler causes the event to trigger multiple times

### ISSUE THREAD

**Issue by JMS55** [rust-windowing/winit#1614]
When you do something like this
```rust
Some(VirtualKeyCode::Key2) => {
    std::thread::sleep(Duration::from_secs(2)); // Could be any long operation, sleep is just an example
    dbg!("done");
}
```
You would expect that the window freezes for 2s, prints "done", and then continues. This is what happens on x11.
On Wayland however, instead it freezes for 2s, prints done, then freezes for 2s, prints done again, repeat infinitely. 

`winit = 0.22.2`

**Comment by kchibisov** [comment]
This could be related to a thing that on Wayland, repeat is done by clients, not by display server, so something could go out of sync on a client side, and I guess it's much more sensitive to sleeps like that. But yeah, I can repro your issue and I bet timers are borken in that case. Or winit somehow messes things up here...

**Comment by JMS55** [comment]
I tested this some more, it's actually also an issue on x11, just not as badly for some reason.

**Comment by JMS55** [comment]
On x11, doing this prints "done" 3 times, instead of the expected 2. Uncommenting the Pressed check gives the expected 1 print only. So x11 is also kinda broken?
```rust
event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Poll;

    match event {
        Event::WindowEvent { event, .. } => match event {
            WindowEvent::CloseRequested => *control_flow = ControlFlow::Exit,
            WindowEvent::KeyboardInput { input, .. } => {
                // if input.state == ElementState::Pressed {
                    thread::sleep(Duration::from_secs(2));
                    dbg!("done");
                // }
            }
            _ => {}
        },
        _ => (),
    }
});
```

**Comment by JMS55** [comment]
Everything's fixed! On both X11 and Wayland, it prints 2 times, or 1 time if wrapped in `if input.state == ElementState::Pressed`.

**Comment by kchibisov** [comment]
I haven't touched X11 at all, so it's placebo.

**Comment by JMS55** [comment]
Weird that X11 works now then, maybe my game was just being weird before. Thanks for all the work on fixing wayland stuff though!

**Comment by kchibisov** [comment]
The patch haven't yet merged, so opening it for now.
