### ISSUE TITLE
Is it possible to open a window without blocking the main thread?

### ISSUE THREAD

**Issue by LukasBombach** [rust-windowing/winit#1628]
Hello 👋

I am fairly new to Rust and I don't know if this is purely a bug tracker or if it is ok to ask questions here. If not, feel free to tell me.

I am trying to bridge `winit` to `Node.js` using [neon-bindings](https://neon-bindings.com/). For this, I just created this very simple class and was trying to build on the simplest example in the docs:

```rust
#[macro_use]
extern crate neon;

use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

pub struct Canvas();

declare_types! {
    pub class JsCanvas for Canvas {
        init(mut _cx) {
            Ok(Canvas())
        }

        method open(mut _cx) {

            let event_loop = EventLoop::new();
            let window = WindowBuilder::new().build(&event_loop).unwrap();

            event_loop.run(move |event, _, control_flow| {
                *control_flow = ControlFlow::Poll;
                *control_flow = ControlFlow::Wait;
                match event {
                    Event::WindowEvent {
                        event: WindowEvent::CloseRequested,
                        ..
                    } => {
                        println!("The close button was pressed; stopping");
                        *control_flow = ControlFlow::Exit
                    },
                    Event::MainEventsCleared => {
                        window.request_redraw();
                    },
                    Event::RedrawRequested(_) => {
                    },
                    _ => ()
                }
            });
        }
    }
}

register_module!(mut cx, {
    cx.export_class::<JsCanvas>("Canvas")?;

    Ok(())
});
```

This allows me to do this in JavaScript:

```js
var { Canvas } = require("../native");

const canvas = new Canvas();
console.log("post canvas");

canvas.open();
console.log("post open");
```

However, this also blocks the main thread so `console.log("post open");` will actually never be called (unless I close the window). 

I tried putting everything in a thready

```rust
declare_types! {
    pub class JsCanvas for Canvas {
        init(mut _cx) {
            Ok(Canvas())
        }

        method open(mut _cx) {

            thread::spawn(move || {

              // same window code as above here

            });

            Ok(JsUndefined::new().upcast())

        }
    }
}
```

but that just does not open a window. I wonder if you can help me here to understand the issue, it would be totally enough if you point me to something I should read or learn about.

Any help appreciated.

Cheers

**Comment by dhardy** [comment]
I suspect the right way to do this is either to do window-management in the main thread and JS in a separate thread, handling thread communication yourself, or to do everything in the main thread and only run JS functions within the winit event handling loop.

**Comment by LukasBombach** [comment]
I see, seems like a long road for me still. Thank you!
