### ISSUE TITLE
Support building without decorations

### ISSUE THREAD

**Issue by Ralith** [rust-windowing/winit#1629]
winit supports applications with no or custom decorations (as is common in e.g. modern web browsers) via `Window::set_decorations`, but applications which unconditionally disable decorations still pay a high dependency cost for the unused capabilities on Wayland. https://github.com/rust-windowing/winit/issues/774 addressed this when Wayland support isn't desired, but for applications which *do* want to support Wayland and which will manage their own decorations, we should provide a lighter experience by supporting builds without that functionality, perhaps by gating it behind an enabled-by-default feature.

This is particularly useful for applications which rely on a Rust-native GUI toolkit whose style/fonts/etc would otherwise clash with an externally-provided titlebar, and for applications like games which don't have much need for conventional decorations and may already have their own drawing code which can more cheaply and attractively fill the role.

I understand that on Wayland this may also require introducing some new interfaces, e.g. to allow application or toolkit code to perform a resize in response to a user input that only the application or toolkit code is in a position to interpret.

**Comment by kchibisov** [comment]
I think this is all done, if something is still missing let me know.

You simply should build without decorations and then you can draw whatever you want yourself on your main surface.

If particular APIs are required open separate issues for each thing you want and they'll be added.

**Comment by Ralith** [comment]
If the `wayland-csd-*` features are disabled, winit will no longer pull in e.g. text rendering libs?

**Comment by kchibisov** [comment]
The only libs that winit pull for text drawing are the `adwaita` thing, if you disable `adwaita` related stuff it won't pull the text rendering or any rendering libs.

It'll pull the solid color drawing, but it's just a bunch of memsets, which I think is still fine?

**Comment by Ralith** [comment]
Sounds good!
