### ISSUE TITLE
How to draw on Window?

### ISSUE THREAD

**Issue by DenizBasgoren** [rust-windowing/winit#1633]
I would like to draw a rectangle on (10,10) with size (30,20) on window 1 for example. I believe most platforms provide methods like fillRect(x,y,w,h) or at least PutPixel(x,y) for each window. My understanding is that at the fundamental level a raw buffer of pixels is provided by X, WinAPI etc. It is not clear in the documentation how to reach this buffer and edit it manually. I think that is how libraries like glutin are built on top pf winit: by editing the buffer. I think it must be doable from  Window objects, or better from raw_window_handle objects.

My request is that (if this api exists) please add documentation and examples, and if it doesnt exist, consider implementing.

**Comment by dhardy** [comment]
Winit does not provide a draw API, only a [raw window handle](https://crates.io/crates/raw-window-handle). I believe that would be beyond the scope of this library.

Libraries such as [Lyon](https://docs.rs/lyon/0.15.9/lyon/) and [euc](https://lib.rs/crates/euc) provide software rendering and [wgpu](https://github.com/gfx-rs/wgpu-rs) hardware rendering. More examples on how to match those up may be useful?

**Comment by DenizBasgoren** [comment]
I will try to use these libraries, thanks
