### ISSUE TITLE
[macos] add NSWindow.hasShadow support

### ISSUE THREAD

**Issue by TakWolf** [rust-windowing/winit#1635]
![image](https://user-images.githubusercontent.com/6064962/88664248-62c4ca00-d10f-11ea-8e04-3523818a9a1f.png)

https://github.com/servo/core-foundation-rs/blob/4b1ccbb467843d97a1b2ce89874c18524d8f813b/cocoa/src/appkit.rs#L909-L910

**Comment by TakWolf** [comment]
I create a PR here try to so solve this.

https://github.com/rust-windowing/winit/pull/1637

**Comment by francesca64** [comment]
Fixed via #1637
