### ISSUE TITLE
On Windows, `set_outer_position` does not accept negative coordinates anymore

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1640]
This has been reported to Alacritty in https://github.com/alacritty/alacritty/issues/4061.

**Comment by Osspial** [comment]
Could you provide more details? `WindowBuilder` doesn't have a `with_position` method, and the following example properly sets the window position to `(-200, -200)` on my system:

```rust
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    simple_logger::init().unwrap();
    let event_loop = EventLoop::new();

    let window = WindowBuilder::new()
        .with_title("A fantastic window!")
        .with_inner_size(winit::dpi::LogicalSize::new(500.0, 500.0))
        .build(&event_loop)
        .unwrap();
    window.set_outer_position(winit::dpi::PhysicalPosition::new(-200, -200));

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;
        // println!("{:?}", event);

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                window_id,
            } if window_id == window.id() => *control_flow = ControlFlow::Exit,
            Event::MainEventsCleared => {
                println!("{:?}", window.outer_position());
                window.request_redraw();
            }
            _ => (),
        }
    });
}
```

**Comment by chrisduerr** [comment]
I'm sorry, I'm talking about set_position not with_position.

It might be interesting to see if @darsain can reproduce the problem with this example, since he reported the issue.

**Comment by chrisduerr** [comment]
Turns out this was due to a bug introduced in Alacritty, my bad.

**Comment by chrisduerr** [comment]
I'd like to add that this problem could have been prevented if the type the `set_outer_position` takes wouldn't perform a lossy conversion between the different positions. So it's a bit unfortunate that the typesystem isn't fully used here.
