### ISSUE TITLE
running event_loop in non main thread

### ISSUE THREAD

**Issue by maitysubhasis** [rust-windowing/winit#1641]
I see that the event_loop have to be created in in a main thread and the event_loop is neither Sync not Send.
Is there any way to wrap the `event_loop::run()` into a task/thread which can then send the event from the `run` method to a channel to be consumed by other thread?

**Comment by kchibisov** [comment]
I'd just say, that there's a reason behind event loop being neither send nor sync. For example, on Wayland, you should send requests to a server on a thread the objects, and event queue is presented, and so everything should be ensured that on a thread, where your event loop is.

However there's no hard **requirement** to create on a main thread, and there's an API to create on other threads, which could panic on platforms, where such things are not allowed.

On ios, the system isn't allowing you to create something on non-main thread.

**Comment by maitysubhasis** [comment]
thanks
