### ISSUE TITLE
addding macOS trackpad events

### ISSUE THREAD

**Issue by adamnemecek** [rust-windowing/winit#1648]
I'm considering adding support for trackpad gesture events on macOS, like magnify, rotate an swipe.

https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/HandlingTouchEvents/HandlingTouchEvents.html

**Comment by Jim-Eckerlein** [comment]
Magnification and rotation have been implemented and merged in #2157

**Comment by Jim-Eckerlein** [comment]
Mac multi-touch gestures: https://support.apple.com/en-us/HT204895

**Comment by Jim-Eckerlein** [comment]
Smart magnification PR: #2554
