### ISSUE TITLE
Disabling logging in release builds

### ISSUE THREAD

**Issue by adamnemecek** [rust-windowing/winit#1649]
Right now, winit generates a too much logging information. It might be a good idea to disable this in the release build.

**Comment by katyo** [comment]
Sometimes it may be helpful have some logs in release builds too.
You can select minimum logging level using __log__ crate features (see [compile time filters](https://docs.rs/log/0.4.11/log/#compile-time-filters)).
If you want to disable logs for winit only you can configure filters per crate using __env_logger__ as frontend for __log__ (or similar frontends which supports this).

**Comment by madsmtm** [comment]
I believe that the question was answered, so I'll close this.
