### ISSUE TITLE
CursorState::Grab does not report mouse delta on macOS

### ISSUE THREAD

**Issue by mystal** [rust-windowing/winit#165]
You still get MouseMoved events with the absolute position of the mouse, but it does not change. As a result, it's kind of useless. According to [macOS documentation](https://developer.apple.com/reference/coregraphics/1454486-cgassociatemouseandmousecursorpo?language=objc), you should instead check for deltaX and deltaY on the NSEvent.

As far as I can tell, winit doesn't currently report the mouse cursor delta in any events. I think it makes sense to add the mouse delta to the MouseMoved event. Any thoughts?

**Comment by Ralith** [comment]
#164 introduces API for raw input events, which is more appropriate for things like first-person camera control. Would it make more sense to extend the macos backend with support generating such events? It seems to me that you generally want either high-resolution unfiltered relative mouse movement data or filtered window-space pointer positions, not filtered window-space relative pointer movement, and certainly not both at once.

**Comment by LPGhatguy** [comment]
@Ralith Will we need a new `DeviceEvent` variant for mouse movement based on the API you introduced? I see that it exposes an axis and an `f64` value, which might not be suitable for platforms like Windows where raw input is reported as one event from the OS

**Comment by Ralith** [comment]
As discussed on IRC, the intention of `DeviceEvent` is explicitly that multiple events be generated if a host even contains motion on multiple axes. For example, an X11 device event may represent motion on arbitrarily many axes at once, but instead of introducing a dynamically allocated vector, we just generate N separate motion events.

**Comment by swiftcoder** [comment]
This is complete, right? `DeviceEvent::MouseMotion` has existed for some time now.
