### ISSUE TITLE
program height becomes smaller when dragged between two screens

### ISSUE THREAD

**Issue by coolit** [rust-windowing/winit#1650]
I used my win10 laptop (the scale_factor was 1.5) with a second big screen (scale_factor was 1) in Extend mode. As I dragged a program in winit examples between the two screens, the program height became smaller and smaller.

**Comment by chelmich** [comment]
Could you provide a few more details? I was unable to reproduce this on my Windows 10 machine.

**Comment by coolit** [comment]
Hold the title bar of a program and drag the program between the two screens. Don't drop and continue to drag many times until you notice the height decrease.

**Comment by chelmich** [comment]
Sorry, but I'm still having trouble replicating this issue. I'm running W10 version 2004 and the latest git master branch of winit. I tested with `cargo run --example window`, resized it to be larger, then dragged it between my monitors multiple times. The value reported by `Window::inner_size()` seemed to only toggle between two resolutions as expected. I tried setting the scale of both my primary and secondary monitor in turn to 150% as shown here:
![image](https://user-images.githubusercontent.com/10083027/89924077-bda1fb00-dbbe-11ea-9267-8c0059c8143f.png)

**Comment by coolit** [comment]
Please see the screenshot below. I could only capture the small laptop screen, hopefully it can be of help. I guess when the program is dragged between two screens, there are some on_changed triggered due to the change in scale_factor.
![GIF](https://user-images.githubusercontent.com/13397709/89926819-f6ca8180-dc37-11ea-820f-f699df4c443f.gif)

**Comment by maroider** [comment]
I'm afraid I couldn't reproduce this either.

**Comment by coolit** [comment]
I changed a new laptop with the latest win10 version, and the problem was gone.
