### ISSUE TITLE
Mouse/pointer not captured when dragging out of the canvas area on web target

### ISSUE THREAD

**Issue by alvinhochun** [rust-windowing/winit#1660]
When dragging from inside the canvas to outside, the `winit` window stops receiving mouse events.

Possible fixes:

- When `PointerEvent` is available, one can use [`canvas.setPointerCapture`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture) on `pointerdown` to capture the pointer.
- When using the `MouseEvent` fallback, the `mouse*` events should be attached to the window and the event handling code has to manually track the mouse capturing state. There is an [implementation in `kiss3d`](https://github.com/sebcrozet/kiss3d/pull/207/files) ([`web-sys` version](https://github.com/sebcrozet/kiss3d/blob/765f49c73d428c871125cbaca940a0320dd291a3/src/window/webgl_canvas.rs#L143) that can serve as an example.

**Comment by ryanisaacg** [comment]
Is there a reason the canvas should continue to receive mouse events once the mouse leaves the area?

**Comment by alvinhochun** [comment]
> Is there a reason the canvas should continue to receive mouse events once the mouse leaves the area?

- It should because this is how it behaves on native targets.
- The window currently does not receive a mouse release event if the mouse is released outside of the canvas, causing the user code to think that the mouse button is stuck.
- This mouse capturing behaviour is beneficial for drag operations like adjusting up/down spinners or performing camera movements due to the increased movement area (though one might argue that using the [pointer lock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API) is more suitable for the task).
- It should for consistency because this is how it behaves on native targets.
