### ISSUE TITLE
[Wayland] Consider fallback to similar cursors if the requested isn't available.

### ISSUE THREAD

**Issue by kchibisov** [rust-windowing/winit#1680]
X11 does that, so there's nothing that prevents Wayland backend from doing so.

**Comment by chrisduerr** [comment]
By similar cursors you mean falling back between cursor shapes? Or is it about fallback between cursor themes?

**Comment by kchibisov** [comment]
>By similar cursors you mean falling back between cursor shapes?

Icons, we're not terminal in the end

You may see how it looks right now on X11 https://github.com/rust-windowing/winit/blob/0f7c82d38fbe52831a51d5b2523e838d1da02407/src/platform_impl/linux/x11/util/cursor.rs#L107.

>Or is it about fallback between cursor themes?

No, you shouldn't do that.
