### ISSUE TITLE
v0.23.0 release

### ISSUE THREAD

**Issue by francesca64** [rust-windowing/winit#1704]
The "Unreleased" section of the CHANGELOG is getting impressively long... it seems like this has led to [inconvenience for some people](https://github.com/bevyengine/bevy/issues/87#issuecomment-691314370).

Does anybody have any objections to cutting a new release soon? These are the only blockers I currently know about:
- [x] use new ndk crate versions ~~rust-windowing/android-ndk-rs#59~~
- [x] #1670 
- [x] #1703 
- [x] #1653 
- [x] deprecate stdweb #1712
- [x] #1724

@cart is there anything else you'd need for switching to upstream other than a new release?

**Comment by cart** [comment]
Theres nothing else I need. I'm very happy to see that parking_lot just got bumped, I was just about to ask for that :smile:

**Comment by JMS55** [comment]
Please also wait for https://github.com/rust-windowing/winit/pull/1653, it is a huge improvement to Wayland, and seems to be pretty much done.

I am looking forward to the next release soon though!

**Comment by kchibisov** [comment]
yeah, we need #1653 downstream, since it fixes a lot of things, it's **done**, but waiting for review at the moment. I'll work on #1670 since it's a breaking change and also a very important API change for Wayland to make fullscreen startup possible.

**Comment by MichaelHills** [comment]
I think there might be an iOS crash when you swipe-up the control centre (or is it swipe down from top right now? I'm on iphone 6 still). I might have a crack at fixing it tonight or before the release is cut but I would regard this more as me trying to sneak some more fixes in before the deadline rather than a blocker.

**Comment by cart** [comment]
I'll pile on to the "lets wait for #1653" train. It results in a nice consolidation of syn/quote dependencies.

**Comment by alvinhochun** [comment]
Should something be done about the `stdweb` backend (#1662) in this release, or should it wait for the next release or later?

**Comment by francesca64** [comment]
@alvinhochun deprecating it now and waiting to remove it until 0.24.0 would be the conservative approach. However, if you believe that fairly few people are currently using the `stdweb` backend and/or if migrating is easy, then I think we should just be aggressive and remove it now.

Also, it looks like you've been doing a lot of good work on winit's web support. Would you like to be made a rust-windowing Member?

**Comment by alvinhochun** [comment]
> deprecating it now and waiting to remove it until 0.24.0 would be the conservative approach. However, if you believe that fairly few people are currently using the `stdweb` backend and/or if migrating is easy, then I think we should just be aggressive and remove it now.

I replied to this in https://github.com/rust-windowing/winit/issues/1662#issuecomment-694419550

> 
> Also, it looks like you've been doing a lot of great work on winit's web support. Would you like to be made a rust-windowing Member?

I can't promise to help maintain the web backend. I'm still not quite familiar with the `winit` codebase, so I would rather not have write permission for now as long as someone is active to review and merge my PRs (this stops me from doing stupid things).

**Comment by chrisduerr** [comment]
> if you believe that fairly few people are currently using the stdweb backend and/or if migrating is easy, then I think we should just be aggressive and remove it now.

I strongly advise against just removing features without clear prior communication. That sends the wrong message for all backends if you ask me.

**Comment by alvinhochun** [comment]
> 
> 
> > if you believe that fairly few people are currently using the stdweb backend and/or if migrating is easy, then I think we should just be aggressive and remove it now.
> 
> I strongly advise against just removing features without clear prior communication. That sends the wrong message for all backends if you ask me.

Agreed. How should we communicate the intention of removing the `stdweb` backend? Is simply marking it deprecated for one or two breaking releases enough?

**Comment by chrisduerr** [comment]
> Agreed. How should we communicate the intention of removing the stdweb backend? Is simply marking it deprecated for one or two breaking releases enough?

Yes, marking it deprecated should be sufficient. The timespan for which it is marked deprecated is probably much more important than the number of breaking releases, since there's very little reason to just update to every second release of winit or something similar.

**Comment by ryanisaacg** [comment]
I'm on chris's side here, I think we should throw a warning at any user of stdweb in this release, note this prominently in the changelog, and possibly reach out to any downstream projects that are still depending on it. In a future release, we can actually make the removal.

**Comment by kchibisov** [comment]
I've opened #1729 since every PR mentioned here was merged. If anyone has any concerns about releasing let me know.

**Comment by kchibisov** [comment]
Release was cut.
