### ISSUE TITLE
window  without titlebar support

### ISSUE THREAD

**Issue by cossonleo** [rust-windowing/winit#1706]
Is winit  support  window created  without  titlebar

**Comment by chrisduerr** [comment]
Like https://docs.rs/winit/0.22.2/winit/window/struct.WindowBuilder.html#method.with_decorations?

**Comment by cossonleo** [comment]
thx

**Comment by DreamSaddle** [comment]
Hey, guy!

This does hide the titlebar, but I want to keep the close/zoom button on the window. How do I do that?

Such as:
![image](https://user-images.githubusercontent.com/31559386/178402372-e80b3466-1637-409b-a235-b6130f9a0248.png)

**Comment by DreamSaddle** [comment]
@chrisduerr

**Comment by paulrouget** [comment]
@DreamSaddle 

```rust
use winit::platform::macos::WindowBuilderExtMacOS;
[…]
let mut window_builder = winit::window::WindowBuilder::new()
  .with_titlebar_transparent(true)
  .with_fullsize_content_view(true)
  […]
```
