### ISSUE TITLE
macOS brightness controls not working in exclusive fullscreen mode

### ISSUE THREAD

**Issue by tuzz** [rust-windowing/winit#1711]
Hello,

On macOS, the brightness controls aren't being handled by the system when a winit window is running in exclusive fullscreen mode (via [`set_fullscreen`](https://docs.rs/winit/0.22.2/winit/window/struct.Window.html#method.set_fullscreen)). This is a problem for me because my application is a game which has some dark areas where it would be desirable if the player could increase the screen brightness to 100%. I am unable to do this for them because that requires Accessibility privileges on macOS.

The other media keys are being handled fine, e.g. I can adjust the volume levels, play+pause music, etc.

I did see in the documentation it says:

>Caveat! macOS doesn't provide task switching (or spaces!) while in exclusive fullscreen mode. 

I wonder if the reason brightness doesn't work is something related to this?

I'm not seeing any `KeyboardEvents` for the brightness controls (or, as expected, the media keys), and I'm not seeing any other winit `Events` relating to those keys being pressed. I'm currently running macOS Catalina 10.15.6. I am using an external display, but I have tested the problem still happens when it is unplugged and I'm running directly on the built-in display.

One possible workaround would be to use borderless fullscreen mode, however, it's far more performant for me to run in exclusive mode (huge amounts of stutter otherwise). This is because in borderless mode, the operating system has to re-scale the content in the framebuffer to match the hidpi scaling settings of the monitor.

Thanks!

**Comment by frewsxcv** [comment]
Not identical, but similar-ish issue here https://github.com/rust-windowing/winit/issues/1195

**Comment by tuzz** [comment]
I just tested this again and the brightness controls are working now. 🎉 

I'm not sure whether something changed in winit or maybe the OS itself was upgraded but I'll close this now. Thanks
