### ISSUE TITLE
Suggestion: Add a web-only event loop run API that returns to caller

### ISSUE THREAD

**Issue by alvinhochun** [rust-windowing/winit#1714]
Motivation
---

With `EventLoop::run` it is currently impossible to start the event loop cleanly from either JavaScript or Rust since it throws an exception to not return execution to the caller. Technically one can use JS to catch the exception, but if someone wants to do this in Rust, it would require some glue code. It is also a pretty awful hack.

Moreover, if the event loop is started from `#[wasm_bindgen(start)]`, the JS `Promise` returned from initializing the WASM module will be rejected, making it harder to distinguish between a successful load and a failure in initializing the WASM module. One can compare the exception string, but this is also quite dirty.

Proposal
---

A new web-only extension method should be added to the `EventLoop`. which kick-starts the event loop and returns without throwing an exception. The caller is still required to return execution to the browser for the event loop to actually start handling events.

```rust
trait EventLoopExtWeb {
    type UserEvent;

    fn run_web(self, event_handler: F)
    where
        F: FnMut(
            Event<'_, Self::UserEvent>,
            &EventLoopWindowTarget<Self::UserEvent>,
            &mut ControlFlow,
        );
}
```

Unresolved questions
---

- Does `run_web` need to keep the `EventLoopWindowTarget` alive beyond the function scope and how? In the existing web backend, it only holds `runner::Shared`, which is effectively kept alive by the DOM event listener closures in the form of an `Rc` loop, so dropping `EventLoopWindowTarget` will not actually cause the event loop to be dropped, but it may not be wise to rely on this behaviour.
- Should there be a way for the user to retrieve and reuse the `EventLoop` after it has exited? In the case of `EventLoopExtDesktop::run_return`, the `EventLoop` and its associated `Window`s can be reused easily. However, to do the same on web will require `run_web` to return a `Future` or a `Promise`, which becomes *ready* or *fulfilled* respectively when the `EventLoop` exits.
- Should we allow the user to create multiple `EventLoop`s which can be run simultaneously? Technically there shouldn't be any issues allowing this,

**Comment by kchibisov** [comment]
Do you just want a `run_return` for web?

**Comment by alvinhochun** [comment]
Not really. My main gripe is the JS exception thrown for execution flow control. Also, it is impossible to implement `run_return` on web.

**Comment by ryanisaacg** [comment]
I support this proposal! Getting rid of the exception would be quite nice.

**Comment by grovesNL** [comment]
The rejected promise is causing some problems for wgpu so we're interested in fixing this.

@alvinhochun have you already started working on this in a branch, or would it be ok for us to start on this?

**Comment by alvinhochun** [comment]
@grovesNL Feel free to work on this. If I've ever done anything about this I must've forgotten about it anyway. I also don't know how many of the "unresolved questions" are still valid.

**Comment by grovesNL** [comment]
@alvinhochun sounds great, thanks! We'll look into this

**Comment by Liamolucko** [comment]
Would `spawn` be a better name? To me, it conveys more meaning than `run_web`.
