### ISSUE TITLE
Moved event should convert into `PhysicalLocation` on Mac?

### ISSUE THREAD

**Issue by kaiwk** [rust-windowing/winit#1718]
If I understand properly, we should convert position in physical as `emit_resize_event` does?

https://github.com/rust-windowing/winit/blob/71e3d254226b47d8cbdb1d9432f11e4cdc659a46/src/platform_impl/macos/window_delegate.rs#L100-L117

**Comment by chrisduerr** [comment]
I'm not quite sure what you're asking here. The `Moved` event already emits a `PhysicalPosition`. Are you requesting some kind of change, or looking for support?

**Comment by kchibisov** [comment]
I feel like the issue that there's no conversion, if so please send patch.

**Comment by kaiwk** [comment]
> I feel like the issue that there's no conversion

that's what i mean, `(x, y).into()` use `x` and `y` directly as physical unit, but seems they are in logical actually. I'm not quite sure though, the patch did fix my problem.

**Comment by francesca64** [comment]
Closing, since this was fixed in #1722
