### ISSUE TITLE
Moving window does not take cursor position into account

### ISSUE THREAD

**Issue by devnought** [rust-windowing/winit#1720]
Dragging around a window to reposition it does not take into account the cursor position, and the window's top left position jumps to the cursor's position.

As a user on Windows, I would expect that moving a window would take into account my cursor position.

This behaviour is consistent with any `winit` spawned window.

![user-input](https://user-images.githubusercontent.com/2523371/93848637-2e393e80-fc78-11ea-8c6b-e644dc0f3f40.gif)

**Comment by devnought** [comment]
That gif was recorded using the master branch, but I have also witnessed this behaviour in `0.22`.

`winver` is reporting `Version 2004 (OS Build 19041.508)`

The window jump is happening on mouse down.

**Comment by maroider** [comment]
I can't reproduce the issue with current master (c9558c5f). I'm using the exact same Windows build (`Version 2004 (OS Build 19041.508`).

**Comment by devnought** [comment]
... just my luck. I had a long post typed up on the exact behaviour of the examples (most are with mouse move, only `resizable` is on mouse down, the multi window ones are a separate case), when I had a thought after @maroider said they couldn't reproduce the issue.

It has nothing to do with `winit`. I have the [MaxTo](https://maxto.net/) window manager installed to better divide up my secondary portrait mode monitor's regions, and that seems to be the culprit.

I have no idea what this window manager is doing to cause this behaviour, and I've only witnessed it with `winit`-based applications.

**Comment by maroider** [comment]
Have `winit`-based applications worked correctly alongside MaxTo in the past?

**Comment by devnought** [comment]
> Have `winit`-based applications worked correctly alongside MaxTo in the past?

Not that I've witnessed. I have only started using MaxTo in the past couple of months, and in that time have only periodically dabbled with `winit`-based applications, all of which experience this issue.

MaxTo has an application compatibility list which [they maintain](https://maxto.net/shims) to modify how it interacts with said applications.

For example:
> Console windows require a different mechanism when moved than other windows do. This shim ensures MaxTo uses MoveWindow instead of SetWindowPos when moving console windows.

I tried modifying one of the examples to use the `windows` subsystem so it's not considered a console application as a shot in the dark, but that didn't change the behaviour.

**Comment by devnought** [comment]
After filing a bug with `MaxTo`, I decided to check out their beta stream. It appears that whatever is causing this behaviour has been fixed in the upcoming version.

Thanks again for everyone that looked at this, and I'll close the issue.
