### ISSUE TITLE
Android redraw requests aren't implemented

### ISSUE THREAD

**Issue by glalonde** [rust-windowing/winit#1723]
https://github.com/rust-windowing/winit/blob/c9558c5f0e8f5ccb7b250a59c46c0f7a41c2416a/src/platform_impl/android/mod.rs#L408

For now, implementing redraw in MainEventsCleared works. But I'm not sure what's supposed to go on here.

**Comment by francesca64** [comment]
It looks like it was just punted:

https://github.com/rust-windowing/winit/blob/be2e17d605d1780bba15cd7fa4a98ef4917cedf4/src/platform_impl/android/mod.rs#L408-L410

I haven't seen any discussion indicating that it'd be thorny to implement; it's fairly simple on most platforms, albeit very platform-specific. A PR would be very welcome!

**Comment by francesca64** [comment]
@dvc94ch do you remember anything about this?

**Comment by dvc94ch** [comment]
Not sure what it's useful for. I guess setting an AtomicBool and calling looper.wake() should do the trick?

**Comment by rmyhovych** [comment]
@francesca64 I've been having an issue with this in my Android application, where the RedrawRequested event was never called and my scene would stay static after 2 frames, so I made my own small function that fixed it for me:

`    pub fn request_redraw() {
        match ndk_glue::native_window().as_ref() {
            Some(native_window) => {
                let a_native_window: *mut ndk_sys::ANativeWindow = native_window.ptr().as_ptr();
                let a_native_activity: *mut ndk_sys::ANativeActivity =
                    ndk_glue::native_activity().ptr().as_ptr();
                unsafe {
                    match (*(*a_native_activity).callbacks).onNativeWindowRedrawNeeded {
                        Some(callback) => callback(a_native_activity, a_native_window),
                        None => (),
                    };
                };
            }
            None => (),
        }
    }
`

I'm very new to Rust and Native Android development, is there anything wrong with my way of doing?
