### ISSUE TITLE
If the event loop fails, how do I save the data?

### ISSUE THREAD

**Issue by botika** [rust-windowing/winit#1730]
There is no way to do anything once the event loop has failed. So I can lose my data at will from the event loop. I understand that it is for compatibility reasons. But in my business application it is very important that the data is always secured. 

Could build two models, one fully compatible with IOS and the other not?

**Comment by chrisduerr** [comment]
> Could build two models, one fully compatible with IOS and the other not?

There already exists a `run_return` method for desktop applications which allows you to continue running after the application has quit. Is that what you're looking for?

**Comment by botika** [comment]
But this function can block the main thread with windows resize. 

Couldn't do a `futures::Stream` from another thread? Or the tools for a snug fit. 

Now I have the `run` in another thread and an unbounded, but the stop is very unnatural and I would like to do it with futures as with a socket.
I can help

**Comment by chrisduerr** [comment]
Of course it can block, this is your event loop. That's kind the point.

Running things on a different thread is not recommended and will cause issues on some platforms.

**Comment by botika** [comment]
Ok, I keep in mind. I will work in unix so I should not have problems. Thanks for your time. I close it
