### ISSUE TITLE
Failed to initialize X11 backend on wayland even with WINIT_UNIX_BACKEND=wayland

### ISSUE THREAD

**Issue by Maxgy** [rust-windowing/winit#1732]
I'm using pure wayland on the Sway WM, and winit fails to create a window and instead panics with the error `'Failed to initialize X11 backend: XOpenDisplayFailed'` even when I specify `WINIT_UNIX_BACKEND=wayland`.

**Comment by chrisduerr** [comment]
Are you running your own code, or an example? Are you making use of any feature flags? And do you use Nvidia graphics?

**Comment by Maxgy** [comment]
I'm running my own code, my libraries don't use any feature flags for winit, and I'm using Intel graphics.

**Comment by chrisduerr** [comment]
What happens if you run with default features disabled and only enable Wayland? I'd assume that this has something to do with winit not being able to find the Wayland socket/that Wayland is active.

Also which winit version are you using?

**Comment by kchibisov** [comment]
I can't reproduce this, my system doesn't have xserver installed at all, and everything is always running on Wayland for me. `WINIT_UNIX_BACKEND=wayland` doesn't crash anything for me and everything runs fine, `WINIT_UNIX_BACKEND=x11` crashes for me, since no Xorg on my system.

**Comment by Maxgy** [comment]
I'm using winit 0.22.2, but regardless of this, it turns out that for some reason one of my libraries is forcing `WINIT_UNIX_BACKEND=x11`. I guess that would be why it still displays that error. After manually forking the repo and removing the line that forced x11, the window works perfectly. For now, I'll have to open an issue on the appropriate repo, and I think this is safe to close. Thank you for your help.

**Comment by chrisduerr** [comment]
@Maxgy Which library is that?

**Comment by Maxgy** [comment]
@chrisduerr [bracket-lib](https://github.com/thebracket/bracket-lib)
