### ISSUE TITLE
Window flickers when resizing

### ISSUE THREAD

**Issue by Ssaely** [rust-windowing/winit#1753]
When resizing a window a transparent window, noticeably from the top and left, the window's contents flicker.  ![A video highlighting this behavior](https://i.imgur.com/QBIykJh.gif)

OS: Windows 10 version 2004, build 19041.572
Winit: 0.23
Rust: Stable 1.47 msvc toolchain

**Comment by chrisduerr** [comment]
I'm not sure what flickering you're talking about? Do you mean that the rectangle isn't redrawn in time for the resize?

**Comment by Ssaely** [comment]
> Do you mean that the rectangle isn't redrawn in time for the resize? At least not at the correct position.
I believe so, I'm not sure what's the proper terminology to describe this behavior. 
I did some research and it seems that this is due to how Windows repaints it's contents

**Comment by chrisduerr** [comment]
> I did some research and it seems that this is due to how Windows repaints it's contents

But you're drawing that rectangle, right? What code are you using to do so?

**Comment by alvinhochun** [comment]
I just found out that there is an extraordinary long question-and-answer on StackOverflow about the window resize flickering issue on Windows: https://stackoverflow.com/questions/53000291/how-to-smooth-ugly-jitter-flicker-jumping-when-resizing-windows-especially-drag

I have not attempted to read it yet, but seems very related to this issue.

**Comment by Ssaely** [comment]
> But you're drawing that rectangle, right? What code are you using to do so?
The video was just me using the `transparent` example but with decorations enabled

**Comment by chrisduerr** [comment]
> The video was just me using the transparent example but with decorations enabled

But that doesn't draw anything?

**Comment by Ssaely** [comment]
I realized that this was an issue with how I drew on my application
