### ISSUE TITLE
Requesting redraw on X11 does not wake up the event loop

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1755]
It seems like while requesting the redraw stores the need for a redraw in a shared variable, it never actually makes an attempt to wake up the event loop. This means that this function only delivers the requested event when users already get other events.

@murarth are you aware of this? If not, is there an easy way to wake up the event loop on X11?

Somewhat related: https://github.com/rust-windowing/glutin/issues/1335

**Comment by murarth** [comment]
Can confirm, just looking at the code. `request_redraw` inserts a window id into an `Arc<Mutex<HashSet<WindowId>>>`, but does not wake the event loop.

It should be an easy fix to replace the container with a mio channel that is registered with the event loop `Poll` instance. I'll start writing up a PR now.
