### ISSUE TITLE
Windows: Fullscreen doesn't preserve minimized/maximized state

### ISSUE THREAD

**Issue by relrelb** [rust-windowing/winit#1765]
## Version information

* winit 0.23.0
* Windows 10

## Steps to reproduce the problem

1. Run the [`fullscreen`](https://github.com/rust-windowing/winit/blob/master/examples/fullscreen.rs) example:
```sh
cargo run --example fullscreen
```
2. Maximize the window.
3. Enter fullscreen by pressing <kbd>F</kbd>.
4. Exit fullscreen by pressing <kbd>F</kbd> again.

After exiting fullscreen, the window is no longer maximized, and it covers the whole screen.

## Expected behavior

After exiting fullscreen, the window is *still* maximized, and unmaximizing it brings it to the initial size and position before it was maximized.

This is how many programs with fullscreen functionality behave (e.g. Chrome, VLC).

**Comment by kchibisov** [comment]
Could you mention the platform you were testing this on?
