### ISSUE TITLE
CloseRequested not fired

### ISSUE THREAD

**Issue by Zenthae** [rust-windowing/winit#1766]
The `CloseRequested` event doesn't seems to be fired when winit is used without window.

OS : Windows
Winit: 0.23
Rust: 1.46

**Comment by kchibisov** [comment]
https://docs.rs/winit/0.23.0/winit/event/enum.WindowEvent.html#variant.CloseRequested

If there's no window there's no close requested, since it's for a window.

**Comment by Zenthae** [comment]
then there is no way to execute code before the app exit ? like saving data. Do i need to use another crate ?

**Comment by chrisduerr** [comment]
Depends on your platform. On Windows you can use `run_return` instead of `run`.

**Comment by kchibisov** [comment]
Use `run_return` and what's the point of using winit (windowing toolkit), without a window?

**Comment by Zenthae** [comment]
> what's the point of using winit (windowing toolkit), without a window?

key and mouse event listener

**Comment by kchibisov** [comment]
>key and mouse event listener

It won't work cross platform though, on some systems you don't have key events without a window. If the goal is to write key logger platforms API may suit a bit better.

**Comment by Zenthae** [comment]
i just need it to work on Windows, and use something like `winapi` wasn't possible because i simply wasn't able to understand how to use it,

**Comment by kchibisov** [comment]
Then using run_return is fine for you.

**Comment by murarth** [comment]
The [`LoopDestroyed`](https://docs.rs/winit/0.23.0/winit/event/enum.Event.html#variant.LoopDestroyed) event exists for exactly this purpose. It is guaranteed to be emitted and guaranteed to be the last event emitted.
