### ISSUE TITLE
Duplicate KeyboardInput events on Windows

### ISSUE THREAD

**Issue by curldivergence** [rust-windowing/winit#1772]
Hello,

I'm trying to handle keyboard input in my program, but for some reason my event loop receives each KeyboardInput event twice.
Probably I'm doing something wrong, but this issue reproduces even on the minimal example from the docs:
```
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                window_id,
            } if window_id == window.id() => *control_flow = ControlFlow::Exit,
            Event::WindowEvent {
                event: WindowEvent::KeyboardInput { input, .. },
                ..
            } => {
                match input.virtual_keycode {
                    Some(code) => {
                        println!("Received keyboard input: {:?}", code);
                    }
                    None => println!("Received keyboard input without virtual keycode")
                }
            }
            _ => (),
        }
    });
}
```

As a result, when I press any keyboard button, the line with debug output "Received keyboard input" executes two times in a row.

Thank you!

**Comment by kchibisov** [comment]
I think you get one for press and one for release? If you try to print them they should be different.

**Comment by curldivergence** [comment]
@kchibisov ohhh, you're right, I've missed the fact that there is other meaningful payload in input besides virtual_keycode member itself. This is embarrassing :) Thanks a lot for help, and sorry for bothering!
