### ISSUE TITLE
 [BUG] attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized

### ISSUE THREAD

**Issue by icefoxen** [rust-windowing/winit#1773]
This is a bug with winit 0.19, so I dunno if it's reasonable to expect a fix, but this appears to be hitting a couple different projects so it deserves to be consolidated here.

Characteristic backtrace:

```
Thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', /home/nikita/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
   3: core::mem::uninitialized
             at /home/nikita/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658
   4: winit::platform::platform::x11::util::input::<impl winit::platform::platform::x11::xdisplay::XConnection>::query_pointer
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/util/input.rs:94
   5: winit::platform::platform::x11::EventsLoop::process_event
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:956
   6: winit::platform::platform::x11::EventsLoop::poll_events
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:270
   7: winit::platform::platform::EventsLoop::poll_events
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/mod.rs:522
   8: winit::EventsLoop::poll_events
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/lib.rs:277
   9: <amethyst_window::system::EventsLoopSystem as shred::system::RunNow>::run_now
             at ./amethyst_window/src/system.rs:116
  10: shred::dispatch::dispatcher::Dispatcher::dispatch_thread_local
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.10.2/src/dispatch/dispatcher.rs:113
  11: shred::dispatch::dispatcher::Dispatcher::dispatch
             at /home/nikita/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.10.2/src/dispatch/dispatcher.rs:65
  12: amethyst::game_data::GameData::update
             at ./src/game_data.rs:47
  13: <T as amethyst::state::State<amethyst::game_data::GameData,amethyst::state_event::StateEvent>>::update
             at ./src/state.rs:345
  14: amethyst::state::StateMachine<T,E>::update
             at ./src/state.rs:447
  15: amethyst::app::CoreApplication<T,E,R>::advance_frame
             at ./src/app.rs:381
  16: amethyst::app::CoreApplication<T,E,R>::run
             at ./src/app.rs:245
  17: animation::main
```

Downstream bugs:

 * https://github.com/ggez/ggez/issues/843
 * https://github.com/amethyst/amethyst/issues/2524

This occurs on Rust 1.48+ due to tightening some constraints over what can be non-initialized: https://github.com/rust-lang/rust/pull/66059/

**Comment by chrisduerr** [comment]
The latest version of winit is 0.23.0, not 0.19.5. Have you confirmed that this issue is still present in the latest winit version?

**Comment by icefoxen** [comment]
Confirmed that winit 0.23 works fine.  Upgrading out of winit 0.19 is just a breaking change for ggez, so it's kind of tricky.  It doesn't look like there's a branch for winit 0.19, so I presume submitting a patch to fix it wouldn't result in a winit 0.19.6 with this fixed.

**Comment by chrisduerr** [comment]
See, having ggez on an ancient winit version has already caused this one bug with maintenance overhead. For winit there's no good reason to keep supporting it. There's nothing inherently wrong with new winit versions and forcing downstream to update only has benefits for winit.

It's not like 0.19 is a LTS release or anything like that. The only *supported* version of winit is the latest one and everyone is encouraged to update that. If previous versions suddenly break completely, that's just more of an incentive to update as far as winit is concerned.

So realistically I feel like allowing patches to 0.19 would just make the situation worse. Any effort put in to support that old version, review code, write that code and maintain it, would be much better spent updating ggez to the latest winit version.

**Comment by kchibisov** [comment]
>So realistically I feel like allowing patches to 0.19 would just make the situation worse. Any effort put in to support that old version, review code, write that code and maintain it, would be much better spent updating ggez to the latest winit version.

I'm against patching 0.19.x, since Wayland is entirely broken on it, and bringing it up to date on it is insane amount of work, which I won't do. So please, don't use 0.19.x.

**Comment by memoryruins** [comment]
ggez is already on the latest winit version on the devel branch. Since there are other libraries running into this issue, I appreciate that you opened this to link to @icefoxen ^^

**Comment by icefoxen** [comment]
Yeah, it's perfectly reasonable to not support/patch 0.19.  Just wanted to have a single point to gather info/links for people having this problem and what the solution is.  Using Rust 1.47 works fine, and updating Winit works fine, so.  :heart:
