### ISSUE TITLE
Passing on web maintainer status

### ISSUE THREAD

**Issue by ryanisaacg** [rust-windowing/winit#1777]
About a month ago, I stopped actively developing my downstream project that made use of winit. It's been harder than I expected to make time to check in on filed bugs, review pull requests, or actively participate in development. For these reasons, I think it's time to pass on maintainer status. I may be available to answer questions about existing technical decisions in the web backend or to review code occasionally, but I'm not sure I have the time that winit deserves. 

Does anyone want to take up the mantle?

**Comment by chrisduerr** [comment]
The current contributors listed in the wiki for this platform are @Osspial, @goddessfreya and @sandbox-irl. None of which I've seen doing any active contributions in the recent past.

I think generally pruning the list in the wiki to represent who is actually around to help out might be beneficial to finding out which platforms need maintenance. Because as far as I can tell this means that the web backend is effectively unmaintained.

**Comment by francesca64** [comment]
@ryanisaacg huge thanks for all the great work you've done, and congrats on moving on! I know it's a hard thing to do, which isn't a joke about the fact that I'm still here. 

@alvinhochun would you be interested?

@chrisduerr I suspect that _a lot_ of the people listed in the table aren't really around anymore. I guess we'd just have to go through and ping everyone?

**Comment by chrisduerr** [comment]
> I suspect that a lot of the people listed in the table aren't really around anymore. I guess we'd just have to go through and ping everyone? (Probably in a separate issue ofc)

Yeah, either that or remove everyone who hasn't been around for a while by looking at reviews/commits. But the only platforms I have somewhat of a feeling for would be X11/Wayland.

**Comment by alvinhochun** [comment]
@ryanisaacg Thank you for supporting Winit for WASM.

@francesca64 Thanks for the ping. I'm not sure if I'm in the position to become a maintainer. I do have some need for Winit's web support and I was hoping to help port Kiss3d's web backend over to Winit (though it might be a distant future). I also have some toy projects making use of it. I would like to keep improving the web backend.

However, I'm currently busier with other stuff than I would like to be, so my side projects involving Winit has been put on hiatus, and it is the same regarding Winit. I can read issues and PRs, but my availability to do actual changes, testing and reviews is limited. More likely I will come and go intermittently. With this in mind I don't think my status is any better than @ryanisaacg's.

**Comment by francesca64** [comment]
@alvinhochun gotcha, thanks for all the contributions you've made!

Do we have any other leads? Maybe a person/project that depends on winit's web support? If not, we can always put up a "call for contributors" post on /r/rust or something.

**Comment by FuriouZz** [comment]
I do not think than I can fit for the maintainer role, but I would like to contribute. I just miss some decision winit. 

My last contribution in winit was about the Gamepad integration #944, it was an interesting contribution and a good start for me. But the discussion does not really evolve and I do not really know who is interested by this feature. What are winit actual purposes?

**Comment by francesca64** [comment]
@FuriouZz thanks for your interest! I responded to you over in https://github.com/rust-windowing/winit/issues/944#issuecomment-743489050, and any further discussion about gamepad support can continue there.

**Comment by Osspial** [comment]
> The current contributors listed in the wiki for this platform are @Osspial, @goddessfreya and @sandbox-irl. None of which I've seen doing any active contributions in the recent past.

Sorry for going quiet for as long as I have. I don't have the drive for Winit to work as a full-on maintainer right now, and I haven't for a while, so I've downgraded myself to just a contributor. I may see about doing smaller contributions here and there, but in the meanwhile the prospect of catching up on *everything* and actively conversating in threads just isn't something I'm interested in managing.

**Comment by daxpedda** [comment]
I would like to take that position.
