### ISSUE TITLE
[MacOS] Dialogues freeze when used in winit event loop

### ISSUE THREAD

**Issue by PolyMeilex** [rust-windowing/winit#1779]
**OS**: OSX 10.15.6

Hi I'm working on `RustyFileDialog` crate, and in the process I found out weird issue related to winit event loop.

*(To make it easier to reproduce I'll use `nfd2` as an example instead of my impl.)*
File dialogs, for example from `nfd2` freeze when opened from winit event loop.
Example:
```rust
fn main() {
    let el = EventLoop::new();
    let win = WindowBuilder::new().build(&el).unwrap();

    // This dialog works as expected
    nfd2::open_file_dialog(None,None).unwrap();

    el.run(move |event, _, control_flow| {
        match event {
            event::Event::WindowEvent {
                event: event::WindowEvent::MouseInput { .. },
                ..
            } => {
                // This dialog freezes
                nfd2::open_file_dialog(None,None).unwrap();
            }
            _ => {}
        }
    })
}
```

### More info
- For this test `NSOpenPanel` is used, and it is opened with `runModal` (blocking)
- If I use `beginWithCompletionHandler` (non-blocking) dialog works as expected 
- SDL2-rs does not have this issue 
- winit window stays responsive, only `NSOpenPanel` is frozen 

![GIF](https://i.imgur.com/pLj4AYr.gif)

**Comment by chrisduerr** [comment]
This sounds like you're blocking inside of the event loop? Shouldn't the expected result be that the application then freezes, or what do you expect? The handling of events has been stopped.

**Comment by PolyMeilex** [comment]
The application should freeze (it did) as MacOS is doing its work with dialog. But for some reason system dialog also freezes

**Comment by chrisduerr** [comment]
Which macOS version?

**Comment by PolyMeilex** [comment]
Mac OS X 10.15.6 (as stated in the issue)

**Comment by chrisduerr** [comment]
> Mac OS X 10.15.6 (as stated in the issue)

Ah, I missed that. Hm, according to macOS docs it says the dialog boxes should be handled by a completely separate process. Though I'm not sure how exactly you hook them up.

**Comment by PolyMeilex** [comment]
I'm quite confused, I never encountered such a behavior in the SDL world

**Comment by PolyMeilex** [comment]
## Small update on my findings:
When testing without any winit window opened:
- Mouse events from file dialog cause [winit handler](https://github.com/rust-windowing/winit/blob/8fb7aa5cef1c3bee28730dc771c7ddb16ba47c66/src/platform_impl/macos/app_state.rs#L109) to be called
- Lock on [handler callback mutex](https://github.com/rust-windowing/winit/blob/8fb7aa5cef1c3bee28730dc771c7ddb16ba47c66/src/platform_impl/macos/app_state.rs#L99) seems to be the cause of the problem (not deeply tested yet, I may be mistaken)

I located a nice example of this behavior in [handle_nonuser_event](https://github.com/rust-windowing/winit/blob/8fb7aa5cef1c3bee28730dc771c7ddb16ba47c66/src/platform_impl/macos/app_state.rs#L169)
```rust
fn handle_nonuser_event(&self, wrapper: EventWrapper) {
        // Dialog Still works
        rfd::open();

        if let Some(ref mut callback) = *self.callback.lock().unwrap() {
            // Nope after the lock this one is frozen
            rfd::open();

            match wrapper {
                EventWrapper::StaticEvent(event) => {
                    callback.handle_nonuser_event(event, &mut *self.control_flow.lock().unwrap())
                }
                EventWrapper::EventProxy(proxy) => self.handle_proxy(proxy, callback),
            }
        }
}
```

**Comment by PolyMeilex** [comment]
@vbogaevsky
Ignoring all incoming events while the callback is running solves the issue (this makes sure that no locks are made to control_flow mutex, and calback_mutex), but I don't know the full impact of this change, so I would like to hear the opinion of someone with more knowledge about macOS backend.
And of course, ignoring some events is always something that should be taken with care.

### Example implementation of this change: https://github.com/PolyMeilex/winit/commit/69a6129d088d0cada976e2da9d3a93954ca1f824

@chrisduerr 
As I know that `vbogaevsky` is kinda inactive lately, I would like to ask you how should I proceed with this? Ignoring events sounds kinda scary (that's why I'm writing here instead of making a PR), but I'm out of ideas.

**Comment by adamnemecek** [comment]
Any update on this?

**Comment by adamnemecek** [comment]
Any update on this @chrisduerr ?

**Comment by thenlevy** [comment]
I am also having this problem. Opening a file dialog with either [`native-dialog-rs`](https://github.com/balthild/native-dialog-rs)`0.5.2` or [`nfd2`](https://github.com/EmbarkStudios/nfd2)`0.2.3` causes the file dialog to freeze on macos.
Using PolyMeilex's fork of `winit` solves the issue for me.

Also, `native-dialog-rs 0.4.*` works fine even with the crates.io version of winit. If I'm not mistaking, this previous version used something called `AppleScript`, which has been replaced by something called `cocoa` (I don't know much about macos programming so this could be wrong/irrelevant..). [Here](https://github.com/balthild/native-dialog-rs/issues/5) is the discussion about this change in `native-dialog-rs`.

**Comment by PolyMeilex** [comment]
Both `nfd2` and my `rfd` use objc api, AppleScript is not used as it is too limiting. I'll have a look at the implementation of the other library, maybe there is some workaround in place

**Comment by PolyMeilex** [comment]
I've implemented async/await syntax in [rfd](https://crates.io/crates/rfd) as a workaround to the problem, so if anyone is interested feel free to give it a try. It can be used with the `crates.io` version of `winit` ([example](https://github.com/PolyMeilex/rfd/blob/3e11a7e901b264eee38a3313095be0827284628a/examples/winit-example/src/main.rs#L53)).

Issue stays open, as the problem still exists inside `winit` and should be fixed nonetheless.

**Comment by OfficialURL** [comment]
I've been using PolyMeilex's fork of `winit`, and it's completely solved this issue for me. What's stopping it from being merged into the main branch?

**Comment by maroider** [comment]
> What's stopping it from being merged into the main branch?

1. There simply isn't a PR open for that.
2. @ArturKovacs may not be aware of this issue.

**Comment by PolyMeilex** [comment]
I'm using my fork in my `neothesia` project, and I haven't heard any complaints yet.
But as I said:
`I don't know the full impact of this change, so I would like to hear the opinion of someone with more knowledge about macOS backend.`
I'm essentially ignoring all incoming events in some cases, so I don't like this solution at all, and I have 0 knowledge about macOS windowing.

**Comment by ArturKovacs** [comment]
Oh so I guess this was the issue you mentioned to me @adamnemecek. I think that the `lock` function call on the `callback` should be replaced with a `try_lock`, since the callback must only be called from the main thread and therefore finding the mutex locked at any point must mean that there was re-entrance (which would cause deadlock anyways) or must mean that there was a developer error and the callback is being accessed from a non-main thread which it shouldn't be.

I just wanted to write this down but unfortunately I don't have time look into this right now, but I will do hopefully soon. 

This whole re-entrance and locking thing might actually be the reason why we queue events instead of dispatching them synchronously, but I'm not sure and that's mostly related to #1911.

**Comment by emilk** [comment]
I managed to fix this by switching from `event_loop.run(|…| { … file_dialog(); })` to `loop { event_loop.run_return(…); … file_dialog(); }`:

https://github.com/emilk/egui/pull/631
