### ISSUE TITLE
 Error: Thread 'main' panicked at '[winit] XRandR extension not available.

### ISSUE THREAD

**Issue by geotyper** [rust-windowing/winit#1781]
On Ubuntu 18.04 with 4 displays
have next  error:
Xlib:  extension "RANDR" missing on display ":0".
thread 'main' panicked at '[winit] XRandR extension not available.', src/platform_impl/linux/x11/monitor.rs:293:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

![Screenshot at 2020-11-30 10-07-50](https://user-images.githubusercontent.com/30755433/100578894-39ea5680-32f4-11eb-8862-3e9a258b3beb.png)

**Comment by kchibisov** [comment]
Are you using xinerama or something like that, so no 'xrandr' on the system?

**Comment by geotyper** [comment]
Yes, on system  use xinerama

**Comment by kchibisov** [comment]
Yeah, winit doesn't support systems without xrandr.
