### ISSUE TITLE
[Windows] Default window size is too large

### ISSUE THREAD

**Issue by maroider** [rust-windowing/winit#1786]
###### I used two machines while gathering information. I'll refer to them as M1 and M2.
M1 OS: Windows 10 (1903)
M1 Monitor resolution: 1366x768
M1 Monitor scale: 100%

M2 OS: Windows 10 (2004)
M2 Monitor resolution: 1920x1200
M2 Monitor scale: 100%

Winit version: 8fb7aa5 (latest master)

Severity: Low

---

When a program which uses Winit opens a window without specifying an initial size, the size that of the resulting window ends up being so large that the bottom of the window is pushed off-screen on M1's monitor.
The problematic (inner) size (1024x749) is marginally smaller than the default size I'm observing on M2's monitor (1024x768).

This has been an issue on M1 for some time now and is also reproducible on M2 by setting the monitor's resolution to 1366x768.

I'll probably end up investigating what programs which _don't_ use Winit do at some later point, but my hunch is that the majority set their initial window size before creating or displaying the window.

**Comment by dhardy** [comment]
Last I checked winit just uses a default size for a new window if the app doesn't specify a size / constraints. That size actually depends on the platform (IIRC 800×600 on some).

**Comment by maroider** [comment]
> Last I checked winit just uses a default size for a new window if the app doesn't specify a size / constraints. That size actually depends on the platform (IIRC 800×600 on some).

That may be true for macOS, Wayland and X11, but not for Windows. The Windows backend relies on passing in `CW_USEDEFAULT` (`0x80000000`) instead of a size to creation function (`CreateWindowExW`) in the case where a size isn't specified.

**Comment by maroider** [comment]
Wow, I just chased the history of those values through `git blame`, and they seem to be a hold-over from Glutin.
