### ISSUE TITLE
DeviceEvent::MouseMotion unimplemented in web-sys wasm backend?

### ISSUE THREAD

**Issue by swiftcoder** [rust-windowing/winit#1792]
It looks like DeviceEvent::MouseMotion isn't emitted when building for web-sys. I do receive WindowEvent::CursorMoved events, but since those don't contain deltas, they are quite inconvenient to implement a 3D camera.

Possibly this is blocked on #1674 ?

**Comment by alvinhochun** [comment]
> Possibly this is blocked on #1674 ?

Not exactly. These two complements each other, as cursor grabbing is not useful without mouse movement delta and mouse movement data is only necessary when the cursor is locked.

This shouldn't be too hard to implement on top of the existing mouse/pointer handling code, except that some consideration needs to be taken regarding the touch and pen input that also comes with the pointer events. This may or may not require #1673 to be dealt with at the same time.

**Comment by willcrichton** [comment]
Note that I've implemented this in #1827, just waiting on review.

**Comment by ArturKovacs** [comment]
@swiftcoder is this issue resolved on the latest commit of the master branch? (which currently is 982ad46c83ea7c4dfcc5dc164d026f6ece3611a9)

**Comment by maroider** [comment]
As I said in #1827: probably.

Guess I'll do it now, then.
