### ISSUE TITLE
How to send an event explicitly?

### ISSUE THREAD

**Issue by nikitablack** [rust-windowing/winit#1794]
Hello.

I couldn't find it in the docs so I'm asking here. Is there a way to send an event explicitly. Let's say I want to send `WindowEvent::CloseRequested` as a reaction to user interaction. How do I do this?

**Comment by dhardy** [comment]
IIUC you can only send user events via [`EventLoopProxy`](https://docs.rs/winit/0.23.0/winit/event_loop/struct.EventLoopProxy.html).

**Comment by maroider** [comment]
> Let's say I want to send `WindowEvent::CloseRequested` as a reaction to user interaction. How do I do this?

Why would you want to do it this way?

Sending arbitrary Winit events from user code is something that's unlikely to _ever_ be supported.

**Comment by nikitablack** [comment]
Well, that's a pretty common requirement - every event-based system I know allows to do that. As an example of why I'd like to have it suppose a window close that happening on close button click. In my case, the confirmation dialog is created and maybe a clean procedure is called. But the same request can happen, for example, on keyboard combination press or in some other module as a result of UI interaction. In that case sending `WindowEvent::CloseRequested` would be much simpler and in fact, cleaner.

**Comment by nikitablack** [comment]
In any case, the `EventLoopProxy` as suggested by @dhardy is sufficient for me, though not ideal.

**Comment by maroider** [comment]
> Well, that's a pretty common requirement - every event-based system I know allows to do that.

Do SDL 2 or GFLW allow this? Those have roles which are comparable to Winit (although Winit is slightly more constrained in its scope), and they don't allow this AFAIK.

> As an example of why I'd like to have it suppose a window close that happening on close button click. In my case, the confirmation dialog is created and maybe a clean procedure is called. But the same request can happen, for example, on keyboard combination press or in some other module as a result of UI interaction. In that case sending `WindowEvent::CloseRequested` would be much simpler and in fact, cleaner.

I suppose there may be a case to be made for this specific example, perhaps through a `Window::request_close` method, but I don't find it to be a particularly strong case.
