### ISSUE TITLE
Intel iGPU is favoured over discrete Nvidia graphics card

### ISSUE THREAD

**Issue by rikvdkleij** [rust-windowing/winit#1800]
Original issue:
https://github.com/gfx-rs/wgpu-rs/issues/673

Let me know if more info is needed.

**Comment by chrisduerr** [comment]
Winit has absolutely nothing to do with which GPU is picked for your application.

If you are running into an issue with winit crashing, please provide a full backtrace from the latest winit master.

**Comment by rikvdkleij** [comment]
@chrisduerr Ok, I will close this issue.
