### ISSUE TITLE
Windows: unable to set fullscreen mode while window is hidden

### ISSUE THREAD

**Issue by simast** [rust-windowing/winit#1803]
Noticed an issue when I was creating my window with:

```rust
let window = WindowBuilder::new()
    .with_fullscreen(Some(Fullscreen::Borderless(None)))
    .with_visible(false)
    .build(&event_loop)?;
```

And then later decided it's time to show it with `window.set_visible(true)`. Tested this on Windows OS and found out that window was not actually displayed and something got broken with input as a result - as you need to Alt-Tab to fix it,

Same flow seems to work on macOS however.

**Comment by maroider** [comment]
<details>
<summary>
I can't seem to reproduce this. Does the following program trigger the bug for you?
</summary>

```Rust
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::{Fullscreen, WindowBuilder},
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let event_loop = EventLoop::new();

    let window = WindowBuilder::new()
        .with_fullscreen(Some(Fullscreen::Borderless(None)))
        .with_visible(false)
        .build(&event_loop)?;

    event_loop.run(move |event, _elwt, control_flow| {
        window.set_visible(true);
        match event {
            Event::WindowEvent { event, .. } => match event {
                WindowEvent::CloseRequested => *control_flow = ControlFlow::Exit,
                _ => {}
            },
            _ => {}
        }
    })
}
```
</details>

Are you able to reproduce this on other machines?
What kind of input was it that got "broken"?
Which versions of Winit and Windows did you test with?

**Comment by simast** [comment]
Yes, your example reproduces the issue I described.

> Are you able to reproduce this on other machines?

Only have one Windows machine, sorry.

>What kind of input was it that got "broken"?

When I run your example program the following things happen:
1. Program launches and taskbar icon appears.
2. Window is not visible however (I can still see my desktop).
3. All mouse input is blocked and to fix it I have to Alt-Tab.

> Which versions of Winit and Windows did you test with?

winit 0.24.0
Windows 10 Pro 19042.685

**Comment by maroider** [comment]
Could you try testing with Winit `master`?

> 3. All mouse input is blocked and to fix it I have to Alt-Tab.

Just to clarify: Is the mouse input blocked for the desktop or the window?
On my machine, the window is entirely transparent, so I can still see the programs I already had open, as well as the task bar, but all interaction with them is blocked by the fullscreen window.

**Comment by simast** [comment]
> On my machine, the window is entirely transparent, so I can still see the programs I already had open, as well as the task bar, but all interaction with them is blocked by the fullscreen window.

That was it :man_facepalming:
Just setup a demo with [winit-blit](https://github.com/rust-windowing/winit-blit) to render something to window surface and sure enough it's working as expected. I read in the docs that you can get some garbage pixels on a window surface until you render on it, but did not expect to actually get fully transparent pixels.

Sorry, will close this issue now.
