### ISSUE TITLE
Attempt to input Korean characters using uim freezes winit windows

### ISSUE THREAD

**Issue by RangHo** [rust-windowing/winit#1813]
Came to upstream from alacritty/alacritty#4469.

When in `uim` "Hangul-mode", attempt to input characters freezes *any* window powered by `winit`. No more screen updates happen, and it never responds to events like `WM_DELETE_WINDOW`. [Here](https://pastebin.com/RrtdiW3G) is the `alacritty` backtrace. When I step out of the functions, the execution hangs in `XIfEvent`.

In the `alacritty` issue I mentioned, I discovered that the core cause is that `uim` crashes and burns when a certain hardcoded font file is not found (uim/uim#156). Still, I don't see issues like this in other X11-based programs (e.g. `emacs`, `urxvt`, ...), so I think `winit` too should be able to handle this kind of issue more gracefully.

### System

* OS: Arch Linux running Zen Kernel 5.8.14
* Display Manager: X11 using `bspwm` window manager with `picom` compositor
* IME: `uim` + `uim-byeoru`, with [custom configuration](https://github.com/RangHo/dotfiles/blob/master/uim/.uim)

### How to reproduce

1. Run `uim-xim &` to start uim (If X session was just started, this step is unnecessary)
2. Build and run any example window in `winit` repository
3. Change input method by pressing `Shift + Space` (at least for my configuration)
4. Type a character, then the focused `winit` window should become unresponsive

P.S. I am not sure if the title reflects the issue well enough. If it doesn't, please change the title to a more appropriate one!

**Comment by kchibisov** [comment]
Seems like it's fixed now.
