### ISSUE TITLE
Windows no longer get fully transparent background with winit v0.24.0

### ISSUE THREAD

**Issue by dotdash** [rust-windowing/winit#1814]
I have a small toy program that uses OpenGL (via glutin) in a non-decorated, transparent window to display some graphics. Starting with v0.24.0 the windows is no longer fully transparent. In the image below, the left side is with winit 0.23, and the right side with 0.24.

![transparency_bug](https://user-images.githubusercontent.com/230962/103421588-759b6900-4b9d-11eb-9f47-edb3cd7d7dbb.jpg)

I identified https://github.com/rust-windowing/winit/pull/1621 as the culprit, reverting this commit fixes the issue for me, but I don't know Windows well enough to know why that is.

**Comment by maroider** [comment]
I've reproduced this with the `transparent` example.
