### ISSUE TITLE
Duplicate dependencies

### ISSUE THREAD

**Issue by baptistemanson** [rust-windowing/winit#1816]
Hi all,
I'm a absolute beginner in Rust.

While using the command "cargo tree -d", I saw duplicates on `core-graphics, core-foundation-sys, core-foundation`.
- Am I reading the dups correctly?
- Is it fair to say that updating core-video-sys to more recent libs would shave of around 100kB of dups out of the 300kB of winit?

Thanks for your patience!
```
core-graphics v0.19.2
└── core-video-sys v0.1.4
    └── winit v0.24.0
        └── wgpu v0.1.0 (/Users/inovia/Desktop/rust/wgpu)

core-graphics v0.22.2
├── cocoa v0.24.0
│   └── winit v0.24.0
│       └── wgpu v0.1.0 (/Users/inovia/Desktop/rust/wgpu)
└── winit v0.24.0 (*)
```

**Comment by madsmtm** [comment]
This is not an issue with `winit`, but with `core-video-sys`, they need to release a new version with newer dependencies (last release was 2020-05-06). See https://github.com/LuoZijun/rust-core-video-sys/issues/16 for a similar issue/suggestion.
