### ISSUE TITLE
EventsLoop should be a trait

### ISSUE THREAD

**Issue by AsafFisher** [rust-windowing/winit#1819]
Does anyone work on EventsLoop trait?

**Comment by msiglreith** [comment]
Hi!
Could you provide some more information on the benefits of changing it into a trait compared to the current approach?

**Comment by katyo** [comment]
I think the current approach is more performant than defining event handlers as a trait. But the traits can be more flexible in some cases. For example we can implement traits for tuples, what allow us combine several event handlers easily.
In any case I think the current aproach is a best for different use cases. When it really needed the thin abstraction layer can be implemented youself.

**Comment by AsafFisher** [comment]
Traits should not have additional runtime complexity, what I mean is for example all the platforms should import a well defined trait called EventLoop that defines the interface which every "abstraction layer" should implement. For example the method `run`. All the platforms that comply to EventLoop should implement a `run` method.

**Comment by AsafFisher** [comment]
This should not exist. Instead it should be a trait and all the platforms should comply to it.
Then you just make sure to link with the correct platform And there is no need for all these weird `self.event_loop.run()`
```
pub struct EventLoop<T: 'static> {
    pub(crate) event_loop: platform_impl::EventLoop<T>,
    pub(crate) _marker: ::std::marker::PhantomData<*mut ()>, // Not Send nor Sync
}
```

**Comment by LoganDark** [comment]
> my change will reduce runtime and code because it will not inline the `self.event_loop.run` when you do an `event_loop.run`. But instead will call the platform specific `run` method.

The optimizer is extremely good at optimizing things. I don't think a function containing a single tail call is a challenge for it.

**Comment by AsafFisher** [comment]
I agree, still the current design is weird and not modular.

**Comment by LoganDark** [comment]
> the current design is weird and not modular

Other libraries cannot implement the event loop because Winit's event loop is tightly tied to its window handling.

You can't just make it a trait and call it good.

**Comment by AsafFisher** [comment]
I think you didn't read my proposal and you don't understand it.

**Comment by LoganDark** [comment]
Yes, I read your proposal - all six words of it. (And the comments after.)

I think you are misunderstanding the purpose of hiding the internals behind a struct rather than exposing them with a trait.

Trait objects are not sized, so each platform would need its own event loop struct, and everything that accepted an event loop would have to be generic (well, more than they are now). At least with a struct, the size is known at compile time (though it may be different per-platform).

It would complicate things massively as suddenly anything could be an event loop, an event loop could come from any crate and have any behavior, and so on. Yes, that may be the purpose of traits but I don't think they want a trait here.

Please re-think your reasoning.

**Comment by AsafFisher** [comment]
> Yes, I read your proposal - all six words of it. (And the comments after.)
> 
> I think you are misunderstanding the purpose of hiding the internals behind a struct rather than exposing them with a trait.
> 
> Trait objects are not sized, so each platform would need its own (public) event loop struct, and everything that accepted an event loop would have to be generic (well, more than they are now). At least with a struct, the size is known at compile time (though it may be different per-platform).

Trait objects are not sized?
"each platform would need its own (public) event loop struct" - Hmm that already happening:
macos - [https://github.com/rust-windowing/winit/blob/b9f3d333e41464457f6e42640793bf88b9563727/src/platform_impl/macos/event_loop.rs#L56](url)
android - [https://github.com/rust-windowing/winit/blob/b9f3d333e41464457f6e42640793bf88b9563727/src/platform_impl/android/mod.rs#L44](url)
ios - [https://github.com/rust-windowing/winit/blob/b9f3d333e41464457f6e42640793bf88b9563727/src/platform_impl/ios/event_loop.rs#L68](url)
wayland - [https://github.com/rust-windowing/winit/blob/b9f3d333e41464457f6e42640793bf88b9563727/src/platform_impl/linux/wayland/event_loop/mod.rs#L71](url)
WebAssembly - [https://github.com/rust-windowing/winit/blob/b9f3d333e41464457f6e42640793bf88b9563727/src/platform_impl/web/event_loop/mod.rs#L15](url)
And so on... Why shouldn't they comply to EventLoop interface?

I don't understand... Each platform will have its own struct but will comply to the `EventLoop` trait. Meaning, it will by definition need to implement `run` and `create_proxy`. Not everything needs to be generic. Each platform can handle their `event_loop` struct as they wish. However they will have to supply the basic generic implementations of the `EventLoop` trait.
Rust give you a powerful tool to make interfaces both generic and low level.

> It would complicate things massively as suddenly anything could be an event loop, an event loop could come from any crate and have any behavior, and so on. Yes, that may be the purpose of traits but I don't think they want a trait here.
> 
> Please re-think your reasoning.

**Comment by msiglreith** [comment]
Similar discussion quite some time ago: https://github.com/rust-windowing/winit/issues/908

Based on my experience back from the gfx-hal api, I'm quite indifferent on this topic - it would probably require such a `Backend` trait aswell followed with a bunch of associated types for `Window` and maybe device types in the future. Another question would be if this should be exposed to users as well or just for implementation. I'm not sure if we could actually get away from the wrapper types as frontend for users, which having the import all the traits and platform specific types.

Based on this I feel this will be more work and code for little gains (CI checks ensure that backend adhere to the frontend API layer already). Nonetheless, if someone comes up with a protoype implementation this can be discussed more properly.

**Comment by LoganDark** [comment]
> "each platform would need its own (public) event loop struct" - Isn't that already happening?

No, it's not, because these types are not directly exported by winit - it's contained behind the implementation details of the main EventLoop struct. Even though the struct is marked `pub`, the module itself is not public.

**Comment by maroider** [comment]
Another issue here is that the experience of browsing the documentation will degrade if you move the `EventLoop` API from an inherent impl to a trait. It would also be a bit confusing to have both a public `EventLoop` type per platform, and a public `EventLoop` trait.

**Comment by AsafFisher** [comment]
I don't think it will degrade. Plus it will make tests more easy to make for each platform in the long term.
As @msiglreith said maybe after a suitable prototype you will change your mind :smiley:

**Comment by LoganDark** [comment]
> Plus it will make tests more easy to make for each platform in the long term.

What makes you think they're not already easy? You need to test on said platform anyway.

**Comment by madsmtm** [comment]
The discussion here has stalled, and I agree that, as I understand it, this proposal would yield relatively little benefit compared to the code churn.

Feel free to reopen if you have further points to add, especially if you can elaborate on how this proposal differs from https://github.com/rust-windowing/winit/issues/908.
