### ISSUE TITLE
Why are `modifiers` fields deprecated?

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-windowing/winit#1824]
For example `KeyboardInput::modifiers` is deprecated as:

> Deprecated in favor of `WindowEvent::ModifiersChanged`

However, the docs still say:

> Modifier keys active at the time of this input.
>
> This is tracked internally to avoid tracking errors arising from modifier key state changes when events from this device are not being delivered to the application, e.g. due to keyboard focus being elsewhere.

Which sounds like a good argument to let `winit` track the modifier keys internally. So I'm a bit confused. Is it actually planned to remove the internal tracking of modifier keys? Can applications now reliably track those modifier keys with `WindowEvent::ModifiersChanged`? Even if I could reliable track modifiers myself, the `modifiers` field sure is very convenient. 

The deprecation was added in https://github.com/rust-windowing/winit/pull/1344

**Comment by maroider** [comment]
IIUC, Winit will still track the state internally, but will only report changes to the state through `WindowEvent::ModifiersChanged`.

**Comment by spearman** [comment]
If i launch my application while a modifier is held down, there can be events before the initial ModifiersChanged event that need to know the current modifiers. Here's an example where I have held down SHIFT while launching:
```
NewEvents(Init)
WindowEvent { window_id: WindowId(X(WindowId(33554434))), event: Resized(PhysicalSize { width: 1596, height: 882 }) }
System(Resized { width: 1596, height: 882 })
WindowEvent { window_id: WindowId(X(WindowId(33554434))), event: CursorEntered { device_id: DeviceId(X(DeviceId(2))) } }
System(CursorEntered)
WindowEvent { window_id: WindowId(X(WindowId(33554434))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 487.0, y: 436.0 }, modifiers: SHIFT } }
Pointer(Pointer { position_horizontal: 487, position_vertical: 436, modifiers: SHIFT })
WindowEvent { window_id: WindowId(X(WindowId(33554434))), event: Focused(true) }
System(Focused(true))
WindowEvent { window_id: WindowId(X(WindowId(33554434))), event: ModifiersChanged(SHIFT) }
```
There is a cursor moved event with modifiers, then modifiers changed comes afterwards.

If i need to track modifiers based on change events, is there a way to get the initial starting modifiers, before any other events are received that might care about the (deprecated) modifiers state?

**Comment by maroider** [comment]
> If i need to track modifiers based on change events, is there a way to get the initial starting modifiers, before any other events are received that might care about the (deprecated) modifiers state?

"Initial starting modifiers" ought to be delivered through an initial `ModifiersChanged` event. If I'm reading the log you've attached correctly, then this seems like a bug in the X11 implementation. The modifier tracking is correct internally (according to your attached log), but it isn't exposed correctly to the user.

In any case, it probably wouldn't hurt to do a pass over all platforms to see if any other platforms exhibit this behavior (and correct it, if need be).

**Comment by ArturKovacs** [comment]
This is why: https://github.com/rust-windowing/winit/issues/1124#issuecomment-558849766

Feel free to repoen this if your question is not answered.
