### ISSUE TITLE
Improve dpi docs

### ISSUE THREAD

**Issue by xixixao** [rust-windowing/winit#1825]
> If a window hasn't received a ScaleFactorChanged event, then its scale factor is 1.0.

should be

> If a window hasn't received a ScaleFactorChanged event, then its scale factor is [[window.scale_factor()]].

Or something like that would be nice (and imho more accurate).

**Comment by adenhaus** [comment]
Hi, I'd like to work on this.

**Comment by adenhaus** [comment]
I've made the change and submitted a PR. https://github.com/rust-windowing/winit/pull/1834
Can someone with write permissions please review? Thanks.
