### ISSUE TITLE
Calling `preventDefault` on `keypress` events suppresses browser clipboard events

### ISSUE THREAD

**Issue by mvlabat** [rust-windowing/winit#1829]
https://github.com/rust-windowing/winit/blob/33fb62bb259b05dcfd6f319328b2f90bd387df13/src/platform_impl/web/web_sys/canvas.rs#L193

This particular line of code prevents browsers to send clipboard events if winit's canvas is focused.

That makes it troublesome to add copy/cut/paste events support to UI frameworks.

**Comment by maroider** [comment]
I believe this problem has already been brought up in #1768, but copy/cut/paste wasn't explicitly called out there.

**Comment by daxpedda** [comment]
You can now use [`WindowBuilder::with_prevent_default(false)`](https://docs.rs/winit/latest/wasm32-unknown-unknown/winit/window/struct.WindowBuilder.html#method.with_prevent_default).

Though ultimately this should also be solved by https://github.com/rust-windowing/winit/pull/2156 or https://github.com/rust-windowing/winit/issues/2831.

But I would actually like to not call `preventDefault()` when we detect a clipboard command, unfortunately I'm not aware of any way to actually do this except detecting the right keybind, e.g. CTRL + C/V/X.

I researched this briefly, as far as I can tell you can change these keybinds, so we could also expose an option to not use `preventDefault()` when we detect certain commands.

**Comment by daxpedda** [comment]
Closing in favor of #2831, which might be extended to handle certain things like that.
