### ISSUE TITLE
How to set the window contents from the CPU (without OpenGL)?

### ISSUE THREAD

**Issue by fschutt** [rust-windowing/winit#1831]
I use webrender-swgl to render a display list to a CPU `Vec<u8>`. However, I don't know how to copy that buffer to the screen without using OpenGL. The implementation for swgl uses this code:

```rust
let swgl = match self.software_gl.as_ref() {
    Some(swgl) => swgl,
    None => return,
};
swgl.finish();
let gl = &self.hardware_gl;
let tex = gl.gen_textures(1)[0];
gl.bind_texture(gl::TEXTURE_2D, tex);
let (data_ptr, w, h, stride) = swgl.get_color_buffer(0, true);
assert!(stride == w * 4);
let buffer = unsafe { std::slice::from_raw_parts(data_ptr as *const u8, w as usize * h as usize * 4) };
gl.tex_image_2d(gl::TEXTURE_2D, 0, gl::RGBA8 as gl::GLint, w, h, 0, gl::BGRA, gl::UNSIGNED_BYTE, Some(buffer));
let fb = gl.gen_framebuffers(1)[0];
gl.bind_framebuffer(gl::READ_FRAMEBUFFER, fb);
gl.framebuffer_texture_2d(gl::READ_FRAMEBUFFER, gl::COLOR_ATTACHMENT0, gl::TEXTURE_2D, tex, 0);
gl.blit_framebuffer(0, 0, w, h, 0, 0, w, h, gl::COLOR_BUFFER_BIT, gl::NEAREST);
gl.delete_framebuffers(&[fb]);
gl.delete_textures(&[tex]);
gl.finish();
```

However, I want my software to work even when no GL context is present. So I just have a `*const c_void image_data, isize width, isize height, isize depth`, how do I copy the contents of that image buffer to the window *without* using OpenGL?

**Comment by maroider** [comment]
Well, there's [`winit-blit`](https://github.com/rust-windowing/winit-blit), but that only has a Windows backend.

**Comment by LoganDark** [comment]
I know this is exactly not what you asked for, but there is an existing library for this: https://github.com/shivshank/mini_gl_fb/

There's currently a pull request that needs to be merged for it to become usable, though. https://github.com/shivshank/mini_gl_fb/pull/5

Take a look at the multi_window example, it's the best showcase of the updated functionality.

https://github.com/LoganDark/mini_gl_fb/blob/update/examples/multi_window.rs

**Comment by maroider** [comment]
Also: If you're willing to eschew Winit, you could go with [`minifb`](https://github.com/emoon/rust_minifb), but you'd have to accept that `minifb` has some ... interesting bugs (last time I checked, anyway).

**Comment by LoganDark** [comment]
> Also: If you're willing to eschew Winit, you could go with [`minifb`](https://github.com/emoon/rust_minifb), but you'd have to accept that `minifb` has some ... interesting bugs (last time I checked, anyway).

- They still use the polling model, so resizing the window blocks the thread
- They don't give you events, only the current state (which you have to poll constantly, so 100% CPU usage)

I'm moving _from_ `minifb`, so I understand its drawbacks well. Trust me, `winit` is way better, and `mini_gl_fb` is exactly what you want.

**Comment by maroider** [comment]
I'm pretty sure `mini_gl_fb` will fail in certain VMs where OpenGL won't work. IIRC, someone ran into an issue like this with Servo.

Updating `mini_gl_fb` will probably be "good enough for now", in the absence of broader platform support in `winit-blit`.

**Comment by LoganDark** [comment]
I _did_ just run into an issue where `mini_gl_fb` refused to run in a virtual machine because I didn't have hardware acceleration. That's probably a problem. However, it did work on bare metal, and even in Linux.

**Comment by trindadegm** [comment]
[`pixels`](https://github.com/parasyte/pixels) might be an option for you. It's still new but appears to be a less "simple" version of [`minifb`](https://github.com/emoon/rust_minifb). I still did not actually used it, but it caught my attention when I was searching around.

The `pixels` crates claims to be cross-platform (implemented on top of `wgpu`), and is designed to work alongside whatever windowing crate that implements `HasRawWindowHandle`, having examples using `winit` and `SDL`. It seems to be quite flexible, see this example with [`Dear-ImGUI + Pixels + Winit`](https://github.com/parasyte/pixels/tree/master/examples/imgui-winit). I'll definitely try it out next time I'm dealing with a bunch of pixels (last time I used `minifb` and missed `winit` a little).

**Comment by LoganDark** [comment]
> [`pixels`](https://github.com/parasyte/pixels) might be an option for you. It's still new but appears to be a less "simple" version of [`minifb`](https://github.com/emoon/rust_minifb). I still did not actually used it, but it caught my attention when I was searching around.
> 
> The `pixels` crates claims to be cross-platform (implemented on top of `wgpu`), and is designed to work alongside whatever windowing crate that implements `HasRawWindowHandle`, having examples using `winit` and `SDL`. It seems to be quite flexible, see this example with [`Dear-ImGUI + Pixels + Winit`](https://github.com/parasyte/pixels/tree/master/examples/imgui-winit). I'll definitely try it out next time I'm dealing with a bunch of pixels (last time I used `minifb` and missed `winit` a little).

That would have been my first choice had it not been for this critical flaw: https://github.com/parasyte/pixels/issues/125

**Comment by trindadegm** [comment]
> That would have been my first choice as well, had it not been for this critical flaw: [parasyte/pixels#125](https://github.com/parasyte/pixels/issues/125)

That's too bad. Maybe this [pull request](https://github.com/parasyte/pixels/pull/122) will fix it later on. I hope it gets fixed soon.

**Comment by JMS55** [comment]
@LoganDark I'm currently working on it, along with updating pixels to wgpu 0.7. It'll probably be a good bit before it's ready. However, I can vouch that pixels is a great crate. I use it in my game https://github.com/JMS55/sandbox.

**Comment by JoshLambda** [comment]
> > [`pixels`](https://github.com/parasyte/pixels) might be an option for you. It's still new but appears to be a less "simple" version of [`minifb`](https://github.com/emoon/rust_minifb). I still did not actually used it, but it caught my attention when I was searching around.
> That would have been my first choice as well, had it not been for this critical flaw: [parasyte/pixels#125](https://github.com/parasyte/pixels/issues/125)

It has been solved with this PR: https://github.com/parasyte/pixels/pull/136. The buffer can now resize itself with the window.

**Comment by LoganDark** [comment]
> > > [`pixels`](https://github.com/parasyte/pixels) might be an option for you. It's still new but appears to be a less "simple" version of [`minifb`](https://github.com/emoon/rust_minifb). I still did not actually used it, but it caught my attention when I was searching around.
> > > That would have been my first choice as well, had it not been for this critical flaw: [parasyte/pixels#125](https://github.com/parasyte/pixels/issues/125)
> 
> It has been solved with this PR: [parasyte/pixels#136](https://github.com/parasyte/pixels/pull/136). The buffer can now resize itself with the window.

Yes, technically it can. But the programmer has no choice in what it is resized to. :(

Well, they _kind of_ do, they can make a fake call to `resize` with their desired resolution and `resize_buffer` set to `true`, and then make a real call with it set to `false`, but that's a weird thing to have to do.

**Comment by madsmtm** [comment]
A pure software draw solution has been made recently in [`softbuffer`](https://github.com/john01dav/softbuffer)

**Comment by LoganDark** [comment]
> A pure software draw solution has been made recently in [`softbuffer`](https://github.com/john01dav/softbuffer)

Oh my god thank you, `softbuffer` simply does not have so many issues, including https://github.com/gfx-rs/wgpu/issues/1168, which was the reason I entirely stopped doing graphics programming. Now I can get back into it. Thank you!!
