### ISSUE TITLE
winapi's HWND used in public functions and is not re-exported.

### ISSUE THREAD

**Issue by PrototypeNM1** [rust-windowing/winit#1836]
Various `ExtWindows` traits have public functions which use `winapi`'s `HWND`, but `HWND` is not reexported by `winit`. The only struct with a public `HWND` member seems to be the Windows builder, which would be `None` unless assigned.

Walking through git blame didn't illuminate this decision, and this decision isn't consistent throughout the crate, e.g. `WindowExtWindows`'s [fn hwnd(&self) -> *mut libc::c_void](https://github.com/rust-windowing/winit/blob/6ddee9a8acede06421df0ccab3b65c019a6c3a0c/src/platform/windows.rs#L79).

These commits predate raw_window_handle which may be preferable over reexporting HWND.

**Comment by maroider** [comment]
With the decisions made in rust-windowing/raw-window-handle#3 in mind (as well as what's proposed in #1976), `core::ffi::c_void` should be preferred to `libc::c_void`.

**Comment by madsmtm** [comment]
I pointed this out in https://github.com/rust-windowing/winit/pull/2057#discussion_r777124694 as well, so this will be fixed by https://github.com/rust-windowing/winit/pull/2057.

**Comment by nerditation** [comment]
> 
> Walking through git blame didn't illuminate this decision, and this decision isn't consistent throughout the crate, e.g. `WindowExtWindows`'s [fn hwnd(&self) -> *mut libc::c_void](https://github.com/rust-windowing/winit/blob/6ddee9a8acede06421df0ccab3b65c019a6c3a0c/src/platform/windows.rs#L79).
>

another inconsistence (and inconvenience): ``fn with_parent_window(self, parent: HWND) -> WindowBuilder`` of trait ``WindowBuilderExtWindows`` take HWND as parameter, while ``fn hwnd(&self) -> *mut c_void`` of trait ``WindowExtWindows`` returns ``*mut c_void``. but the ``hwnd`` method inside the ``impl WindowExtWindows for Windows`` block actually calls the platform specific ``hwnd()`` method, which returns ``HWND``, and then cast it to ``*mut c_void``. I suppose this is not intended and should be fixed.

**Comment by madsmtm** [comment]
Thanks @nerditation, that is also handled by #2057

**Comment by msiglreith** [comment]
Should be fixed with https://github.com/rust-windowing/winit/pull/2057 in the upcoming version
