### ISSUE TITLE
Request for clarification: How to create multiple windows in one application

### ISSUE THREAD

**Issue by ckaran** [rust-windowing/winit#1844]
I've been reading the documentation for winit to see how I can create multiple windows in one application.  Here is my current understanding of how windows are created:

1. To create a new window, you need to pass in an event loop (see [`Window::new`](https://docs.rs/winit/0.24.0/winit/window/struct.Window.html#method.new)).
2. Event loops can only be created on the main thread (see [`EventLoop::new`](https://docs.rs/winit/0.24.0/winit/event_loop/struct.EventLoop.html#method.new)) and are neither `Send` nor `Sync`, and so cannot be moved to a background thread (not even if they're created on the main thread, wrapped in a mutex, and then sent to a background thread).
3. Once the event loop is started by calling [`EventLoop::run`](https://docs.rs/winit/0.24.0/winit/event_loop/struct.EventLoop.html#method.run), it will never return.  Thus, you can only create one event loop in an application.

This implies to me that winit expects there to be a single, global event loop instance that is shared between all windows.  Is this correct?  And if I want to create new windows, I need to use the [`EventLoopWindowTarget`](https://docs.rs/winit/0.24.0/winit/event_loop/struct.EventLoopWindowTarget.html) that is passed to my callback function within the event loop, correct?

My apologies if all of this should be obvious, I'm used to writing headless multi-threaded simulations so the whole GUI world is kind of new to me and taking some time to get used to.  Thank you for any advice you can give me.

**Comment by maroider** [comment]
> To create a new window, you need to pass in an event loop

You actually "only" need `EventLoopWindowTarget`, but `EventLoop` has a `Deref<Target = EventLoopWindowTarget>` impl.

> This implies to me that winit expects there to be a single, global event loop instance that is shared between all windows. Is this correct?

Yep. Winit expects you to only ever create one `EventLoop`. If you make any more than that, then you're probably going to encounter some _interesting_ issues.

> And if I want to create new windows, I need to use the EventLoopWindowTarget that is passed to my callback function within the event loop, correct?

Well, if you want to create them after you've called `EventLoop::run`, then yes. You can still create multiple windows before entering the event loop. The `multiwindow` [example] demonstrates both cases.

> My apologies if all of this should be obvious, I'm used to writing headless multi-threaded simulations so the whole GUI world is kind of new to me and taking some time to get used to. Thank you for any advice you can give me.

It's perfectly OK to ask questions if you're not sure of something. Feel free to reach out on any of the channels listed in the [README] (under "Contact Us").

[example]: https://github.com/rust-windowing/winit/blob/e4754999b7e7f27786092a62eda5275672d74130/examples/multiwindow.rs
[README]: https://github.com/rust-windowing/winit#contact-us

**Comment by ckaran** [comment]
@maroider Wow, fast response! :+1:

Thank you, I'll look into the examples as well and see what I can learn.
