### ISSUE TITLE
Linux: Implement is_maximized

### ISSUE THREAD

**Issue by msiglreith** [rust-windowing/winit#1845]
New method `Window::is_maximized` has been added in https://github.com/rust-windowing/winit/pull/1804
Currently lacking linux support.
- [ ] X11
- [ ] Wayland

**Comment by garasubo** [comment]
For X11, we can get maximized status using `_NET_WM_STATE_MAXIMIZED_*`.
https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html#id2522991

I can work on it on this weekend.
