### ISSUE TITLE
Closure-captured values aren't dropped on panic

### ISSUE THREAD

**Issue by kvark** [rust-windowing/winit#1850]
This is similar to #1058, but unlike a normal termination, I'm talking about panics. A panic inside the closure is something that can happen in a user application, and it would generally expect the involved objects to be dropped in order to do safe cleanup. This is blocking https://github.com/gfx-rs/wgpu/issues/861

**Comment by maroider** [comment]
Which platform(s) does this affect?

Values seem to get dropped on panic just fine on Windows.

**Comment by kvark** [comment]
IIRC, I was testing mostly on macOS. I'll double check other platforms as well.

**Comment by kvark** [comment]
Yep, Linux is fine, and you checked windows. So it looks to be Apple-only.

**Comment by maroider** [comment]
This seems to be related to #141.

Sadly, I'm not in a position to address macOS issues.

cc @ArturKovacs

**Comment by maroider** [comment]
There's a PR open to fix this now (#1853).

Feel free to test it at your leisure, @kvark.

**Comment by kvark** [comment]
I confirm this fix works for us. Thanks @ArturKovacs for addressing this!

**Comment by ArturKovacs** [comment]
I'm happy to help!
