### ISSUE TITLE
Exiting process internally makes the library extremely intrusive

### ISSUE THREAD

**Issue by notdanilo** [rust-windowing/winit#1857]
This is a really bad regression. I am not able anymore to run separated [tests](https://github.com/notdanilo/gpu/tree/master/tests) each one with its own EventLoop.
https://github.com/rust-windowing/winit/blob/b1be34c6a040c643d3bd15193850ae2484743e39/src/platform_impl/linux/x11/mod.rs#L399

**Comment by maroider** [comment]
Is [`EventLoopExtRunReturn::run_return`](https://docs.rs/winit/0.24.0/winit/platform/run_return/trait.EventLoopExtRunReturn.html#tymethod.run_return) insufficient for your use case?

**Comment by notdanilo** [comment]
@maroider thanks for pointing it out. It seems to be a problem only on Linux. But it's good to have a workaround for it available in the API.
