### ISSUE TITLE
Transparent window isn't fully transparent?

### ISSUE THREAD

**Issue by PutterBeanut** [rust-windowing/winit#1859]
OS: Windows
Winit Version: Latest (0.24.0)
Rust Version: 2018

I'm using winit just to play around and I turned off decorations and enabled transparency with the following code
```rust
let window = WindowBuilder::new()
        .with_transparent(true)
        .with_decorations(false)
        .build(&event_loop).unwrap();
```
and whenever I run, you'd expect the window to be completely hidden from the screen, but no, it's only _partly_ transparent. There's a mostly transparent gray box where the window would be, instead of there being a completely clear window as seen in the image below. It's hard to notice but it's not the look I'm going for. Can someone tell me why this happens and how to get around this? Thank you!
![transparency](https://user-images.githubusercontent.com/36495037/107864243-e205bb00-6e1f-11eb-89f1-eb1365fc43bd.png)

**Comment by maroider** [comment]
Hi, thanks for reporting this.

This is a known issue (#1814), and there is a fix in the works (#1815).
Feel free to check if the proposed changes work for you.
