### ISSUE TITLE
Is it possible to exit an event loop without exiting the process?

### ISSUE THREAD

**Issue by lokegustafsson** [rust-windowing/winit#1860]
`EventLoop::run` returns `!`, so it will never return to the thread that calls it. I tried creating an event loop in a child thread (possible on unix), running it and then exiting. I expected the main thread to be able to carry on, but it turns out the entire process exits after an event loop in a child thread exits.

The weird thing is that `EventLoopProxy::send_event` is not infallible. Its docs suggest the possibility of an event loop being closed, presumably without exiting the process. Trivially one can create an event loop and a proxy, then drop the event loop without ever running it to create a proxy to a closed event loop. But is there any other way to do so?

**Comment by lokegustafsson** [comment]
Another, related question: While I can't imagine doing this in a reasonable use case, what happens if I create and run two event loops in the same process? Would they exit simultaneously, when the first of them exits?

**Comment by maroider** [comment]
> While I can't imagine doing this in a reasonable use case, what happens if I create and run two event loops in the same process?

AFAIK, you're only ever expected to have a single `EventLoop` instance at any time. This isn't really enforced anywhere.

[`EventLoopExtRunReturn::run_return`](https://docs.rs/winit/0.24.0/winit/platform/run_return/trait.EventLoopExtRunReturn.html#tymethod.run_return) sound like what you want, but it isn't supported on every platform.

**Comment by ArturKovacs** [comment]
I'm closting this, as the question seems to have been answered. Feel free to indicate/reopen if this is not true.
