### ISSUE TITLE
winit doesn't work on Fedora

### ISSUE THREAD

**Issue by opalien** [rust-windowing/winit#1862]
to introduce, I'm not a developer, just a guy who want to try using winit...
I'm not able to say you what going wrong exactly but I have some details that can help you. First, it's not an hardware issue because i tried winit before on the same computer with pop!_os and winit worked well.
when I tried to launch an application using winit (like your examples), no warning or problem is displayed in terminal ; the background program works. But no window appeared, only an default icon is displayed on the dock (of Gnome)...
I suspect it's from wayland/X11 but I'm not sure.
I write this issue just to warn you about this problem not for help. (too hard to solve for my level)

Sorry for my very bad English, I'm French ;)

**Comment by dhardy** [comment]
I guess this relates to Wayland (I think the default now for Gnome on Fedora). Winit certainly works on X11 on Fedora (for me).

**Comment by JMS55** [comment]
I can chime in, I've tested both X11 and Wayland on Fedora 33 and 32. Works fine for me.

**Comment by opalien** [comment]
thank you for your answers and sorry for replaying late.
So I have tried some tests like the proposes examples and I realized that with fedora, without refresh application script, this last doesn't appear... sorry
And finally, winit works well on fedora.
