### ISSUE TITLE
KMS/DRM/GBM as a new backend

### ISSUE THREAD

**Issue by NathanRoyer** [rust-windowing/winit#1865]
Hello ! I'm working on a 'kiosk' mode application with runs on an embedded linux system configured for rust.
The choice was made to not have any compositor (wayland/x11) at all on the system, and to rely on Kernel Modesetting, the Direct Rendering Manager API and Generic Buffer Management (from mesa3d) for the graphics.
I'm at the point where I can draw to the screen via a framebuffer, I have details about the hardware and I have an opengl context via [khronos-egl](https://crates.io/crates/khronos-egl).

I was wondering if this could become a winit backend ? I would gladly develop such a thing.
I guess it would give a single non-resizeable fullscreen window at a time (like most activities in Android), and while I currently don't handle inputs in my test program, I'm sure I can deal with libinput to get keypresses and pointer movement. I have zero knowledge about touchscreens though.

What are your impressions / first thoughts ?
Be welcome to give any advice or direction if you want me to do it.

**Comment by NathanRoyer** [comment]
Hi @goddessfreya, I'm pinging you because I can see that [you already worked with gbm.rs](https://github.com/Smithay/gbm.rs/pull/2) a year ago, a crate which I also use in this project to interface DRM and EGL.

**Comment by maroider** [comment]
Related issues:
#1205
#1006
#696
#33

**Comment by NathanRoyer** [comment]
Thanks, I'm closing this to reply to #1006.
