### ISSUE TITLE
winit hits unreachable! code when xkbcommon isn't on the load path

### ISSUE THREAD

**Issue by yilinwei** [rust-windowing/winit#1870]
For original issue see [here](https://github.com/Smithay/wayland-rs/issues/372).

Not including `xkbcommon` causes winit to hit `unreachable!`. *Usually*, this isn't a problem because it's going to be on the load path already but Nix requires users to explicitly specify all dependencies. 

It would be nice to catch this earlier and panic with a better error message.

**Comment by kchibisov** [comment]
It's a nixos feature that you have to modify rpath, no? For example nix build for alacritty modifiers rpath and includes things like libxkbcommon, as well as some other stuff(not needed, unless you're using glutin). So I don't see any issue here. Maybe we can modify the message you see from unreachable...

**Comment by yilinwei** [comment]
It's not a "bug" per se; it's more that `unreachable!` is misleading and will probably lead to more misdiagnosed problems and open issues later down the line (though arguably, anyone who is used to NixOS is used to yak-shaving...).

Thinking on it a little more, even a documentation change on the `README` would maybe be enough saying which dependencies are needed on the `LD_LIBRARY_PATH`. This really *only* really affects developers who are on NixOS when bootstrapping a new project. wdyt @kchibisov?

**Comment by kvark** [comment]
Can't winit just return some kind of an error in this case?

**Comment by kchibisov** [comment]
Closing in favor of #1760.
