### ISSUE TITLE
Python quit unexpectedly when run examples on M1 Ship macOS

### ISSUE THREAD

**Issue by aircloud** [rust-windowing/winit#1872]
run `cargo run --example window` on M1 Ship macOS and get `Python quit unexpectedly.` (every-time):

I want to know if this is the problem of M1 or winit：

crash details:
https://github.com/aircloud/winit_crash/blob/master/Python_2021-02-28-174918_bytedance-m1deMac-mini.crash

Thanks

**Comment by LoganDark** [comment]
1. SIP disabled on an M1? Geez, didn't know it was possible. Thought Apple seriously locked down those things.
2. I don't see anything involving python anywhere in the project, so I don't think this has anything to do with winit.
3. I can't believe macOS still ships Python 2. They really need to get rid of that old mess. Try installing 3.

**Comment by ArturKovacs** [comment]
The example runs just fine on my OS X 10.11. I looked at the crash report but I couldn't see anything that would point to the source of this issue. If someone with an M1 machine could share their experience, that would be great.

**Comment by ArturKovacs** [comment]
> Python shouldn't be executing when you run cargo.

Are you sure? For the first compilation, I could imagine a build script (indirectly) invoking Python.

Regardless this is not an issue with winit, if it works fine for you, @ecton. I'll close this but feel free to continue the discussion here. I'm not sure how I could help at this point.

**Comment by ecton** [comment]
You're right, a build command could spawn it. 

If my original guess was incorrect and anyone is still having the problem, pasting the output of `cargo` from the terminal might help identify the issue. In my experience, cargo should identify which crate is failing to build if it's related to an issue executing a build script/tool.
