### ISSUE TITLE
[Big endian] Linux - select_xinput_events is not endian agnostic

### ISSUE THREAD

**Issue by msirringhaus** [rust-windowing/winit#1880]
Trying the examples on a Linux machine s390x (big endian), I got errors upon `cargo run --example window`:
```
2021-03-11 16:14:17,387 ERROR [winit::platform_impl::platform] X11 error: XError {
    description: "BadValue (integer parameter out of range for operation)",
    error_code: 2,
    request_code: 132,
    minor_code: 46,
}
```
This is, I think, because `select_xinput_events()` deconstructs `mask: i32` to an array of bytes (see [here](https://github.com/rust-windowing/winit/blob/599477d754db296016e50cb28f86f25eb7d6a4a5/src/platform_impl/linux/x11/util/input.rs#L70)). This leads to wrong results on a big endian machine.
Putting `mask: &mask.to_le_bytes() as *const _ as *mut c_uchar`, the examples seem to work fine. But this is probably a very hacky solution, as I haven't thought very hard about possible consequences.

**Comment by j-piecuch** [comment]
It appears ([here](https://github.com/freedesktop/xorg-xserver/blob/05b3c681ea2f478c0cb941c2f8279919cf78de6d/Xi/xiselectev.c#L201) and [here](https://github.com/freedesktop/xorg-xserver/blob/05b3c681ea2f478c0cb941c2f8279919cf78de6d/include/inputstr.h#L64)) that in the case of `mask` the X server assumes a little-endian representation (i.e. bits 0-7 are in the first byte, bits 8-15 in the second byte, and so on). Your fix seems correct to me.

**Comment by notgull** [comment]
As of #2825 this code has been replaced, I believe that `x11rb` automatically translates the endianness into its proper form. If you have the opportunity can you test this again?

**Comment by msirringhaus** [comment]
`cargo run --example window` doesn't crash anymore, when run from main!

I'm not 100% sure, if key events work as expected, though. 
E.g. running `cargo run --example theme`, I see no output when pressing keys. After added a few `println!()` for the default-cases, I only see `NewEvents(WaitCancelled {..})`, followed by `AboutToWait`, whenever I hit a key or move the mouse, etc.

But this might very well be a problem with VNC. I think, we can close this.
