### ISSUE TITLE
Compiling `glutin` fails with missing `set_suspend_callback`

### ISSUE THREAD

**Issue by M2WZ** [rust-windowing/winit#1886]
I'm on Windows 10 and tried to compile the [egui_template](https://github.com/emilk/egui_template/) for android, but got [a few errors (pastebin)](https://pastebin.com/DnZcF6Np). It are problems with glutin, but after asking on [glutin's freenode](https://webchat.freenode.net/#glutin), someone said the first error 
```
error[E0599]: no method named `set_suspend_callback` found for reference `&EventLoopWindowTarget<T>` in the current scope
--> C:\Users\Me\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.26.0\src\api\android\mod.rs:76:12 
     |
76 |         el.set_suspend_callback(Some(Box::new(move |suspended| {
     |            ^^^^^^^^^^^^^^^^^^^^ method not found in `&EventLoopWindowTarget<T>`
```
is an error from winit, from [an older commit](https://github.com/rust-windowing/winit/commit/b8828105cf6231e249da279851285aecd2970b4b#diff-8a469f9184766b66e49647a75192f001ef549e5f6fcf8c98eb4fc23ce9e87e15L7-L10) and pointed out that the CI from winit doesn't test android since the switch to Github Actions.
Could someone look into this (and does anyone know anything about the other errors)?

**Comment by msiglreith** [comment]
Hi!
`winit` includes Android CI checks (https://github.com/rust-windowing/winit/blob/master/.github/workflows/ci.yml#L42) and I also did some Android dev with wgpu a few weeks ago. It seems more like `glutin` bump the `winit` dependencies at some point which caused issues with the Android platform implementation. See also https://github.com/rust-windowing/glutin/issues/1307, which also includes some more WIP branch/PR.

**Comment by maroider** [comment]
> someone said [...] and pointed out that the CI from winit doesn't test android since the switch to Github Actions.

Hi! That was me.

What was actually written was:

> That first error looks like a regression from b8828105 (Winit), which didn't get caught by CI somehow

> >    Date: Wed May 6 15:27:49 2020 +0200 

> lol, this must have been broken for a while

> https://github.com/rust-windowing/winit/commit/b8828105cf6231e249da279851285aecd2970b4b#diff-8a469f9184766b66e49647a75192f001ef549e5f6fcf8c98eb4fc23ce9e87e15L7-L10

> wow, Glutin hasn't had android CI since the switch to GitHub actions

And yeah, Glutin really doesn't apppar to have any Android [CI](https://github.com/rust-windowing/glutin/blob/a727027a8b73a8e04376d27ed73ccfb897871ec0/.github/workflows/ci.yml#L33-L48).

**Comment by M2WZ** [comment]
> And yeah, Glutin really doesn't apppar to have any Android CI, but that's a Glutin issue.

Oh sorry, misunderstood then.
> See also rust-windowing/glutin#1307, which also includes some more WIP branch/PR.

So to be sure, should I use (a rebase of) [Kaiser1989's fork of glutin](https://github.com/Kaiser1989/glutin) as dep for my project?

**Comment by Kaiser1989** [comment]
I rebased my winit fork to current version and added a pull request:

https://github.com/rust-windowing/winit/pull/2118

I also added some pull request for glutin to finally fix the android problems

**Comment by MarijnS95** [comment]
As mentioned above this is a `glutin` issue, and is already tracked in https://github.com/rust-windowing/glutin/issues/1307. While both projects live under the same GitHub organization `glutin` itself is responsible for remaining compatible and/or testing Android in CI, not `winit`.

Note that I'm picking up this issue as there seem to many affected users over time and no upstream solution yet, stay tuned on the `glutin` repo if you're interested.
