### ISSUE TITLE
Update smithay-client-toolkit

### ISSUE THREAD

**Issue by JMS55** [rust-windowing/winit#1889]
https://github.com/Smithay/client-toolkit/blob/master/CHANGELOG.md#0130---2021-03-04

v0.13 brings with it an important fix - Rendering the title text now correctly works in a flatpak, and on systems without legacy font metadata.

---

Note that the version _after_ 0.13 will remove the current wayland window decorations. It relied on an unmaintained crate and didn't look that great. Winit should implement its own. I quite like how visual studio code's looks, and how they let you theme the colors.

**Comment by maroider** [comment]
I think the quickest way forward would be to forego adding any client-side decorations in Winit *for now*, and instead get add a way to signal that the user should draw their own. Resolving #725 would then lead to a better cross-platform client-side decoration situation, and I already have an API in mind for that.

**Comment by bnjbvr** [comment]
+1 to this! Note it would also remove the indirect dependency on `rusttype`, which is now unmaintained and depends on even older versions of other crates.
