### ISSUE TITLE
`NewEvents` continuously emitted without new events.

### ISSUE THREAD

**Issue by timothee-haudebourg** [rust-windowing/winit#1894]
Hi,

I've created a Vulkan surface on Linux and I'm getting a weird series of events that is continuously emitted:
```
NewEvents(Poll)
MainEventsCleared
RedrawEventsCleared
NewEvents(Poll)
MainEventsCleared
RedrawEventsCleared
NewEvents(Poll)
MainEventsCleared
RedrawEventsCleared
...
```
If I understand well, `NewEvents` is here to signal that new events are arriving from the OS, and `MainEventsCleared/RedrawEventsCleared` are here to signal that all events have been processed. But there are no other events in between. In particular, as stated in the doc, I was expecting to see a `RedrawRequested` somewhere between `MainEventsCleared` and `RedrawEventsCleared`, but it's not there.

This just seems to me like a bunch of nonsensical events that are emitted continuously, eating an entire core of my CPU. Am I doing something wrong here?

**Comment by maroider** [comment]
You seem to be setting `control_flow` to `ControlFlow::Poll`, which makes this the expected behaviour.
If you'd like to wait until the OS gives you some events to process, use `ControlFlow::Wait` or `ControlFlow::WaitUntil`.
If you'd like some `Event::RedrawRequested` events, you can call `Window::request_redraw`.

**Comment by timothee-haudebourg** [comment]
Oh I see, that's my bad then. And it is even mentioned in the example. Thanks for your time.

**Comment by timothee-haudebourg** [comment]
Well, actually, even now with `ControlFlow::Wait` I'm getting pretty much the same result:
```
NewEvents(WaitCancelled { ... })
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { ... })
MainEventsCleared
RedrawEventsCleared
...
```
The event callback is called without actual events (although this time it is taking much less CPU, but still...). Is that expected?

**Comment by maroider** [comment]
I don't think so, no, but I'm not familiar enough with X11 and/or Wayland to say anything definitively.

**Comment by timothee-haudebourg** [comment]
In this case that would be Wayland.

**Comment by maroider** [comment]
cc @vberger

**Comment by vberger** [comment]
Could you provide the stderr output generated by running your app with the env variable `WAYLAND_DEBUG=1` ?

**Comment by timothee-haudebourg** [comment]
I'm writing some kind of a game using Vulkan, and those events seems to be emitted whenever I present a new image to the window (30 times per second). Here is the debug output of wayland every time a new image is presented:
```
[1061002.133] wl_buffer@60.release()
[1061002.186] wl_callback@63.done(70691815)
[1061002.893]  -> wl_surface@17.attach(wl_buffer@60, 0, 0)
[1061002.978]  -> wl_surface@17.damage(0, 0, 2147483647, 2147483647)
[1061003.024]  -> wl_surface@17.frame(new id wl_callback@63)
[1061003.054]  -> wl_surface@17.commit()
[1061006.958] wl_display@1.delete_id(63)
```

I understand that Wayland will react when Vulkan wants to present an image, but it seems to me that the events emitted by winit are unnecessary.

**Comment by vberger** [comment]
Oh, so are you drawing and submitting frames from a other thread than the one running your winit event loop?

Not sure we can have a way for winit de guess whether it should wake-up the event loop or not after some reaction from the wayland connection. These wakeups are furthermore necessary to make it possible to drive potential secondary event queues used by the user, so trying to remove them would restrict what can be done using winit for little to no gain.

**Comment by timothee-haudebourg** [comment]
I see. I guess I have my answer. As long as it's not taking too much CPU it's not really an issue. Thanks!
