### ISSUE TITLE
Feature to create Metal surface (or documentation of existing feature)

### ISSUE THREAD

**Issue by mcclure** [rust-windowing/winit#1896]
Your list of features in your FEATURES.md doc says

> * Providing pointer to init OpenGL: Winit provides the necessary pointers to initialize a working opengl context
> * Providing pointer to init Vulkan: Same as OpenGL but for Vulkan

However, it does not mention Metal. Moreover, the "Missing features provided by other crates" doc does not mention this as a non-winit feature that can be tacked on by another crate.

I do not need to be able to run Metal in a winit window currently. However, I might need this at some point in the future.

**Expected behavior:** There should be a feature "Providing pointer to init metal", or a link in the "Missing features" doc to a crate that allows doing this to Metal.

**This might already exist:** I find issue #596 which is more or less about this exact feature. It is closed with a PR, which I interpret as "closed as fixed". **However, if this feature exists, it is not in the top level documentation.** If "provide a pointer to init metal" is possible now, this should be explicitly noted in either FEATURES.md or the Missing-features doc.

**Comment by maroider** [comment]
While I've never used Metal and Winit together myself, I'd assume that it works fine given that `gfx-rs`' `metal-rs` crate uses Winit in its examples.

You do admittedly have a bit of a point, in that it's hard to see that something is supported if it's not documented. The same can admittedly be said for D3D, which can also be initialized through Winit's public API.

**Comment by mcclure** [comment]
I think it would be great to do the same thing with DirectX, yeah! I just didn't mention it because I don't know so much about DX.

Putting two links "metal-rs can display in a winit window" and "[whatever d3d/dx library]" can display in a winit window" in the "Missing features provided by other crates" document would I think resolve this completely. It's just that as is, if someone who is new to Rust [me] looks at the Winit landing page, they won't be able to tell offhand whether there are metal/dx libraries that integrate with it cleanly [I couldn't]. Looking up DirectX on docs.rs tonight, I found two separate DirectX rust libraries; I can't tell if one is still maintained, and I can't tell if the other is full-featured or unfinished, and I don't know if either are straightforward to integrate with winit.

**Comment by msiglreith** [comment]
We probably should align it closer with the crate documentation: https://docs.rs/winit/0.24.0/winit/#drawing-on-the-window
and add a section in the wiki regarding `raw-window-handle` which acts as primary interface with the graphics APIs. It provides the native handles which can be directly filled into the corresponding graphics API windows system interfaces (Vulkan Surface, DXGI swapchain and metal surface).
fwiw in regards the Metal I tried to extract some parts of obtaining the `MetalSurface` as `raw-window-handle` leans to both side, window and graphics api, so some transformations may be needed: https://github.com/norse-rs/raw-window-metal

**Comment by madsmtm** [comment]
[The top-level documentation on docs.rs](https://docs.rs/winit/0.30.5/winit/index.html#drawing-on-the-window) now documents `raw-window-handle`, DirectX and Metal as well.

Agree that if you want to integrate well between Winit and Metal, [`raw-window-metal`](https://docs.rs/raw-window-metal/) is a fine starting point.

The `FEATURES.md` file will be removed in https://github.com/rust-windowing/winit/pull/3479, so I'll close this now.
