### ISSUE TITLE
No way to handle keyboard layout change events

### ISSUE THREAD

**Issue by kotauskas** [rust-windowing/winit#1907]
I'm referring to the [`WM_INPUTLANGCHANGE`] WinUser message. Not sure what event would it be with X11/Wayland/macOS. The current workaround is to check [`GetKeyboardLayout`] when handling [`NewEvents`], but that requires platform-specific boilerplate.

This would require a first-class notion of keyboard layouts in Winit, one which would work uniformly across all platforms. Can't help with this since I'm not fluent in the nomenclature for X11, Wayland and macOS.

[`WM_INPUTLANGCHANGE`]: https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-inputlangchange " "
[`GetKeyboardLayout`]: https://docs.microsoft.com/en-au/windows/win32/api/winuser/nf-winuser-getkeyboardlayout " "
[`NewEvents`]: https://docs.rs/winit/0.24.0/winit/event/enum.Event.html#variant.NewEvents " "

**Comment by maroider** [comment]
This is definitely on my radar, and I've brought it up (in some form) in #753, but it is probably not likely to be added particularly soon.

Just out of curiosity: what are you using the keyboard layout for?

**Comment by kotauskas** [comment]
> Just out of curiosity: what are you using the keyboard layout for?

Displaying keybindings with respect to the keyboard layout while defining them in terms of layout-agnostic scancodes. As in, a `Ctrl`+`Z` keybind would fire when the Z key is pressed on QWERTY but for the Y key on QWERTZ, and hints for it would be displayed as that key as it appears physically on the keyboard rather than as the QWERTY key for the scancode which would incorrectly report it as `Ctrl`+`Z` on QWERTZ where it's actually `Ctrl`+`Y`.

**Comment by maroider** [comment]
> Displaying keybindings with respect to the keyboard layout while defining them in terms of layout-agnostic scancodes.

Yeah, that's definitely a planned feature as well.

**Comment by kchibisov** [comment]
I'll move this issue under the #2678.
