### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Joe23232** [rust-windowing/winit#1908]
Hi, I have some questions regarding this project.

1. How low level does it get when using this crate?
2. Is it supported on Windows, Linux x11 and Linux wayland?
3. Is it also supported on Android if I used something like [`cargo-mobile`](https://github.com/BrainiumLLC/cargo-mobile) or [`android-ndk-rs`](https://github.com/rust-windowing/android-ndk-rs)
4. So like I can create GUI menus and stuff inside the window all by using winit without the need of using another graphics crate?
5. So if I need to update a specific part of the window would it or would it refresh the entire window?

**Comment by rkanati** [comment]
Had you considered reading the docs?

**Comment by maroider** [comment]
> 1. How low level does it get when using this crate?

You may have a look at the examples, or at the documentation on docs.rs and figure this one out for yourself; I have no idea what you mean by "low level" here.

> 2. Is it supported on Windows, Linux x11 and Linux wayland?

From (the top of) [FEATURES.md](https://github.com/rust-windowing/winit/blob/master/FEATURES.md):
> # Winit Scope
> 
> Winit aims to expose an interface that abstracts over window creation and input handling, and can
> be used to create both games and applications. It supports the main graphical platforms:
> - Desktop
>   - Windows
>   - macOS
>   - Unix
>     - via X11
>     - via Wayland
> - Mobile
>   - iOS
>   - Android
> - Web
>   - via WASM

> 3. Is it also supported on Android if I used something like [`cargo-mobile`](https://github.com/BrainiumLLC/cargo-mobile) or [`android-ndk-rs`](https://github.com/rust-windowing/android-ndk-rs)

Yes.
`android-ndk-rs` is a `rust-windowing` project, and Winit itself uses `android-ndk-rs`.
The main developer of `cargo-mobile` is (was?) actually one of Winit's maintainers ([francesca64](https://github.com/francesca64)). 

> 4. So like I can create GUI menus and stuff inside the window all by using winit without the need of using another graphics crate?

No.

From [FEATURES.md](https://github.com/rust-windowing/winit/blob/master/FEATURES.md):
> Winit ***does not*** directly expose functionality for drawing inside windows or creating native
> menus, but ***does*** commit to providing APIs that higher-level crates can use to implement that
> functionality.

> 5. So if I need to update a specific part of the window would it or would it [not] refresh the entire window?

As far as I'm aware, it should be possible to re-paint parts of windows created through Winit, although Winit itself exposes no such API.

**Comment by maroider** [comment]
Closing for now, as I believe adequate answers have been provided. Feel free to re-open the issue if you disagree.

**Comment by Joe23232** [comment]
Thanks guys
