### ISSUE TITLE
Window corner resize cursor has the wrong orientation

### ISSUE THREAD

**Issue by EmbersArc** [rust-windowing/winit#1912]
This is an issue that appeared in [egui](https://github.com/emilk/egui/). But we suspect that it might be an issue with winit.

Original report (https://github.com/emilk/egui/issues/332):

**Describe the bug**
When I place the cursor in any corner of a window that can be resized, it points in the wrong direction.

![image](https://user-images.githubusercontent.com/1352472/115754909-fe345400-a39c-11eb-9229-d4b1fc37ff89.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/1352472/115754827-e78dfd00-a39c-11eb-8234-fdbb6710b7e1.png)

**System information**
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.81.0
Qt Version: 5.15.2
Kernel Version: 5.11.14-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11

**Comment by maroider** [comment]
Could you find the exact `CursorIcon` variant causing this issue? I always have a hard time guessing which one is which when it comes to the resizing icons.
[This](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/linux/x11/util/cursor.rs#L96-L110) is where you want to look if you want to try fixing it yourself. I'll see if I can't get a repro on this tomorrow.

**Comment by EmbersArc** [comment]
It seems to be the diagonal ones `NeswResize` and `NwseResize` that are flipped. Apparently this issue does not exist on other platforms, at least not on Mac.

**Comment by maroider** [comment]
I'm not able to reproduce this.
For reference, I'm using Arch Linux with default i3 settings.

**Comment by EmbersArc** [comment]
Might be a KDE-related issue then. I haven't seen the issue in any other application, except imgui-rs, which uses winit as well.

**Comment by maroider** [comment]
It may be worth looking into which strings GTK and QT use to load the affected cursors and cross-referencing that with what Winit is doing.
I'm somewhat busy (for some definition of busy), so you'll probably get a quicker turnaround by digging deeper by yourself.

**Comment by EmbersArc** [comment]
I checked the icons folder `/usr/share/icons` on a fresh install and saw that the cursors in question are stored as `size_bdiag` (oriented like `/`) and `size_fdiag` (oriented like `\`).

winit loades them here:

https://github.com/rust-windowing/winit/blob/0152508a393ccb46764a733f489a25cc23885a0c/src/platform_impl/linux/x11/util/cursor.rs#L107-L108

https://github.com/rust-windowing/winit/blob/0152508a393ccb46764a733f489a25cc23885a0c/src/platform_impl/linux/wayland/seat/pointer/mod.rs#L96-L97

It looks to me like those should be swapped.

**Comment by EmbersArc** [comment]
Can anyone check if this is an issue on wayland as well?

**Comment by akhilman** [comment]
> Can anyone check if this is an issue on wayland as well?

Yes it is.
