### ISSUE TITLE
Add mouse buttons as described in the Linux event codes

### ISSUE THREAD

**Issue by maxheyer** [rust-windowing/winit#1914]
I would add all mouse buttons to the events as described in the Linux [event codes](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h#L358-L362). This would prevent incorrect implementations of these keys.

**Comment by maroider** [comment]
Could you elaborate on what you mean by:
> incorrect implementations of these keys

We've already had a short discussion on expanding the `MouseButton` enum in #1785, but that was specifically for buttons which are exposed on multiple platforms.

I'd also like to know what the following buttons are, as they are entirely foreign to me: `BTN_SIDE`, `BTN_EXTRA`, and `BTN_TASK`. A quick search suggests that android seems to treat `BTN_SIDE` and `BTN_EXTRA` as `BTN_BACK` and `BTN_FORWARD`, respectively.

**Comment by maxheyer** [comment]
I have not found this discussion before, I will join this discussion if needed.
