### ISSUE TITLE
"Testers and Contributors" table maintenance

### ISSUE THREAD

**Issue by maroider** [rust-windowing/winit#1917]
The "[Testers and Contributors](https://github.com/rust-windowing/winit/wiki/Testers-and-Contributors)" wiki page feels like it has gotten a bit stale over time. In particular, @vberger has stepped down as a maintainer for Wayland (#972), and @ryanisaacg has effectively stepped down as a maintainer for WASM (#1777), yet the wiki page does not reflect this. Additionally, @goddessfreya and @kchibisov seem to have dropped off the face of the earth if their commit activity is anything to go by.

I did chat briefly with @vberger about their incorrect listing as a maintainer, and it seems like there's a need for a status beyond maintainer/contributor/tester to indicate that the person in question is only really available to answer questions about the platform in question. To this end, I've added the following to the table legend and pre-emptively changed @vberger and @ryanisaacg's `M`s to `E`s:
> - `E` - Expert: Can answer questions and/or give advice about this platform

The idea of pruning this table was brought up in #1777, and I think that's a good idea.

The following is a list of everyone on the "Testers and Contributors" table.
If you're ok with what you're currently listed as, and able to act in that capacity, please add 👀 as a reaction, and I'll add a checkmark next to your name. I'm not quite sure about what sort of time-limit to put on this, but two weeks feels like an ok amount of leeway. Those who don't respond can then be removed from the table.

- [x] @msiglreith
- [ ] @vbogaevsky
- [x] @ArturKovacs
- [ ] @murarth
- [x] @vberger
- [ ] @kchibisov
- [x] @francesca64
- [x] @ryanisaacg
- [ ] @Osspial
- [x] @maroider
- [ ] @goddessfreya
- [ ] @mitchmindtree
- [ ] @jdm
- [ ] @felixrabe
- [x] @notriddle
- [x] @0xpr03
- [x] @arthrp
- [x] @FliegendeWurst
- [x] @chelmich
- [ ] @sanbox-irl
- [x] @lberrymage
- [x] @kaimast

**Comment by francesca64** [comment]
@maroider thanks a ton for opening this! Would you like to be made a Member? You seem good at seeming responsible, from everything I've seen of you. I've heard you're even watching All Activity, which shows true grit.

At the risk of disappointing @ArturKovacs, I'll assert that I'm not actually able to give macOS reviews. I barely remember anything about that backend, despite there being evidence that I supposedly wrote a lot of it.

It could be good to have a designation/list for people that can be pinged for administrative stuff too, since that's currently tribal knowledge. It'd essentially be the intersection of Owners and active people.

Maybe the page should also note that it can't be assumed everyone listed is necessarily watching the repo? I personally don't, which seems to be fairly common.

**Comment by maroider** [comment]
> Would you like to be made a Member?

I'd like that, yes.
That would enable me to act on my urge to slap tags on untagged issues.

> You seem good at seeming responsible

Ah-ha! My charade is working :P

> I've heard you're even watching All Activity, which shows true grit.

I'm "fortunate" enough to not be deeply involved in other projects, so the volume of notifications isn't too big of a deal.
It also helps that I procrastinate by looking through my notifications, and by looking at issues and PRs.

> It could be good to have a designation/list for people that can be pinged for administrative stuff

So this would be people who can (among other things) add and remove people from the @rust-windowing org?

> Maybe the page should also note that it can't be assumed everyone listed is necessarily watching the repo?

Both this and the previous suggestion sound like good ideas.

**Comment by francesca64** [comment]
> I'd like that, yes.
> That would enable me to act on my urge to slap tags on untagged issues.

Fantastic, sent you an invite!

> So this would be people who can (among other things) add and remove people from the @rust-windowing org?

Correct.

**Comment by maroider** [comment]
Two weeks (and a bit more) have passed, so I guess now is the time to trim the table.

As of writing this, the following people haven't responded to being pinged, and will as such be removed from the table:
- @vbogaevsky (macOS maintainer)
- @murarth (X11 maintainer)
- @kchibisov (Wayland maintainer)
- @Osspial (Windows contributor, formerly maintainer)
- @goddessfreya (X11 contributor)
- @mitchmindtree (Tester)
- @jdm (Tester)
- @felixrabe (Tester)
- @sanbox-irl (Tester)

Feel free to re-add yourselves to the table if you're up to resuming your previous role(s), or some other role(s).

---

I've also gone ahead and added a [page](https://github.com/rust-windowing/winit/wiki/Admins) listing *active* admins on the GitHub Wiki.
