### ISSUE TITLE
v0.25.0 release

### ISSUE THREAD

**Issue by ArturKovacs** [rust-windowing/winit#1926]
The list of changes under "Unreleased" is approximately as long as the list under 0.24.0

It seems reasonable to make a new release at this point.

Is there anyone opposing to this? @francesca64 @maroider @msiglreith @murarth @kchibisov @madsmtm

**Comment by maroider** [comment]
I've been having toughs along the same lines, but I'd like to see #1925 resolved before releasing an new version.

**Comment by fschutt** [comment]
Is there a way to actually HMENU messages in Windows? It doesn't make much sense to me to allow the window to have a HMENU, but not respond to entries. In Windows, this would just require winit to add support for the `WM_COMMAND` message: https://github.com/fschutt/winit/commit/601d052b2bda3a3c69ffde40ef416d8ba750cffb

**Comment by maroider** [comment]
I'd prefer if we had this discussion in a separate issue, @fschutt, as I don't see how this impedes a release.

**Comment by ArturKovacs** [comment]
#1925 (and #1934) also happen with winit 0.24 and I currently don't see a way of fixing those. Therefore I think we should make a release at the current state (i.e. at 41d9826ee9e2a05eca6805aa94655efd98b0451c)

**Comment by maroider** [comment]
> Therefore I think we should make a release at the current state (i.e. at 41d9826)

That seems reasonable, but I feel like we can squeeze in #1930, as it's a pretty simple PR.

**Comment by ArturKovacs** [comment]
Yes, let's include that as well and make the release at 078b9719cc3ba06630291d5bc05c90787bd84c4f

**Comment by ArturKovacs** [comment]
It's released. Yaay 😄
