### ISSUE TITLE
X11 i3 is always creates window in a full screen

### ISSUE THREAD

**Issue by paulefoe** [rust-windowing/winit#1955]
I don't know if that just me, but I just ran a 
`cargo run --example window`
and it's fullscreen for me.

And I would expect it to be (128.0, 128.0) size

```rust
let window = WindowBuilder::new()
        .with_title("A fantastic window!")
        .with_inner_size(winit::dpi::LogicalSize::new(128.0, 128.0))
        .build(&event_loop)
        .unwrap();
```

I'm willing to add some more info and will dig a little bit more into it, but so far I'm reading the  `new` implementation of `UnownedWindow` and it seems pretty hard.

**Comment by chrisduerr** [comment]
Sizes are a suggestion to the WM, it is free to ignore it. A tiling manager should not comply with a request for a specific size, so this is to be expected.

**Comment by paulefoe** [comment]
You're right, but I actually was able to work sizes by setting 

`for_window [title="Event Tester"] floating enable`

inside `i3/config`

I still wonder how the other apps working, i.e. thunderbird can create floating windows without me changing anything in config.

Anyway, thanks for the reply, I'm closing this.

**Comment by maroider** [comment]
> I still wonder how the other apps working, i.e. thunderbird can create floating windows without me changing anything in config.

The WM will usually use some heuristic to determine which windows should be floating. Making a non-resizable window (with `WindowBuilder::with_resizable`) seems to do the trick for me.

**Comment by paulefoe** [comment]
It does indeed work, thank you!

**Comment by paulefoe** [comment]
Actually, I was wrong, it's not working for me.

Do you know what could be the case?

```rust
use simple_logger::SimpleLogger;
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    SimpleLogger::new().init().unwrap();
    let event_loop = EventLoop::new();

    let window = WindowBuilder::new()
        .with_title("Different name")
        .with_inner_size(winit::dpi::LogicalSize::new(128.0, 128.0))
        .with_resizable(true)
        .build(&event_loop)
        .unwrap();

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;
        println!("{:?}", event);

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                window_id,
            } if window_id == window.id() => *control_flow = ControlFlow::Exit,
            Event::MainEventsCleared => {
                window.request_redraw();
            }
            _ => (),
        }
    });
}

```

**Comment by maroider** [comment]
You need to use `.with_resizable(false)` to make it non-resizable. You can make it resizable again after creating the window, and it *should* stay floating.

**Comment by paulefoe** [comment]
Yes, now it works!
 I thought resizable and floating were kind of the same.
