### ISSUE TITLE
Alternatives to throwing error in `run` on wasm?

### ISSUE THREAD

**Issue by grovesNL** [rust-windowing/winit#1956]
Currently we throw an error to break out of `run` on wasm. This causes problems downstream for crates using futures and trying to hide errors in the browser console (e.g. projects running in production that want clean consoles).

For example, there are a couple workarounds in https://github.com/gfx-rs/wgpu-rs/pull/923 and https://github.com/gfx-rs/wgpu-rs/pull/508, but it would be nice to find a solution in winit because it affects all projects using wasm+winit(+futures).

Is there anything else we could do here instead of throwing an exception? If not, could we consider a wasm-only alternative to `run` that changes the return type (possibly consider loosening the return type in general on all platforms)?

I'd be happy to experiment with this if anyone has some ideas we could explore here.

**Comment by Frizi** [comment]
There is already an issue https://github.com/rust-windowing/winit/issues/1714 with the same concerns and even a proposed API, and nothing has been done about it for a year.

**Comment by grovesNL** [comment]
Thanks for the link! I'll close this in favor of #1714
