### ISSUE TITLE
Hang and event loop's event handling closure not getting dropped after `ControlFlow::Exit`

### ISSUE THREAD

**Issue by JackRedstonia** [rust-windowing/winit#1958]
I think I am encountering an issue with my game engine on Windows, using winit from glutin. `*flow = ControlFlow::Exit` causes the entire application to hang after `LoopDestroyed` emits and the closure passed to `event_loop.run(...)` is NOT dropped. It just hangs and the window never closes unless I Ctrl+C in the terminal or let Windows kill the unresponsive window.

I tested the same code on Linux, no issues, game runs and closes as expected, the closure gets dropped.

Relevant source code https://github.com/JackRedstonia/stacks/blob/9244022274c90a569edad382de3a8751663078eb/src/game/runner.rs#L209-L261

Commenting away the code in `Event::WindowEvent {...} =>` and `Event::RedrawRequested(_) =>` seems to make it close properly, but then of course the application does nothing.

**Comment by msiglreith** [comment]
Hi, I believe that's mostly an interaction with/caused by skia: https://github.com/rust-skia/rust-skia/issues/476

**Comment by JackRedstonia** [comment]
Thanks for your quick response, I'll check this when I can and close this issue when it's resolved.

**Comment by JackRedstonia** [comment]
closing, solved, let's track this on the rust-skia repo's issue
