### ISSUE TITLE
Taking the pulse on the IRC situation

### ISSUE THREAD

**Issue by maroider** [rust-windowing/winit#1966]
There was a suggestion on Matrix last Wednesday that we may want to move off of freenode given the current "situation".
Today, I checked if the `Matrix <-> IRC` bridge still worked after "the purge" that happened, and it doesn't seem to be working.
I have no idea if we *can* get it working again in a timely manner since @goddessfreya is the only admin in the Matrix room, and I don't really understand how the bridge was set up and run in the first place, so any move to libera.chat or some other IRC network might still be hampered by a lack of a bridge.

In the end, I think the opinion of those that actually use IRC should matter the most here (and I don't), so ...

cc @kchibisov @chrisduerr

**Comment by chrisduerr** [comment]
@vberger switched the bridge of smithay to libera without any issues afaik, so if the problem's about *how* to do it he can certainly chime in. But obviously there's nothing that can be done at all unless someone has access to the channel.

**Comment by vberger** [comment]
Indeed, @goddessfreya is the only admin of the channel. Apart from that moving to an other network would be pretty painless I think.

Given the appservice is still in the room, it'd require messaging suppot@matrix.org so that they remove it, and then the room can be bridged to somewhere new by @goddessfreya.

**Comment by maroider** [comment]
Quick update: the bridge appears to be working again. I don't know why it stopped working, and I don't know why it started working again.

**Comment by maroider** [comment]
As noted by @Ralith on Matrix: @goddessfreya is not responsive, and we may need to move to a new matrix room because of this. To that end, I've created `#rust-windowing:matrix.org` with `#winit:matrix.org` as an alias, although the room is set to "invite-only" for now. If we do decide to move, then we should make sure that there is more than one active administrator at any given time in order to avoid situations like this.

**Comment by kchibisov** [comment]
I'm not present on matrix, so bridging to libera is something I'd need for myself. I'm pretty active on irc in general, though not available right now.

**Comment by maroider** [comment]
I have managed to bridge [`#winit:matrix.org`](https://matrix.to/#/#winit:matrix.org) to `#winit` on libera. [`#rust-windowing:matrix.org`](https://matrix.to/#/#rust-windowing:matrix.org) is now a "matrix space" with both #winit and the (presumably to-be migrated from) #Glutin channel in it.

**Comment by chrisduerr** [comment]
@maroider Want to update the readme of winit/glutin with the new IRC channels? Then this issue can be closed I think.

**Comment by maroider** [comment]
> Want to update the readme of winit/glutin with the new IRC channels?

Will do.

**Comment by madsmtm** [comment]
The contact links have been updated, so I'll close this, thanks for your work in setting it up @maroider
