### ISSUE TITLE
Memory leak in EventLoop

### ISSUE THREAD

**Issue by GloopShlugger** [rust-windowing/winit#1984]
On version 0.25.0 and the current git version when taking the example from the documentation summarized below, the application continues to climb in memory usage. That does not happen in version 0.24.0

Compiled in release for target x86_64_unknown_linux_gnu on X11

```rust
use winit::{event::*, event_loop::*, window::WindowBuilder};

fn main() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Poll;

        match event {
            Event::WindowEvent { event: WindowEvent::CloseRequested, window_id } if window_id == window.id() => {
                *control_flow = ControlFlow::Exit
            }
            Event::MainEventsCleared => {
                window.request_redraw();
            }
            Event::RedrawRequested(_) => {}
            _ => (),
        }
    });
}
```

**Comment by Davester47** [comment]
I can confirm the existence of this bug. Using `git bisect`, the leak seems to have been introduced in commit 889258f538010d4fa222e5e897fc0affd389dccf when mio was updated to 0.7.
