### ISSUE TITLE
Version 0.25 nor latest master allowing Surface to be acquired in android.

### ISSUE THREAD

**Issue by nmpribeiro** [rust-windowing/winit#1986]
Even though `winit` works fine in android, I cannot ever grab a valid surface. Try latest master with wgpu triangle example in android and it will crash on surface creation. If you downgrade to `v0.24` it works fine.

Following this thread from [wgpu](https://github.com/gfx-rs/wgpu/issues/1757), I have tried to fix the surface not found on startup by adapting my logic to use `Resume`/`Suspended` events. However, only with `winit` `v0.24` that works. If I move to `v0.25` or latest master the behaviour is changed, not triggering the `Resume` event nor the ability to grab the surface on app startup (hence never grabbing it).

This is what happens with `winit` from my forked repo and ios fix, forked from tag v0.23 with just a small ios fix already in PR in `winit` repo:
```
winit = { git="https://github.com/nmpribeiro/winit.git", branch="working_android_winit"}
```
output:
```
I/rust-app: rust_jsx_ui:     --- EVENT LOOP ---
D/ActivityThread: add activity client record, r= ActivityRecord{36f0754 token=android.os.BinderProxy@66c03de {io.github.nmpribeiro.rust_jsx_ui/android.app.NativeActivity}} token= android.os.BinderProxy@66c03de
D/HiTouch_PressGestureDetector: onAttached, package=io.github.nmpribeiro.rust_jsx_ui, windowType=1, mHiTouchRestricted=false
I/rust-app: rust_jsx_ui: App resumed
    rust_jsx_ui: ----------------------------------------- Activating!
    rust_jsx_ui: Activating now!
    rust_jsx_ui: Size: 1080 x 2312
    rust_jsx_ui: Instance
```

This is with `winit` `v0.24`:
```
I/rust-app: rust_jsx_ui:     --- EVENT LOOP ---
D/ActivityThread: add activity client record, r= ActivityRecord{36f0754 token=android.os.BinderProxy@66c03de {io.github.nmpribeiro.rust_jsx_ui/android.app.NativeActivity}} token= android.os.BinderProxy@66c03de
D/HiTouch_PressGestureDetector: onAttached, package=io.github.nmpribeiro.rust_jsx_ui, windowType=1, mHiTouchRestricted=false
I/HwViewRootImpl: removeInvalidNode jank list is null
D/AwareBitmapCacher: handleInit switch not opened pid=22664
```

While in my android simulator it doesn't work, it is expected that support for OpenGL for android is still lagging behind.

**Comment by nmpribeiro** [comment]
I was able to figure out some `winit` vs `ndk_glue` version combinations. It seems to make sense:

# Android compatability
### winit versions test with ndk_glue 0.2.1
# winit 0.24 + ndk_glue 0.2.1 -> works
# winit 0.25 + ndk_glue 0.2.1 -> fails

### winit versions test with ndk_glue 0.3.0
# winit 0.24 + ndk_glue 0.3.0 -> fails
# winit 0.25 + ndk_glue 0.3.0 -> works

### winit versions test with ndk_glue 0.4.0
# winit 0.25 + ndk_glue 0.4.0 -> fails
# winit master + ndk_glue 0.4.0 -> fails

That would suggest latest working pair combination is `winit` v0.25 with `ndk_glue` v0.3.0.

**Comment by msiglreith** [comment]
Hi, right the `ndk_glue` version needs to match the version used by `winit`. Otherwise, the application will probably not even start correctly as they internal NativeActivity `static` is not the same due to version mismatch.

**Comment by nmpribeiro** [comment]
Hi @msiglreith I guess then `ndk_glue` usually releases first, then `winit` will follow and efforts are/will be made to keep up with `ndk_glue::0.4.0` right?
That is super cool to know, but a bit annoying that this is not mentioned anywhere in the winit documentation. And we only see the error happening when we use something like `wgpu`. Kinda hard to figure this out.

Is there place to add such a versioning table anywhere?

**Comment by msiglreith** [comment]
> Is there place to add such a versioning table anywhere?

I agree, it's not immediately clear. README in the [Android](https://github.com/rust-windowing/winit#android) section seems best to me.

> ndk_glue usually releases first, then winit will follow and efforts are/will be made to keep up with ndk_glue::0.4.0 right?

yep, next releases would support 0.4 then

**Comment by nmpribeiro** [comment]
Hi, I've issued a [PR](https://github.com/rust-windowing/winit/pull/1993) to have some documentation relevant to this. Let me know if you guys are ok with it!

**Comment by MarijnS95** [comment]
@nmpribeiro It looks like this is solved now, can we close this?

**Comment by nmpribeiro** [comment]
Sure. Closed!
