### ISSUE TITLE
Coordinate Android NDK update with winit 0.27

### ISSUE THREAD

**Issue by msiglreith** [rust-windowing/winit#1995]
https://github.com/rust-windowing/winit/issues?q=is%3Aopen+label%3A%22platform%3A+Android%22+milestone%3A%22Version+0.27%22+

- [ ] https://github.com/rust-windowing/android-ndk-rs/pull/314 Coordinate with the release of `ndk 0.7.0` (breaking changes: https://github.com/rust-windowing/android-ndk-rs/blob/master/ndk/CHANGELOG.md) prior to releasing `winit` (seems like a nice cut-off point);
- [ ] Alongside the update, re-exporting ndk-glue would be helpful under the light of https://github.com/rust-windowing/winit/pull/1993
  - [ ] Consider extending `ndk_context` instead and automagically support a wider range of `ndk-glue` versions?
  - [ ] Alternatively there have been suggestions [TODO: reference needed] of reworking how `ndk-glue` passes its structs to the user and removing `static` globals plus their accessor functions;
- [x] Use `NativeWindow`'s `RawWindowHandle` implementation directly: https://github.com/rust-windowing/android-ndk-rs/pull/274
- [x] https://github.com/rust-windowing/winit/pull/2307
- [x] https://github.com/rust-windowing/android-ndk-rs/pull/282
- [x] https://github.com/rust-windowing/android-ndk-rs/pull/285
- [x] https://github.com/rust-windowing/android-ndk-rs/pull/286
- [x] https://github.com/rust-windowing/android-ndk-rs/pull/287
- [x] https://github.com/rust-windowing/android-ndk-rs/pull/288
- [x] Fix `winit` CI failures on Android: https://github.com/rust-windowing/android-ndk-rs/pull/289
- [x] https://github.com/rust-windowing/android-ndk-rs/pull/290
- [x] https://github.com/rust-windowing/android-ndk-rs/pull/291
- [x] https://github.com/rust-windowing/android-ndk-rs/pull/292
- [x] https://github.com/rust-windowing/android-ndk-rs/pull/293
- [x] https://github.com/rust-windowing/android-ndk-rs/pull/294
- [x] https://github.com/rust-windowing/android-ndk-rs/pull/295
- [x] https://github.com/rust-windowing/android-ndk-rs/pull/296
- [ ] https://github.com/rust-windowing/android-ndk-rs/pull/320

**Comment by msiglreith** [comment]
Some thoughts on the second point regarding re-exporting: https://github.com/rust-windowing/winit/pull/2047#issuecomment-957930111

**Comment by MarijnS95** [comment]
@msiglreith Is this issue now used as tracking for Winit 0.27? If so, I think we should add the following entries:

- [ ] Coordinate with the release of `ndk 0.7.0` (breaking changes: https://github.com/rust-windowing/android-ndk-rs/blob/master/ndk/CHANGELOG.md) prior to releasing `winit` (seems like a nice cut-off point);
- [ ] Use `NativeWindow`'s `RawWindowHandle` implementation directly: https://github.com/rust-windowing/android-ndk-rs/pull/274

**Comment by MarijnS95** [comment]
@msiglreith Given your thumbs-up I've moved the entries into your top-post so that they get counted towards the number of tasks, and renamed the title to state that we'd like to sync up with 0.27.

I have a few other breaking changes in mind that require coordination between winit and the `ndk`, so it'd be great if we can bump ndk->winit->glutin in that order when the time comes to it. So a request to the `winit` maintainers to ping me (in this issue) whenever plans are commencing to set out 0.27 :)
