### ISSUE TITLE
[Wayland] touch_points never removed

### ISSUE THREAD

**Issue by bytbox** [rust-windowing/winit#1996]
In `platform_impl/linux/wayland/seat/touch/handlers.rs`, elements of `touch_points` are not removed even when a touch event ends. I think in principle this is a memory leak, but it also means that if a touch is started and ended without any movement in between, the `location` associated to the `Touch` with `TouchPhase::Ended`, is the wrong location!

I think (but have not tested) that this is repaired simply by removing any element with matching `id` after a `TouchEvent::Up`.

**Comment by tronical** [comment]
I've observed the very same bug, with the consequence of the `TouchPhase::Ended` reporting the wrong location.
