### ISSUE TITLE
Winit is having issues with Wayland(Gnome)

### ISSUE THREAD

**Issue by Sakura0134** [rust-windowing/winit#2000]
I recently tried out winit (As a replacement for glfw) and I am noticing issues with it especially in Wayland(Gnome). Besides the issues mentioned about window decoration, it is also having issues

1. Showing improper cursor(Cursor not following window scheme).
2. It won't draw a window unless I give it a backend like wgpu.
3. The name of the window is written as "unknown" in task manager. 

And I can confirm these issues are not present in x11. (The program I am trying is an example implementation of wgpu). (TBN, I am new to winit scene and I don't know whether these behaviours can be changed.)

1.
![Screenshot from 2021-08-17 11-38-48](https://user-images.githubusercontent.com/85794603/129655883-63f244bd-fe73-410b-9017-3d6ec9030e49.png)
![Screenshot from 2021-08-17 11-39-25](https://user-images.githubusercontent.com/85794603/129655933-da059a8b-3b13-4029-8613-cced15401b0a.png)

Notice the cursor here. It is using the same cursor from the editor layout in geany ide.
![Screenshot from 2021-08-17 11-43-04](https://user-images.githubusercontent.com/85794603/129655981-d649f5f5-e223-4963-9be7-d070ce815306.png)

2.
No window is created beside a zombie  program named "unknown" running as depicted by the tools icon
![Screenshot from 2021-08-17 11-57-32](https://user-images.githubusercontent.com/85794603/129656784-e9c735f7-9541-4df5-85f2-18d22f870691.png)

3.
Look at the taskbar, the name of my window is written as "unknown"
![Screenshot from 2021-08-17 11-44-01](https://user-images.githubusercontent.com/85794603/129656113-0bf2b57a-ec2a-44e9-8fd0-be6967a54505.png)

No such issues with x11
![Screenshot from 2021-08-17 11-43-27](https://user-images.githubusercontent.com/85794603/129656156-a7d63046-d551-4467-a3bd-155ef671a7a6.png)

Link to the example I am trying: https://github.com/sotrh/learn-wgpu

**Comment by Sakura0134** [comment]
Also, I am noticing 100% CPU usage when creating a window in x11(Without any backends)
![Screenshot from 2021-08-17 12-47-05](https://user-images.githubusercontent.com/85794603/129660540-c83fd627-04e7-4ea0-ba4f-5a1351024d2f.png)

**Comment by kchibisov** [comment]
>The name of the window is written as "unknown" in task manager.

You should set `app_id` to solve that.

>It won't draw a window unless I give it a backend like wgpu.

The Wayland window isn't visible unless you draw something into it.

>Showing improper cursor(Cursor not following window scheme).

Try setting `XCURSOR_THEME` before running your app?

**Comment by Sakura0134** [comment]
> > The name of the window is written as "unknown" in task manager.
> 
> You should set `app_id` to solve that.
> 
> > It won't draw a window unless I give it a backend like wgpu.
> 
> The Wayland window isn't visible unless you draw something into it.
> 
> > Showing improper cursor(Cursor not following window scheme).
> 
> Try setting `XCURSOR_THEME` before running your app?

Thanks. Your suggestions worked like charm. Before closing this, is there a way to make the cursor follow the system theme rather than giving an environment variable(Like the way x11 does it in winit) and also, do you know why x11 window consumes 100% of a single core in my CPU(Wayland with environment variable)? (Sorry for the trouble since this is my first day trying anything besides glfw and x11)

**Comment by kchibisov** [comment]
>fore closing this, is there a way to make the cursor follow the system theme rather than giving an environment variable(Like the way x11 does it in winit)?

No there's no protocol for that on wayland unfortunatelly, the most known and wide spread way for now is that environment variable. GNOME is using dbus for that, but that's not an option for us, and for a lot of other simple clients and toolkits.

>Also, I wish to know about the status of Window decoration(using native ones) in Wayland and window following system theme(dark and light)(like x11).

There's a protocol for providing server side decorations which is supported in winit(xdg_decoration_unstable_v1`). As for client side decorations(that's what you get on GNOME, since it doesn't support server side decorations for Wayland and they refuse to do so) they are visually poor compared to things like gtk, but winit doesn't position itself as an alternative to libraries like gtk, it's a cross platform rust library to create a window. Ofc we want to find a way to deliver better interfaces for the end users, when it comes to decorations, but for now situation isn't clear, and I'm not sure that anything will be changed in that regard until wayland-rs 0.30 release.

**Comment by Sakura0134** [comment]
> > fore closing this, is there a way to make the cursor follow the system theme rather than giving an environment variable(Like the way x11 does it in winit)?
> 
> No there's no protocol for that on wayland unfortunatelly, the most known and wide spread way for now is that environment variable. GNOME is using dbus for that, but that's not an option for us, and for a lot of other simple clients and toolkits.
> 
> > Also, I wish to know about the status of Window decoration(using native ones) in Wayland and window following system theme(dark and light)(like x11).
> 
> There's a protocol for providing server side decorations which is supported in winit(xdg_decoration_unstable_v1`). As for client side decorations(that's what you get on GNOME, since it doesn't support server side decorations for Wayland and they refuse to do so) they are visually poor compared to things like gtk, but winit doesn't position itself as an alternative to libraries like gtk, it's a cross platform rust library to create a window. Ofc we want to find a way to deliver better interfaces for the end users, when it comes to decorations, but for now situation isn't clear, and I'm not sure that anything will be changed in that regard until wayland-rs 0.30 release.

Thanks. Have a Great Day :smile:
