### ISSUE TITLE
Incorrect virtual_keycode for numpad key presses on macOS

### ISSUE THREAD

**Issue by wtfleming** [rust-windowing/winit#2002]
I'm using winit 0.25.0 and macOS 11.5.2

When I run `cargo run --example window | grep KeyboardInput`

And I press the 8 key I get this output:

    WindowEvent { window_id: WindowId(Id(140618894547696)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Key8), modifiers: (empty) }, is_synthetic: false } }

I press the numpad 8 key:

    WindowEvent { window_id: WindowId(Id(140618894547696)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 91, state: Released, virtual_keycode: Some(Key8), modifiers: (empty) }, is_synthetic: false } }

I press the NumpadEnter key:

    WindowEvent { window_id: WindowId(Id(140618894547696)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 76, state: Released, virtual_keycode: Some(NumpadEnter), modifiers: (empty) }, is_synthetic: false } }

The scancodes look correct, but the virtual_keycode for numpad8 is coming back as `Some(Key8)`, when I would expect it to be `Some(Numpad8)`

I was seeing this issue trying to get the numpad input working in bracket-lib here https://github.com/amethyst/bracket-lib/issues/222
And it looks like someone using Bevy is seeing something similar https://github.com/bevyengine/bevy/issues/1666

**Comment by maroider** [comment]
Thanks for taking the time to report your issue  We're aware of this problem, and a fix exists in #1890.
