### ISSUE TITLE
Make keyboard input events continuous

### ISSUE THREAD

**Issue by IntellectualKoala** [rust-windowing/winit#2004]
I am currently trying to write a game with Vulkano/Winit and have realized that the Winit keyboard input events don't fire continuously which leaves me with very glitchy player movement. I tried making a hashmap of VirtualKeyCodes/ElementStates thinking maybe I can just update that hashmap upon a KeyboardInput event and check the individual keys elsewhere in the event loop, but I am not sure if the event loop runs continuously itself or if it just fires whenever any general event occurs, which could lead to weird behavior with the player movement once again. Is there something else I should be trying or am I simply limited by the API currently? Thank you.

**Comment by maroider** [comment]
> I am currently trying to write a game with Vulkano/Winit and have realized that the Winit keyboard input events don't fire continuously which leaves me with very glitchy player movement.

How exactly is it glitchy? The keyboard events only fire when a key has been pressed, released, or when the OS gives us key repeat events.

> I tried making a hashmap of VirtualKeyCodes/ElementStates thinking maybe I can just update that hashmap upon a KeyboardInput event and check the individual keys elsewhere in the event loop

This is sort of what I'd recommend, but I'd rather just do a `HashSet<VirtualKeyCode>` where the presence of a `VirtualKeyCode` in the `HashSet` indicates that the button is down.

> but I am not sure if the event loop runs continuously itself or if it just fires whenever any general event occurs

It depends on what `ControlFlow` you specify. `ControlFlow::Poll` makes the loop run continuously.

**Comment by catcon0** [comment]
> How exactly is it glitchy? The keyboard events only fire when a key has been pressed, released, or when the OS gives us key repeat events.

Perhaps glitchy wasn't the best term.. What I meant to say is that the player movement was very rigid and stop-and-go

> It depends on what ControlFlow you specify. ControlFlow::Poll makes the loop run continuously.

Ah okay, thank you. I will definitely use that!

**Comment by dhardy** [comment]
@catconn You need to track [Pressed and Released](https://docs.rs/winit/0.25.0/winit/event/enum.ElementState.html) status manually. Key events don't fire continuously while held, they fire whenever text input would be expected (when pressed, delay, then at some repeat rate).
