### ISSUE TITLE
Can not input the Chinese character on wasm32 platform

### ISSUE THREAD

**Issue by startewho** [rust-windowing/winit#2012]
When i used the sixty-fps crate.and i use the wasm32 demo.and i found i can not insert the Chinese character by the Ime.and it only input the key what i type. In the ime mode.when i type zhongguo.it can not insert the 中国.and only the pinyin input.
And i found the code 
https://github.com/rust-windowing/winit/blob/9e723967090ae9cd2ac90f5950523c20cf98592c/src/platform_impl/web/web_sys/canvas.rs#L181
it used seems use the keypress event .it only can capture the keyboard input like zhonguo in English.

**Comment by maroider** [comment]
This should hopefully not be a problem with #1888, which will eventually make its way onto `master`.
#1888 does not use `on_received_character`, but rather `on_composition_end`.
Feel free to verify that it does the right thing with [my test program](https://github.com/maroider/winit_keyboard_tester).

**Comment by startewho** [comment]
use the `on_composition_end` should be ok and i test on mdn 
[mdn](
https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event)
![image](https://user-images.githubusercontent.com/898009/130765403-b9f0fc32-3122-42b1-b665-45eaad620648.png)

**Comment by daxpedda** [comment]
This is tracked by https://github.com/rust-windowing/winit/issues/1497.
