### ISSUE TITLE
`Failed to unfocus input context: XError` on X11

### ISSUE THREAD

**Issue by Lucky4Luuk** [rust-windowing/winit#2018]
Console gets spammed with
```
 ERROR winit::platform_impl::platform              > X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 151,
    minor_code: 5,
}
```

After clicking the window that pops up (which visually is a duplicate of the terminal I ran `cargo run --release` from, strangely), it crashes with
```
thread 'main' panicked at 'Failed to unfocus input context: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 151, minor_code: 5 }', /home/spaceman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/x11/event_processor.rs:945:30
```

I'll provide a minimal code example that triggers this if needed, but my usage of winit is very basic. I use run_return identical to the example provided for it, I'm running pop!_os with the awesomewm, and the window has OpenGL support. Hope thats enough information :)

**Comment by Lucky4Luuk** [comment]
It gets weirder. The basic example of run_return does appear to function, however the window is a visual clone of my code editor. Not sure what is going on. Here's how I use run_return:
```
event_loop.run_return(|event, _, control_flow| {
    *control_flow = ControlFlow::Wait;
    match event {
        Event::WindowEvent { event, window_id } => {
            match event {
                WindowEvent::CloseRequested => {
                    //Some basic code here to trigger an application exit
                },
                _ => {},
            }
        },
        Event::MainEventsCleared => {
            *control_flow = ControlFlow::Exit;
        }
        _ => {},
    }
});
```

As you can see, there really is not much of a difference with the example. The only difference I can think of is that my event loop is hidden behind a mutex, and that there is an EventLoopProxy which does not get used in the example. My code also works perfectly on Windows.

**Comment by Lucky4Luuk** [comment]
I think the issue might not be with winit, it might be with the way I create an opengl context from the raw window handle. Closing this, sorry for the trouble :)

**Comment by holdengreen** [comment]
I am still having this is exact same issue trying to run the [Veloren / airshipper](https://gitlab.com/veloren/airshipper).
