### ISSUE TITLE
Request_redraw() call from a task spawned by async_std::task::spawn_local doesn’t produce RedrawRequested event.

### ISSUE THREAD

**Issue by VincentJousse** [rust-windowing/winit#2019]
Request_redraw() call from a task spawned by async_std::task::spawn_local doesn’t produce RedrawRequested event.
Need to wait for another event like a mouse event to receive the RedrawRequested event.

**Comment by maroider** [comment]
What platform does this happen on?

**Comment by VincentJousse** [comment]
Sorry about this, I forgot this information !
It happens on the web.
See my previous bug which covered macOS and web : #1763

**Comment by daxpedda** [comment]
I just hit that and started investigating it, the problem is very simple: `request_redraw()` doesn't wake up the event loop, it just queues the request but does nothing else.

A simple workaround is just to send a custom event, which actually does the whole waking up process.
Working on a PR!
