### ISSUE TITLE
Support updating resize increments

### ISSUE THREAD

**Issue by necauqua** [rust-windowing/winit#2020]
As an answer to #135, `WindowBuilderExt::with_resize_increments` was added and implemented where WM supports it (X11/MacOS).

However this is limited, since it only allows you to set those increments at window creation and you cannot change them later.

The example from the first issue still holds, to add resize increments to Alacritty (that still was not done so far, and which I've tried to do myself) you need to set the increments for existing window dynamically - so when the glyph size changes (because user changed the font in the config and it was reloaded) the resize increments can be fixed as well.

As far as I understood both on X11 and on MacOS nothing prevents you from setting the increments for the existing window (and continuing with the example, other terminal emulators are doing just that) any number of times.

**Comment by maroider** [comment]
Feel free to send a PR our way if you're up to implementing this change.

From the documentation pages linked in #135, it does indeed seem entirely reasonable to dynamically alter the resize increments.
