### ISSUE TITLE
Expose occlusion state via NSWindowOccludedState

### ISSUE THREAD

**Issue by xacrimon** [rust-windowing/winit#2022]
On newer MacOS versions and Apple Silicon machines, Metal only runs resource cleanup *when* `NSWindowOccludedState` is set to false. Winit needs to expose this so the user can stop rendering when the window is fully occluded to prevent resource exhaustion.

**Comment by maroider** [comment]
> Metal only runs resource cleanup `NSWindowOccludedState` is set to false

I can only assume you're missing an "if" between "cleanup" and "`NSWindowOccludedState`", and that you're referring to the instance property documented on [this page](https://developer.apple.com/documentation/appkit/nswindow/1419321-occlusionstate). However, that looks like a read-only property, so I don't see how we can even *set* it to `false`.

**Comment by xacrimon** [comment]
@maroider Yeah I made a typo. We shouldn't set it but merely expose it somehow. It should return this on Mac and `true` on other platforms. This allows a user to stop rendering when the window is occluded so they don't exhaust the Metal resources.

**Comment by maroider** [comment]
I guess something like `Window::is_visible()` might work, although this *could* conceivably also be a mac-specific extension (ie. a method on `WindowExtMacOS`).

**Comment by xacrimon** [comment]
Yeah, that call is up to you guys but my take is that `Window::is_visible` is the better alternative due to end user simplicity.

**Comment by xacrimon** [comment]
I can submit a patch to implement whatever you guys decide on.

**Comment by kchibisov** [comment]
We have `Occluded` event for that.
