### ISSUE TITLE
Most Device events do not work on the web.

### ISSUE THREAD

**Issue by FrankenApps** [rust-windowing/winit#2036]
I found that the [`DeviceEvent`s](https://docs.rs/winit/0.25.0/winit/event/enum.DeviceEvent.html) `Button`, `Key` and `MouseWheel` do not work in the browser. The only one that fires (as long as the mouse pointer is above the canvas) is `MouseMotion`.

I am not sure, if this is of any importance, but note that I create the `window` with:
```rust
let window = WindowBuilder::new()
        .with_title("Mouse Wheel events")
        .with_canvas(Some(canvas))
        .build(&event_loop)
        .unwrap();
```

I have a little repro of this over [here](https://github.com/FrankenApps/winit-wasm-events-repro). 

Just check the browser console and compare it with the console output when running on native.

**Comment by kaimast** [comment]
I seem to have the issue even on the desktop when the project references some wasm specific crates (I compile to both native binary and webassembly).

I get mouse move movements and redraws just fine, but no mouse input or close requested.

**Comment by rivertam** [comment]
Interestingly, bevy's winit integration has the exact opposite problem: wheel events, button presses, and keyboard events _do_ work, but mouse motions don't work. Checking the differences ([bevy's winit integration for reference](https://github.com/bevyengine/bevy/blob/main/crates/bevy_winit/src/lib.rs#L342)), I was able to put in a [PR to fix your example](https://github.com/FrankenApps/winit-wasm-events-repro/pull/1) and hopefully this will also allow me to make a fix to bevy as well. My proposed fix is simply matching on `WindowEvent`, not `DeviceEvent`.

P.S. While I don't understand the full scope of winit, I recognize that technically speaking, winit should probably be firing both events. Nonetheless, I think as far as practicality goes, this likely solves the problem you're encountering.

**Comment by FrankenApps** [comment]
I merged @rivertam s PR, so now the Issue can not be reproduced anymore on the master branch in the linked repo.
But because I also think, that `WindowEvent` and `DeviceEvent` should probably do the same thing (at least not mouse click beeing in `WindowEvent` and mouse move beeing in `DeviceEvent`) I left a branch showing the original issue [here](https://github.com/FrankenApps/winit-wasm-events-repro/tree/device-events).
