### ISSUE TITLE
Infected file detected

### ISSUE THREAD

**Issue by felipetesc** [rust-windowing/winit#2052]
When developing an application my antivirus (Bitdefender)  keeps telling me that the file at  "ProjectName"\target\debug\build\winit-d2c42852c8351dbb\build_script_build-d2c42852c8351dbb.exe is infected. 
When I build winit I receive the message: 
winit\target\debug\build\winit-4c21f94903e45a43\build_script_build-4c21f94903e45a43.exe is infected with Gen:Variant.Bulz.868649. Bitdefender blocked this item, your device is safe.
Command to reproduce : cargo build
OS: Windows 11
Arc x86_x64

Contents from terminal: 
```bash
PS L:\Repositories\winit> cargo build
    Updating crates.io index
   Compiling winapi v0.3.9
   Compiling cfg-if v1.0.0
   Compiling parking_lot_core v0.8.5
   Compiling libc v0.2.106
   Compiling scopeguard v1.1.0
   Compiling log v0.4.14
   Compiling smallvec v1.7.0
   Compiling winit v0.25.0 (L:\Repositories\winit)
   Compiling lazy_static v1.4.0
   Compiling bitflags v1.3.2
   Compiling instant v0.1.12
   Compiling lock_api v0.4.5
error: failed to run custom build command for `winit v0.25.0 (L:\Repositories\winit)`

Caused by:
  could not execute process `L:\Repositories\winit\target\debug\build\winit-4c21f94903e45a43\build-script-build` (never executed)

Caused by:
  Access is denied. (os error 5)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

From where the file build_script_build-4c21f94903e45a43.exe  is downloaded ?
Thanks!

**Comment by maroider** [comment]
The file in question is generated by `cargo build` from `winit`'s `build.rs` when you build `winit`, so this sounds like a false positive to me.

**Comment by felipetesc** [comment]
> The file in question is generated by `cargo build` from `winit`'s `build.rs` when you build `winit`, so this sounds like a false positive to me.

The code inside build.rs is this : 
```rust
fn main() {
    // If building for macos and WINIT_LINK_COLORSYNC is set to true
    // use CGDisplayCreateUUIDFromDisplayID from ColorSync instead of CoreGraphics
    if std::env::var("CARGO_CFG_TARGET_OS").map_or(false, |os| os == "macos")
        && std::env::var("WINIT_LINK_COLORSYNC")
            .map_or(false, |v| v == "1" || v.eq_ignore_ascii_case("true"))
    {
        println!("cargo:rustc-cfg=use_colorsync_cgdisplaycreateuuidfromdisplayid");
    }
}
```
When I comment it  no warnings are shown, that means my antivirus finds nothing. The question is why Windows is being  affected, since the code above, accordingly the comments  should work only change something in the case Mac is the target ? It is strange.

**Comment by maroider** [comment]
It only uses the standard library and prints to standard output after reading environment variables. I can't do much more than tell you that this is probably a false positive. You should take it up with your antivirus vendor and/or upload the file to VirusTotal if it's all that bothersome.
