### ISSUE TITLE
hello-triangle panics on fullscreen mode (Vulkan)

### ISSUE THREAD

**Issue by timokoesters** [rust-windowing/winit#2054]
If I add this line to wgpu/examples/hello-triangle/main.rs:
```
     let window = winit::window::Window::new(&event_loop).unwrap();
+    window.set_fullscreen(Some(winit::window::Fullscreen::Borderless(None)));
     #[cfg(not(target_arch = "wasm32"))]
```
I get this error:
```
thread 'main' panicked at 'Error in Surface::configure: parent device is lost', wgpu/src/backend/direct.rs:204:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This also happens in the exclusive fullscreen mode.

cc @kvark

**Comment by maroider** [comment]
Is there a reason you're filing this here first and not with wgpu?

**Comment by timokoesters** [comment]
I am on Linux and use the Vulkan backend. But I think you are right and this should be moved over to wgpu.

**Comment by timokoesters** [comment]
Moved to https://github.com/gfx-rs/wgpu/issues/2155
