### ISSUE TITLE
Make `event::VirtualKeyCode::LWin` and `RWin` names more generic.

### ISSUE THREAD

**Issue by alterae** [rust-windowing/winit#2055]
Currently, these enum variants are named `LWin` and `Rwin`, respectively.  However, on MacOS, these key codes map to the *Command* key.  Considering this, and the fact that referring to it as the Windows key is somewhat platform-specific, it might be worth renaming these variants to something more generic (IE: `LSuper` and `RSuper`).

**Comment by maroider** [comment]
I believe those variants (or rather, their counterparts in the two new key enums) are already being renamed to `Super` as a part of the keyboard event rework (see #1806 for an entry-point into that).
