### ISSUE TITLE
Release with updated `smithay_client_toolkit`

### ISSUE THREAD

**Issue by bhansconnect** [rust-windowing/winit#2056]
Hi, just wondering if it is possible to get a release of `winit` with `smithay_client_toolkit` updated to a version compatible with `0.15`.

With the current version of winit, `smithay_client_toolkit` is only at `0.12`. This is mostly important for build times. The project I am working on ends up having to compile both `0.12` and `0.15`. With all of the `wayland-*` crates also having to be compiled twice, this has a decent build time overhead.

**Comment by msiglreith** [comment]
https://github.com/rust-windowing/winit/pull/2034 updated the crate version, which should be then in the upcoming 0.26 release https://github.com/rust-windowing/winit/pull/2043

**Comment by bhansconnect** [comment]
Perfect. I'll follow that issue.
