### ISSUE TITLE
Windows: Parent of owned child window not visible

### ISSUE THREAD

**Issue by msiglreith** [rust-windowing/winit#2060]
Declaring one windows as owner will make the owner window invisible which is unintentional and a regression from 0.25.
Seems to be caused by https://github.com/rust-windowing/winit/pull/1933

Minimum example:
```rust
fn main() -> anyhow::Result<()> {
    let event_loop = EventLoop::new();

    let owner = WindowBuilder::new()
        .with_title("owner")
        .build(&event_loop)
        .unwrap();

    let child = WindowBuilder::new()
        .with_title("child")
        .with_owner_window(owner.hwnd() as _)
        .build(&event_loop)
        .unwrap();

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;
    })
}
```

**Comment by msiglreith** [comment]
hm looks like only the child window receives a `WM_PAINT` event

**Comment by msiglreith** [comment]
Not passing the parent HWND on window creation for owned windows seems to alleviate the issue and show the parent window correctly - doing the initialization in `WM_CREATE` instead of `WM_NCCREATE` as well but that would defeat the purpose of #1933
Unsure what's the underlying issue tho

**Comment by maroider** [comment]
If I've understood the issue correctly, it seems you've run into what Raymond Chen describes [here](https://devblogs.microsoft.com/oldnewthing/20100315-00/?p=14613). That is, a window can optionally have `a parent XOR an owner`.

**Comment by msiglreith** [comment]
@maroider sorry, forget that part - not setting the handle delete the ownership which isn't the goal either 😓

**Comment by maroider** [comment]
I think there were only a couple of things that absolutely *had* to happen in response to `WM_NCCREATE` rather than `WM_CREATE`, like a call to `EnableNonClientDpiScaling` (which strictly speaking doesn't require our window state to be initialized). We don't currently dispatch any events in response to `WM_NCCREATE` and `WM_CREATE`, so it should be feasible to move most of the initialization logic into `WM_CREATE` (with some care).

**Comment by maroider** [comment]
I finally have a Windows 10 VM I can test with, and I managed to reproduce the bug.
Strangely enough, the owner window still appears when I hover over the preview in the taskbar.
I'll get you a review for #2062 shortly.
