### ISSUE TITLE
Input lag with nvidia 495 driver and wayland backend

### ISSUE THREAD

**Issue by VitalyAnkh** [rust-windowing/winit#2063]
It seems that every application built on `winit` experiences serious input lag when using wayland backend with nvidia 495 driver:
1. Alacritty: https://github.com/alacritty/alacritty/issues/5595#issuecomment-962496177 and https://forums.developer.nvidia.com/t/nvidia-495-on-sway-tutorial-questions-arch-based-distros/192212/2
2. Examples of [wgpu](https://github.com/gfx-rs/wgpu). For example, run the [water example](https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples/water) with `RUST_LOG=info WINIT_UNIX_BACKEND=wayland WGPU_BACKEND=vulkan cargo run --example water`. After the window shows up, the water stops flowing and the window gets almost unresponsive when the mouse hovers on the window.
3. Other apps, like [abstreet](https://github.com/a-b-street/abstreet), [iced](https://github.com/iced-rs/iced)'s examples...
![2021-11-15 02-21-38 的屏幕截图](https://user-images.githubusercontent.com/24508452/141693563-e747cddf-ec9f-4d42-9a74-8822ebb1b96d.png)
(This screenshot shows iced's [tour](https://github.com/iced-rs/iced/tree/master/examples/tour) example is unresponsive, runs with `RUST_LOG=info WINIT_UNIX_BACKEND=wayland WGPU_BACKEND=vulkan cargo run --package tour`)

My OS information: 
```
Linux 5.15.2
Gnome 41 on Wayland
Nvidia 495.44
```

Maybe the problem comes with lower level crates(glutin, or wayland-client?) but I'm not familiar with the code then I report it here for further discussion.

**Comment by maroider** [comment]
> Maybe the problem comes with lower level crates(glutin, or wayland-client?) but I'm not familiar with the code then I report it here for further discussion.

FYI, glutin is built on top of winit.

> It seems that every application built on `winit` experiences serious input lag when using wayland backend with nvidia 495 driver

I *think* experienced something similar with alacritty when I briefly tried the beta driver.

**Comment by Newbytee** [comment]
I experience something similar when working with wgpu. Does this look like the same bug?

https://user-images.githubusercontent.com/4428753/142775267-2c205aa9-6810-4b1f-a3d8-199c41846396.mp4

I can reproduce it with this code: https://github.com/sotrh/learn-wgpu/blob/master/code/beginner/tutorial2-surface/src/challenge.rs

**Comment by VitalyAnkh** [comment]
This should be triggered by this problem: https://github.com/NVIDIA/egl-wayland/issues/47.

**Comment by devmattrick** [comment]
> This should be triggered by this problem: [NVIDIA/egl-wayland#47](https://github.com/NVIDIA/egl-wayland/issues/47).
I'm also having this same issue, but I'm not sure if that issue is the same. Downgrading to the 1.1.7 version doesn't seem to work for me.

**Comment by Molytho** [comment]
I looked into this issue an it turns out that it is not a bug of winit but is inherited from a library [Client-Toolkit](https://github.com/Smithay/client-toolkit). I'm not able to fix it as it needs rather big changes in [Calloop](https://github.com/Smithay/calloop). I will open issues there.

**Comment by vberger** [comment]
I just released SCTK version 0.15.3 which should fix the issue, `cargo update` should pull it.
