### ISSUE TITLE
HasRawWindowHandle is not satisfied with winit 0.26

### ISSUE THREAD

**Issue by happy-turtle** [rust-windowing/winit#2085]
Updating to winit 0.26 with wgpu the build process breaks on the HasRawWindowHandle trait. Isn't this supposed to not be a breaking change, or am I missing something? https://github.com/rust-windowing/winit/releases/tag/v0.26.0

<details><summary>Error:</summary><pre>
error[E0277]: the trait bound `Window: raw_window_handle::HasRawWindowHandle` is not satisfied
  --> src\lib.rs:96:65
   |
96 |                 surface = Some(unsafe { instance.create_surface(&window) });
   |                                                                 ^^^^^^^ the trait `raw_window_handle::HasRawWindowHandle` is not implemented for `Window`
   |
help: trait impl with same name found
  --> github.com-1ecc6299db9ec823\raw-window-handle-0.4.2\src\lib.rs:58:1
   |
58 | / unsafe impl<'a, T: HasRawWindowHandle + ?Sized> HasRawWindowHandle for &'a T {
59 | |     fn raw_window_handle(&self) -> RawWindowHandle {
60 | |         (*self).raw_window_handle()
61 | |     }
62 | | }
   | |_^
   = note: perhaps two different versions of crate `raw_window_handle` are being used?
</pre></details>

How to reproduce:
- Clone https://github.com/happy-turtle/wgpu-android.git
- Run cargo apk build

**Comment by kchibisov** [comment]
According to semver it's a breaking change. But anyway, you could bump `raw-window-handle` in your project to `v0.3.4` or `v0.4.1`(run cargo update -p raw-window-handle) iirc and it should solve the issue.

**Comment by madsmtm** [comment]
Yeah, I think a regular `cargo update -p raw-window-handle` should solve it, but dammit I didn't think that would be necessary, sorry for the trouble! We should probably update the changelog entry to note this.

Maybe yanking the previous versions of `raw-window-handle` would make it better, though that also just seems disruptive? Paging @Lokathor.

**Comment by happy-turtle** [comment]
Yes `cargo update -p raw-window-handle` solved it. Thanks!

**Comment by aloucks** [comment]
> I didn't think that would be necessary

This is expected when the project has a `Cargo.lock` file.

**Comment by Lokathor** [comment]
yeah if `cargo update` can fix up the issue it's worth putting in the changelog but no need for a yank.
