### ISSUE TITLE
[Feature Proposal] Attach an empty buffer on new wayland surfaces

### ISSUE THREAD

**Issue by Diegovsky** [rust-windowing/winit#2089]
I've stumbled upon a wayland bug caused by the protocol demanding that for a window to be shown (and also have some of it's properties available) it must be mapped, and it seems I'm not the first one: #1257, #793.

To solve this and to make wayland behave a bit more like other platforms (for ease of use), I propose mapping a bogus buffer (with undefined data) to the surface when creating it. Since we're already using SCTK anyways, that wouldn't be a hard task as it provides wrappers for [simple memory buffers](https://docs.rs/smithay-client-toolkit/latest/smithay_client_toolkit/shm/struct.AutoMemPool.html).

This would make `examples` work on wayland. I'm willing to submit a PR :)

**Comment by kchibisov** [comment]
The way for working examples is to use software rendering.

Attaching a null buffer will result in `unmapping` actually.

So the issue in the way it's created is out of scope.

**Comment by Diegovsky** [comment]
I meant attaching a buffer filled with black pixels or garbage data, not a null buffer. I know that attaching a null buffer unmaps the surface.

Anyways, it seems that using soft rendering does fix it

**Comment by kchibisov** [comment]
It'll cause issues for the OpenGL/Vulkan, like it already did.

For examples will use softbuffer.

**Comment by Diegovsky** [comment]
ack
