### ISSUE TITLE
Version 0.26.0 breaks macOS IME

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#2097]
It appears that a recent change has caused IME to no longer work on macOS.

Originally reported to Alacritty in https://github.com/alacritty/alacritty/issues/5669.

@wendajiang could you maybe more detailed description of your issue? A short video of expected/actual would probably be helpful. In your Alacritty report it's not entirely obvious if "ni hao" was what you typed or if that was inserted.

**Comment by ArturKovacs** [comment]
I don't currently have a macOS device but I'll take a look either a weeks from now or in January. Given that this is a regression and a rather significant one, it wouldn't hurt if someone else could also try to get to the end of this. @madsmtm

**Comment by madsmtm** [comment]
Not something I know anything about (nor how to test), sorry!

**Comment by tinaun** [comment]
a minimal example works fine on my machine running macOS 11.6.2 - the correct receivedCharacter events are being emitted when manipulating the IME input

**Comment by tinaun** [comment]
on further testing, some IMEs (like jp hiragana) work and some (like pinyin) don't

**Comment by madsmtm** [comment]
Thanks a lot for reproducing @tinaun.

Would it be possible for you to `git bisect` or similar to find the commit that introduces the issue?
