### ISSUE TITLE
Horizontal Scrolling Backwards on Windows

### ISSUE THREAD

**Issue by aevyrie** [rust-windowing/winit#2099]
**Issue**
Horizonal and vertical scrolling directions do not match.

**Expected Behavior**
Both x/y should behave the same, e.g. both directions are "natural" scrolling on the touchpad.

**Observed Behavior**
Vertical scrolling respects OS and is in the "natural" direction. Horizontal scrolling is inverted and does not follow the "natural" scroll direction. First noticed when using native builds of https://github.com/emilk/egui/issues/356.

**Reproducing the Bug**
I've created a minimal reproducible winit example here: https://github.com/aevyrie/winit_scroll_test.

**Comment by msiglreith** [comment]
For my understanding as there is https://github.com/rust-windowing/winit/pull/2105 as well: The x direction should be inverted on all platforms? What's the desired coordinate system for scrolling?

**Comment by aevyrie** [comment]
> For my understanding as there is #2105 as well: The x direction should be inverted on all platforms? What's the desired coordinate system for scrolling?

No, see here: https://github.com/rust-windowing/winit/pull/2101#discussion_r772017805. The goal is to match GLFW prior art.

**Comment by akhilman** [comment]
I have the same behaviour on Manjaro Gnome with trackball mouse and Debian Xfce with touchpad. In both machines the X-axis is flipped. Tested with https://github.com/aevyrie/winit_scroll_test.

**Comment by msiglreith** [comment]
Unfortunately, I didn't get vertical scrolling to work on any my devices so far with `winit` ):
Regarding the coordinate system: currently it's defined in `winit` as https://docs.rs/winit/latest/winit/event/enum.MouseScrollDelta.html#variant.LineDelta, so basically bottom-left corner.

Do the raw value output match with coordinate system in the documentation? The window position coordinate system is top-left IIRC which might be confusing. Overall I don't mind if we adapt the GLFW approach but I want to be sure that it matches with the documentation and it's clear if this a bugfix or breaking change.

**Comment by aevyrie** [comment]
Closed by #2105
