### ISSUE TITLE
How can I prevent the cursor from moving out of the window?

### ISSUE THREAD

**Issue by yogarasu** [rust-windowing/winit#2122]
I'm a mac user using maxos 12.1.

How can I prevent the cursor from going off the screen?

In my experience with other screen libraries I think there is such an option, but I couldn't find it in the docs.

**Comment by madsmtm** [comment]
[`Window::set_cursor_grab`](https://docs.rs/winit/latest/winit/window/struct.Window.html#method.set_cursor_grab) might be what you are looking for.

This doesn't work the web, though it probably could, see https://github.com/rust-windowing/winit/issues/1674

**Comment by yogarasu** [comment]
@madsmtm
Thank you for your comment.

I've already tried this feature, but it wasn't what I was looking for.

You may have misunderstood the specifications of Window :: set_cursor_grab, so I'd like to ask you just in case. Is this the function that the cursor moves in the screen?

In my environment, when I used Window::set_cursor_grab, the cursor didn't move in the screen, so I couldn't understand the purpose of this function.

Since I'm using WindowEvent instead of DeviceEvent as a workaround for #1470, Window::set_cursor_grab may not work as expected and I may have misunderstood it.

**Comment by yogarasu** [comment]
I'm sorry, I was misunderstanding
As a workaround for # 1470, I also used WindowEvent for mouse events, so it seems that the cursor did not move within the screen even when using Window :: set_cursor_grab.

I solved it by using DeviceEvent for mouse events.

**Comment by maroider** [comment]
> In my environment, when I used Window::set_cursor_grab, the cursor didn't move in the screen, so I couldn't understand the purpose of this function.

This is a known (and documented) limitation with `Window::set_cursor_grab` on macOS.

**Comment by yogarasu** [comment]
@maroider 

Sorry,
I thought I was reading the docs, but looking only at the content here, I didn't think the cursor would move on the screen when using DeviceEvent, so I thought it was a strange feature.
https://docs.rs/winit/latest/winit/window/struct.Window.html#method.set_cursor_grab
