### ISSUE TITLE
Release v0.26.1

### ISSUE THREAD

**Issue by ArturKovacs** [rust-windowing/winit#2124]
v0.26.0 had a regression that made the Pinyin IME input unusable on macOS. See #2097

#2119 fixed that regression, and I think it's a good idea to publish a new release with the fix quickly.

@madsmtm @maroider @msiglreith @kchibisov @francesca64

**Comment by kchibisov** [comment]
Sure, you can open a PR.

**Comment by ArturKovacs** [comment]
I'm closing this. Let's continue under the PR #2125
