### ISSUE TITLE
Missing events when using Vulkan (ash)

### ISSUE THREAD

**Issue by lwjglgamedev** [rust-windowing/winit#2127]
I am doing some tests with Vulkan using the ash library and winit. When running the examples provided by ash, I've noticed that when changing the presentation mode of the swap chain from `MAILBOX` to `FIFO`, to limit the frames to the scan rate, it seems that the window looses events. In this situation, it is even difficult or impossible to close it or to drag it. I have raised this issue first in the ash project but their response is that ash library is not involved at all in handling window events and that it may be related to DXGI’s internals.

I’m currently using Windows 11, you can reproduce the problem by using ash triangle example. If you clone the repository, you just need to change the file: https://github.com/MaikKlein/ash/blob/master/examples/src/lib.rs, chaning the value in line 362, from `MAILBOX` to `FIFO`.

Any ideas?

**Comment by msiglreith** [comment]
Hi, I guess the WSI is effectively blocking the event loop in the `FIFO` case. The example code unconditionally renders on each incoming event (https://github.com/MaikKlein/ash/blob/master/examples/src/lib.rs#L188) which probably causes the present queue running out of available images faster than desired. Only updating on a `MainEventsCleared` or `RedrawRequested` event should alleviate this.

**Comment by msiglreith** [comment]
(discussion in the ash repo for reference: https://github.com/MaikKlein/ash/issues/541)

**Comment by lwjglgamedev** [comment]
Thanks for the response, I can confirm that rendering only upon `MainEventsCleared` solves the problem. My guess is that in `FIFO` mode, the event loop is blocked at some periods, to sync with scan rate, and this provokes the events to be lost. This does not happen in `MAILBOX` mode (altought many more render calls ara achieved), sine there is no blocking. I will close the issue.
