### ISSUE TITLE
Update wayland-client to 0.30

### ISSUE THREAD

**Issue by mahkoh** [rust-windowing/winit#2128]
wayland-client below 0.30 is fundamentally broken in that updating your compositor can cause wayland-client applications to abort immediately on start. This is because wayland-client below 0.30 cannot handle unknown shm formats but compositors are allowed to add new formats at any time.

**Comment by kchibisov** [comment]
wayland-client 0.30 isn't even released. And it'll take time to update things, since first of all sctk should be updated. But yeah, I'm long aware of this issue, and I think I saw it only once in the wild in like 3 years.

**Comment by mahkoh** [comment]
I've been hacking on a wayland compositor and I saw it immediately when trying to start alacritty because wayland-client in alacritty is not up to date with the upstream wayland protocol.

Here is the wayland-client 0.30 issue: https://github.com/Smithay/wayland-rs/issues/431

**Comment by kchibisov** [comment]
You can ask @vberger for wayland-protocols bump for old wayland-client. Will like solve the issue for a few month or so while migrating to wayland-client v0.30.0 is happening.

**Comment by mahkoh** [comment]
As you say but either way it would take many days for a fixed alacritty to be released. For now I've simply removed the more obscure shm formats from my code.

**Comment by kchibisov** [comment]
I mean, it'll take like a week at max, since alacritty is in a release process and waiting for winit version bump.

**Comment by mahkoh** [comment]
@vberger Could you release wayland-client 0.29.2 with the current version of wayland.xml?

**Comment by vberger** [comment]
Technically, this update would be a breaking change (as it is adding new variants to an enum exposed in the rust API), however I think we can reasonably assume that no client using wayland-rs  is exhaustively matching on that enum. So yes, I should be able to release 0.29.3 with the protocol update in a few hours.

**Comment by vberger** [comment]
`0.29.3` is now released

**Comment by mahkoh** [comment]
Thanks

**Comment by mahkoh** [comment]
Why did you close this?

**Comment by kchibisov** [comment]
Well, I can reopen this issue to track update to new wayland-client, but the whole purpose of the original issue was to update to wayland.xml winit is using, since you've opened issues on alacritty and winit trackers in near the same time.

**Comment by jimblandy** [comment]
The `wgpu` project [is also interested](https://github.com/Smithay/wayland-rs/pull/538#issuecomment-1243038663) in having `winit` update to `wayland-protocols` to 0.30, because that will clean up our `cargo audit` output. 0.30 migrates off of xml-rs, which is unmaintained.

**Comment by kchibisov** [comment]
I'm working on it, but it'll take time... More likely weeks/month, given that even if I write an update it'll take some time to verify that everything is working as before.

Be aware that wayland-protocols is a `build` time dependency. So it's like irrelevant.

**Comment by jimblandy** [comment]
I appreciate it - thanks very much for your work here!

I do worry a bit about build-time dependencies, too: after all, they run on my computer when I'm doing development.
