### ISSUE TITLE
Ideas for solving changelog conflicts

### ISSUE THREAD

**Issue by madsmtm** [rust-windowing/winit#2135]
Most changes warrant an entry in `CHANGELOG.md`, however, this means that we get `git` conflicts whenever a PR is merged; this is tough on contributors, because they have to keep their PRs "up to date" to have a chance of being merged.

A few ideas for solving this problem, for fun let's react with the corresponding emoji for the solution(s) you like the most:

🎉: The maintainer that merges solves the conflict before merging.

❤️: We add changelog placeholders [like GitLab did in 2015](https://about.gitlab.com/blog/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/), and users just randomly pick one of these to add their entry to.

🚀: We set up a bot that does the merge when a maintainer says `@winitbot merge`, and in this process it fixes the changelog conflicts, kinda like Rust itself does with [@bors](https://github.com/bors). [This is hard work, not something I want to spearhead FYI]

👀: The PR author adds the changelog entry to the PR description, and the person doing a new release manually collects all of these together.

👎: We keep the status-quo.

Whichever solution we choose, I'll make sure to document it.

EDIT: Added the 👀 proposal

**Comment by maroider** [comment]
> 🎉: The maintainer that merges solves the conflict before merging.

This seems reasonable when people check the "give contributors write access to the branch" checkbox when creating the PR. I don't know how we'd resolve merge conflicts in the absence of this permission.

**Comment by madsmtm** [comment]
Right, we'll document that as well.

**Comment by madsmtm** [comment]
@kchibisov suggested on Matrix that we remove `merge=union` so that old entries don't accidentally get put in the wrong place

**Comment by ArturKovacs** [comment]
> we remove `merge=union` so that old entries don't accidentally get put in the wrong place

As far as I can tell, if we remove `merge=union`, then PRs will just have more conflicts in the changelog, but once "resolving" the conflict the item would still stay under the wrong release if a release is published while the PR is open.

Or would the changelog line in the PR  magically jump to the top after making the release? That doesn't seem likely. What am I missing here?

**Comment by madsmtm** [comment]
The difference is that `merge=union` puts the entry under the wrong header _automatically_, while with the default settings it, a person has to manually resolve the conflict, hopefully in the process discovering that the entry is in the wrong place.

**Comment by madsmtm** [comment]
I've added a new "👀" proposal, tagging voters @msiglreith, @maroider, @kchibisov, @MultisampledNight, @chrisduerr and @vberger so that you have the opportunity to review it.

Pro: It would remove all `git` conflicts.
Cons: The changelog does not represent the current `master`, `git blame` doesn't work on the changelog.

**Comment by MultisampledNight** [comment]
I still stay at "letting the PR submitter do it". Forcing the maintainer to collect everything without automatization is unnecessarily repetetive and also offers a large opportunity to eventually miss one PR. Thus I can't seem to find a way to list all PRs on GitHub which have been merged in a time range, but that's easily solvable with a script.

**Comment by ArturKovacs** [comment]
> The difference is that `merge=union` puts the entry under the wrong header _automatically_

I think this is false. If the latest release of winit is identical to the one that was the latest at the time the branch was created, then the changelog entry is under the correct section, regardless whether `merge=union`


When a new release is made, it doesn't introduce a conflict in open PRs, regardless whether `merge=union`.

Therefore removing `merge=union` doesn't help avoiding to merge an incorrect changelog entry. Admittedly it does help detecting an incorrect placement but only after an incorrect one got merged and then an open PR conflicts with the incorrectly merged one.

**Comment by madsmtm** [comment]
> When a new release is made, it doesn't introduce a conflict in open PRs, regardless whether `merge=union`.

You're right, though I think it depends on a few other factors. Assuming we want to prevent this problem (that a maintainer accidentally resolves the conflict by auto-merging the entry under the wrong section) from happening, here's a way to do so:

1. Remove `merge=union`. 
2. Mandate that PRs must have new changelog entries at the top. Their diff would be:
```diff
@@ -1,5 +1,6 @@
 # Unreleased
 
+- New entry
 - Old entry 1
 - Old entry 2
 - Old entry 3
```

3. When releasing we create a new section instead of modifying the `# Unreleased` section. So the diff would be:
```diff
@@ -1,5 +1,8 @@
 # Unreleased
 
+
+# Version X
+
 - Old entry 1
 - Old entry 2
 - Old entry 3
```

Trying to merge or rebase the PR would result in the following conflict, because `git` views the addition of the newline above `Old entry 1` as conflicting with the added entry:
```
# Unreleased

<<<<<<< HEAD

# Version X

=======
- New entry
>>>>>>> new
- Old entry 1
- Old entry 2
- Old entry 3
```

**Comment by ArturKovacs** [comment]
Alright, fair enough. Then I'm in favor of removing `merge=union` for CHANGELOG.md. But that only makes sense if we make it clear that all changelog entries must go to the top of the section, and that new releases must keep the `# Unreleased` header with an empty space below it, otherwise this whole thing doesn't work.
