### ISSUE TITLE
Can I use this library to detect focus event on other windows?

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [rust-windowing/winit#2170]
Thanks for the library and all your work! I am wondering if my use case fits into this.

My use case is the following:

I want to watch which window of all windows (which are not managed by my application) is focused.
I wonder if this library can be used for that.

My first experiments seem to reveal, that I don't get WindowEvents (which is the only place where I could find something related to focus) for Windows not created by me.

Am I overseeing something or is this possible with winit?

**Comment by kchibisov** [comment]
No, you can't do that since it won't work cross platform. On something like Wayland you don't known anything about thins you haven't created.

**Comment by RudolfVonKrugstein** [comment]
Thank you!
