### ISSUE TITLE
Change workflow settings

### ISSUE THREAD

**Issue by madsmtm** [rust-windowing/winit#2183]
As a maintainer, I find myself needing to click the "Approve running workflows for this pull request" button quite a lot, would be nice if we didn't have to (PR authors would get quicker feedback on whether their code works or not).

Pinging admin @francesca64 to do this: In https://github.com/rust-windowing/winit/settings/actions, please change the "Fork pull request workflows from outside collaborators" setting, as in the following screenshot.
![Desired setup](https://user-images.githubusercontent.com/10577181/152644734-817897dd-35bd-4d71-a0c3-1ac14ba29728.png)

**Comment by madsmtm** [comment]
I suspect the same is true for:
- https://github.com/rust-windowing/glutin
- https://github.com/rust-windowing/android-ndk-rs
- https://github.com/rust-windowing/raw-window-handle

Would be nice to have it changed there as well.

**Comment by francesca64** [comment]
Done for all 4 repos 👍

**Comment by madsmtm** [comment]
Wonderful, thanks!
