### ISSUE TITLE
Wayland: cursor does not show up

### ISSUE THREAD

**Issue by alandiwix** [rust-windowing/winit#2186]
Cursor doesn't show up upon calling window.set_cursor_visible(true) on Wayland.
The bug is easily reproducable on 0.25.0 and 0.26.1:
1. Order a window to hide cursor using window.set_cursor_visible(false).
2. Call window.set_cursor_visible(true).
3. The cursor doesn't show up unless you move the cursor out of the window's borders and then move it back.
X11 and other backends seem to be non-affected.

Related: https://gitlab.com/veloren/veloren/-/issues/1353
I wrote a simple app with wgpu-based filler to reproduce that and it's indeed reproducable.

**Comment by kchibisov** [comment]
What Wayland setup do you have? I think it's a bug in your environment.

**Comment by alandiwix** [comment]
It's reproducable both on GNOME (as described in the issue above) and on sway.

**Comment by kchibisov** [comment]
If you do `XCURSOR_THEME=Adwaita <your_app>` is it working?

**Comment by alandiwix** [comment]
Yes, you're right, installing cursor theme and specifying the env var works.
I'm wondering is there a way to show the default cursor without any theme installed, like on X11 or Xwayland?

**Comment by kchibisov** [comment]
The thing is that on Wayland the cursor is drawn by the user, so it should get that cursor image somewhere, thus cursor theme is required. On X11 the cursor is drawn by the Xorg server, which solves such problem and image loading is also Xorg thing iirc.

So I'd rather suggest including cursor theme with flatpack that game is shipping, since providing default cursor would mean basically embeding some cursor theem and all its sized into binary which is just huge. (And Adwaita is like 11 Mb alone for example).

**Comment by kchibisov** [comment]
Also, if you don't want to specify the env var, just specify the cursor theme in `default/index.theme` as libxcursor and friends suggest you to do. Just to clarify for GNOME apps it's a bit different though, since they are using dbus for this.

**Comment by kchibisov** [comment]
@alandiwix Would you mind pointing to that issue on veloren gitlab since I don't have account there?

**Comment by alandiwix** [comment]
@kchibisov Yes, I will take care care of it.

**Comment by alandiwix** [comment]
@kchibisov I'm wondering where does the default icon theme come from?
I tested several other wayland apps and they seem to hide and return cursor just fine.

**Comment by kchibisov** [comment]
@alandiwix are you testing gtk apps or some native apps? But it's basically this https://wiki.archlinux.org/title/Cursor_themes .  Look at XDG specification part.

**Comment by alandiwix** [comment]
@kchibisov It's mpv and qtwebengine-based browser I tested this with.
