### ISSUE TITLE
Feature request: Support exiting event loop without quitting program

### ISSUE THREAD

**Issue by surban** [rust-windowing/winit#2187]
I am using winit via eframe for a command line application. The app displays a window for the user to provide some input. After the window is closed I would like winit to exit the event loop and return from [EventLoop::run](https://docs.rs/winit/latest/winit/event_loop/struct.EventLoop.html#method.run), so that the app can continue running.

However this is currently impossible because the return type is ! and std::process::exit is called when the event loop is exited.

See also https://github.com/emilk/egui/issues/1223

**Comment by maroider** [comment]
See [`EventLoopExtRunReturn::run_return`](https://docs.rs/winit/latest/winit/platform/run_return/trait.EventLoopExtRunReturn.html#tymethod.run_return)

**Comment by surban** [comment]
Unfortunately, according to the egui developers this is not working properly, see https://github.com/emilk/egui/issues/1223#issuecomment-1033849861.

**Comment by maroider** [comment]
My intuition is that even if `run_return` leads to "very jittery resizing of windows", such behaviour should only manifest if one repeatedly returns and re-enters the event loop. For your use-case, which seems to call for exiting the event loop a single time once you've shown your prompt, seems like it might work without much of an issue. `run` uses `run_return` under the hood, so I don't think there's much room for additional bugs to sneak in (ignoring the previously mentioned "return + re-enter" case).

**Comment by kchibisov** [comment]
I'm not sure what the issue to solve here, `run` just calls `run_return` on desktop platforms iirc. `run_return` isn't possible on mobile iirc, but that's about it.

**Comment by lucafulgenzi** [comment]
@surban I am in the same situation as you, have you found an alternative method? Or have you changed libraries, if so could you tell me which one you used?

**Comment by rib** [comment]
`run_return` should be ok on Android I think (at least I can't think of a reason off the tip of my head why it wouldn't work)

**Comment by lucafulgenzi** [comment]
It is not for android

**Comment by rib** [comment]
> It is not for android

yeah, I was just thinking about the comment about `run_return` potentially not being supported on mobile. I've added a quote to clarify what I was commenting on.

**Comment by surban** [comment]
> @surban I am in the same situation as you, have you found an alternative method? Or have you changed libraries, if so could you tell me which one you used?

I haven't tried myself, but wasn't this fixed in egui in https://github.com/emilk/egui/pull/1889 ?
