### ISSUE TITLE
`EventLoop::run` with OOP style

### ISSUE THREAD

**Issue by leontepe** [rust-windowing/winit#2206]
What would a clean OOP (as far as Rust is OO) implementation of an `App` that owns a `window` and `event_loop` look like?

I'm looking for something that would look roughly like this:

```rs
impl App {
    // snip
    pub fn run(mut self) {
        // Run the event loop
        self.event_loop.run(move |event, _, control_flow| self.handle_event(event, control_flow));
    }
    // snip
}
```

I can't get past the borrow checker with any structure that resembles this.

Did anyone already do this? Some references or examples for a `struct` + `impl` focused implementation?

#1543 is related, but even changing to `run_return` doesn't get me past the borrow checker. Also, I want to deploy to Wasm so would like to keep the `run` instead.

**Comment by maroider** [comment]
If you want to avoid having to use an `Option<EventLoop>` and `Option::take`, you need to separate the "setup" and "live" states, instead of bundling them like you have here.

**Comment by leontepe** [comment]
> If you want to avoid having to use an `Option<EventLoop>` and `Option::take`, you need to separate the "setup" and "live" states, instead of bundling them like you have here.

Can you elaborate?

**Comment by maroider** [comment]
You can sort of solve your issue by making `self.event_loop` be an `Option<EventLoop>`, and then doing `self.event_loop.take().unwrap().run()` to enter the event loop, but it's sort of a dirty trick.

Instead, you may want to make something like an `AppBuilder` with a `run` method that constructs the `App` and calls `EventLoop::run`.

**Comment by leontepe** [comment]
> Instead, you may want to make something like an `AppBuilder` with a `run` method that constructs the `App` and calls `EventLoop::run`.

How would this solve the problem? I'm afraid I don't even really understand what's going wrong here or why this isn't possible. Why is the ownership messed up in my example?

**Comment by maroider** [comment]
````rust
    self.event_loop.run(
//       ^^^^^^^^^^ `self.event_loop` is moved out of `self` here because `EventLoop::run` takes
//                  `EventLoop` by value. This means that `self` cannot be moved after this.
        move |event, _, control_flow| {
//      ^^^^ `move` closures take ownership of captured varaibles and moves said variables into the closure
            self.handle_event(event, control_flow)
//          ^^^^^^^^^^^^^^^^^ This method call presumably takes `&mut self`, which means the entirety
//                            of `self` must be moved into the closure, but that's not possible since
//                            `self` is partially moved
        }
    );
````
