### ISSUE TITLE
Currently pressed Keys as String / Char

### ISSUE THREAD

**Issue by markusmoenig** [rust-windowing/winit#2219]
Hi,

I am probably missing something: What is the way to get the currently pressed keys as a String or char ?

I can only find a way to query if a single key is pressed or not. I want to implement a text input dialog for my game.

Thanks

**Comment by maroider** [comment]
You should use `WindowEvent::ReceivedCharacter` to implement text input.

**Comment by markusmoenig** [comment]
Thanks, is there an example somewhere ? As I am new to Rust I find the way events are checked inside winit very confusing. In the documentation there are no examples at all.

**Comment by markusmoenig** [comment]
Never mind, figured it out, thanks!
