### ISSUE TITLE
Wrong scale factor on X11/KDE

### ISSUE THREAD

**Issue by jmaargh** [rust-windowing/winit#2229]
This may well be a problem with my system, rather than winit, but I don't think it is.

With this simple example:
```
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new()
        .with_inner_size(winit::dpi::LogicalSize::new(800, 600))
        .build(&event_loop)
        .unwrap();

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                window_id,
            } if window_id == window.id() => *control_flow = ControlFlow::Exit,
            Event::MainEventsCleared => {
                window.request_redraw();
            }
            Event::WindowEvent {
                event: WindowEvent::CursorMoved { position, .. },
                ..
            } => {
                let logical_position = position.to_logical::<i32>(window.scale_factor());
                println!(
                    "Scale Factor: {}    Physical {:?}    Logical: {:?}",
                    window.scale_factor(),
                    position,
                    logical_position
                );
            }
            _ => (),
        }
    });
}
```

I can see that my `scale_factor()` is always reporting as `1.1666666666666667`, rather than the expected 1.0. This is a surprise because I have everything set to 100% scaling in settings, and indeed I see everything on the monitor at 100% scaling. No `ScaleFactorChanged` events are received.

System:
Manjaro KDE
KDE Plasma 5.24.2
X11 X.Org 1.21.1.3
Kernel 5.15.25-1

Happy to provide more details if required.

**Comment by jmaargh** [comment]
On closer inspection of [these docs](https://docs.rs/winit/latest/winit/dpi/index.html#how-is-the-scale-factor-calculated), I can verify that this scale factor seems to be coming from the `platform_impl::linux::x11::util::randr::calc_dpi_factor` function, the logic of which is a complete mystery to me.

Those docs allude to a lot of effort trying to work out how to get scale factor in X11. I respect that I wasn't part of those conversations and I'm sure their conclusions we well motivated. However, I struggle support the idea of `winit` falling back on some hard-coded mathematics based on millimetre dimensions when it's not getting a clear answer from X11. Surely it is more consistent to just treat it as 1.0? Right now I'm in the position where every application on my system renders 1px as 1px, except winit applications which render  c. 17% larger, which is ugly, unexpected, and just unnecessary.

**Comment by dhardy** [comment]
Is this coming from font size? KDE offers an option to force font DPI, which might have an effect here.

> which is ugly

If you want to write a scalable app, then it's up to you to address that somehow, whether by ensuring all graphics scale well or by rounding the scale-factor to nearest 25% or whatever is easier to render.

If you just want to turn off scaling locally, you can: `export WINIT_X11_SCALE_FACTOR=1`.

**Comment by jmaargh** [comment]
After some more thought and reading, I've moved my concerns to a [more specific issue](https://github.com/rust-windowing/winit/issues/2231)
