### ISSUE TITLE
Please publish a new release

### ISSUE THREAD

**Issue by Jasper-Bekkers** [rust-windowing/winit#2234]
It would be nice now that #2057 got merged to get a new release. We've been test driving it for a while on our end and it's been working well for us so it would be nice to be able to get off of our git dependency.

**Comment by kchibisov** [comment]
I'd like to get IME stuff in before doing breaking release, since it's basically done, and won't take me longer to fine tune the last parts of it.

However if you're maintaining some large downstream application that is being shipped in various Linux/BSD distributions and you really want to make release we could probably accelerate things a bit.

**Comment by maroider** [comment]
> However if you're maintaining some large downstream application that is being shipped in various Linux/BSD distributions and you really want to make release we could probably accelerate things a bit.

Neovide already ships with a forked version of winit as a git dependency, so I don't quite understand why a crates.io release is all that necessary (although I'll concede that it's *nice* to not have any git dependencies).

**Comment by kchibisov** [comment]
@maroider they ship snapcraft or something like that, however certain distros like debian/fedora pulling deps from crates.io and package them as well. So you can't use git dependencies for release. It also affects offline builds iirc in certain distros.

**Comment by kennykerr** [comment]
I'm planning to exclude `windows-sys` from the regular 3-week release cadence that we've been on to allow the current version (0.36) to establish itself. Notably, `windows-sys 0.36` has now been adopted by [tokio](https://github.com/tokio-rs/mio/pull/1569) and [parking_lot](https://github.com/Amanieu/parking_lot/pull/339). It may be worthwhile updating to 0.36 as well before publishing `winit`.
