### ISSUE TITLE
`WindowExtAndroid` has no method to get the window handle

### ISSUE THREAD

**Issue by Rua** [rust-windowing/winit#2236]
Someone pointed out in https://github.com/vulkano-rs/vulkano/issues/1417 that the `WindowExtAndroid` trait at one point had a `native_window()` method, which could be used to get the raw window handle. Vulkano relied on this function, but it was apparently mostly overlooked. What happened to this method, and can it or some equivalent be provided again?

**Comment by msiglreith** [comment]
https://docs.rs/winit/latest/winit/window/struct.Window.html#impl-HasRawWindowHandle is implemented on every platform which should be used as interface for graphics apis providing the native window handle
