### ISSUE TITLE
Win32API WS_EX_TRANSPARENT alternative for Winit?

### ISSUE THREAD

**Issue by TriedAngle** [rust-windowing/winit#2237]
WS_EX_TRANSPARENT makes window background transparent and it doesn't capture any input. Instead the window 1 below in the window stack takes the input. Is there any way to do something like this in winit?

**Comment by msiglreith** [comment]
https://github.com/rust-windowing/winit/pull/2232 implements this but still in review process

**Comment by maroider** [comment]
Can this be closed now?

**Comment by TriedAngle** [comment]
@maroider 
yes thanks for notifying me :+1:
