### ISSUE TITLE
Behaviour of resizable is different across platforms

### ISSUE THREAD

**Issue by sourcebox** [rust-windowing/winit#2242]
When setting `window.set_resizable(false)` the window is still resizable via `window.set_inner_size()` on macOS and Windows, but not on Linux. I would expect that `window.set_resizable(false)` just disables the manual handles for the mouse on all platforms but keep it possible to change the size from the application itself.

**Comment by kchibisov** [comment]
I think it makes sense to allow setting size manually.

I'll try sending patch for X11/Wayland and update docs wrt that when I have time, should be pretty simple from what I can see.
