### ISSUE TITLE
Mysterious VirtualKeyCode variant

### ISSUE THREAD

**Issue by alice-i-cecile** [rust-windowing/winit#2265]
[When documenting Bevy's equivalent of the `VirtualKeyCode`](https://github.com/bevyengine/bevy/pull/4517), we were unable to decipher the meaning of the [`Ax` keycode](https://docs.rs/winit/latest/winit/event/enum.VirtualKeyCode.html#variant.Ax). Does anyone have ideas for what this represents?

**Comment by maroider** [comment]
It appears that it's only emitted on the web backend, and I can't really track down why it exists just by grepping through the source. I couldn't find it in [the spec](https://www.w3.org/TR/uievents-code/) where the strings we match on are defined either.

**Comment by kchibisov** [comment]
The API was changed and this thing is sort of gone.
