### ISSUE TITLE
Window activation support

### ISSUE THREAD

**Issue by kchibisov** [rust-windowing/winit#2279]
On Wayland for link to raise window(e.g. when clicking a link in application, the launcher application should be opened with some env variable set to specific token).

Both X11 and Wayland has concept like that, see

https://wayland.app/protocols/xdg-activation-v1 and its `XDG_ACTIVATION_TOKEN` variable.

And X11
https://cgit.freedesktop.org/startup-notification/tree/doc/startup-notification.txt 

I'm not sure whether macOS or Windows have something like that, but they probably should.

For now, to account for Wayland,  we should add a method on `WindowBuilder::with_activation_token(<Option<String>>)` and add a method on a particular window to request activation token.

The first will be used when the application is raised from other process or in multiwindow context. The later to run launchers e.g. `xdg-open` or same in multiwindow context.

cc @ArturKovacs @maroider @madsmtm 

--

I'll send Wayland impl and impl it in alacritty, since it looks pretty straightforward.

**Comment by kchibisov** [comment]
I was a bit wrong wrt API, given that Wayland is async here and you must creating a token is a request to compositor leaving you wait until the request is done means that it should reply to application async via some event...

**Comment by madsmtm** [comment]
Not sure I understand, is the "activation token" equivalent to an "application id" (macOS has those)? If no, how do they differ? Would this allow a similar thing as https://github.com/rust-windowing/winit/issues/1751?

**Comment by kchibisov** [comment]
No, it's completely different thing. It's basically what `Window::focus_window` does. And if you pass it to a launcher, launched window can read this token and request focus.

Example, clicking on links in terminal will switch focus to a browser or mark it as urgent(depends on compositor). Without token passing it's impossible to know where the link opened or what actually launched.

It could be passed to other winit window, so it'll get focus or if you want to switch focus to other winit window when feel like.

**Comment by psychon** [comment]
Are you sure that xdg-activation and startup-notification do similar things? The xdg-activation spec begins with:

> The way for a client to pass focus to another toplevel is as follows.

startup-notification... doesn't have any explanation that I can find. So, instead I found: https://developer-old.gnome.org/platform-overview/stable/dev-launching-startupnotify.html.en

> Notify the user when your application has finished starting up.
> 
> GNOME implements the [Startup Notification protocol](https://standards.freedesktop.org/startup-notification-spec/startup-notification-latest.txt), to give feedback to the user when application startup finishes.
> 
> GTK applications automatically support startup notification, and by default notify that application startup is complete when the first window is shown. Your application must declare that it supports startup notification by adding StartupNotify=true to its desktop file.
> 
>More complicated startup scenarios, such as showing a splash screen during startup, would need custom handling with [gdk_notify_startup_complete()](https://developer.gnome.org/gdk3/stable/gdk3-General.html#gdk-notify-startup-complete).

I understand this as a completely different use case. Basically, I vaguely remember that KDE would change my mouse cursor when I started an application via the menu, showing the app's icon next to the mouse cursor while the app was starting. I bet it doesn't do that anymore, so just imagine an hourglass as mouse cursor between "the app is started" and "the app is done starting".

I am not saying that something somewhere does some focus-passing via sn events, but I am trying to say that these two protocols (xdg-activation and startup-notification) don't seem closely related to me.

**Comment by kchibisov** [comment]
@psychon it's wired the same in GTK if you read its code and it's wired the same inside the firefox. The Wayland spec refers to X11 spec and wayland compositors use the tokens from xdg-activation for `DESKTOP_STARTUP_ID`.
