### ISSUE TITLE
Winit doesn't open windows in Wayland

### ISSUE THREAD

**Issue by sosacode20** [rust-windowing/winit#2296]
Hi, winit doesn't show me a windows since I update fedora from version 35 to 36 and the problem is just with the use of Wayland but with Xorg it just works. I think this is because of an update in the Wayland API that winit doesn't take in account, but am not sure

**Comment by maroider** [comment]
Are you making sure to draw to the window? Wayland won't show a window until it has been drawn to.

**Comment by sosacode20** [comment]
Yes.... In fact I use the same code that is provided as an example of the crate and with Xorg it works, but with Wayland it doesn't

**Comment by maroider** [comment]
The example code in this repo won't show a window on Wayland because the examples don't draw to them. This is a known issue. You can try the glutin examples instead, as those *do* draw to the window.

**Comment by Liamolucko** [comment]
Also, as a workaround, you can set `WINIT_UNIX_BACKEND=x11` to fall back on Xwayland.

**Comment by kchibisov** [comment]
Closing as a known limitation of winit examples.
