### ISSUE TITLE
[X11] Eventloop with ControlFlow::Poll hangs if there are no windows.

### ISSUE THREAD

**Issue by HindrikStegenga** [rust-windowing/winit#2309]
So I was playing around with this library as part of a rendering engine project and wanted to defer window creation until a later point. As such, I did not create a window before starting the eventloop. It seems that, atleast on X11, this causes the entire program to hang and wait until some event is fired, which won't happen as there is no window present yet which generate events. This happens in Winit 26.1. 

See the stack trace here:  
![image](https://user-images.githubusercontent.com/10209433/170889672-531c5eb1-75d0-4704-98e2-625d1f51212b.png)

**Comment by maroider** [comment]
Can you create a minimal, reproducible example?

**Comment by HindrikStegenga** [comment]
So it turned out to be a variant on this issue: https://github.com/vulkano-rs/vulkano/issues/844
