### ISSUE TITLE
Incorrect position with CursorMoved when dragging out of window left/top with mouse button pressed

### ISSUE THREAD

**Issue by apessino** [rust-windowing/winit#2310]
The `position` value received with `WindowEvent::CursorMoved { position, .. }, ...` is incorrect when a mouse button is being held and the pointer crosses over the left or top edge of the window.

Instead of the proper negative value, `position` contains `65536.0 - offset to window edge`, this is obviously the result of some intermediate conversion to `u16` before `position` is turned into `PhysicalPosition<f64>` and given to the event. I believe this problem was introduced in the last update to `winit`, but I am not positive.

For now, I have worked around the problem as follows:

```
  Event::WindowEvent {
      event: WindowEvent::CursorMoved { position, .. },
      ..
  } => {
      let px = if position.x > 32767.0 {
          (position.x - 65536.0)
      } else {
          position.x
      };
      let py = if position.y > 32767.0 {
          (position.y - 65536.0)
      } else {
          position.y
      };
   // ... use `vec2(px, py)` instead of `position`...
```

I have only tried this on Windows, I am not sure the problem exists on other platforms.

A=

**Comment by msiglreith** [comment]
thanks for the report, looks like `get_x/y_lparam` misses a cast to i16. It slipped through during the transition to windows-sys.
