### ISSUE TITLE
`rust-windowing`: Administrator rights and ownership

### ISSUE THREAD

**Issue by madsmtm** [rust-windowing/winit#2319]
Tagging @rust-windowing, and since I'm not sure if people are pinged by that, every member of the organization:
@adamnemecek @ArturKovacs @dvc94ch @francesca64 @goddessfreya @kchibisov @Lokathor @madsmtm @MarijnS95 @maroider @mb64 @mitchmindtree @msiglreith @murarth @Osspial @tomaka @vberger @vbogaevsky

Currently the `rust-windowing` organization has three "assets":
1. The [GitHub organization](https://github.com/rust-windowing) and all repositories under it.
2. The [crates on `crates.io`](https://crates.io/teams/github:rust-windowing:publishers).
3. The Matrix ["Space"](https://matrix.to/#/#rust-windowing:matrix.org) and [room](https://matrix.to/#/#winit:matrix.org).

**These are valuable, and we must ensure that the right people have access to them!**

In the past we've had to change Matrix channel because the original owner disappeared, which was bad, and I'd very much like that to not happen again! Also, it's a hassle to release new versions, the `winit` maintainers often need to ping an admin to do so. Of course, we can't just give everyone administrator rights, we have a responsibility to ensure that malicious code is not published to our crates, and hostile takeovers [have been seen in open source before](https://en.wikipedia.org/wiki/UBlock_Origin) (I understand that this could be seen as an attempt to do so, to alleviate such concerns I have left myself out of receiving admin rights).

Currently, @francesca64 is the only really active GitHub "Owner" and @maroider and @vberger are the only admins on Matrix. I have written a few suggestions below for how we could improve this situation.

Note: I don't really follow what's happening over at [`glutin`](https://github.com/rust-windowing/glutin) and [android-ndk-rs](https://github.com/rust-windowing/android-ndk-rs), but they're of course also affected by this, so feel free to state if you think they need something else!

### Suggestion 1

Promote the following people to "Owner" (GitHub org.), "Owner" (`crates.io`) and "Administrator" (Matrix Space & rooms):
- @francesca64: iOS maintainer, old n' trusty (currently GitHub owner)
- @msiglreith: Very active, Windows and Android maintainer
- @kchibisov: Very active, Wayland maintainer
- @maroider: Very active, soon to be [paid for working on `winit`](https://github.com/rust-windowing/winit/issues/1174#issuecomment-1150608443) (might help you setting up sponsoring for the `rust-windowing` organization directly?)

### Suggestion 2

Demote the following people that doesn't really seem to need GitHub "Owner" permissions to "Member" (all mentioned in the [Hall of Champions](https://github.com/rust-windowing/winit/blob/master/HALL_OF_CHAMPIONS.md)). I mean no offence by any of this, just wanted to take this opportunity to clean up admin rights from uninterested people, please do state if you would like to retain such permissions:
- @Osspial?
- @tomaka?
- @vberger?

### Suggestion 3

Change the "Publishers" team (doesn't have the right to add/remove people/teams from a crate, only the right to push/yank a package) so that it consists of:
- @francesca64
- @msiglreith
- @kchibisov
- @maroider
- @dvc94ch (maintains `ndk-*` packages)
- @MarijnS95 (same ^)
- @Lokathor (maintains `raw-window-handle`)

### Suggestion 4

Policy-wise, give trusted maintainers admin rights of these things a bit more quickly in the future (of course still a balancing act). Maybe @ArturKovacs?

---

EDIT: Added @dvc94ch and @MarijnS95 to Publishers

**Comment by vberger** [comment]
Given I've basically stopped all involvement with the winit project, it seems natural to see my admin rights removed.

**Comment by kchibisov** [comment]
I can't say more about matrix, but in general I do agree about the proposal in general.

In glutin land I feel like I was mostly the only one there, but in a more of bug fixing mode, though, we likely to rewrite it soon to be winit independent.

In general I do like when permissions are restricted and not given to the whole system, so certain folks could be limited to the projects they are working on, like raw-window-handle or android-ndk-rs, etc.

I agree with owners you've listed. In addition I'd change access for:  

@dvc94ch - limit to android-ndk-rs?
@Lokathor - limit to raw-window-handle.

Long gone developers I'd likely remove access from, given that there're no signs of them being active torwards winit.

@vbogaevsky - old macOS maintainer, haven't seem them for ages.
@goddessfreya - seems like they are gone, hope they are doing fine.
@tomaka - not sure they are interested in glutin/winit anymore, so not sure why keeping access.
@vberger - they explicitly step away from winit, though they are still around to ask questions.
@murarth - also looks like they are away for a long time.
@Osspial - haven't seen any sign from them for ages.

And I don't know anything about the following folks: @adamnemecek @mb64 @mitchmindtree

Also, I'd also remove everything related to publishing on CI. I think that owners should do that, so there will be more attention to releases itself and the rights won't be bypasses.

So the crates.io access should be limited to owners, so they can release everything under winit umbrella. In certain projects like android-ndk-rs they could have local folks to make releases, but in general it should protect unintended releases or so.

**Comment by dvc94ch** [comment]
Limiting publishing rights seems a bit weird, given that the issue with winit is to few releases not too many. @MarijnS95 and I should retain publishing right for android-ndk-rs at least.

**Comment by madsmtm** [comment]
I agree with everything you said @kchibisov (modulo the CI part, don't have an opinion here), though not sure we can actually change how the publishing work that way since GitHub teams can't add/remove other teams to/from crates, and @tomaka is the only "human owner" on most of these crates.

**Comment by MarijnS95** [comment]
Having publishing rights for `android-ndk-rs` may be nice. We currently have this arranged through our CI but it publishes under the name of @francesca64 (same for `winit` and `glutin`) which may seem odd when there has been no direct involvement in that particular release. I'm also helping out @kchibisov with Android support for `glutin`, maintaining review/merge rights weren't at stake but mentioning it just to be sure :)

Other than that, being able to yank a crate in the event that something wrong was published seems useful, but it's a non-issue if the publishers are many and easily reachable (ie. [the publishers team](https://github.com/orgs/rust-windowing/teams/publishers)).

I'm on board with the idea of reducing permissions for inactive "veteran" contributors, especially when their GitHub profile has gone stale (hope they're all-right though, just moved on :crossed_fingers:) just in case their account gets compromised.

**Comment by mitchmindtree** [comment]
> And I don't know anything about the following folks: ... @mitchmindtree

I used to contribute in the very early days, but haven't for quite a while. I still regularly use `winit` via [`nannou`](https://github.com/nannou-org/nannou), and it's possible I'll continue contributing issues and PRs in the future, though I don't need any special privileges to do so.

In general, very happy to see a review of the winit permissions/ownership.

**Comment by madsmtm** [comment]
I think interested parties have had enough time to give input.

@vberger or @francesca64, would one of you mind giving @kchibisov, @msiglreith and @maroider "Owner" access to the organization? Then you may leave it to one of them to implement the rest of the changes.

**Comment by francesca64** [comment]
@madsmtm done! Thanks so much for organizing all of this!

**Comment by maroider** [comment]
<details>
<summary>
Obligatory gif
</summary>

![](https://c.tenor.com/jQHdFftrgwMAAAAC/power-unlimited-power.gif)
</details>

**Comment by madsmtm** [comment]
I should note that I ended up getting admin rights as well, but I guess I'll keep 'em, if I wanted to do bad with it, the damage would already be done

**Comment by madsmtm** [comment]
Okay, I've cleaned things up, including removing extern contributors, the remaining situation is as follows (to the other maintainers, feel free to change parts of the setup you don't like):

Owners:
- @francesca64
- @maroider
- @msiglreith
- @kchibisov
- @madsmtm

Write permissions to `raw-window-handle`:
- @Lokathor

Write permissions to `winit`:
- @ArturKovacs

Write permissions to `glutin`:
- @MarijnS95

Write permissions to `android-ndk-rs`:
- @dvc94ch
- @MarijnS95

I unfortunately can't make publisher teams more specific, since only humans (not teams) have admin rights to crates, so most of these people have publishing rights as well.

I'm bound to have made a mistake somewhere, please, feel free to state if you would like access to something!
