### ISSUE TITLE
MainEventsCleared event received while key events still queued.

### ISSUE THREAD

**Issue by John-Nagle** [rust-windowing/winit#2320]
I have a game-type application which uses Rend3 and Winit. It's mostly running well, but there are some performance problems which sometimes show down the frame rate. The arrow keys move the viewpoint, and so, holding down an arrow key produces continuous motion. Redraws only when **Event::MainEventsCleared** is received. Normal game behavior.

Mostly this works fine. But sometimes, the player's viewpoint keeps moving for a second after they let up on the arrow key. This indicates keyboard events were still in some queue even when MainEventsCleared is received. if the frame rate drops below the keyboard repeat rate, there's a problem.

The documentation seems to indicate that the queue should be empty when MainEventsCleared is received. So this doesn't seem right.

* Linux 20.04 LTS. 
* Winit 0.26.1

**Comment by kchibisov** [comment]
Just in general, you should draw on `RedrawEventsCleared`.

**Comment by John-Nagle** [comment]
> Just in general, you should draw on `RedrawEventsCleared`.

Ah. that seems to help.Thanks.

For games, the documentation suggests otherwise: https://docs.rs/winit/latest/winit/event/enum.Event.html#variant.MainEventsCleared

**Comment by John-Nagle** [comment]
Nope, didn't actually fix it. 

It looks like I can reproduce it with my

https://github.com/John-Nagle/render-bench

which is a test case for a different problem. I can have to make a branch of that to get a clear example.
Is that needed?

**Comment by kchibisov** [comment]
Are you using Wayland or X11. And are you using vsync?

**Comment by MarijnS95** [comment]
> Linux 20.04 LTS.

Ubuntu?

**Comment by John-Nagle** [comment]
> Ubuntu?

Yes.

> Are you using Wayland or X11

Type=x11

> And are you using vsync?

Not me explicitly, but Rend3 or wgpu probablly are, since they reach but do not exceed 60 FPS.

> 

Thinking about this, is it reasonable to expect winit to work when refresh is so slow that key repeat is faster?

**Comment by kchibisov** [comment]
no `MainEventsCleared` anymore.
