### ISSUE TITLE
Duplicate device events on X11

### ISSUE THREAD

**Issue by maroider** [rust-windowing/winit#2332]
I've begun to experience consistently duplicated device events for both my keyboard and mouse on X11, and I've tracked down the PR that introduced this bug: #2195. The events are somehow *completely* identical, even down to the device id, which seems *very* strange to me.

I tried to check if it is a known issue with X.Org, but their GitLab instance refuses to serve a working website, and I spent some time trying to fix it on my own to no avail.

cc @chrisduerr

**Comment by kchibisov** [comment]
@maroider Could you change https://github.com/rust-windowing/winit/blob/9e6f666616341ddd76fc61c6a0ed8dcbf3392a28/src/platform_impl/linux/x11/mod.rs#L558 to `XIAllMasterDevices`?

**Comment by kchibisov** [comment]
You could send a patch if you feel like or I'll do that this evening.

**Comment by maroider** [comment]
Do I just merge it since it's so tiny, or?
