### ISSUE TITLE
Mac: WindowBuilder::with_position() places window incorrectly when using PhysicalPosition

### ISSUE THREAD

**Issue by tronical** [rust-windowing/winit#2355]
When trying to place a window at a specific physical position with `WindowBuilder` on macOS, the window appears at what looks like the wrong position.

The following patch reproduces this for me on macOS:

```patch
diff --git a/examples/window.rs b/examples/window.rs
index 23a633d2..9a74445c 100644
--- a/examples/window.rs
+++ b/examples/window.rs
@@ -14,6 +14,7 @@ fn main() {
     let window = WindowBuilder::new()
         .with_title("A fantastic window!")
         .with_inner_size(winit::dpi::LogicalSize::new(128.0, 128.0))
+        .with_position(winit::dpi::Position::new(winit::dpi::PhysicalPosition::new(500, 500)))
         .build(&event_loop)
         .unwrap();

```

Using the free ruler app and counting the pixels, the window appears at 250, 250 on my screen, when it should be 500, 500.

**Comment by kchibisov** [comment]
Are you sure that your pixel counting application counts not points, but pixels? Since macOS has scaling 2 by default, so 250 logical pixels is 500 physical, so it seems like winit places it correctly?

**Comment by tronical** [comment]
Visually, in the ruler app, the window appears at 250/250 when specifying 500/500 as physical position (as per above patch). When using 500/500 but LogicalPosition then it appears at 500/500 per ruler.

So it looks like to me the two are swapped (given the scale factor of 2).

**Comment by kchibisov** [comment]
I mean are you sure that your ruler is using physical pixels and not logical ones, hence it's macOS. So the right side of the screen is actually a 2560 or whatever resolution you have.

**Comment by tronical** [comment]
You're correct, I was measuring logical pixels. Apologies - seems winit is correct :)
