### ISSUE TITLE
[Wayland] Fullscreen change is dropped when exiting event loop too early (using run_return)

### ISSUE THREAD

**Issue by exoticorn** [rust-windowing/winit#2386]
Version: 0.26.1
Backend: Wayland

See this minimal repro example: [winit-fullscreen-repro.zip](https://github.com/rust-windowing/winit/files/9154740/winit-fullscreen-repro.zip)

This example repeatedly calls `run_return` until the window is closed. `ControlFlow::Exit` is set on every `RedrawEventsCleared`. When the `F` key is pressed, the program attempts to toggle the fullscreen mode, however `set_fullscreen` has no observable effect. Even `window.fullscreen()` continues to return `None`.

When passing `--workaround` to the program, it will only set `ControlFlow::Exit` once `window.fullscreen()` matches the fullscreen mode that was requested with `window.set_fullscreen()`. With this workaround toggling fullscreen works as expected.

On X11 setting the fullscreen mode works without the workaround.

**Comment by kchibisov** [comment]
Could you try the latest master?

**Comment by exoticorn** [comment]
Good point, I should have tried that earlier. On master, fullscreen switching works as expected without any workaround.
