### ISSUE TITLE
Wayland support for `set_visible`?

### ISSUE THREAD

**Issue by flukejones** [rust-windowing/winit#2388]
Apologies, this is my first foray in to use of winit via egui. I'm in need of `set_visible` for an app that can run in the background - but this feature doesn't work on wayland.

Is there any plan to add support for `set_visible` in wayland?

**Comment by notgull** [comment]
We should be able to use [`set_hidden`](https://docs.rs/smithay-client-toolkit/latest/smithay_client_toolkit/window/trait.Frame.html#tymethod.set_hidden) in order to implement this.

**Comment by maroider** [comment]
What sort of application are you making? As far as I'm aware, you won't get much of any input events from Winit on Wayland if your window isn't focused (or visible, even).

**Comment by rdrpenguin04** [comment]
The goal is to be able to hide the window and show it later from a tray icon click without entirely restarting the program

**Comment by kchibisov** [comment]
>We should be able to use [set_hidden](https://docs.rs/smithay-client-toolkit/latest/smithay_client_toolkit/window/trait.Frame.html#tymethod.set_hidden) in order to implement this.

No that's irrelevant, decorations have nothing to do with that.

>The goal is to be able to hide the window and show it later from a tray icon click without entirely restarting the program

From what I know this is usually done by destroying the window and creating it over on reaction to some dbus event. The only way to make window invisible on Wayland is by dropping it and creating later on. There's no way to do it differently, sorry.

**Comment by tronical** [comment]
> From what I know this is usually done by destroying the window and creating it over on reaction to some dbus event. The only way to make window invisible on Wayland is by dropping it and creating later on. There's no way to do it differently, sorry.

It seems that there is another way. Qt folks implemented this in https://bugreports.qt.io/browse/QTBUG-125592 / https://codereview.qt-project.org/c/qt/qtwayland/+/583059 by what I think is this part of the spec:

> If wl_surface.attach is sent with a NULL wl_buffer, the following wl_surface.commit will remove the surface content.


Would you be open to this approach? (I might volunteer to try to implement this, if you consider it feasible)

**Comment by kchibisov** [comment]
You can already do so by destroying and recreating the window, since it's effectively it, you can not do that transparently, since you basically recreate the window.

**Comment by tronical** [comment]
Ahh, do you mean the application could do those attach/commit calls behind some wayland `#[cfg]`?

Do I understand correctly that you'd prefer the application do that instead of doing that behind `set_visible`?

**Comment by tronical** [comment]
I think a difference between dropping the `winit::window::Window` and supporting `set_visible` is that in the former case the application needs to do additional book-keeping to maintain state (title, etc. - everything in WindowAttributes), in the latter case winit takes care of that. This affects the complexity of the application code to deal with this *just* for Wayland.

**Comment by kchibisov** [comment]
Well, keep in mind that wayland semantic of set_visible is very different, and if you by any chance draw to that hidden window, your entire app will get killed by compositor, so I do believe that if user/toolkit manages it themselves is a bit better, winit can not really prevent users from it.
