### ISSUE TITLE
winit picking up strange version of raw-window-handle on Windows

### ISSUE THREAD

**Issue by buzmeg** [rust-windowing/winit#2389]
For some reason that I can't figure out, winit 0.26.1 seems to be picking up raw-window-handle 0.4.3 instead of 0.5.0 on Windows.  This is wreaking all kinds of havoc when rust tries to resolve things.

I don't see the same behavior on Linux where 0.5.0 does seem to get picked up and everything works.

It's very strange and I don't have a nice minimal case yet.  Sorry.

**Comment by kchibisov** [comment]
Make sure you are using winit master, since the raw window handle v0.5.0 is only present there.

**Comment by buzmeg** [comment]
This seemed to have something to do with build tools on Windows.  I had to do a bunch of upgrading to make Rust builds on a lot of things consistent.  

I can't seem to verify that this is broken or fixed anymore.  So, I'm closing.  I'll file again if I see something.

Thanks.
