### ISSUE TITLE
`wasm-unknown-emscripten` support

### ISSUE THREAD

**Issue by makspll** [rust-windowing/winit#2391]
I know this crate swapped completely to `wasm-unknown-unknown` , but are there any plans to bring back support for that target?

I am coming from: https://github.com/khvzak/mlua/issues/23,

Providing such support would bring WASM lua scripting one step closer to reality!

**Comment by maroider** [comment]
> are there any plans to bring back support for that target

Not really, no. We don't even have a maintainer for the WASM backend, so I don't think we'll be adding back emscripten support any time soon.

**Comment by makspll** [comment]
Alright, that's good to know, will have to explore other options!
