### ISSUE TITLE
Scaling is far too large on Steam Deck desktop mode (X11)

### ISSUE THREAD

**Issue by mtkennerly** [rust-windowing/winit#2401]
This was reported by some users in https://github.com/mtkennerly/ludusavi/issues/91, and @psymin helped by reproducing it with Winit's basic `window` example (https://github.com/mtkennerly/ludusavi/issues/91#issuecomment-1197455159) using Winit 0.26.1.

The Steam Deck's desktop mode uses X11. In comparison, "game mode" uses Wayland and scales correctly. The device has a resolution of 1280x800.

As a copy from the comment linked above, here's how the `window` example looks (transparent on the left), taking up almost half of the screen width despite setting an inner size of merely `winit::dpi::LogicalSize::new(128.0, 128.0)`:

> ![image](https://user-images.githubusercontent.com/4934192/181396815-ce3b2a0b-58b5-427b-8d1c-2ccdeb25aa2c.png)

Log: [window-output.log](https://github.com/rust-windowing/winit/files/9204401/window-output.log)

```
2022-07-27 16:46:47,080 TRACE [mio::poll] registering event source with poller: token=Token(0), interests=READABLE
2022-07-27 16:46:47,083 INFO  [winit::platform_impl::platform::x11::window] Guessed window scale factor: 4.5
2022-07-27 16:46:47,083 DEBUG [winit::platform_impl::platform::x11::window] Calculated physical dimensions: 576x576
```

**Comment by kchibisov** [comment]
Well, you can enforce the scaling with `WINIT_X11_SCALE_FACTOR=1` or use the `Xft`, nothing winit can help here if the driver reports weird scale and monitor sizes.

**Comment by notgull** [comment]
How do normal X11 programs get around this?

**Comment by kchibisov** [comment]
They always use 1 as scaling and don't try to do anything.

**Comment by mtkennerly** [comment]
> nothing winit can help here if the driver reports weird scale and monitor sizes.

Based on the "guessed" log message, I think Winit's doing the XRandR calculation here, right? The Steam Deck is 1280x800 at just 7", and I wasn't sure if Wint's XRandR logic might be more geared for traditional desktop sizes than mobile sizes.

Would it be feasible to allow individual programs to skip the XRandR logic and leave it at 1? Since the Steam Deck could be a significant part of my target audience, I'd rather default to 1 than have those users [see this](https://github.com/mtkennerly/ludusavi/issues/91#issuecomment-1195649095) if they forget to override the scale.

**Comment by maroider** [comment]
I think you can technically set the env var for your own process before initializing winit, but that's hardly an elegant solution.

**Comment by kchibisov** [comment]
In general I always wanted to gate randr calculation under a env variable and just default to 1 on X11, however I'm not sure that it's something we can change, given that some apps do rely on that sort of scaling.

**Comment by mtkennerly** [comment]
> I think you can technically set the env var for your own process before initializing winit, but that's hardly an elegant solution.

I wouldn't mind doing that, although I'd still like to respect `Xft.dpi` if it's set. What would you think of adding support for something like `WINIT_X11_SCALE_FACTOR=deferred:1` or `WINIT_X11_SCALE_FACTOR_DEFERRED=1`, that would only kick in right before the XRandR logic?

**Comment by sluedecke** [comment]
> I think you can technically set the env var for your own process before initializing winit, but that's hardly an elegant solution.

Indeed one can do that (my code is ugly, that must be because it is a hack ...):

```rust
use std::env;
fn check_for_steam_deck() {
    /*
    https://www.reddit.com/r/SteamDeck/comments/telfda/comment/i6pfkpz

    Just checked this again on the Deck that I finally received - looks like
    Valve does indeed fill the mainboard vendor and name with useful values -
    so you can just check /sys/devices/virtual/dmi/id/board_vendor and
    /sys/devices/virtual/dmi/id/board_name which are both readable without
    root and will contain "Valve" and "Jupiter" (which seems to be an
    internal code name for the Steam Deck).
    */

    if std::env::consts::OS != "linux" {
        return;
    }

    println!("Linux detected.");

    match fs::read_to_string("/sys/devices/virtual/dmi/id/board_vendor") {
        Err(err) => println!("Could not open /sys/.../board_vendor: {}", err),
        Ok(vendor) => {
            if vendor.trim() != "Valve" {
                println!("Board vendor is not Valve: {}", vendor);
            } else {
                match fs::read_to_string("/sys/devices/virtual/dmi/id/board_name") {
                    Err(err) => println!("Could not open /sys/.../board_name: {}", err),
                    Ok(board) => {
                        if board.trim() != "Jupiter" {
                            println!("Valve board, but not Jupiter: {}", board);
                        } else {
                            println!("Steam Deck detected, setting WINIT_X11_SCALE_FACTOR=1");
                            env::set_var("WINIT_X11_SCALE_FACTOR", "1")
                        }
                    }
                }
            }
        }
    }
}
```
