### ISSUE TITLE
init fails on x11 (winit 0.27)

### ISSUE THREAD

**Issue by rukai** [rust-windowing/winit#2402]
On the latest git master and in the recently released 0.27, when I run the window example via: `cargo run --release --example window`, it panics with:
![image](https://user-images.githubusercontent.com/5120858/181673665-cbdacdd5-2cd3-459d-bbc5-bedd870437b9.png)

0.26 did not have this issue

**Comment by kchibisov** [comment]
I can't repro that in neither XWayland nor in GNOME, what system are you using?

**Comment by kchibisov** [comment]
That's literally what changed by default. And instead of nothing we request `None`.

![Uploading picture.png…]()


So without extra logging from you it'll be impossible to fix it given that we're intentionally creating a context without any IME.

Please try altering the `create_none_ic` (to previous state) and check whether it still fails.

**Comment by kchibisov** [comment]
Could also try setting it to just `ffi::XIMPreeditNone`.

**Comment by kchibisov** [comment]
I've tried to repro it on ubuntu,fedora,gentoo, and arch. On different GNOME, i3 versions without any success, so without any extra information it would be really hard to make a proper fix.

**Comment by rukai** [comment]
I am on arch and i3 and I have some sort of IME setup from a while back that I dont remember what its called.

As suggested by you, it no longer panics when I make this change:
![image](https://user-images.githubusercontent.com/5120858/181860594-e0cf67fe-a910-4f85-90e5-123102681f4e.png)

**Comment by kchibisov** [comment]
Could you try setting just `ffi::XIMPreeditNone`? It seems like there`s no way to disable IME or the IME is sort of strange.

**Comment by rukai** [comment]
![image](https://user-images.githubusercontent.com/5120858/181861067-0b8a1ede-2401-45f3-9179-3eb6909630da.png)

**Comment by kchibisov** [comment]
Well, I guess we will tune the logic to handle a case when you can't disable IME for some wierd imes.

**Comment by kchibisov** [comment]
Could you try https://github.com/rust-windowing/winit/pull/2404 ?
