### ISSUE TITLE
Alt-space does not open the system menu on Windows

### ISSUE THREAD

**Issue by sshock** [rust-windowing/winit#2406]
On Windows I am unable to open the system menu with the keyboard shortcut alt+space.

Steps to reproduce:
* `cargo run --example window`
* Hold down Alt and hit Spacebar.

Expected results:
* It should show the system menu.

Actual results:
* It does not show the system menu.

You can open the system menu by clicking on the window's icon in the top-left corner, but not by pressing alt+space.  Being able to trigger it with alt+space is expected behavior for all well-behaved apps on Windows.

**Comment by ajtribick** [comment]
Looks like this is related to handling of the `WM_SYSKEYDOWN` and `WM_SYSCHAR` messages. According to [Microsoft's documentation](https://docs.microsoft.com/en-us/windows/win32/learnwin32/keyboard-input), these should be passed to `DefWindowProc`, as far as I can see this never happens for `WM_SYSCHAR` and only happens for `WM_SYSKEYDOWN` in the case of ALT+F4.

If I remove the handling of `WM_SYSKEYDOWN` and `WM_SYSCHAR` entirely by removing these cases from the `match` in `public_window_callback_inner`, the ALT+Space combination works again, but I believe this would also prevent the application from receiving ALT+{any key}.

**Comment by sshock** [comment]
Interesting.  If it's helpful and you want to send me a patch I could maybe help test whether or not it prevents the app from receiving any other alt combinations (I could test with alacritty).

**Comment by sshock** [comment]
Thanks!  Looking forward to seeing this in downstream project alacritty.
