### ISSUE TITLE
with_max_inner_size() not respected on Windows 10

### ISSUE THREAD

**Issue by buzmeg** [rust-windowing/winit#2408]
Even if I specify with_max_inner_size() with a PhysicalSize, Windows 10 will happily create a scaled window with more pixels than this (I bumped into this because I had with_max_inner_size() of 2048x2048 but created a window with 1920x1080 which Windows10 scaled 1.25x to (2400, 1350) and crashed my program).

There also seem to be some issues that resize will also allow the window to exceed with_max_inner_size().

Thanks.

**Comment by msiglreith** [comment]
thanks for the report, should be fixed with #2393
