### ISSUE TITLE
Volume buttons not working on Android?

### ISSUE THREAD

**Issue by Hoodad** [rust-windowing/winit#2432]
Hello!

I have done some investigation on the topic of volume buttons and why they are not working on Android. I thought it could be related to how types of input events was handled by `winit`'s Android implementation ([source](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/android/mod.rs#L465-L494)) but no. I also suspected it could be related to being in fullscreen mode but that does not appear to be it either.  Then I stumbled upon mention by @msiglreith in issue #2010 mentioning that some buttons are marked as handled. So I figure I post a question here and see if anyone has good ideas on where to start looking? 

I have tried using Android Studio and intercepting key events there and I was able to prevent the UI to appear. See comment in code below. However I'm not able to achieve similar things in Rust. 

```java
    public boolean dispatchKeyEvent(KeyEvent event){
        int keyCode = event.getKeyCode();
        if(event.getAction() == KeyEvent.ACTION_DOWN){
            switch (keyCode) {

                case KeyEvent.KEYCODE_VOLUME_UP:
                    return false;  // If changed to true the media volume button does not appear
                case KeyEvent.KEYCODE_VOLUME_DOWN:
                    return false;  // If changed to true the media volume button does not appear

                default:
                    return super.dispatchKeyEvent(event);
            }
        }
        return super.dispatchKeyEvent(event);
    }
```

Goal is to have the "media volume panel" appear when pressing the volume buttons, so that the application does not have to reimplement that UI and the volume should change according to the pressed buttons.

**Comment by msiglreith** [comment]
Hi, for volume buttons there is PR which would do this already https://github.com/rust-windowing/winit/pull/1919. In general as mentioned it would be probably good to expose some feedback option/filtering for these button events on Android.

**Comment by Hoodad** [comment]
Oh, I didn't see that PR only searched in issues 😢

That's about exactly the fix what I tried with no success, however looking again at my attempt I found the issue! Thanks now it works as expected 👍 

Closing this issue as the PR exists.
