### ISSUE TITLE
Wayland: always_on_top does not do anything

### ISSUE THREAD

**Issue by dit7ya** [rust-windowing/winit#2435]
https://github.com/rust-windowing/winit/blob/da2cef97a3e63b8f73512b2c0c8d42020b7123e6/src/platform_impl/linux/mod.rs#L471-L479

Can this be implemented, please?

**Comment by kchibisov** [comment]
This should go directly to wayland-protocols, nothing winit can do aboit it.

In general compositors provide a way to set window always on top, regular applications have no way of doing so on Wayland.
