### ISSUE TITLE
(L\R)Shift, (L\R)Ctrl, (L\R)Alt not repeating Pressed Event for held button

### ISSUE THREAD

**Issue by JMDowns** [rust-windowing/winit#2447]
When working with winit, I have noticed that the LShift, RShift, LAlt, RAlt, LCtrl, and RCtrl buttons do not repeat their pressed event when the button is held, unlike keys like W, A, S, D. After searching, I do not know if this is intentional, so I am reporting this as an issue. [Here](https://github.com/JMDowns/bad_keys_example) is an example of the issue. Run the project, press a key while focused on the window, and the console will print out the key and its state.

For reference, I am on Linux using X11. When I run this code on Windows, the buttons do repeat their pressed event.

**Comment by kchibisov** [comment]
Those keys should not repeat, if they repeat or not is platform specific behavior. Use `ModifiersChanged` event for them to track modifiers.

**Comment by JMDowns** [comment]
Cool beans, thank you!
