### ISSUE TITLE
New XIM composition support doesn't not correctly negotiate with input method

### ISSUE THREAD

**Issue by wengxt** [rust-windowing/winit#2448]
X input method may choose not to support all the input styles.

https://github.com/rust-windowing/winit/blob/fd72000a9a60f3ee647f6a9fd9cbba1eca383f6d/src/platform_impl/linux/x11/ime/context.rs#L289

Basically this line will make client always create an input context with preedit callback, which is not supported by input method.

The correct way to do this is to do GetIMValues first, to list all the supported style
https://www.x.org/releases/X11R7.6/doc/libX11/specs/XIM/xim.html#Getting_IM_Values

Then send over a style in XCreateIC that is supported by input method.

**Comment by kchibisov** [comment]
We try to pick method and fallback to other variant on failure if you look closely on the code. Using `GetIMValues` should help us here, but I'm not sure that it'll be any different in the end? It's hard to read through the issue in your tracker since I don't know chinise, but basically what issue we had that preedit was created, but wasn't sent at all. I had expectation that I'd get `NULL`, like with some other IMEs, hence the fallback we have https://github.com/rust-windowing/winit/blob/fd72000a9a60f3ee647f6a9fd9cbba1eca383f6d/src/platform_impl/linux/x11/ime/context.rs#L302.

**Comment by wengxt** [comment]
@kchibisov there are 3 different issues. I'm just trying point one of them in this report.

The actual issue
1. winit doesn't use get im values, so always send the create ic (***This is what this issue is about***)
2. fcitx5 doesn't really check the ic style matches the one it supports and always accept it. (this is what need to be fixed on fcitx5 side and I submit a fix https://github.com/fcitx/fcitx5/commit/1d69497480c7d0128dc4c6f7d1ba1270890b7a29)
3. alacritty+winit still  somehow doesn't display preedit <- This is what still need to be investigated and probably belongs to a different issue report. I'm still investigating this.

**Comment by kchibisov** [comment]
Yeah, I haven't tested fcitx at all during development and mostly used ibus, since that is what gnome uses, and I'm on Wayland and here we have a bit different IMEs and a bit better docs for all of that.

I'll look into fixing this on X11 when I have time, thx for you feedback.

**Comment by wengxt** [comment]
Also, I don't think if there's any XIM server  implementation send over a XIMError to make XCreateIC fail. The two state of art implementation (IMdkit which is used by xlib based one, used by fcitx4/ibus), xcb based on I created for fcitx5 https://github.com/fcitx/xcb-imdkit/, doesn't reject the style if it doesn't match the announced ones, which means GetIMValues should always be used.

The else branch "create_none_ic" will never be executed in real world.

**Comment by wengxt** [comment]
> > The else branch "create_none_ic" will never be executed in real world.
> 
> It actually was executed, since adding it was a bug fix, see:
> 
> #2402

ah, uim..  never know they're using their own xim implementation.. nice to know :)
