### ISSUE TITLE
Support XIMPreeditPosition for XIM

### ISSUE THREAD

**Issue by wengxt** [rust-windowing/winit#2449]
Right now, only XIMPreeditCallbacks and XIMPreeditNothing is supported, but XIMPreeditPosition is also a good candidate to allow XIM to report spot rect.

In Xlib implementation, it doesn't send spot rect if the IC style doesn't use XIMPreeditPosition (Even if you try to send it over via Xlib API). XIMPreeditPosition should be preferred over XIMPreeditNothing.

**Comment by kchibisov** [comment]
You'd be surprised, but we've been using `Nothing` for a very long time actually and it was setting the spot with xlib on every implementation I'm aware of, maybe you have a wrong memory that spot won't be sent, since it clearly is.

**Comment by wengxt** [comment]
ah, you're right. I kinda confused because of the usage of PreeditCallbacks.
