### ISSUE TITLE
Formalize release process

### ISSUE THREAD

**Issue by kchibisov** [rust-windowing/winit#2454]
winit should have a reliable not blocking way to handle releases and patch releases.-

We have something like that formally documented in alacritty and I'd suggest that we can port it with adjustments into winit. See https://github.com/alacritty/alacritty/blob/master/CONTRIBUTING.md#release-process.

**Comment by madsmtm** [comment]
I think it's a good idea to have a process for this, two quick notes:
- Alacritty is an application, `winit` is a library, so things are different
- The release candidate stuff is a bit overkill for my taste
- Having a newer version field (`0.x.0-dev`) on `master` than is used in libraries would be annoying for me; I often change something in `winit` and use a `patch.crates-io` to test that out in another crate that uses `winit`

**Comment by rib** [comment]
> On master, the version is bumped to 0.3.0-dev and the -dev suffix is removed from the 0.2.0-dev changelog

This was a practice I'd become quite used to for non-Rust projects and it seems like it should be good but as @madsmtm suggests, it doesn't really seem to be common practice for Rust projects and I also often use `[patch]` to redirect dependencies to some git master branch which is more convenient if the version in git master still matches the last release.

**Comment by kchibisov** [comment]
>The release candidate stuff is a bit overkill for my taste

Yeah, we don't need them. At least now.

>Having a newer version field (0.x.0-dev) on master than is used in libraries would be annoying for me; I often change something in winit and use a patch.crates-io to test that out in another crate that uses winit

That's something that is arguable. The problem I'm trying to solve is having a way to make patch releases without holding master. So the version we're using on master doesn't make any sense, since it doesn't represent the latest release.
