### ISSUE TITLE
[Bug] iOS platform crash if swipe from bottom up and root cause(maybe)

### ISSUE THREAD

**Issue by shuoli84** [rust-windowing/winit#2471]
# Bug and trouble shooting
I've been debugging the crash bug for hours. It was reported by others and had a quick fix by setting ScreenEdge::ALL. Since the crash is reproducible, so I tried to tackle it down or at least find the root cause, I think I got something.
Currently, we create UIWindow first, then run UIApplicationMain, which is problematic, since UIApplicationMain actually setup some global state that UIKit requires, like following
```
Stack:
[UIGestureEnvironment init]
[UIApplication init]
UIApplicationInstantiateSingleton
_UIApplicationMainPreparations
UIApplicationMain
```
UIGestureEnvironment is also a singleton which is inited and stored inside UIApplication. Also, it is stored in each UIGestureRecognizer instance if it is already created. And UIGestureRecognizer is created when we create UIWindow, which means at that time, the global didn't created, so all the recognizer with `_gestureEnvironment` property as nil. 

When ScreenEdge preference is 0, it triggers some logic of delay touch handling, and in that code path, it read the property as nil,  which crashed when add into a nsarray.

# How to fix:
UIWindow/UIView should be created by method on ApplicationDelegate, since UIApplicationMain will never return.

# Other
Some evidence (crashed is the bevy_ios_example. good is a normal created ios app):
```
crashed:
(lldb) po ((_UISystemGestureGateGestureRecognizer*)0x15fe115f0) -> _gestureEnvironment
 nil

Good
(lldb) po ((_UISystemGestureGateGestureRecognizer *)0x101808750) -> _gestureEnvironment
<UIGestureEnvironment: 0x281ee4af0>
```
Crashed
<img width="567" alt="Screen Shot 2022-09-04 at 22 25 53" src="https://user-images.githubusercontent.com/3402035/188318528-c15a3064-82e5-4b8f-b6ba-e56f82c318e5.png">

Good call stack
<img width="523" alt="Screen Shot 2022-09-04 at 22 24 46" src="https://user-images.githubusercontent.com/3402035/188318488-71aedbc3-4976-45c7-8c2b-5291d8159af9.png">

**Comment by shuoli84** [comment]
Good full stack, we can see the window is created inside UIApplicationMain. 

<img width="560" alt="Screen Shot 2022-09-04 at 22 37 27" src="https://user-images.githubusercontent.com/3402035/188319033-d0d60658-aa06-4c9b-8ecf-0b76a22eb11d.png">

Also link to original issue: #1705

**Comment by maroider** [comment]
Please post this under #1705, since it looks like all you've done is dig deeper into a potential root cause (which we really appreciate that you did). If you still feel this is a different enough issue, feel free to re-open this issue.

**Comment by shuoli84** [comment]
@maroider sure
