### ISSUE TITLE
Running winit 0.26.0+wgpu0.13 on android giving runtime errors

### ISSUE THREAD

**Issue by ElhamAryanpur** [rust-windowing/winit#2472]
I've been trying to port my [engine](https://github.com/ElhamAryanpur/BlueEngine) to android, and in the process I've tries a looot of ways and bugfixes for winit to at least show something. It does build, but error after error... Stumbled across [this](https://github.com/andraantariksa/wgpu-winit-android-example/blob/master/v0.13) which did work and showed a triangle, however following it step by step and line by line... still gave an error I couldn't fix.

The error was stating `'Cannot get the native window, it's null and will always be null before Event::Resumed and after Event::Suspended. Make sure you only call this function between those events.'`. I had this:

```rust
                Event::Resumed => {
                    renderer.surface = Some(unsafe { renderer.instance.create_surface(&window) });
                    renderer
                        .surface
                        .as_ref()
                        .unwrap()
                        .configure(&renderer.device, &renderer.config);
                }
                Event::Suspended => {
                    renderer.surface.take();
                }
```
yet still was getting the error... I am really not sure what's the issue. Also for the record, the changes I've been adding for port aren't on the github, in my local changes the swapchain is only created on Resumed similar to the example I've seen, and the window is only called there... yet I'm still getting the runtime error.

If anyone can guide me towards the right direction, or help me out, I would really really appreciate it!

Thanks

**Comment by ElhamAryanpur** [comment]
still no success

**Comment by ElhamAryanpur** [comment]
updated to winit 0.27.2, same error. Here's the whole error log:

 λ adb logcat RustStdoutStderr:D '*:S'                
--------- beginning of main
09-07 00:34:59.151 16803 16828 I RustStdoutStderr: thread '<unnamed>' panicked at 'Cannot get the native window, it's null and will always be null before Event::Resumed and after Event::Suspended. Make sure you only call this function between those events.', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/android/mod.rs:598:13
09-07 00:34:59.151 16803 16828 I RustStdoutStderr: stack backtrace:
09-07 00:34:59.163 16803 16828 I RustStdoutStderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
09-07 00:36:16.471 17175 17202 I RustStdoutStderr: thread '<unnamed>' panicked at 'env_logger::init should not be called after logger initialized: SetLoggerError(())', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/env_logger-0.9.0/src/lib.rs:1158:16
09-07 00:36:16.471 17175 17202 I RustStdoutStderr: stack backtrace:
09-07 00:36:16.472 17175 17202 I RustStdoutStderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
09-07 01:16:33.537 23526 23574 I RustStdoutStderr: thread '<unnamed>' panicked at 'wgpu error: Validation Error
09-07 01:16:33.537 23526 23574 I RustStdoutStderr: 
09-07 01:16:33.537 23526 23574 I RustStdoutStderr: Caused by:
09-07 01:16:33.537 23526 23574 I RustStdoutStderr:     In Device::create_texture
09-07 01:16:33.537 23526 23574 I RustStdoutStderr:       note: label = `Depth Buffer`
09-07 01:16:33.537 23526 23574 I RustStdoutStderr:     Dimension X is zero
09-07 01:16:33.537 23526 23574 I RustStdoutStderr: 
09-07 01:16:33.537 23526 23574 I RustStdoutStderr: ', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.13.1/src/backend/direct.rs:2391:5
09-07 01:16:33.537 23526 23574 I RustStdoutStderr: stack backtrace:
09-07 01:16:33.717 23526 23574 I RustStdoutStderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by msiglreith** [comment]
Hello,

without source code it's more of random guessing given the other example works.
- verify there is no other call which queries the surface (e.g on wgpu adapter selection)
- check the other errors in your log: one seems to be related to the setting up `env_logger` the other due passing invalid values on depth buffer creation
- the entries in the log are 40min aparts, if necessary try manually opening the application in case it's done via `cargo apk run` and verify the log output

**Comment by ElhamAryanpur** [comment]
Hello!

I did provide the [source](https://github.com/ElhamAryanpur/BlueEngine) above too.

1) yes the surface is only in the Resumed, for adapter following the example it's None.

2) yeah for normal one I had only the middle error of it not being available until Resumed.

3) I'm not sure, will try. I'm now trying to log per part to debug where it gives the error to find the exact part.

Thank you for the response,

**Comment by msiglreith** [comment]
I just threw together some parts with an external example based on the triangle shape and seems to run on my device at least: https://github.com/ElhamAryanpur/BlueEngine/commit/a24b33754478a5bf64e38db697a292b7fcfe9e3d

**Comment by ElhamAryanpur** [comment]
Ooooooooooooooooooooooooo, I did all that too except one part, do you see a triangle on the screen? I see u commented out the triangle code so was curious

**Comment by msiglreith** [comment]
Yes, as mentioned I put it into a separate crate
```
use blue_engine::{
    header::{Engine, ObjectSettings, WindowDescriptor},
    primitive_shapes::triangle,
};

#[cfg_attr(
    target_os = "android",
    ndk_glue::main(backtrace = "full", logger(level = "debug"))
)]
fn main() {
    println!("start");
    let mut engine = Engine::new(WindowDescriptor::default()).expect("win");

    let _ = triangle(ObjectSettings::default(), &mut engine).unwrap();

    engine
        .update_loop(move |_, _, _, _, _| {})
        .expect("Error during update loop");
}
```

**Comment by ElhamAryanpur** [comment]
oh nice, building an apk with the changes u made

**Comment by ElhamAryanpur** [comment]
omg working, after some size fixes!!!!

Thank you so much! The only thing I was missing was on resize I still was using surface...

I'll try to write a blog or some docs on this, because the resources on mobile build is lacking a lot in general. Thank you again!

**Comment by MarijnS95** [comment]
> The only thing I was missing was on resize I still was using surface...

Would a `full` backtrace have helped you spot this issue, as suggested by the error message?

**Comment by ElhamAryanpur** [comment]
> > The only thing I was missing was on resize I still was using surface...
> 
> Would a `full` backtrace have helped you spot this issue, as suggested by the error message?

It could, but couldn't get a full backtrace build, idk why but cargo apk never builded full backtrace version. But the way I found the issue was by checking my changes against @msiglreith 's fork.
