### ISSUE TITLE
Add an interactive tests set

### ISSUE THREAD

**Issue by tomaka** [rust-windowing/winit#251]
One of the major problems of winit in general is the lack of precise API design, which in turn causes a lack of uniformity between platforms.

This can't really be solved with unit tests. If for example you want to test whether a window correctly appears, you would have to write platform-specific code in the test. Not only is it very annoying to do, but it also means that the tests wouldn't solve the problem of the lack of uniformity.

However I think we could add an interactive tests suit. The user would run a program, which spawns windows and asks the user whether some feature works, or asks the user to perform some actions like pressing a specific key or resizing the window. This program would be the same on all platforms, allowing one to quickly determine whether something works or doesn't work correctly on any given platform.

**Comment by daxpedda** [comment]
Closing in favor of #2866.
