### ISSUE TITLE
Failed to open fallback input method: ContextCreationFailed(Null)

### ISSUE THREAD

**Issue by lolicon0930** [rust-windowing/winit#2510]
### What happens
Restart fcitx5 cause Alacritty close.
### What should happen
Alacritty should not be closed.
### System
OS: Debian GNU/Linux bookworm/sid x86_64
Version: winit-0.27.3
Alacritty Version: alacritty 0.12.0-dev (e9ee8dc)
 cargo build with only X11 support
Display server: X11
Compositor: picom
WM: dwm
### How to reproduce the issue
I can post it again if needed, but probably not necessary.
https://github.com/alacritty/alacritty/issues/6370#issuecomment-1264634153

**Comment by lolicon0930** [comment]
Thanks, do I need to close this issue myself?

**Comment by kchibisov** [comment]
It'll be closed once the PR merges automatically. Do you have any difference before and after reload though? wrt preedit and such?

**Comment by lolicon0930** [comment]
I didn't find any other obvious problems.
