### ISSUE TITLE
macOS fullscreen toggle is broken

### ISSUE THREAD

**Issue by rofferom** [rust-windowing/winit#2520]
## Problem description

Mutiple toggle of fullscreen on macOS won't work:
```
.set_fullscreen(Some(window::Fullscreen::Borderless(monitor)))
.set_fullscreen(None)
.set_fullscreen(Some(window::Fullscreen::Borderless(monitor)))
```

The first and the second calls are working, but the last one does nothing.

## Analysis try

After a quick `git bisect`, it seems that #2458 (d67c9281) has broken the feature.

I put some logs to try to track what is happening, it seems to be because `WinitWindowDelegate` isn't called on `windowWillEnterFullscreen`, whereas `windowWillExitFullScreen` is called.

So this state is updated in `windowWillExitFullScreen` handler [full code here](https://github.com/rust-windowing/winit/blob/462bb4d3245d39f10dc3e0706cd6f892b8cd9e74/src/platform_impl/macos/window_delegate.rs#L242) :
```rust
shared_state.in_fullscreen_transition = true;
```

Then, `macos::UnownedWindow::set_fullscreen()` will return here ([full code here](https://github.com/rust-windowing/winit/blob/462bb4d3245d39f10dc3e0706cd6f892b8cd9e74/src/platform_impl/macos/window.rs#L775))
```rust
        if shared_state_lock.in_fullscreen_transition {
            // We can't set fullscreen here.
            // Set fullscreen after transition.
            shared_state_lock.target_fullscreen = Some(fullscreen);
            return;
        }
```

## Infos

* OS version: 12.6 (x64)
* SHA-1 used: 462bb4d3245d39f10dc3e0706cd6f892b8cd9e74

**Comment by madsmtm** [comment]
Good catch! I've put up a fix here: https://github.com/rust-windowing/winit/pull/2546

**Comment by rofferom** [comment]
Nice, thanks !

I took my some time to understand the patch :sweat_smile:
