### ISSUE TITLE
Can compatibility w/ `raw_window_handle` v0.4 be opt-in (or removed)?

### ISSUE THREAD

**Issue by noib3** [rust-windowing/winit#2523]
`raw_window_handle` v0.5.0 was released a few months ago and wgpu 0.14 now also uses 0.5.0. Can we remove the dependency or put it behind a `"raw_window_handle_04"` feature flag? Motivation: We use `cargo tree -d` in CI and building two versions of `raw_window_handle` is giving us problems.

Happy to send a PR if this is something you'd consider merging.

**Comment by kchibisov** [comment]
What kind of problems are you getting, I'm just curious.

**Comment by noib3** [comment]
Not problems in the code, just in the output of `cargo tree -d`.

**Comment by a1phyr** [comment]
This was fixed by #2601
