### ISSUE TITLE
feature: callback that is called when visibility of the window changes 

### ISSUE THREAD

**Issue by idipot** [rust-windowing/winit#2536]
I'd like to have a method which registers a callback that is called everytime the visibility of a window changes. 
Is it already possible? ( i couldn't find anything on how to do this)

**Comment by madsmtm** [comment]
Would [`WindowEvent::Focused`](https://docs.rs/winit/0.27.5/winit/event/enum.WindowEvent.html#variant.Focused) work for you?

**Comment by kchibisov** [comment]
That's not what focused is supposed to do, since it's about focus and not visibility. What they want is [`WindowEvent::Occulded`](https://docs.rs/winit/0.27.5/winit/event/enum.WindowEvent.html#variant.Occluded).

**Comment by kchibisov** [comment]
Be aware that minimized doesn't mean that the window isn't visible, we'd like to expose that state too, but it's something already tracked separately.
