### ISSUE TITLE
"Cannot get the native window" on android

### ISSUE THREAD

**Issue by Kirottu** [rust-windowing/winit#2542]
I have been trying to get an application to run on android, but anything I do seems to lead to that error. With eframe it crashes with that error and now with vulkano and winit it seems to crash at the point of starting the event loop. Here is the full error reported by logcat:
```
RustStdoutStderr: thread '<unnamed>' panicked at 'Cannot get the native window, it's null and will always be null before Event::Resumed and after Event::Suspended. Make sure you only call this function between those events.', /home/kirottu/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/android/mod.rs:840:13
```

**Comment by kchibisov** [comment]
>'Cannot get the native window, it's null and will always be null before Event::Resumed and after Event::Suspended. Make sure you only call this function between those events.',

Have you tried following the error and do what it tells you to do?

**Comment by Kirottu** [comment]
I do not manually get the native window, winit handles it all. Nor do I manually run any android related code at that stage. The project is basically an example project with some modifications, and I also reproduced the issue using a "pure" example project.

**Comment by kchibisov** [comment]
Then tell example to create winit window at the right place. If you want an example how to do android window look at https://github.com/rust-windowing/glutin/blob/master/glutin_examples/src/lib.rs . It has `android` example that shows how to start it.

**Comment by Kirottu** [comment]
Alright I finally got it working, thanks.
