### ISSUE TITLE
Side mouse buttons are recognized by MouseButton::Other(32) and MouseButton::Other(64) instead of an expected number

### ISSUE THREAD

**Issue by Satellile** [rust-windowing/winit#2562]
I expected the two common side mouse buttons (Mouse4 and Mouse5) to be referenced by MouseButton::Other(1) and MouseButton::Other(2) (or by 4 and 5), but they are currently referenced by MouseButton::Other(32) and MouseButton::Other(64).

I believe this is a relatively recent change (and perhaps unintended?), as I had been referring to them previously using 1 and 2 (in a Bevy 0.8 project).

**Comment by madsmtm** [comment]
Which operating system / display server protocol are you using?

**Comment by Satellile** [comment]
> Which operating system / display server protocol are you using?

I'm on Windows 10 (Education, Version 10.0.19045 Build 19045)

**Comment by madsmtm** [comment]
Good catch, I've opened a PR to fix this in https://github.com/rust-windowing/winit/pull/2565
