### ISSUE TITLE
Main thread cant capture keyboard input

### ISSUE THREAD

**Issue by KarryCharon** [rust-windowing/winit#2590]
# Main thread cant capture keyboard input
Platform: Windows11

See this code:
```rust
fn run(){
    let f = move || {
        let event_loop = EventLoop::new_any_thread();
        loop {};
    };
    std::thread::spawn(f);
}
```
Function run is running on sub thread, and can receive all events.
But main thread cant receive event after this!
Is there a way to pass sub thread events to main thread?
Or create event_loop without keyboard input capture?

**Comment by maroider** [comment]
Are you trying to send the `Event` enum to the main thread, or do you have a different mechanism in mind? If you're trying to pass along the `Event` enum, then the you can use `Event::to_static` to make it so you can send `Event` over a channel. Do note that this will discard any events with lifetimes (currently, that would only be `WindowEvent::ScaleFactorChanged`).

**Comment by KarryCharon** [comment]
> 

Blender has it's own event loop, and the rust function `run` is execute on blender's addon thread like this:
```python
def f():
    from . import renderer # this is a dll export by pyo3
    c = renderer.Render(width=800, height=600, dir=cur_dir)
    c.run() # this run function is export from rust by pyo3

# called by blender ui button
def run():
    Thread(target=f).start()
```
And I found no way to send Event from rust event_loop to blender event loop.
Now I change the `register_all_mice_and_keyboards_for_raw_input` function to ban KeyBoardInput manually:
```rust
// platform_impl/platform/raw_input.rs
pub fn register_all_mice_and_keyboards_for_raw_input(window_handle: HWND) -> bool {
    // RIDEV_DEVNOTIFY: receive hotplug events
    // RIDEV_INPUTSINK: receive events even if we're not in the foreground
    let flags = RIDEV_DEVNOTIFY | RIDEV_INPUTSINK;

    let devices = [
        RAWINPUTDEVICE {
            usUsagePage: HID_USAGE_PAGE_GENERIC,
            usUsage: HID_USAGE_GENERIC_MOUSE,
            dwFlags: flags,
            hwndTarget: window_handle,
        },
        // RAWINPUTDEVICE {
        //     usUsagePage: HID_USAGE_PAGE_GENERIC,
        //     usUsage: HID_USAGE_GENERIC_KEYBOARD,
        //     dwFlags: flags,
        //     hwndTarget: window_handle,
        // },
    ];

    register_raw_input_devices(&devices)
}
```
It works fine, but doesn't seem very friendly。。。haaaha

**Comment by KarryCharon** [comment]
On the other hand, I try some to_static method like this:
```rust
let f = move || {
    let mut event_loop: EventLoop<()> = EventLoop::new_any_thread();
    event_loop.run(|event, _, _| {
        event.to_static();
    });
};
```
But nothing to change...

**Comment by maroider** [comment]
> Blender has it's own event loop, and the rust function run is execute on blender's addon thread like this:

Ah, that certainly makes things more clear. The root cause would be a limitation of [`RegisterRawInputDevices`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerrawinputdevices)/`WM_INPUT`, which you seem to already have somewhat figured out

> Only one window per raw input device class may be registered to receive raw input within a process (the window passed in the last call to RegisterRawInputDevices). Because of this, RegisterRawInputDevices should not be used from a library, as it may interfere with any raw input processing logic already present in applications that load it.

To disable this, you need to disable winit's use of raw input entirely (there is currently no way to only disable raw keyboard events), which *should* be doable by calling `EventLoopWindowTarget::set_device_event_filter` with `DeviceEventFilter::Always`.

**Comment by KarryCharon** [comment]
@maroider 
Exciting. It works very well !
Gratitude expressed in words !
