### ISSUE TITLE
Draw using winit and glad rust

### ISSUE THREAD

**Issue by Anderson0xFF** [rust-windowing/winit#2595]
I've looked in several places for some way to create a context with winit, but nothing is documented.
Could someone leave a code example of how I can use Winit together with Glad, or any kind of OpenGL?
I don't want to depend on glutin, just use winit + opengl.

**Comment by kchibisov** [comment]
So you want OpenGL and you don't want glutin. Seems like you're out of luck.

But it seems like you don't understand how OpenGL works, OpenGL functions are completely useless unless you have context which you create with EGL/GLX/WGL. Then you use their helpers to get the addresses for the functions you get from the glad.

glutin is very lightweight crate that does all the EGL/GLX/WGL stuff, so you use gl_generator or whatever with the context you've got from gl platform.

**Comment by Anderson0xFF** [comment]
> So you want OpenGL and you don't want glutin. Seems like you're out of luck.
> 
> But it seems like you don't understand how OpenGL works, OpenGL functions are completely useless unless you have context which you create with EGL/GLX/WGL. Then you use their helpers to get the addresses for the functions you get from the glad.
> 
> glutin is very lightweight crate that does all the EGL/GLX/WGL stuff, so you use gl_generator or whatever with the context you've got from gl platform.

I am writing an engine, and window must support not only OpenGL, but also DX and Vulkan.
I understand how opengl works, I just don't understand how to use winit together with opengl.
What is the function to create a context in winit?

**Comment by kchibisov** [comment]
There's no, it's outsourced to glutin. You can mix glutin with vulkan,dx,without any issue.

**Comment by Anderson0xFF** [comment]
> There's no, it's outsourced to glutin. You can mix glutin with vulkan,dx,without any issue.

how can i create the context and load the opengl functions together with winit?
