### ISSUE TITLE
Raspberrypi support ?

### ISSUE THREAD

**Issue by Snowiiii** [rust-windowing/winit#2603]
Maybe its a good idea to add Raspberrypi support in winit,You can use/make a Rust wrapper for the [firmware](https://github.com/raspberrypi/firmware) and then do windowing Stuff with it like [SDL it does](https://github.com/libsdl-org/SDL/blob/main/src/video/raspberry/SDL_rpivideo.c)

**Comment by kchibisov** [comment]
Do you want the direct KMS stuff? Stuff like this could be used then https://github.com/rust-windowing/winit/pull/2272 ? But from what I see you mean some rpi specific stuff, which I'm not sure is a good idea to have support for upstream given how niche the platform is.
