### ISSUE TITLE
`set_minimized(false)` does not work on kde plasma when losing focus

### ISSUE THREAD

**Issue by SunDoge** [rust-windowing/winit#2606]
The minimum code is here:
https://gist.github.com/SunDoge/47b69bf1fa8177408804cfb60eb8c30a
Just press `m` and click other windows and wait 3 seconds. This function works fine on x11 gnome.

![Peek 2022-12-27 23-10](https://user-images.githubusercontent.com/16167062/209685887-f969bb58-44fe-4485-877e-1e4e05b76760.gif)

**Comment by kchibisov** [comment]
Maybe plasma preventing such behavior? winit just asks to minimize, wm can safely ignore. On i3 for example you can't ever minimize your window.
