### ISSUE TITLE
MacOS setting an ActivationPolicy prevent LSUIElement and LSBackground from functioning via editing Info.plist

### ISSUE THREAD

**Issue by gliheng** [rust-windowing/winit#261]
Hi, I'm trying to hide dock icon for my mac application. According to [this](https://stackoverflow.com/questions/620841/how-to-hide-the-dock-icon),
I should set `LSUIElement` in Info.plist to true, and it should work, but it is not.
Setting `LSUIElement` and `LSBackground` in Info.plist are both useless for winit apps.

Further investigation, revealed that winit set ActivationPolicy to regular on start. Hence dock icon is shown. Maybe it should leave it at its default?

I tried that approach. It works fine for packaged mac apps. (dock icon is hidden when LSUIElement is true, shown otherwise). Only dock icon is not shown when it's launched as unpackaged executable. Maybe we should give user an oppotunity to bypass this `setActivationPolicy` call?

**Comment by francesca64** [comment]
Is this covered by `os::macos::WindowBuilderExt::with_activation_policy`?

**Comment by Osspial** [comment]
Closing since there hasn't been any discussion on this and it seems that `with_activation_policy` would indeed solve this issue. If that isn't an accurate assessment of this, please feel free to re-open this for further discussion.

**Comment by purajit** [comment]
> Closing since there hasn't been any discussion on this and it seems that `with_activation_policy` would indeed solve this issue. If that isn't an accurate assessment of this, please feel free to re-open this for further discussion.

I think there is still some value to this issue. A user of an application that uses `winit` should still be able to set LSUIElement to get their desired behavior, versus having to ask each application developer to pipe the config through. I think it makes sense that winit should honor what's in the package manifest, unless the application is explicitly setting `activation_policy` on top of that. I'm willing to do some work to get a patch, if this approach is acceptable.

**Comment by purajit** [comment]
> I don't really want Winit to try to read the bundle information

Gotcha. I'll try to do some quick checks this weekend to see. Hopefully "only call `setActivationPolicy` if explicitly asked" works.

**Comment by Hacksore** [comment]
We are also looking into hiding the process from the dock. We are using [notan](https://github.com/Nazariglez/notan) which winit under the hood so once support is available in winit we'd have to add that functionally to notan.

<img width="741" alt="image" src="https://github.com/user-attachments/assets/7cf4cc81-e782-464d-af53-dddb7c8ef4b9">

FWIW We also tried setting it at runtime via FFI but it didn't work because I believe you can't do it when the window is already created?

**Comment by purajit** [comment]
Not setting it worked! Going to see how to best implement this.
