### ISSUE TITLE
set exclusive fullscreen mode causes panics on windows

### ISSUE THREAD

**Issue by xyning** [rust-windowing/winit#2620]
run the fullscreen example on latest master branch:
```
> cargo run --example fullscreen
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
     Running `target\debug\examples\fullscreen.exe`
Monitor: Some("\\\\.\\DISPLAY1")
Mode: 0x240 @ 0 mHz (1080 bpp)
Keys:
- Esc   Exit
- F     Toggle exclusive fullscreen mode
- B     Toggle borderless mode
- S     Next screen
- M     Next mode for this screen
- D     Toggle window decorations
- X     Maximize window
- Z     Minimize window
Setting mode: Some(Exclusive(VideoMode { size: (0, 240), bit_depth: 1080, refresh_rate_millihertz: 0, monitor: MonitorHandle(2690321) }))
thread 'main' panicked at 'assertion failed: res != DISP_CHANGE_BADMODE', src\platform_impl\windows\window.rs:524:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\fullscreen.exe` (exit code: 101)
```
regression comes from the windows crate (https://github.com/microsoft/windows-rs/issues/2138), the fix is still not released.
actually not a winit bug, but this should block https://github.com/rust-windowing/winit/pull/2600

**Comment by madsmtm** [comment]
This is an issue in `winit` `0.27.5` as well, so I block a new release on it. We can always update `windows-sys` in a patch release

**Comment by msiglreith** [comment]
I verified that it works again when patched with the git version, need to wait for a release now

**Comment by kchibisov** [comment]
@msiglreith could you provide that information upstream and probably open a follow up issue?

As you can see https://github.com/microsoft/windows-rs/issues/2138#issuecomment-1397151649 they are open to make a release, just need to prove that it works with the git version from what I can see. So you could open a PR against winit with your update to `git` version and point them to it showing before/after?

**Comment by msiglreith** [comment]
sure, I will open one in the evening
