### ISSUE TITLE
Query the currently focused display

### ISSUE THREAD

**Issue by fxdave** [rust-windowing/winit#2621]
I use X.Org, and I need a functionality for querying the focused display. My GUI is a daemon that shows up and hides. I need to show it up wherever my cursor is.

I can query the display setup with resolution.
I also need the cursor position, which is provided by this XCB function: https://www.systutorials.com/docs/linux/man/3-xcb_query_pointer/

However, I need the xcb connection and the xcb window to run this command, and I can't access it.

Is it possible somehow?
I tried to write a linux-xorg-only backend for egui, because of this, but it would be so much work for a single feature.

**Comment by kchibisov** [comment]
I'm not sure if `focused` display is exposed anyhow. You can access the `current_monitor` of the window. The cursor position could be tracked via `DeviceEvent`'s I guess. 

Probably @notgull knows how to do that...

**Comment by notgull** [comment]
[`query_pointer`](https://docs.rs/x11rb/latest/x11rb/protocol/xproto/fn.query_pointer.html) can be done relatively easily. In fact, would there be a way to expose a "get the current pointer position" function in `winit`? Win32 has [`GetCursorPos`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getcursorpos), but that's where my GUI knowledge ends.

There isn't really a concept of a "focused" display in X11. In the usual setups, there's only one X display. If you mean getting a focused monitor, we could use [`get_input_focus`](https://docs.rs/x11rb/latest/x11rb/protocol/xproto/struct.GetInputFocusReply.html) and the nget the monitor from there.

**Comment by notgull** [comment]
> However, I need the xcb connection and the xcb window to run this command, and I can't access it.

These can be directly accessed by calling the `HasRawDisplayHandle` and `HasRawWindowHandle` traits

**Comment by fxdave** [comment]
@kchibisov I use the "current_monitor", but it is always the laptop's monitor. It seems it doesn't watch which monitor has the pointer on.

**Comment by fxdave** [comment]
I could make it work:

```rust

fn query_pointer(display: RawDisplayHandle, window: RawWindowHandle) -> (i32, i32) {
    let display = if let RawDisplayHandle::Xlib(raw) = display {
        raw.display
    } else {
        panic!("(Connection) We only support X.org over Xlib")
    };
    let window = if let RawWindowHandle::Xlib(raw) = window {
        raw.window
    } else {
        panic!("(Window) We only support X.org over Xlib")
    };
    let mut r: x11::xlib::Window = Default::default();
    let mut c: x11::xlib::Window = Default::default();
    let mut x: i32 = Default::default();
    let mut y: i32 = Default::default();
    let mut rx: i32 = Default::default();
    let mut ry: i32 = Default::default();
    let mut m: u32 = Default::default();

    let ptr_r: *mut x11::xlib::Window = &mut r;
    let ptr_c: *mut x11::xlib::Window = &mut c;
    let ptr_x: *mut i32 = &mut x;
    let ptr_y: *mut i32 = &mut y;
    let ptr_rx: *mut i32 = &mut rx;
    let ptr_ry: *mut i32 = &mut ry;
    let ptr_m: *mut u32 = &mut m;
    unsafe {
        x11::xlib::XQueryPointer(
            display as *mut _XDisplay, window, ptr_r, ptr_c, ptr_rx, ptr_ry, ptr_x, ptr_y, ptr_m,
        );
    }

    (rx, ry)
}
```

I see why it was confusing. I probably saw the "RawDisplayHandle" but Display in XCB is another term. It doesn't mean the connection. So I thought I would need a RawConnectionHandle, which wasn't there.
The other factor is that I only learnt XCB, because that's newer than Xlib. Unfortunately glutin or winit (idk) uses Xlib instead. 
But in Xlib's terms the "Display" makes sense.

Thanks for the help.

@kchibisov I think it would be good to have a `window().query_pointer()` function that is only for X.org. Or a `window().focused_monitor()` that would return the monitor's properties which has the mouse on. This could work even on other platforms. But I made it work, so I close the issue. Reopen if you want.

**Comment by kchibisov** [comment]
@fxdave for your information. The XCB connection is on XCB raw display handle. But since winit isn't using xcb you won't have access to it.
