### ISSUE TITLE
Alacritty crashed on Awesome WM

### ISSUE THREAD

**Issue by lodisy** [rust-windowing/winit#2633]
```thread main panicked at failed to call XResizeWindow: XError { description= GLXBadFBConfig, error_code: 167, request_code: 152, minor_code: 0}, ".../winit-0.27.5/src/platform_impl/linux/x11/windows.rs:1116:10```

**Comment by kchibisov** [comment]
Doesn't look like related to winit. Bring to alacritty with a full backtrace and information about your system.
