### ISSUE TITLE
macOS: Dead keys in custom keyboard layouts cause IME to trigger when modifiers are used

### ISSUE THREAD

**Issue by loovjo** [rust-windowing/winit#2651]
This is a bit of an odd one. When using my custom keyboard layout I noticed that whenever I used a dead key in alacritty, it stopped respecting any modifier keys (cmd, alt, ctrl) until I restarted it. The behaviour did not occur when using a default macOS keyboard layout with dead keys.

I managed to track down the issue to being that when using a custom keyboard layout, Ime Preedits and Commits still triggered as though the modifier key was not pressed. A minimal reproducible example:

```rs
use winit::{event::{Event, WindowEvent}, event_loop::EventLoop, window::WindowBuilder};

fn main() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();

    window.set_ime_allowed(true);

    event_loop.run(move |event, _, control_flow| {
        match event {
            Event::WindowEvent { event: WindowEvent::CloseRequested, .. } => { control_flow.set_exit(); },
            Event::WindowEvent { event: WindowEvent::KeyboardInput { input, .. }, .. } => { println!("Got input {input:?}"); },
            Event::WindowEvent { event: WindowEvent::Ime(ime), .. } => { println!("Got IME {ime:?}"); },
            Event::MainEventsCleared => {
                window.request_redraw();
            },
            _ => {}
        }
    });
}
```

Running the program, and with the Swedish layout on macOS (Svensk) pressing `¨` (enter dead key), `a` (combining to an `ä`), and then `CTRL-a` gives the following output:
```
Got IME Enabled
Got IME Preedit("¨", Some((2, 2)))
Got IME Preedit("", None)
Got IME Commit("ä")
Got input KeyboardInput { scancode: 0, state: Released, virtual_keycode: Some(A), modifiers: (empty) }
Got input KeyboardInput { scancode: 59, state: Pressed, virtual_keycode: Some(LControl), modifiers: CTRL }
Got input KeyboardInput { scancode: 0, state: Pressed, virtual_keycode: Some(A), modifiers: CTRL }
Got input KeyboardInput { scancode: 0, state: Released, virtual_keycode: Some(A), modifiers: CTRL }
Got input KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: (empty) }
```

Running the program again, but with a minimal custom keyboard layout which I've attached, pressing the dead key (with terminator X), pressing `a` (which under the dead key layer produces a `b`), and then pressing `CTRL-a` produces

```
Got IME Enabled
Got IME Preedit("X", Some((1, 1)))
Got IME Preedit("", None)
Got IME Commit("b")
Got input KeyboardInput { scancode: 0, state: Released, virtual_keycode: Some(A), modifiers: (empty) }
Got input KeyboardInput { scancode: 59, state: Pressed, virtual_keycode: Some(LControl), modifiers: CTRL }
Got IME Preedit("", None)
Got IME Commit("a")
Got input KeyboardInput { scancode: 0, state: Released, virtual_keycode: Some(A), modifiers: CTRL }
Got input KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: (empty) }
```

Here, we can see that pressing `CTRL-a` actually produces an IME event, even though it shouldn't (no character is being produced).

The keyboard layout attached:

[test-layout.zip](https://github.com/rust-windowing/winit/files/10511195/test-layout.zip)

The layout with no dead keys applied:
![bild](https://user-images.githubusercontent.com/8290983/214889090-9b9bedba-f0d1-4228-84c6-002e19e3b562.png)

The layout under the dead key layer:
![bild](https://user-images.githubusercontent.com/8290983/214889175-e61de82e-6a63-4892-b2b7-35a647bbb221.png)

**Comment by kchibisov** [comment]
Should be fixed on master. If not - reopen.
