### ISSUE TITLE
Windows builds not working at all

### ISSUE THREAD

**Issue by apessino** [rust-windowing/winit#2655]
After syncing this morning, winit does not work on Windows at all. Created windows are never shown, and this can be verified simply by running any of the examples.

Reverting the two files `window.rs` and `window_state.rs` in commit https://github.com/rust-windowing/winit/commit/b457329003e8e8f163565039c48690bb4c6a0d59 fixes the problem.

I will look into the cause when I have a moment if you guys don't get to it first.. :)

**Comment by kchibisov** [comment]
>I will look into the cause when I have a moment if you guys don't get to it first.. :)

You likely need to pass with `active_true`? The examples don't draw so that could be it.

**Comment by madsmtm** [comment]
[`MARKER_ACTIVATE`](https://github.com/rust-windowing/winit/blob/b457329003e8e8f163565039c48690bb4c6a0d59/src/platform_impl/windows/window_state.rs#L119) seems to conflict with `IGNORE_CURSOR_EVENT`, perhaps that's it?

**Comment by kchibisov** [comment]
cc @amrbashir

**Comment by apessino** [comment]
Wow - this is one sloppy commit. First, at `window_state:119`:

```
        const MARKER_ACTIVATE = 1 << 18;
```

Overrides the previous constant `IGNORE_CURSOR_EVENT`, I am guessing it should be:

```
        const MARKER_ACTIVATE = 1 << 21;
```

Then, starting at `window_state:310`:

```
    if new.contains(WindowFlags::VISIBLE) {
        let flag = !if self.contains(WindowFlags::MARKER_ACTIVATE) {
            self.set(WindowFlags::MARKER_ACTIVATE, true);
            SWP_NOACTIVATE
        } else {
            SW_SHOW
        };
        unsafe {
            ShowWindow(window, flag);
        }
    }
```

should actually be:

```
    if new.contains(WindowFlags::VISIBLE) {
        let flag = if !self.contains(WindowFlags::MARKER_ACTIVATE) {
            self.set(WindowFlags::MARKER_ACTIVATE, true);
            SW_SHOWNOACTIVATE
        } else {
            SW_SHOW
        };
        unsafe {
            ShowWindow(window, flag);
        }
    }
    }
```

Since `SWP_NOACTIVATE` is the wrong constant (it's a flag for `SetWindowPos` not `ShowWindow`), and then the `!` is on the wrong side of the `if` statement and it would turn either constant into a `bool`.

Making the changes above seems to fix the problems, unless I am missing something.

A=

**Comment by amrbashir** [comment]
Oh wow, sorry about that, I must have been quite dumb when I made that PR.

@apessino the changes you proposed is correct, thanks for looking into it.

**Comment by apessino** [comment]
Thanks for confirming! 👍

**Comment by madsmtm** [comment]
> Oh wow, sorry about that, I must have been quite dumb when I made that PR.

We accepted it, so don't take the entire blame ;) - I understand that you're mostly just porting older `tao` commits, which is very tedious, thanks for the hard work on that!

**Comment by apessino** [comment]
Fixed in https://github.com/rust-windowing/winit/pull/2656
