### ISSUE TITLE
On all platforms, winit is rebuilt every time I build

### ISSUE THREAD

**Issue by apessino** [rust-windowing/winit#2657]
Sorry if this is a known/expected behavior - I could not find any mention of it.

I link my projects to a master-branch-clone of `winit` by relative path, and for a while now I've noticed that doing a `cargo build` on any of my apps causes `winit` and all my dependencies on it to rebuild, even when no changes have been made to any code (and certainly not to `winit` itself).  Doing a `cargo build --verbose` confirms that `winit` is never "fresh" and it recompiles each time.

I tried to understand why but so far I have failed. Perhaps it is unavoidable and related to the custom `build.rs` step? This happens on MacOS and Windows, and it is confirmed by others working on my codebase.

Anyone else seeing this? Any suggestions?

Thanks!

**Comment by madsmtm** [comment]
Hmm, perhaps https://github.com/rust-windowing/winit/pull/2637 broke the `rerun-if-changed` stuff we otherwise have?

**Comment by oxalica** [comment]
> Hmm, perhaps #2637 broke the `rerun-if-changed` stuff we otherwise have?

The `cargo:rerun-if-changed=` instruction accepts only one path. The line below is is monitoring a non-existing file `build.rs:wayland_protocols`, thus rerun the build script every time.

https://github.com/rust-windowing/winit/blob/23b821285ce93bddb38dd71e0290296488140910/build.rs#L31

It should be,
```rust
 println!("cargo:rerun-if-changed=wayland_protocols"); 
```

**Comment by kchibisov** [comment]
Hm, I guess I got it wrong, since cargo uses `PATH` and I've assumed that it's like `PATH` variable.

**Comment by kchibisov** [comment]
Thanks, @oxalica.
