### ISSUE TITLE
Is there a way to access macos events or raw Object ?

### ISSUE THREAD

**Issue by ta3pks** [rust-windowing/winit#2674]
I was trying to implement openWith support for my app and on macos this is done using the events by overwriting the methods under NsApplication (thats my understanding of it) [here](https://developer.apple.com/documentation/appkit/nsapplicationdelegate)

Is there a way to tap into these events somehow ?

**Comment by madsmtm** [comment]
There is work in progress on the generic case in https://github.com/rust-windowing/winit/issues/2120, but no clear solution has emerged yet.

**Comment by madsmtm** [comment]
After https://github.com/rust-windowing/winit/pull/3758, listening to `NSApplicationDelegate` events will be possible by using `objc2::declare_class!`, Objective-C, Swift, or similar. [The WIP docs for `winit::platform::macos`](https://rust-windowing.github.io/winit/winit/platform/macos/index.html) should contain a rough example of how to do this once the PR is merged. Feel free to open an issue, probably preferably on [the `objc2` repo](https://github.com/madsmtm/objc2), if you're having trouble with doing so.
