### ISSUE TITLE
KeyCode::Plus corresponds to = input on North American keyboard

### ISSUE THREAD

**Issue by alice-i-cecile** [rust-windowing/winit#2682]
Detected using Bevy 0.9.1.

This keybinding doesn't trigger as expected when "+" is pressed, but works when "=" is pressed.

`KeyCode::Equals` works though, so these appear to be swapped.

**Comment by madsmtm** [comment]
On which platform(s) do you experience this?

On macOS, I find that the behaviour perhaps works a bit weirdly, but that is at least fixed in https://github.com/rust-windowing/winit/pull/2662

**Comment by alice-i-cecile** [comment]
This was detected on PopOS 22.04.

**Comment by kchibisov** [comment]
I'd close this as a part of #1932, which should be in the next winit release anyway.
