### ISSUE TITLE
Moderate CPU usage under Wayland

### ISSUE THREAD

**Issue by marcospampi** [rust-windowing/winit#2690]
As I found curious a load of 8% on a 12 thread system with just a [bare-bone wgpu instance](https://sotrh.github.io/learn-wgpu/beginner/tutorial2-surface/#wait-what-s-going-on-with-renderpassdescriptor), I first thought it was polling but even as I switched to `ControlFlow::Wait` got same load , I executed the application with `WINIT_UNIX_BACKEND=x11` and load is down to 0.00%, as you'd expect from an application that displays a blue window.

Sorry for such a bland report.

Ps. The system in question is a Ryzen 5600U running Fedora 37.

**Comment by kchibisov** [comment]
Show me your event loop. You're likely forcing the wake up.

**Comment by marcospampi** [comment]
```
pub async fn run() {
    env_logger::init();
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();
    let mut state = State::new(window).await;

    event_loop.run(move |event, _, control_flow| match event {
        Event::WindowEvent {
            ref event,
            window_id,
        } if window_id == state.window.id() => {
            if !state.input(event) {
                // this few lines ahead do nothing
                if *control_flow == ControlFlow::Poll {
                    *control_flow = ControlFlow::Wait;
                }
                match event {
                    WindowEvent::CloseRequested
                    | WindowEvent::KeyboardInput {
                        input:
                            KeyboardInput {
                                state: ElementState::Pressed,
                                virtual_keycode: Some(VirtualKeyCode::Escape),
                                ..
                            },
                        ..
                    } => *control_flow = ControlFlow::Exit,
                    WindowEvent::Resized(physical_size) => state.resize(*physical_size),
                    WindowEvent::ScaleFactorChanged { new_inner_size, .. } => {
                        state.resize(**new_inner_size)
                    }
                    _ => {
                    }
                }
            }
        }
        Event::RedrawRequested(window_id) if window_id == state.window().id() => {
            state.update();
            match state.render() {
                Ok(_) => {}
                // Reconfigure the surface if lost
                Err(wgpu::SurfaceError::Lost) => state.resize(state.size),
                // The system is out of memory, we should probably quit
                Err(wgpu::SurfaceError::OutOfMemory) => *control_flow = ControlFlow::Exit,
                // All other errors (Outdated, Timeout) should be resolved by the next frame
                Err(e) => eprintln!("{:?}", e),
            }
        },
        Event::MainEventsCleared => {
            state.window.request_redraw();
        }
        _ => {}
    });
}
```
it's mostly like the link above

**Comment by kchibisov** [comment]
Which version of winit you're using?

**Comment by kchibisov** [comment]
Just so you know, if you're not using winit 0.28.1

```
        Event::MainEventsCleared => {
            state.window.request_redraw();
        }
```

Will cause busy looping on Wayland.

**Comment by notgull** [comment]
Just a heads up: `event_loop.run()` blocks, so it's generally discouraged to use it in an `async` function.

**Comment by marcospampi** [comment]
> Just a heads up: `event_loop.run()` blocks, so it's generally discouraged to use it in an `async` function.

It's perfectly fine here, async is only required for wgpu initialization.


> Just so you know, if you're not using winit 0.28.1
> 
> ```
>         Event::MainEventsCleared => {
>             state.window.request_redraw();
>         }
> ```
> 
> Will cause busy looping on Wayland.

I was using 0.27, but I have this behaviour even with 0.28.1.  
of course if no redraw is requested, the usage gets to zero, any advice?

**Comment by kchibisov** [comment]
>I was using 0.27, but I have this behaviour even with 0.28.1.
of course if no redraw is requested, the usage gets to zero, any advice?

Could you share the entire example with me using winit 0.28.1 so I can verify that?

In general, your event loop code is faulty, because there's no guarantee that you won't get spurious wake ups and you should draw only once your content actually changed, which you're not doing.

**Comment by marcospampi** [comment]
> > I was using 0.27, but I have this behaviour even with 0.28.1.
> > of course if no redraw is requested, the usage gets to zero, any advice?
> 
> Could you share the entire example with me using winit 0.28.1 so I can verify that?
> 
> In general, your event loop code is faulty, because there's no guarantee that you won't get spurious wake ups and you should draw only once your content actually changed, which you're not doing.

Since I'm following the tutorial I linked in first post, this is [the tutorial code linked at the end](https://github.com/sotrh/learn-wgpu/tree/master/code/beginner/tutorial2-surface/), except I have updated dependencies to latest winit as you suggested and had wgpu to latest version.

**Comment by kchibisov** [comment]
I was just hoping for archive I could simple `cargo run` instead of going through the tutorial myself.

**Comment by kchibisov** [comment]
Anyway, your example isn't really a real world one. The CPU usage is because you force the redraw, and with X11 you don't get extra wakeup to start your loop, but with Wayland, you might, because your video driver decided to dispatch something.

In general, draw when something changed, not every time you get `MainEventsCleared`.

**Comment by kchibisov** [comment]
An alternative would be for winit to not callback to the user when no events interested by winit were generated, but that will break existing clients relying on such behavior.
