### ISSUE TITLE
Macos fires `WindowEvent::Focused(false)` on `WinitWindow` creation

### ISSUE THREAD

**Issue by TimonPost** [rust-windowing/winit#2695]
In this commit: https://github.com/rust-windowing/winit/commit/b457329003e8e8f163565039c48690bb4c6a0d59#diff-4803bb2335a17d700335730b9f62828e001faa602b9b894dff572422c737b78aR480 the author fires the `Focused(false)` event on macos window creation. It seems to be inconsistent with the other platforms. 

In my case on macos I receive first `Focused(true)` and then `Focused(false)` when creating a window. The `Focused(true)` is caused by `window_did_become_key` and then `Focused(false)` is caused by the window init function queuing it when it is created. 

On other platforms it seems like the `focused` boolean is automatically set to false upon creation without firing an event. This seems to create divergent behavior on different platforms as macos has an additional event now. 

For now my fix is the following:

```rust
 WindowEvent::Focused(_focused) => {
        self.focused = winit.has_focus();
}
```

Sending an event on window creation creates unexpected behavior. Evenwhile my window is focused winit just informed me it isn't.

**Comment by TimonPost** [comment]
cc: @amrbashir @kchibisov

**Comment by kchibisov** [comment]
>In my case on macos I receive first Focused(true) and then Focused(false) when creating a window. The Focused(true) is caused by window_did_become_key and then Focused(false) is caused by the window init function queuing it when it is created.

So do you have `Focused(false)` for un-focused window?

**Comment by TimonPost** [comment]
Yes! `Window::has_focus` does result in expected output. It tells me my window is focused while the event tells me it isn't.

**Comment by kchibisov** [comment]
@TimonPost could you verify whether my patch changes anything for you? Because I can't repro the original issue you're having in the first place to begin with.

**Comment by TimonPost** [comment]
Will give it a try soon. Yes I found it hard to replicate the same behavior in an standalone app. We do have quite some complex setup of our window logic so many moving parts.

**Comment by kchibisov** [comment]
Yeah, that would be nice, since my testing target is usually alacritty, and it works fine with the current logic we have.

**Comment by TimonPost** [comment]
I will still confirm the changes just need to get to work where I have a MacBook.

**Comment by kchibisov** [comment]
Well, it was already confirmed, but yeah, sure.
