### ISSUE TITLE
Error Winit BadDrawable

### ISSUE THREAD

**Issue by edap** [rust-windowing/winit#2716]
Hello, I am using winit 0.27, I have this error:

```
[2023-03-04T13:21:42Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
thread 'main' panicked at 'Failed to focus input context: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }', /home/dapx/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/event_processor.rs:912:30


```

I have tried to remove /usr/share/vulkan/icd.d/intel_icd.x86_64.json and then run `vkcube` (as suggested here https://github.com/iced-rs/iced/issues/70#issuecomment-558872369), the vulkan cube works, but the  error above is still there.

**Comment by kchibisov** [comment]
Winit has nothing to do with vulkan.

**Comment by edap** [comment]
Many thanks for your  observation. I see your point, but as the error comes from "winit-0.27.5/src/platform_impl/linux/x11/event_processor.rs" I think it make sense to report it. Do you have some hints about what could be the issue?

**Comment by kchibisov** [comment]
The error handling on X11 is done that way that everything comes to exactly the same error handling `hook`, so your error raised in your vulkan code was just send to the winit's error handling hook (the hook is one per process).

I'd suggest to reference Vulkan X11 extension and see what could produce such error in the first place, also if your application wants to check errors right away instead of silently doing so, they could use latest winit + https://docs.rs/winit/0.28.2/winit/platform/x11/fn.register_xlib_error_hook.html , so they can handle errors right away, similar to what `glutin` does with GLX and EGL, so errors from it are never reaching winit in the first place.

**Comment by edap** [comment]
Ok, thanks for your time. I will have a look at the VulaknX11 extension. The weird thing is that I have this error just on my pop_os laptop, in the desktop with Ubuntu 22.04 everything runs smoothly. They do have different graphics card though.

**Comment by kchibisov** [comment]
I'm not that familiar with Vulkan, but I swear it should still deal with X11 visual crap, which could be an issue if you don't pass it around directly. For example it could lead to window you can't really draw to.

It actually could be an issue if someone will try to pass winit's visual to something, because winit doesn't set the visual inside the raw window handle.

**Comment by edap** [comment]
Many thanks, I will try to investigate further, I am not a Vulkan expert neither. By the way the code causing the trouble is https://github.com/sotrh/learn-wgpu/blob/master/code/beginner/tutorial2-surface/src/lib.rs . It's a popular tutorial about how to learn WebGPU in rust. The entry points seems to be this line https://github.com/sotrh/learn-wgpu/blob/master/code/beginner/tutorial2-surface/src/lib.rs#L191

```
2023-03-04T14:58:53Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
thread 'main' panicked at 'Failed to focus input context: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }', /home/dapx/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.4/src/platform_impl/linux/x11/event_processor.rs:912:30
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::expect
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1070:23
   4: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
             at /home/dapx/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.4/src/platform_impl/linux/x11/event_processor.rs:909:25
   5: winit::platform_impl::platform::x11::EventLoop<T>::drain_events
             at /home/dapx/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.4/src/platform_impl/linux/x11/mod.rs:517:13
   6: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
             at /home/dapx/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.4/src/platform_impl/linux/x11/mod.rs:348:13
   7: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/dapx/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.4/src/platform_impl/linux/x11/mod.rs:448:31
   8: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/dapx/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.4/src/platform_impl/linux/x11/mod.rs:503:25
   9: winit::platform_impl::platform::EventLoop<T>::run
             at /home/dapx/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.4/src/platform_impl/linux/mod.rs:755:56
  10: winit::event_loop::EventLoop<T>::run
             at /home/dapx/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.4/src/event_loop.rs:278:9
  11: tutorial2_surface::run::{{closure}}
             at ./code/beginner/tutorial2-surface/src/lib.rs:191:5
  12: pollster::block_on
             at /home/dapx/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.5/src/lib.rs:125:15
  13: tutorial2_surface::main
             at ./code/beginner/tutorial2-surface/src/main.rs:4:5
  14: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

Anyway, as said before, thanks for your time.

**Comment by kchibisov** [comment]
It just looks that some error got in place, `BadDrawable`. You could try to run `ash`/`glutin` window example on your system and see if they work, if they do, then it's an issue with wgpu x11 handling. The errors on X11 are just bad, whatever you get in winit has very little to do with winit.

https://github.com/rust-windowing/glutin/ (`cargo run --example window`).
https://github.com/ash-rs/ash/ (not sure what to run from it, see examples folder).

**Comment by edap** [comment]
The glutin example works. The ash example doesn't. In the instructions it is written that I should install the Lunar SDK, but this was not required previously neither in the webGPU tutorial nor in the WebGPU repo.

**Comment by kchibisov** [comment]
Hm, i don't think you need lunar sdk for its basic examples.


You should run this example https://github.com/ash-rs/ash/tree/master/ash-window/examples
