### ISSUE TITLE
Update `objc2` version

### ISSUE THREAD

**Issue by madsmtm** [rust-windowing/winit#2724]
Fixes https://github.com/rust-windowing/winit/issues/2722.

I recently found out that cargo can't duplicate pre-release versions, so we need to coordinate this upgrade with `AccessKit` (see https://github.com/AccessKit/accesskit/pull/200) if we don't want to break the projects that rely on both @mwcampbell.

Ideally, I'd release `objc2 v0.3` first, and then we'd all just upgrade to that, but not sure I have the time for that atm.

**Comment by mwcampbell** [comment]
I'm happy to coordinate on this. I wonder if this requires semver-major updates (i.e. winit 0.29, accesskit_macos 0.7, and accesskit_winit 0.13).

**Comment by mwcampbell** [comment]
Then ideally, I guess the updates to winit and the AccessKit crates need to be published very close together.

I'm in the middle of another project right now, but I can take a little time to work on this in the next few days if needed. Where would be the best chat channel for us to coordinate on this?

**Comment by madsmtm** [comment]
The `winit` Matrix is probably the best place for me, but I think the easiest is just for me to publish `objc2 v0.4` (e.g. skipping `v0.3`), which avoids the problem altogether

**Comment by mwcampbell** [comment]
Yes, publishing objc2 0.4 sounds like a good solution. Then I can update to that version on my own schedule (or, at least, when some downstream dependency complains about the multiple versions).
