### ISSUE TITLE
Child window without decorations not working on Win 10

### ISSUE THREAD

**Issue by siriux** [rust-windowing/winit#2754]
Setting decorations to false doesn't work on child windows on Win 10, the decorations are still visible.

This might be related to other decoration issues that appeared after https://github.com/rust-windowing/winit/pull/2419 

I don't have much experience with the winit code base, but as far as I can see WS_CAPTION and WS_BORDER are always added to the window style and never removed (except in adjust_rect(...) that is not initially called).

Maybe they can only be added if decorations are activated in the first place?

Thanks

**Comment by msiglreith** [comment]
Thanks for the report, right these window styles should probably be excluded as the are only needed for system native behavior of the top level windows.
