### ISSUE TITLE
Wayland 1.22.0 Errors :D

### ISSUE THREAD

**Issue by Snowiiii** [rust-windowing/winit#2761]
Wayland 1.22.0 has just been released today, and I woke up to the news. After updating my Arch system, I was excited to try it out. However, while working on my Rust project using Winit, I encountered new Wayland errors that I had never seen before. Here are the errors:
```
warning: queue 0x5578b2108c90 destroyed while proxies still attached:
  wl_display@1 still attached
warning: queue 0x5578b25728d0 destroyed while proxies still attached:
  zwp_linux_dmabuf_feedback_v1@49 still attached
warning: queue 0x5578b22f2b00 destroyed while proxies still attached:
  wl_display@1 still attached
  ```

**Comment by kchibisov** [comment]
Those a warnings from mesa, they're are innocent.

**Comment by flukejones** [comment]
Innocent maybe, but I suspect this is going to be pulled up more than a few times as an issue. The way SDL2 sovled it is [this commit](https://github.com/libsdl-org/SDL/commit/132b88749c284e4d51d93f1e08f5bb0ff9d705dc)

**Comment by kchibisov** [comment]
winit itself destroys everything it creates correctly, this issue is closed for a reason...
