### ISSUE TITLE
Window visual glitching on linux mint 2.3 cinnamon

### ISSUE THREAD

**Issue by StarLitDragon404** [rust-windowing/winit#2762]
I am using winit example in the crates.io page

here is my code
```
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};
fn main() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                window_id,
            } if window_id == window.id() => *control_flow = ControlFlow::Exit,
            _ => (),
        }
    });
}
```

here is the output

![image](https://user-images.githubusercontent.com/97881292/230740972-547f856e-68a5-4f03-adfb-0e9db05dffc3.png)

the winit window is reflecting the vs code window
and when i try to maximize

![image](https://user-images.githubusercontent.com/97881292/230741092-cd8bc21c-daec-4411-9c05-65712fd2d968.png)

the window duplicates and goes to the corner

**Comment by kchibisov** [comment]
You should draw into window, the default window contains arbitrary garbage values, thus it's expected.

Winit doesn't do or provide any drawing, background clearing and so on, that's intended.
