### ISSUE TITLE
Replace mio with calloop in the X11 backend

### ISSUE THREAD

**Issue by notgull** [rust-windowing/winit#2763]
Right now, there are two backends for Free Unix systems; one for X11 and one for Wayland. The X11 backend uses `mio` to query for display readiness and query for other things (such as user events), while the Wayland backend uses the `calloop` crate in a very similar way.

It would be nice for dependency reduction if the X11 backend used `calloop` instead. In fact, there is probably a lot of code that can be shared between the backends if both used `calloop`.

**Comment by kchibisov** [comment]
They were used calloop in the past, it's just X11 decided to use `mio` at some point, and I don't remember exact motivation for that…

**Comment by notgull** [comment]
Looks like the switch happened in https://github.com/rust-windowing/winit/pull/1098/commits/ed3c62422569ba516ac11650a1c7aadf7e05b567. It looks like they couldn't work the [`ScaleFactorChanged`](https://docs.rs/winit/latest/winit/event/enum.WindowEvent.html#variant.ScaleFactorChanged) event into `calloop`. Maybe the newer version of `calloop` fixes that?
