### ISSUE TITLE
macOS: memory leak when getting monitor handle

### ISSUE THREAD

**Issue by xiaopengli89** [rust-windowing/winit#2796]
Related fix #2758

```rust
fn main() {
    let event_loop = EventLoop::new();

    let window = WindowBuilder::new()
        .with_title("A fantastic window!")
        .build(&event_loop)
        .unwrap();

    loop {
        let _mh = window.current_monitor().unwrap();
        thread::sleep(Duration::from_millis(20));
    }
}
```
<img width="897" alt="图片" src="https://user-images.githubusercontent.com/11287532/236737287-38684ab4-81bb-4bfe-8540-081a85e49eec.png">

**Comment by madsmtm** [comment]
Yeah, you're right, I haven't bothered to check the fix yet because it very likely won't happen in user-code, since they'll be using it inside `run`, which is wrapped in an autorelease pool.

**Comment by xiaopengli89** [comment]
User may call this method on other thread.

**Comment by madsmtm** [comment]
Hmm, that's true. I guess I'll take a look then
