### ISSUE TITLE
Wayland window's size doesn't respect user's settings. It changes after the intial Resized event. 

### ISSUE THREAD

**Issue by Nazariglez** [rust-windowing/winit#2799]
Hello! 

We're having an issue with notan https://github.com/Nazariglez/notan/issues/265, where the user sets the window's inner_size to 400x400 and the first `Resized` event comes with 420x455. 

The user's setup: `Arch Linux with GNOME on Wayland, and 125% display scaling.`. 

Some curated logs:
```
// before winit Resized event after creating the window
inner_size PhysicalSize { width: 400, height: 400 }, scale 1.0
// resized event arrives
size on the Resized event PhysicalSize { width: 420, height: 455 } inner:PhysicalSize { width: 420, height: 455 } outer:PhysicalSize { width: 420, height: 455 }, dpi:1
```

After that event, we update the GL surface leading to a black padding between what is drawn and the window's limit. 

Is this the right behavior? Should not be different the outer size from the inner size? If so, should not be size into the Resized event the inner size?

In other platforms, the size set by the user is respected and the first Resized event sent by winit contains the inner size of the window (it matches with what the user sets).

Thanks for the help.

**Comment by kchibisov** [comment]
Would suggest to try with latest master.

**Comment by kchibisov** [comment]
>After that event, we update the GL surface leading to a black padding between what is drawn and the window's limit.

While this is a bit off-topic here, I'd suggest to read this thing when dealing with GL on Wayland https://github.com/rust-windowing/glutin/commit/cc223a6d8a1eaf7c608e44de7b4b17b1459c181d . One advise would be if you create a surface, to get the `inner_size` out of the window right after creating it, but that thing will work only against latest master branch.

**Comment by Nazariglez** [comment]
I need to do some changes in notan to be able to use the latest version of winit, and then ask the user to test it, I'll come back in a few days. Thanks for the help @kchibisov!

**Comment by kchibisov** [comment]
You should be able to use https://github.com/rust-windowing/winit/commit/249609889029af3e5ec19afbd02464e11a265378 without any changes assuming that you're using `0.28` release. This commit is enough to test it.

**Comment by Nazariglez** [comment]
Sadly it's not the case, we're on `0.27.5´. I should be able to update it fairly easily (I hope so) tomorrow if I got time.

**Comment by Nazariglez** [comment]
hey @kchibisov I did try this using the latest master (I had to patch.crate-io to force glutin-winit to use it too) and it's fixed there, there is no issue at all. Thanks!

**Comment by kchibisov** [comment]
Good to know.
