### ISSUE TITLE
winit doesn't work with wayland or X11 on nixos unstable - wayland doesn't show any windows and on X11 window is blank

### ISSUE THREAD

**Issue by uzytkownik** [rust-windowing/winit#2807]
When I try to run `window_debug` or 'web` example with wayland on nixos unstable with gnome-shell no window is shown. X11 shows just black screen that doesn't refresh.

Not sure if this helps but on 2.27.5 the program panics on Wayland:

```
thread 'main' panicked at 'internal error: entered unreachable code', /tmp/winit/src/platform_impl/linux/wayland/window/mod.rs:297:77
```

**Comment by kchibisov** [comment]
Winit examples don't draw anything into the window, so the behavior is expected.

The error you've encountered before is because you're missing `libxkbcommon`, which you can try to avoid by statically linking to it(feature in the config).

winit relies on `dlopen` which is not friendly to nix, so you should set `LD_LIBRARY_PATH` or `patchelf`.

**Comment by notgull** [comment]
> winit relies on `dlopen` which is not friendly to nix, so you should set `LD_LIBRARY_PATH` or `patchelf`.

An option to avoid `dlopen` might be nice in the future

**Comment by kchibisov** [comment]
you can have wayland without dlopen if you disable `wayland-dlopen` feature. Only x11 is lacking.

**Comment by uzytkownik** [comment]
> The error you've encountered before is because you're missing `libxkbcommon`, which you can try to avoid by statically linking to it(feature in the config).
> 

Ok. I was expecting the error message about failing to load as with other. Library I was using 2.27.x so I got confused by errors.

> winit relies on `dlopen` which is not friendly to nix, so you should set `LD_LIBRARY_PATH` or `patchelf`.

I know. Here's my shell.nix:

```nix
{ pkgs ? import <nixpkgs> {} }:
pkgs.mkShell {
  packages = [ pkgs.gdb ];
  buildInputs = [ pkgs.stdenv pkgs.cmake pkgs.pkgconfig pkgs.libxkbcommon ];
  nativeBuildInputs = [ pkgs.fontconfig ];
  shellHook = ''
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${pkgs.wayland}/lib:${pkgs.libxkbcommon}/lib
    #export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${pkgs.xorg.libX11}/lib:${pkgs.xorg.libXcursor}/lib:${pkgs.xorg.libXrandr}/lib:${pkgs.xorg.libXi}/lib

    '';
}
```

I missed `${pkgs.libxkbcommon}/lib` for 2.27.5 as the error was not clear but now behaviour is the same on both (no window on Wayland in example though wgpu shows one).

**Comment by kchibisov** [comment]
>Winit examples don't draw anything into the window, so the behavior is expected.
