### ISSUE TITLE
`set_window_icon` does not work on Wayland

### ISSUE THREAD

**Issue by mkoncek** [rust-windowing/winit#2810]
winit version: 0.28.6

Calling the function `set_window_icon` has no effect when running on Wayland.
This has been confirmed because when the application is run with environment variable `WAYLAND_DISPLAY=X11` which forces the use of Xwayland, then the icon is set.

**Comment by kchibisov** [comment]
From the documentation:

>iOS / Android / Web / Wayland / macOS / Orbital: Unsupported.

And on Wayland it's not possible to change icon. The icon is usually set according to the `.desktop` file

**Comment by Its-Just-Nans** [comment]
Just to keep track

- It wasn't possible at the time of #2810 but will be possible with #3859
