### ISSUE TITLE
`wgpu` example appears to constantly redraw on X11, not so on MacOS

### ISSUE THREAD

**Issue by adrian5** [rust-windowing/winit#2818]
I'm trying to narrow down and issue in [iced](https://github.com/iced-rs/iced/issues/1867) => [wpu](https://github.com/gfx-rs/wgpu/issues/3788) => winit?

1. The `wgpu` [hello-triangle](https://github.com/gfx-rs/wgpu/tree/trunk/wgpu/examples/hello-triangle) example eats more CPU-time on my X11 Linux machine than one would expect, even when minimized.
   ![wpgu-idle-cputime](https://github.com/gfx-rs/wgpu/assets/5426924/fc21ed3b-5372-4bbd-b337-6fef9951f795)
   It doesn't appear to [do so](https://github.com/gfx-rs/wgpu/issues/3788#issuecomment-1562323315) on macOS.
2. The `winit` [window_run_return](https://github.com/rust-windowing/winit/blob/master/examples/window_run_return.rs) example, which looks to be designed to continuously redraw, uses a near identical amount of CPU-time as `hello-triangle`.

Conceivably some interaction between my OS and `winit` triggers constant redraws where it wouldn't on other systems. Any thoughts on this? Is there something I can do to help narrow this down?

I don't observe this behavior with any other Desktop applications. None of them use `winit` to my knowledge.

**Comment by kchibisov** [comment]
is it happening when the window is focused or not focused?

**Comment by adrian5** [comment]
> is it happening when the window is focused or not focused?

It happens regardless of window visibility and focus state (unfocused too), in all cases the CPU-consumption is effectively identical.

**Comment by adrian5** [comment]
Yes, fair enough — it doesn't look to me either like `winit` is the culprit regarding the unfocused window. I'm just out of ideas since neither [iced](https://github.com/iced-rs/iced/issues/1867#issuecomment-1559564437) nor [wgpu](https://github.com/gfx-rs/wgpu/issues/3788#issuecomment-1571477535) seem to see a problem on their part. I guess I'll try with the `wgpu` devs again. Thanks.

**Comment by vladh** [comment]
@adrian5 Did you ever figure this out? I'm running into a similar iced issue, but with 100% CPU usage.

**Comment by adrian5** [comment]
@vladh I have not found a solution on Xfce. I intend to switch to a Wayland-based DE in the future and hope to leave this problem behind that way.

**Comment by vladh** [comment]
@adrian5 Oh…I'm having this problem on Wayland. 🤦🏻

**Comment by kchibisov** [comment]
@vladh as I told you on your original issue, just don't ask to draw on each iteration of the loop and there won't be any issue because you ask for such behavior yourself. The same was with X11 on this issue.

**Comment by vladh** [comment]
@kchibisov Yes, I got that, thanks so much. But unfortunately it seems like my problem has to do with something else.

I'm trying to fix this bug in iced: https://github.com/iced-rs/iced/issues/2558

I can't tell if iced is using winit improperly, or if this is a winit Wayland bug.

Sorry to have bothered you about this, I've been trying to fix this for 2 days and haven't gotten anywhere. :(

**Comment by kchibisov** [comment]
The only time winit can queue redraw for you is when compositor really wants it or when you constantly change size to something different.

So, likely not winit issue and you can try to repro with winit example (or alacritty), if the don't do that, it's not winit issue.
