### ISSUE TITLE
Window icons not working under wayland

### ISSUE THREAD

**Issue by nelind3** [rust-windowing/winit#2819]
Window icons don't seem to be working properly under Wayland. They aren't showing up at all even though the same code gives an icon properly under X11/Xorg

Minimal code to reproduce (I'm using KDE Plasma Desktop Wayland running on Fedora 36 in case that becomes relevant):

```
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::{WindowBuilder, Icon},
};
use image::open;

fn main() {
    let image = open("./icon.png").unwrap();

    let event_loop = EventLoop::new();
    let window = WindowBuilder::new()
    .with_window_icon(Some(Icon::from_rgba(image.as_rgba8().unwrap().to_vec(), 32, 32).unwrap()))
    .build(&event_loop).unwrap()

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                window_id,
            } if window_id == window.id() => *control_flow = ControlFlow::Exit,
            _ => (),
        }
    });
}

```
This opens a window under X with the window icon correctly being the icon located at ./icon.png (if its the right size at least) but doesn't register the icon properly under Wayland (judging by the icon being the default Wayland icon on the task bar since this this of course doesn't display any window under Wayland)

**Comment by kchibisov** [comment]
Icons as per docs are not supported on Wayland, because on Wayland you must ship `.desktop` file with your app and set `app_id`(use `.with_name`)
