### ISSUE TITLE
Return the applied size for synchronious `set_inner_size`

### ISSUE THREAD

**Issue by kchibisov** [rust-windowing/winit#2868]
The `Window::set_inner_size(Size)` is an async request with the semantic of asking the OS to resize, such request results in a response with the `Resized` event from the OS, however it's not the case on at least Wayland, because the buffer is managed by the client, and the intent of doing `set_inner_size` could mean that you want to draw the window with the sizes you want. However on async platforms you can't really do that, because you have to wait for OS to reply back.

What we could do is the following:

```rust
#[must_use]
fn set_inner_size(Size) -> Option<PhysicalSize>
```

Where `Some` will be returned when the value was applied immediately so the users can use it and `None` when the request went to OS for waiting.

The key point here, is that some clients might want to draw with the sizes they want to set on the current frame, so what they could do with such API is the following

```rust
let new_size = window.set_inner_size(PhysicalSize(200, 200)).unwrap_or_else(|| window.inner_size());
```

So when they want to draw with the sizes they set, they'll not unconditionally assume that what they've used was applied right away.

In addition, the `set_inner_size` should state explicitly that semantic of `Size` under the hood is not being taken into the account and the value which fits better for the backend is used.

**Comment by kchibisov** [comment]
Maybe we could rename the function along the way to say `request_inner_size`, so it's clear what it does.

**Comment by rib** [comment]
Hmm, I think you often want to optimistically use the size you have requested on async platforms. I'm fairly sure there was an x11 resize issue that I commented on ages ago that could have been addressed if the backend could return the pending/requested size. It's possible that a window manager might not eventually honor a request but the requested size can still be the best information you have. It's often just apps like terminals that will constrain sizes to certain multiples and in other cases you're pretty likely to get what you asked for.

**Comment by rib** [comment]
This is the old x11 issue I was thinking of https://github.com/rust-windowing/winit/issues/2306

**Comment by kchibisov** [comment]
I remember that there was an issue with Vulkan validation layers, where they queried the sizes like we do with `inner_size` and got a missmatch. It was sort of addressed at some point, but I think there's no reliable way other than using the `inner_size()`.

**Comment by kchibisov** [comment]
Also, the intent is to say that `Resized` won't be delivered on Wayland, because the request was `sync` in the first place. Applications are free to use the size they want, as in what they've requested, but we should clearly state that they might desync on async platforms.
