### ISSUE TITLE
X11: Allow to set WM_NAME window property

### ISSUE THREAD

**Issue by unclechu** [rust-windowing/winit#2892]
I found no way to set `WM_NAME` property for an X11 window in the documentation. I’m not very familiar with X11 internals so I can be missing something.

It seems to me that most of the X11 applications I have in my hands (say Firefox for instance) set both the *window title* (that does not appear in the X11 window properties if I try to inspect them using `xprop` utility) and also `WM_NAME` window property. `winit` can set the window title via a dedicated method (`WindowBuilder::with_title`) but it doesn’t seem to set `WM_NAME` nor provide a way to set it. `WM_NAME` appears as an empty string in the `xprop` output.

While I can see the window title on the WM’s bar, in the list of windows in [Rofi](https://github.com/davatorium/rofi) (`rofi -show window`) the column where the window title is rendered for other applications is just empty. I can set the `WM_NAME` by calling `xprop -set WM_NAME testing` and then I could see “testing” in the Rofi’s output (so it’s clearly reading `WM_NAME` for rendering the window title).

I was trying to find a way to customize the window title to solve the https://github.com/neovide/neovide/issues/1904 feature request but by looking at the [documentation page for WindowBuilderExtX11](https://docs.rs/winit/latest/winit/platform/x11/trait.WindowBuilderExtX11.html) I couldn’t find the right method for the job. `with_name` sets the `WM_CLASS` and not the `WM_NAME`. `WindowBuilder::with_title` sets the window title but also not the `WM_NAME`. I also couldn’t find a way to set an arbitrary X11 window prop which I could use to set `WM_NAME`.

---

I guess it can be either a dedicated X11-specific method (a part of the `WindowBuilderExtX11`) or the `with_title` can be implemented in the way that it also sets the `WM_NAME` property. I don’t know which one would be the best solution.

**Comment by notgull** [comment]
As of https://github.com/rust-windowing/winit/commit/d7ec899d6983e5eb257941308b632d7e8665b213 we set `WM_NAME` in addition to the window title (`_NET_WM_NAME`).
