### ISSUE TITLE
Heads Up: Updated The Android-Activities Crate

### ISSUE THREAD

**Issue by lexi-the-cute** [rust-windowing/winit#2905]
I updated the android-activities crate so it can work with modern versions of GameActivity. I'm just giving you a heads up about the PR so winit can be updated with the newer version once it's available. https://github.com/rust-mobile/android-activity/pull/88.

The current version of winit cannot work on modern Android projects due to the outdated GameActivity code in use, so this'll allow Android apps to work again with winit

**Comment by kchibisov** [comment]
@MarijnS95 @rib 

Could you provide some info wrt android backend update? I'm planning on doing a new winit beta release by the end of the week/next week and probably a release in a week or two afterwards.

**Comment by rib** [comment]
hmm, yeah there are a few things ideally I'd like to roll up into another android-activity release.

Ideally I want to remove the unintentional, public Deref implementations for KeyEvent which will require a semver bump technically.

It's ambiguous whether we need a semver bump to update the GameActivity backend (it doesn't affect the Rust API, so it's kind of comparable to a MSRV bump) but if it's beneficial to have a semver bump anyway then we may as well sync this update with that.

I have one notable features I'd like to land in android-activity and integrate with Winit too, to expose unicode characters for key events, but should just be an api addition for android-activity and effectively just a backend fix for Winit - so doesn't need a semver bump.

This change would require a semver bump too: https://github.com/rust-mobile/android-activity/issues/92 and I still can't quite decide which way to go here.

When is end of the week for you? it's already end of Friday here. I can try and prioritize landing things for android-activity + making a release, to hopefully be able to bump the android-activity version in winit for the next beta.

**Comment by kchibisov** [comment]
@rib yeah, sorry, I just used to working 7 days a week, so for me it's like 2.5 more. Beta doesn't need android bump, so you have plenty of time (like 2-3 weeks).

What's the state of the soft keyboard stuff in the mean time?

**Comment by rib** [comment]
Right, yeah, also tricky to guess what day people count as the end of the week.

I guess you mean the input method support for GameActivity.

I haven't had a look at it recently but I did notice someone picked up some of my older branches and it sounded like they had got something working so maybe it's possible to land something there too if I can aim to look at that too.

It would be good to take a look after landing the GameActivity 2.0.2 update.

**Comment by kchibisov** [comment]
@rib I was referring to this https://github.com/rust-windowing/winit/issues/1497#issuecomment-1627438140 since it's based on some of your branches.

**Comment by rib** [comment]
thanks for the link, that's also what I was thinking of but couldn't recall where it was

**Comment by rib** [comment]
looking at the changes needed to expose keymaps for getting unicode characters for key events, that might also need a semver breaking change for android-activity actually, since the current way that input events are dispatched requires them to hold a lock for the AndroidApp that would lead to dead locks trying to do key_map lookups.

**Comment by MarijnS95** [comment]
@kchibisov I had hoped to time the next "breaking" `ndk` release with `winit`, though more breaking changes always trickle in right as I want to make the cut-off for the current release.

**Comment by kchibisov** [comment]
@MarijnS95 I mean if you need more time it's not like we're in the rush.

**Comment by MarijnS95** [comment]
@kchibisov I'll see what we can do and will let you know.
