### ISSUE TITLE
Security advisory: xml-rs

### ISSUE THREAD

**Issue by erwanvivien** [rust-windowing/winit#2910]
![image](https://github.com/rust-windowing/winit/assets/44021072/6a67b746-8456-4a6e-8185-3987be870b91)

I traced where we use `xml-rs` and it's only for `wayland-scanner@0.29`, if we update wayland scanner to 0.30, there will be no issue as they removed `xml-rs` in favor of `quick-xml` here https://github.com/Smithay/wayland-rs/commit/f19bab151010ff77b270fbb9ecb0254699b91368

**Comment by erwanvivien** [comment]
I've updated winit and got and update so my bad for the issue, I also saw that there was a bump of wayland version so, no worries 😅 
```
    Updating xml-rs v0.8.13 -> v0.8.14
```

**Comment by kchibisov** [comment]
wayland scanner is compile time dep anyway, so even updating not a big deal.
