### ISSUE TITLE
Change with_parent_window or re-export RawWindowHandle

### ISSUE THREAD

**Issue by ecton** [rust-windowing/winit#2913]
I've been working on a little wrapper for winit, and I originally thought I would be able to avoid depending on raw-window-handle by giving users access to the winit Window which implements `RawWindowHandle`.

My wrapper I'm building is multi-threaded, and I can't send a winit WindowBuilder across threads due to some x11 types not being Send. So, I've recreated my own WindowBuilder, and in an effort to support `with_parent_window`, I realized I cannot actually `WindowBuilder::with_parent_window` providing it a `winit::window::Window`. Instead, I must explicitly use the `RawWindowHandle` trait. This forces my crate to have two dependencies, instead of just winit. This is obviously a very minor issue, but part of me wishes I didn't have to add this dependency.

In my opinion, offering a public API that can't be used without first adding another dependency is a friction point that should be avoided for end users of crates. I would suggest two solutions to this friction point:

- Re-export `RawWindowHandle` so that users of winit can call `raw_window_handle()` on `winit::window::Window` without adding an entry to their Cargo.toml.
- Change `with_parent_window` to accept a generic parameter that implements `RawWindowHandle`, allowing winit to acquire the handle via the trait rather than requiring the user to call the trait directly.

Thank you for the wonderful library.

**Comment by kchibisov** [comment]
>My wrapper I'm building is multi-threaded, and I can't send a winit WindowBuilder across threads due to some x11 types not being Send. So, I've recreated my own WindowBuilder, and in an effort to support with_parent_window, I realized I cannot actually WindowBuilder::with_parent_window providing it a winit::window::Window. Instead, I must explicitly use the RawWindowHandle trait. This forces my crate to have two dependencies, instead of just winit. This is obviously a very minor issue, but part of me wishes I didn't have to add this dependency.

Aside from the issue, but why you'd want to send a `WindowBuilder` across the threads if you can only create a window on the thread event loop is on? Do you send requests with `WindowBuilder` from other threads to build a window on the main thread?

**Comment by ecton** [comment]
> Do you send requests with WindowBuilder from other threads to build a window on the main thread?

Yes. The wrapper I'm writing creates a one-thread-per-window model, which I'm fond of, as no single window can block the event loop or each other.

**Comment by ecton** [comment]
Correct. Or more specifically, an Arc-clone of it, because the event loop thread maintains a collection of open windows.

**Comment by daxpedda** [comment]
I just briefly research this and unfortunately using a generic here isn't possible because `RawWindowHandle` itself doesn't implement a common trait, see https://github.com/rust-windowing/raw-window-handle/issues/49.

I'm down with re-exporting `raw_window_handle`, I do agree with ecton that a libraries public API shouldn't include types that require users to add another dependency to use.

Looking at the API guidelines, I couldn't find anything but https://github.com/rust-lang/api-guidelines/discussions/176, which is inconclusive.

**Comment by kchibisov** [comment]
I guess I'd better reexport raw-window-handle.
