### ISSUE TITLE
status of `winit::platform::macos` on `aarch64-apple-darwin` toolchain?

### ISSUE THREAD

**Issue by SyedFasiuddin** [rust-windowing/winit#3025]
just that

**Comment by SyedFasiuddin** [comment]
I just did `cargo add winit` on `aarch64-apple-darwin` and tried to use the `winit::platform::maros` and I'm unable to, docs.rs in its platforms section doesn't show aarch for darwin it has x86_64 darwin

**Comment by kchibisov** [comment]
`docs.rs` is a hosting site which builds whatever targets we tell it to build and we specify `x86_64` because there's no difference.

Use `cargo doc --open -p winit`.
