### ISSUE TITLE
Regression: All touch event phases that were previously `Moved` are now `Cancelled`

### ISSUE THREAD

**Issue by MultisampledNight** [rust-windowing/winit#3035]
Setup: Sway 1.8.1/Hyprland 0.25.0 on NixOS 23.05. Observable in `0.29.1-beta`, not present in `0.28.3`. Bisect with 309e6aa85ae60104308d039763d28f42d6fe1595 as bad and 64a97c16c74ac12c81d0601d1a38ee8e3f623a81 as good has lead to 249609889029af3e5ec19afbd02464e11a265378 as the **first bad** commit. Since that is the commit where wayland-client is updated to 0.30, the issue might stem from wayland-client, but I'm not exactly sure if that's the case.

Again I've setup a small testing app at https://github.com/MultisampledNight/winit-testing-grounds/tree/7f65d463b08a042bb8d7ef946df68364efff481c which can be used to confirm that, given a touch-capable device. When tapping anywhere in the created window after launch, the current touch phase and position are printed to stderr.

### Expected

For the phase to go `Started` → `Moved` → `Ended`/`Cancelled`.

### Actual

- On `0.29.1-beta`, the phase actually goes `Started` → `Cancelled` → `Ended`/`Cancelled`
- On `0.28.3`, everything behaves as expected

**Comment by ondra05** [comment]
Setup: GNOME Shell / Mutter 44.3 on Fedora Linux 38.20230808.0 (Silverblue), used Intel® HD Graphics 630.

I do confirm this issue. When I tap it goes Started / Ended but dragging on the area causes `Cancelled`.

**Comment by kchibisov** [comment]
Could you test this https://github.com/rust-windowing/winit/pull/3065 ?

**Comment by MultisampledNight** [comment]
It fixes the issue indeed! Thank you!
