### ISSUE TITLE
Move `Event::RedrawRequested` to `WindowEvent`

### ISSUE THREAD

**Issue by daxpedda** [rust-windowing/winit#3047]
Not entirely sure what the history of this is, but I would argue that it would make more sense to live in `WindowEvent`.

Happy to do the PR if we are all in agreement.

**Comment by madsmtm** [comment]
Fully agree, something I've been wanting to do as well.

**Comment by kchibisov** [comment]
+1 on this one, though, some clients like to handle this event separately.
