### ISSUE TITLE
Invalid text in KeyEvent on Linux after recent change

### ISSUE THREAD

**Issue by Riateche** [rust-windowing/winit#3079]
`KeyEvent::text` always contains a lowercase Latin letter, even if the current layout uses another language. Pressing Shift while typing still produces a lowercase letter. This issue first appeared in bb9b629b.

**Comment by madsmtm** [comment]
CC @notgull

**Comment by notgull** [comment]
Confirmed this issue on my end. Standby for a fix.

**Comment by notgull** [comment]
This code appears to be the issue, as it appears that reverting it to the old implementation of `select_xkb_events` fixes the issue.

https://github.com/rust-windowing/winit/blob/8fdd81ecefd39e70c7b464ad642164814bb00fee/src/platform_impl/linux/x11/util/input.rs#L19-L34

**Comment by kchibisov** [comment]
@notgull maybe the keymap stuff is not delivered?

**Comment by notgull** [comment]
> @notgull maybe the keymap stuff is not delivered? 

I tried putting an explicit synchronization between the server and client before/after the event call, but nothing changes. My current working theory is that the `XkbUseExtension` internal function is doing something else that I don't quite understand yet.
