### ISSUE TITLE
Update wayland DPI documentation

### ISSUE THREAD

**Issue by mahkoh** [rust-windowing/winit#3100]
Documentation still says that scaling is

- per screen
- an integer

Both haven't been true for some time.

**Comment by kchibisov** [comment]
Could you link where have you found that? I find a hard time figuring out where you got this from.

**Comment by mahkoh** [comment]
https://docs.rs/winit/0.29.1-beta/winit/dpi/index.html#how-is-the-scale-factor-calculated

**Comment by kchibisov** [comment]
Ah, I think in the `dpi.rs` file in the top level docs... Since the methods say how it's done actually and they are not integer.

**Comment by kchibisov** [comment]
See https://github.com/rust-windowing/winit/pull/3101
