### ISSUE TITLE
Consider giving example their own Cargo.toml files

### ISSUE THREAD

**Issue by nixpulvis** [rust-windowing/winit#3104]
I'm trying to build the `fullscreen.rs` example and it's somewhat cumbersome having to cherrypick a bunch of stuff. I assume all the examples work, but I haven't gotten it building quite yet.

**Comment by nixpulvis** [comment]
Actually, I'm not sure all the examples work...

```rust
error[E0432]: unresolved import `winit::event::KeyEvent`
 --> src/gui.rs:5:41
  |
5 | use winit::event::{ElementState, Event, KeyEvent, WindowEvent};
  |                                         ^^^^^^^^ no `KeyEvent` in `event`
```

Or am I doing something wrong?

**Comment by nixpulvis** [comment]
Yep, doing something wrong. `cargo run --example fullscreen` from a fresh clone of winit works no problem...

**Comment by nixpulvis** [comment]
Oh nice, the `0.29` beta seems to fix some things...

Now I'm stuck on this:

```rust
error[E0593]: closure is expected to take 3 arguments, but it takes 2 arguments
  --> src/gui.rs:54:16
   |
54 |     event_loop.run(move |event, elwt| {
   |                ^^^ ------------------ takes 2 arguments
   |                |
   |                expected closure that takes 3 arguments
```

weird.

**Comment by nixpulvis** [comment]
OK, screw it. I just referenced `master` directly. Now I get this error:

```rust
error[E0502]: cannot borrow `self` as immutable because it is also borrowed as mutable
  --> src/gui/fill.rs:39:56
   |
38 |           fn surface(&mut self, w: &Window) -> &mut Surface {
   |                      - let's call the lifetime of this reference `'1`
39 |               self.surfaces.entry(w.id()).or_insert_with(|| {
   |               ---------------------------                ^^ immutable borrow occurs here
   |               |
   |  _____________mutable borrow occurs here
   | |
40 | |                 unsafe { Surface::new(&self.context, w) }
   | |                                        ------------ second borrow occurs due to use of `self` in closure
41 | |                     .expect("Failed to create a softbuffer surface")
42 | |             })
   | |______________- returning this value requires that `self.surfaces` is borrowed for `'1`
```

WTF is going on!?

**Comment by kchibisov** [comment]
I have no idea what you're doing, but the code failing is not inside the winit. Consult the changelog entry on what was changed and ho w to fix that.

**Comment by kchibisov** [comment]
All examples are built on `CI`, so they all built just fine.

**Comment by nixpulvis** [comment]
> I have no idea what you're doing, but the code failing is not inside the winit.

I copied the code from https://github.com/rust-windowing/winit/blob/master/examples/util/fill.rs verbatim, so IDK...

> Consult the changelog entry on what was changed and ho w to fix that.

Will do.

**Comment by nixpulvis** [comment]
Ah, it seems I had to set the Rust `edition = 2021`. I guess this is what I get for not following the release notes anymore. Ugh.

**Comment by nixpulvis** [comment]
@kchibisov is there a good example of how to request redraw on an interval timer? or as a response to a buffer being changed?

**Comment by kchibisov** [comment]
>Ah, it seems I had to set the Rust edition = 2021. I guess this is what I get for not following the release notes anymore. Ugh.

I had this issue the other day with sctk, I don't remember the clousures thing changing as well.

>@kchibisov is there a good example of how to request redraw on an interval timer? or as a response to a buffer being changed?

Well, alacritty code is doing exactly that now. You can sort of get familiar with it or remember. If you want app to run on `web`/`wayland` throttling is done with the `request_redraw` automatically.
