### ISSUE TITLE
IME on Windows does not work with multi-threading

### ISSUE THREAD

**Issue by fredizzimo** [rust-windowing/winit#3123]
Sorry for the vague bug report. 

We have trouble with the IME system on Windows where we use a separate render thread, for example the positions are not updating. I have not looked further into it, but it appears like it's not safe to use in a multi-threaded manner by default.

https://learn.microsoft.com/en-us/windows/win32/intl/developing-ime-aware-multiple-thread-applications.

So that seems like the most likely reason. I think we can work around this on the Neovide side, but it would be nice if the user did not have to care.

**Comment by fredizzimo** [comment]
I guess the simplest implementation would be to use a single IME context, the default, and run all the `Imm*` functions on the main thread. Otherwise there needs to be an API for creating contexts associated with threads, and I don't really see a use case for multiple contexts, especially since it's not supported on all platforms.

**Comment by kchibisov** [comment]
Doing main-thread roundtrips sounds good enough. Windows backend already has a main thread running so should ok to add?

**Comment by fredizzimo** [comment]
Yes, at least in our case that should be enough.
