### ISSUE TITLE
How to set canvas to full size in web?

### ISSUE THREAD

**Issue by RicardoHS** [rust-windowing/winit#3140]
I've looking through some issues in the repo but I see no clear way on how to do such thing.

Any instructions on how to proceed?

**Comment by daxpedda** [comment]
Winit provides no way to do this.
You can do this on your end by simply setting the size (`width` and `height`) of the canvas to `100%` with CSS. This is also doable through `web-sys`.

Eventually Winit will support this when https://github.com/rust-windowing/winit/issues/696 is tackled.

**Comment by RicardoHS** [comment]
Thanks for the info. I finally managed to achieve this with some adjustems of #1491 

I will leave the code here in case anyone found it helpfull

```rust
let window = WindowBuilder::new().build(&event_loop).unwrap();

web_sys::window().and_then(|win| {
    let width = win.inner_width().unwrap().as_f64().unwrap() as u32;
    let height = win.inner_height().unwrap().as_f64().unwrap() as u32;
    let factor = window.scale_factor();
    let logical = LogicalSize { width, height };
    let PhysicalSize { width, height }: PhysicalSize<u32> = logical.to_physical(factor);
    window.set_inner_size(PhysicalSize::new(width, height));
    Some(())
});
```

And the CSS

```css
* { margin:0; padding:0; } 
html, body { width:100%; height:100%; }
canvas {
    background-color: black;
    display:block;
}
```
