### ISSUE TITLE
Guarantee sending WindowEvent::Resized on window creation?

### ISSUE THREAD

**Issue by dhardy** [rust-windowing/winit#3192]
Testing shows my app always receives `WindowEvent::Resized` after window creation (tested on Wayland and X11). Great, can I rely on it (avoid setting up the surface until receiving `Resized`)?

The same applies to `ScaleFactorChanged` which is received on Wayland but not X11. A guarantee that it will always be sent on start (at least when not 1) would allow simpler app logic.

I don't see any documentation in this regard and haven't checked other platforms, but can make a PR if requested.

**Comment by kchibisov** [comment]
I think on Wayland it's always send as long as it's not `1`. We can probably try to do so, but I really want to just get rid of the events in the current form all together, since we're solving problem that shouldn't even exist...

**Comment by dhardy** [comment]
The same applies to a trait-based solution: guaranteeing a call to `resize` after window creation simplifies app logic.

The current situation is actually a bit worse (Wayland):
```
# Initial constraints with scale_factor=1:
[2023-10-26T16:06:11Z DEBUG kas_core::layout::sizer] find_constraints: min=Size(326, 143), ideal=Size(378, 677), margins=Margins { horiz: (0, 0), vert: (0, 0) }
# Updated constraints with scale_factor=1.5:
[2023-10-26T16:06:11Z DEBUG kas_core::layout::sizer] find_constraints: min=Size(508, 220), ideal=Size(569, 1042), margins=Margins { horiz: (0, 0), vert: (0, 0) }
[2023-10-26T16:06:11Z INFO  kas_core::shell::window] new: constructed with physical size Size(569, 1043), scale factor 1.5
# ...
WindowEvent::ScaleFactorChanged(1.5)
# This is a queued resize?
WindowEvent::Resized(PhysicalSize { width: 567, height: 1016 })
# Now the real resize:
WindowEvent::Resized(PhysicalSize { width: 569, height: 1043 })
```

**Comment by kchibisov** [comment]
>The same applies to a trait-based solution: guaranteeing a call to resize after window creation simplifies app logic.

it's just all the logic will be different, but probably simpler.

@dhardy could you post a `WAYLAND_DEBUG=1` log for me actually? We don't queue anything on wayland.

**Comment by dhardy** [comment]
https://gist.github.com/dhardy/83e48fe7b83042fb6f8602dcbc79d088

**Comment by dhardy** [comment]
The same is true of `Window::request_inner_size`: having to handle two paths in the app (immediate or postponed resize) should not be necessary.

**Comment by kchibisov** [comment]
>The same is true of Window::request_inner_size: having to handle two paths in the app (immediate or postponed resize) should not be necessary.

But why should we do `async` roundtrip with all of that? You do understand that your resize will have to go thread the event loop and back to you, while in reality you don't need any of that on Wayland? And you handle the resize logic in some handler if you want to or just mark the state as resized and run the resize logic.

It's sort of common...

**Comment by dhardy** [comment]
Great for Wayland but a slight pain to code for multiple platforms when an event-loop round-trip should be cheap. But it isn't important.

**Comment by kchibisov** [comment]
The thing is that you could just have a function to handle resize separate from `resize` and `request_inner_size`, it's just on Wayland the user controls the size, this is quite unique and I don't see why we need a rountrip.

It was discussed in the past when I brought the `request_inner_size`. I really don't see a big issue in any of that. You also sometimes know that something was not resized at all.

**Comment by kchibisov** [comment]
```
11:[  59468.112] wl_registry@2.global(10, "wp_fractional_scale_manager_v1", 1)
56:[  59468.669]  -> wl_registry@2.bind(10, "wp_fractional_scale_manager_v1", 1, new id [unknown]@9)
70:[  59468.964] wl_output@5.scale(2)
105:[  59510.513] wl_registry@2.global(10, "wp_fractional_scale_manager_v1", 1)
173:[  59538.480] wl_registry@2.global(10, "wp_fractional_scale_manager_v1", 1)
240:[  59542.241] wl_registry@2.global(10, "wp_fractional_scale_manager_v1", 1)
304:[2023-10-26T16:25:02Z DEBUG kas_core::event] full_configure of Window#1
313:[  59609.195]  -> wp_fractional_scale_manager_v1@9.get_fractional_scale(new id wp_fractional_scale_v1@29, wl_surface@24)
327:[  59609.731] wp_fractional_scale_v1@29.preferred_scale(180)
328:[  59609.736] zxdg_toplevel_decoration_v1@27.configure(1)
330:[  59609.744] xdg_toplevel@26.configure_bounds(2488, 1440)
331:[  59609.748] xdg_toplevel@26.configure(0, 0, array[0])
332:[  59609.752] xdg_surface@25.configure(39634)
333:[  59611.184]  -> xdg_surface@25.ack_configure(39634)
373:[2023-10-26T16:25:02Z INFO  kas_core::shell::window] new: constructed with physical size Size(569, 1043), scale factor 1.5
403:[  59629.306] wl_registry@43.global(10, "wp_fractional_scale_manager_v1", 1)
410:[  59629.331] wl_registry@45.global(10, "wp_fractional_scale_manager_v1", 1)
530:[  59638.182] wl_registry@39.global(10, "wp_fractional_scale_manager_v1", 1)
608:[  59638.519] wl_registry@33.global(10, "wp_fractional_scale_manager_v1", 1)
684:[  59638.948] wl_registry@30.global(10, "wp_fractional_scale_manager_v1", 1)
791:WindowEvent::ScaleFactorChanged(1.5)
792:WindowEvent::Resized(PhysicalSize { width: 567, height: 1016 })
793:Surface resize from Size(569, 1043) to Size(567, 1016)
808:[  59641.703] wl_registry@54.global(10, "wp_fractional_scale_manager_v1", 1)
884:[  59642.025] wl_registry@50.global(10, "wp_fractional_scale_manager_v1", 1)
1020:[  59653.347] xdg_toplevel@26.configure(379, 695, array[4])
1021:[  59653.355] xdg_surface@25.configure(39641)
1023:[  59653.502]  -> xdg_surface@25.ack_configure(39641)
1030:WindowEvent::Resized(PhysicalSize { width: 569, height: 1043 })
1031:Surface resize from Size(567, 1016) to Size(569, 1043)
1043:[  59653.831] wl_registry@51.global(10, "wp_fractional_scale_manager_v1", 1)
1119:[  59654.189] wl_registry@32.global(10, "wp_fractional_scale_manager_v1", 1)
1325:[  61510.077]  -> wp_fractional_scale_v1@29.destroy()

```

It's just `KDE` decided to resize you, the event was not queued at all. Though, from the log I'd like to change some minor thing and remove all of that surface deletions since you hide the frame from what I can see.

**Comment by kchibisov** [comment]
>331:[  59609.748] xdg_toplevel@26.configure(0, 0, array[0])

That's initial configure where winit used the `inner_size` you provided during build.

>1020:[  59653.347] xdg_toplevel@26.configure(379, 695, array[4])

That's kwin just send us for whatever reason.

**Comment by dhardy** [comment]
Is this an attempt to restore the previous size and position? If so, it would be good to have a way of accepting that without requesting another resize (provided certain constraints are met).

**Comment by kchibisov** [comment]
I don't know, winit has no control over that, it's all on kwin.

**Comment by kchibisov** [comment]
btw, if you try to create a window with decorations do you see this happening?

**Comment by dhardy** [comment]
Yes.

**Comment by kchibisov** [comment]
idk, I'd ask kwin folks on that matter.

**Comment by dhardy** [comment]
It's definitely not an attempt to restore the previous window size but probably is due to kwin not merging batched resizes...

... however, I notice that `WindowState::configure` does call `resize` and hence `set_window_geometry` gets called twice from my `Window::resume` method (when the window is initially constructed to get the scale factor, and when I set the recalculated size).

This ties in to the original topic of this issue and your redesign: could window creation be a two-step process, perhaps requiring the user to resize the window immediately after construction?

**Comment by kchibisov** [comment]
>This ties in to the original topic of this issue and your redesign: could window creation be a two-step process, perhaps requiring the user to resize the window immediately after construction?

I'll just add a hook to finish window building on handling `None` better, since we can actually get replies back. But yeah, if you resize yourself `kwin` could decide to send a confirmation with `configure` back, but some stacking wms.

**Comment by kchibisov** [comment]
That would be nice but it's hard to guarantee that because X11 is async, so we wait until we get the event back, and we may not really get it back.

**Comment by dhardy** [comment]
... I've now encountered a case (on X11) where `Resized` does not occur *at all* after `request_inner_size` returns `None`. I guess at this point I should just accept that the only viable option is to resize the app immediately even when a window size change is expected, so we can close this issue.

```
[2024-02-24T18:18:35Z DEBUG kas_core::event] full_configure of Window#1
[2024-02-24T18:18:35Z TRACE kas_perf::layout] find_constraints: 4μs
[2024-02-24T18:18:35Z DEBUG kas_core::layout::sizer] find_constraints: min=Size(64, 64), ideal=Size(192, 192), margins=Margins { horiz: (0, 0), vert: (0, 0) }
[2024-02-24T18:18:35Z TRACE kas_perf::layout] find_constraints: 1μs
[2024-02-24T18:18:35Z DEBUG kas_core::layout::sizer] find_constraints: min=Size(75, 75), ideal=Size(224, 224), margins=Margins { horiz: (0, 0), vert: (0, 0) }
Window created with size PhysicalSize { width: 224, height: 224 }, requested size LogicalSize { width: 192.0, height: 192.0 }
[2024-02-24T18:18:35Z INFO  kas_core::app::window] Window::resume: constructed with physical size Size(224, 224), scale factor 1.1666666666666667; immediate sizing: false
[2024-02-24T18:18:35Z TRACE kas_perf::wgpu::window] resume: 1081µs
[2024-02-24T18:18:35Z TRACE kas_core::app::event_loop] WindowEvent: Ime(Disabled)
[2024-02-24T18:18:35Z TRACE kas_core::app::event_loop] WindowEvent: RedrawRequested
[2024-02-24T18:18:35Z DEBUG kas_core::app::window] Ignoring redraw request before window is (re)sized.
```

**Comment by kchibisov** [comment]
I mean it tells so that it may not result in resize at all, because your request will be ignored. And also hence it's name `request` and not `set` anymore.

Only Wayland is easy here(and maybe macOS) because the user controls the size.
