### ISSUE TITLE
Docs no longer give clear instructions on how to hook in a game loop

### ISSUE THREAD

**Issue by DevJac** [rust-windowing/winit#3199]
The [docs used to say](https://docs.rs/winit/0.28.7/winit/event/enum.Event.html#variant.MainEventsCleared):

> MainEventsCleared
> 
> Emitted when all of the event loop’s input events have been processed and redraw processing is about to begin.
> 
> **This event is useful as a place to put your code that should be run after all state-changing events have been handled and you want to do stuff (updating state, performing calculations, etc) that happens as the “main body” of your event loop.** If your program only draws graphics when something changes, it’s usually better to do it in response to [Event::RedrawRequested](https://docs.rs/winit/0.28.7/winit/event/enum.Event.html#variant.RedrawRequested), which gets emitted immediately after this event. **Programs that draw graphics continuously, like most games, can render here unconditionally for simplicity.**

The [current docs say something similar](https://docs.rs/winit/latest/winit/event/enum.Event.html#variant.AboutToWait), but don't give complete advice:

> 
> AboutToWait
> 
> Emitted when the event loop is about to block and wait for new events.
> 
> Most applications shouldn’t need to hook into this event since there is no real relationship between how often the event loop needs to wake up and the dispatching of any specific events.
> 
> High frequency event sources, such as input devices could potentially lead to lots of wake ups and also lots of corresponding AboutToWait events.
> 
> **This is not an ideal event to drive application rendering from and instead applications should render in response to [WindowEvent::RedrawRequested](https://docs.rs/winit/latest/winit/event/enum.WindowEvent.html#variant.RedrawRequested) events.**

The problem is that hooking into `RedrawRequested` will not redraw the window continuously like we want for a game loop. Where should we hook in the repeated `request_redraw` calls needed for a game loop?

**Comment by kchibisov** [comment]
you should draw in response to `RedrawRequested` if you want to side step all of that use `pump_events`, but I recommend against it. `AboutToWait` could be used just as fine, it's just on web it's still more reliable to use `RedrawRequested` and ask for redraws.

**Comment by DevJac** [comment]
That is incomplete advice. If I follow that advice and draw *only* in response to `RedrawRequested`, then my game will just sit there not rendering anything unless I move the mouse or resize the window.

**Comment by kchibisov** [comment]
Have you tried asking to redraw yourself? https://docs.rs/winit/latest/winit/event/enum.WindowEvent.html#variant.RedrawRequested

**Comment by kchibisov** [comment]
>The application has explicitly requested a redraw via [Window::request_redraw](https://docs.rs/winit/latest/winit/window/struct.Window.html#method.request_redraw).

If your game needs to draw just ask to draw.

**Comment by DevJac** [comment]
Yes. I end my `RedrawRequested` event handling with a `Window::Request_redraw`. It works, but it feels a little weird to be requesting a redraw while handling a redraw.

Would it be better to request redraws in `NewEvents` or `AboutToWait`?

**Comment by kchibisov** [comment]
Request a redraw when you feel like it, but unless you're using `Poll`, `NewEvents` won't work. You can ask in `AboutToWait` if you want to.

**Comment by DevJac** [comment]
You're right, requesting redraw from `AboutToWait` does work.

In a sense, requesting a redraw from `AboutToWait` is driving application rendering from the `AboutToWait` handler, and the `AboutToWait` docs specifically say "this is not an ideal event to drive application rendering from". The `request_redraw` in `AboutToWait` must be the *driving* force because if I remove it then no rendering happens.

Or, as I've been doing, you can request redraws from the `RedrawRequested` handler. This seems like circular logic to me though, because the code that *drives* the rendering by requesting redraws is the same code that handles the redraw requests.

**Comment by kchibisov** [comment]
Well, you generally just ask for redraw when you want to redraw. If you want to just spin the loop use `Poll`.

Asking for redraw from `RedrawRequested` could be the right thing on web though. Requesting for redraw just means that you notify that you want to draw, winit will deliver the event back to you when there's a time for it. The docs on `Window::request_redraw` should be more or less explicit on that matter.

it's just there's no good answer and every case is specific to the application you're writing. I'd probably just asked from `RedrawRequested` and as a fallback in `AboutToWait`, the event is squashed anyway.
