### ISSUE TITLE
How to prohibit winit from drawing a white background before the first frame is drawn by wgpu?

### ISSUE THREAD

**Issue by ZhangXiChang** [rust-windowing/winit#3208]
![52A4A19FC0C94358A2B39A175A7B7CC1](https://github.com/rust-windowing/winit/assets/68778073/7f01ceed-12d8-4f74-a522-92d8f6fc1494)
As shown in the figure, setting the resolution is relatively large, such as 1600x900 will appear this situation.

**Comment by kchibisov** [comment]
winit doesn't draw anything, in general you could start window invisible.

**Comment by ZhangXiChang** [comment]
> winit doesn't draw anything, in general you could start window invisible.

I solved this problem by hiding the window before creating the swap chain.
