### ISSUE TITLE
Change dependency "raw-window-handle" to exclude the feature "std"

### ISSUE THREAD

**Issue by Xx-EvilPanda-xX** [rust-windowing/winit#3223]
When using feature "rwh_05", a dependency cannot be resolved. Specifically, the dependency "raw-window-handle" version ^0.5 (locked to 0.5.0) does not have a feature flag "std". This feature is only introduced in version 0.5.2, but an attempt for its use is being made for version 0.5.0.

line 62 in winit/Cargo.toml:
rwh_05 = { package = "raw-window-handle", version = "0.5", features = ["std"], optional = true }`

This is fixable by either removing the constraint of using feature "std", or by changing the raw-window-handle version to at least 0.5.2.

**Comment by madsmtm** [comment]
You could run `cargo update` instead, and let cargo bump your locked version to `v0.5.2`?

**Comment by alexheretic** [comment]
As already suggested an easy fix is bumping the rwh_05 min version to `0.5.2`, since it won't build on earlier versions that lacked "std" feature.
