### ISSUE TITLE
Cannot compile app with eyra due error `undefined reference to `setlocale'`

### ISSUE THREAD

**Issue by qarmin** [rust-windowing/winit#3230]
When trying to compile gui app with [eyra](https://github.com/sunfishcode/eyra/tree/main) enabled, I got this errors when linking app

```
  = note: LC_ALL="C" PATH= ... /deps/krokiet-56df5367c2904a85" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-nostartfiles"
  = note: /usr/bin/ld: /home/rafal/Projekty/Rust/czkawka/target/debug/deps/libi_slint_backend_winit-b3db1449698ef22e.rlib(i_slint_backend_winit-b3db1449698ef22e.i_slint_backend_winit.a0f24300e3a6e2b6-cgu.15.rcgu.o): in function `winit::platform_impl::platform::x11::EventLoop<T>::new':
          /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/x11/mod.rs:213:(.text._ZN5winit13platform_impl8platform18EventLoop$LT$T$GT$3new17hbe182808a2c15b4aE+0x493): undefined reference to `setlocale'
          /usr/bin/ld: /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/x11/mod.rs:214:(.text._ZN5winit13platform_impl8platform18EventLoop$LT$T$GT$3new17hbe182808a2c15b4aE+0x4ad): undefined reference to `setlocale'
          /usr/bin/ld: /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/x11/mod.rs:221:(.text._ZN5winit13platform_impl8platform18EventLoop$LT$T$GT$3new17hbe182808a2c15b4aE+0x4cd): undefined reference to `setlocale'
          /usr/bin/ld: /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/x11/mod.rs:228:(.text._ZN5winit13platform_impl8platform18EventLoop$LT$T$GT$3new17hbe182808a2c15b4aE+0x61f): undefined reference to `setlocale'
          collect2: error: ld returned 1 exit status
```

**Comment by kchibisov** [comment]
have you tried compiling with standard libc?

**Comment by qarmin** [comment]
With standard libc everything works fine, but I wanted to check if fully(almost) rust gui app is possible to compile

**Comment by kchibisov** [comment]
Well, we need `setlocale`, it's a _standard_ function and external libraries, like libxkbcommon rely on locale to provide compose tables for users.

**Comment by qarmin** [comment]
Is there any rust-only alternative provided e.g. by rustix?

**Comment by kchibisov** [comment]
no, locales are part of the libc you don't have syscalls for them.

**Comment by kchibisov** [comment]
Also, we'll always link to system C libraries, there's no way around that, unless you want something very constrained or you have infinite amount of time to reimplement all the stack for no real reason.

**Comment by sunfishcode** [comment]
@qarmin Eyra has enough limitations that chances are any problems you hit are problems with Eyra, so the Eyra repo is generally a better place for these kinds of issues and questions. I'll add more followup in the [discussion thread](https://github.com/sunfishcode/eyra/discussions/26) there!
