### ISSUE TITLE
Window not appearing when running winit event loop in WSL

### ISSUE THREAD

**Issue by NitishNaineni** [rust-windowing/winit#3232]
I'm trying to create a window using the `winit` crate, but the window is not appearing when I run the program. I have verified that other GUI apps work and WSL is configured correctly. Here's the code I'm using:

```rust
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    env_logger::init();
    let event_loop = EventLoop::new().unwrap();
    let window = WindowBuilder::new().build(&event_loop).unwrap();

    event_loop.set_control_flow(ControlFlow::Poll);

    let _ = event_loop.run(move |event, elwt| {
        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => {
                println!("The close button was pressed; stopping");
                elwt.exit();
            },
            Event::AboutToWait => {
                // Application update code.
                window.request_redraw();
            },
            Event::WindowEvent {
                event: WindowEvent::RedrawRequested,
                ..
            } => {
                // Redraw the application.
            },
            _ => ()
        }
    });
}
```

When I run this program, I expect to see an empty window pop up, but nothing happens. There are no error messages in the console output or log files.

Here's the log output when I run the program:

> Finished dev [unoptimized + debuginfo] target(s) in 0.04s
 Running `target/debug/raycast`
[2023-11-20T01:40:06Z DEBUG sctk] Bound new global [11] wl_output v3
[2023-11-20T01:40:06Z DEBUG sctk] Bound new global [4] zxdg_output_manager_v1 v2
[2023-11-20T01:40:06Z DEBUG sctk] Bound new global [19] wl_seat v7
[2023-11-20T01:40:06Z DEBUG sctk] supported wl_shm format Argb8888
[2023-11-20T01:40:06Z DEBUG sctk] supported wl_shm format Xrgb8888
[2023-11-20T01:40:06Z DEBUG sctk] supported wl_shm format Rgb565
[2023-11-20T01:40:06Z DEBUG sctk_adwaita::buttons] Ignoring "appmenu" button

Do i need to post any more information?

**Comment by kchibisov** [comment]
on wayland you must draw to get a window visible
