### ISSUE TITLE
Pressing `Fn` key on Macbook logs an error

### ISSUE THREAD

**Issue by emilk** [rust-windowing/winit#3246]
Pressing the `Fn` key on a MacBook keyboard (macOS Ventura 13.4.1) prints the following error:

> [2023-11-28T12:46:14Z ERROR winit::platform_impl::platform::event] `UCKeyTranslate` was succesful but gave a string of 0 length.

**Comment by emilk** [comment]
I'm on `0.29.4`

**Comment by kchibisov** [comment]
Yeah, it's just doesn't happen for me iirc and I can't update further 12 version. You could send a patch, should be fairly easy.

The start chain for that is from update flags stuff in macos platform.

**Comment by emilk** [comment]
It could be that I have two keyboard layouts (English and Swedish), and pressing `Fn` switches between the two.
In any case, a PR is incoming!
