### ISSUE TITLE
(Wayland) receiving a `Resized` event on every focus change

### ISSUE THREAD

**Issue by MarijnS95** [rust-windowing/winit#3263]
Since `0.29.x` / `main`, every time the user clicks in and out of a Wayland window a `Resized` event is sent. Some debugging shows that it originates from `WindowHandler::configure()`.

Is this expected, and can it be circumvented somehow? The size is always the same so I can debounce it, but it seems strange to receive it so often.

Other backends don't do this, like X (tested by setting `WAYLAND_DISPLAY=` to use Xwayland).

**Comment by kchibisov** [comment]
it's because the configure is sent every time, you can micro optimize in winit to not do so. Usually you don't resize to the same which matches your current size?

**Comment by MarijnS95** [comment]
Any clue why this wasn't happening on `0.28.x`? Just making sure we aren't doing something strange before I ignore resizes to the same size.

**Comment by kchibisov** [comment]
it had micro optimization I told you :p
