### ISSUE TITLE
Bus error when changing cursor

### ISSUE THREAD

**Issue by jeffs** [rust-windowing/winit#3267]
Pressing the space bar seven times in the cursor example causes the program to crash with a bus error on macOS Sonoma 14.2.

1. Run the example.
    ```sh
    $ git checkout v0.29.4
    $ cargo run --example cursor
    ```
2. Focus the example window.
3. Press the space bar seven times (trying to load CursorIcon::Help).
4. The program crashes.
    ```
    Setting cursor to "Help"
    TRACE [winit::platform_impl::platform::view] Triggered `resetCursorRects`
    TRACE [winit::platform_impl::platform::view] Completed `resetCursorRects`
    [1]    9362 bus error  cargo run --example cursor
    ```

**Comment by madsmtm** [comment]
Hmm, using Sonoma 14.2 (23C64) myself, and I can't seem to reproduce this?

Do the other cursors work for you?

**Comment by madsmtm** [comment]
What's your system specs? I'm interested in the output of `rustc --version --verbose`, your Xcode version, and the hardware you're running on.

**Comment by madsmtm** [comment]
And would you be able to get a backtrace somehow? Maybe by attaching a debugger?

**Comment by jeffs** [comment]
> Hmm, using Sonoma 14.2 (23C64) myself, and I can't seem to reproduce this?
> 
> Do the other cursors work for you?

These all seem to cause the same issue, but I've only just been poking at it:

```rs
CursorIcon::Help,
CursorIcon::ContextMenu,
CursorIcon::VerticalText,
CursorIcon::Alias,
CursorIcon::EResize,
CursorIcon::NResize,
CursorIcon::NeResize,
CursorIcon::NwResize,
CursorIcon::SResize,
CursorIcon::WResize,
```

**Comment by jeffs** [comment]
> What's your system specs? I'm interested in the output of `rustc --version --verbose`

```sh
$ rustc --version --verbose
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: aarch64-apple-darwin
release: 1.73.0
LLVM version: 17.0.2
```

> your Xcode version

```
$ xcodebuild --version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

$ /Library/Developer/CommandLineTools/usr/bin/c++ --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

> and the hardware you're running on.

MacBook Pro
16-inch, 2023
Apple M2 Pro
32 GB

**Comment by jeffs** [comment]
I hit a similar (but maybe unrelated?) issue hiding the cursor.  See https://github.com/rust-windowing/winit/issues/3268.

**Comment by madsmtm** [comment]
> rustc --version --verbose

I tried with Rust 1.73 instead, still can't reproduce.

> Xcode version

I tried with `sudo xcode-select -switch /Library/Developer/CommandLineTools`, still can't reproduce.

> hardware you're running on.

I have basically the same specs, only difference is that mine is 14 inch instead of 16 inch.

---

In short, I have no idea why you're hitting this issue :/

A suggestion that seems stupid, but I'm shooting blind here: Try to restart your computer? Perhaps the AppKit framework binary somehow got corrupted?

**Comment by jeffs** [comment]
It's definitely flakey:  It doesn't always crash.  I tried running under lldb, but couldn't get the executable to crash there.  Will boot.  Any suggestions for reinstalling anything in particular?  I don't know much about modern macOS development.

**Comment by madsmtm** [comment]
Maybe I could get you to run the following Objective-C program (that way we'll be more convinced if it's winit or something else that's wrong).

```objective-c
#import <AppKit/AppKit.h>

@interface NSCursor (Undocumented)
+ (NSCursor*) _helpCursor;
@end

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSCursor* cursor;
        NSLog(@"responds to _helpCursor: %B", [NSCursor respondsToSelector: @selector(_helpCursor)]);
        cursor = [NSCursor performSelector: @selector(_helpCursor)];
        NSLog(@"help cursor: %@", cursor);
        cursor = [NSCursor _helpCursor];
        NSLog(@"help cursor direct: %@", cursor);
    }
    return 0;
}
```

**Comment by jeffs** [comment]
> Maybe I could get you to run the following Objective-C program (that way we'll be more convinced whether it's winit or something else that's wrong).

Good idea.

```sh
$ clang -framework Foundation -framework AppKit foo.m

$ ./a.out
2023-12-17 09:31:23.679 a.out[1712:14914] responds to _helpCursor: B
2023-12-17 09:31:23.679 a.out[1712:14914] help cursor: <NSCursor: 0x600003e7c000>
2023-12-17 09:31:23.679 a.out[1712:14914] help cursor direct: <NSCursor: 0x600003e7c000>
```

**Comment by madsmtm** [comment]
I updated the sample, could you try again? But so far it looks like a problem with `winit` (but again, really hard to determine without a backtrace).

**Comment by jeffs** [comment]
> I updated the sample, could you try again? So far it looks like a problem with `winit` (but again, really hard to determine without a backtrace).

```
$ clang -framework Foundation -framework AppKit bar.m

$ ./a.out
2023-12-17 09:37:30.482 a.out[3286:25370] responds to _helpCursor: 1
[1]    3286 bus error  ./a.out

$ lldb ./a.out
(lldb) target create "./a.out"
Current executable set to '/Users/jeff/issue3267/a.out' (arm64).
(lldb) run
Process 3365 launched: '/Users/jeff/issue3267/a.out' (arm64)
2023-12-17 09:38:46.857662-0500 a.out[3365:26162] responds to _helpCursor: 1
2023-12-17 09:38:46.965248-0500 a.out[3365:26162] help cursor: <NSCursor: 0x600000df80f0>
<NSImage 0x6000032f8140 Size={18, 18} RepProvider=<NSImageArrayRepProvider: 0x6000001f4830, reps:(
    "NSBitmapImageRep 0x6000028f9570 Size={18, 18} ColorSpace=Device RGB colorspace BPS=8 BPP=32 Pixels=18x18 Alpha=YES Planar=NO Format=1 CurrentBacking=<CGImageRef: 0x13df0e820>",
    "NSBitmapImageRep 0x6000028f95e0 Size={36, 36} ColorSpace=Device RGB colorspace BPS=8 BPP=32 Pixels=36x36 Alpha=YES Planar=NO Format=1 CurrentBacking=<CGImageRef: 0x13df09450>"
)>>
2023-12-17 09:38:46.966644-0500 a.out[3365:26162] zoom in cursor direct: <NSCursor: 0x600000dfcde0>
<NSImage 0x6000032f80a0 Size={20, 20} RepProvider=<NSImageArrayRepProvider: 0x6000001f5210, reps:(
    "NSBitmapImageRep 0x6000028f9f10 Size={20, 20} ColorSpace=Device RGB colorspace BPS=8 BPP=32 Pixels=20x20 Alpha=YES Planar=NO Format=1 CurrentBacking=<CGImageRef: 0x13df0f030>",
    "NSBitmapImageRep 0x6000028f9ea0 Size={40, 40} ColorSpace=Device RGB colorspace BPS=8 BPP=32 Pixels=40x40 Alpha=YES Planar=NO Format=1 CurrentBacking=<CGImageRef: 0x13df0ea70>"
)>>
Process 3365 exited with status = 0 (0x00000000)
(lldb)
```

**Comment by jeffs** [comment]
This is super flakey.  It doesn't always crash.  Will keep trying to get a stack trace.  This isn't urgent from my perspective, just confusing.

**Comment by jeffs** [comment]
To your point:  The last sample you posted has produced a couple of bus errors, which I guess implies the issue isn't winit per se?

**Comment by jeffs** [comment]
After reboot, the cursor example crashes on Crosshair rather than Help, when it crashes at all.

Feel free to close this, since it seems like it's not winit, and I'll post back with any update.

**Comment by madsmtm** [comment]
I thought it might be a `winit` thing because we _are_ using slightly undocumented features to get the help cursor; but `crosshairCursor` is definitely documented, so it really seems like there's a problem with your system.

> Any suggestions for reinstalling anything in particular

I'm not really experienced with system recovery sadly, all I know is how to run the Disk Utility to check for corruption :/

Though that the error is a bus error, and not a segmentation fault, may point to faulty hardware? But again, very unsure on this.

> Feel free to close this

Yeah, I will, good luck though!

**Comment by jeffs** [comment]
> I'm not really experienced with system recovery sadly, all I know is how to run the Disk Utility to check for corruption :/

Ha, same.

> Though that the error is a bus error, and not a segmentation fault, may point to faulty hardware? But again, very unsure on this.

"Bus error" usually means an operation was given an invalid argument, such as an address that doesn't meet the instruction's alignment requirements.  It happens sometimes when pointers get corrupted.  If this one ever gets cleared up, I'll let you know (but it's a mystery to me, too).
