### ISSUE TITLE
Bus error when hiding cursor

### ISSUE THREAD

**Issue by jeffs** [rust-windowing/winit#3268]
* Calling `window.set_cursor_visible(false)` crashes the calling process.
  - winit v0.29.4 on macOS Sonoma 14.2
* Possibly related to https://github.com/rust-windowing/winit/issues/3267.
* I ended up here trying to debug a Bevy crash when hiding the cursor.
* Here's an example program that demonstrates the issue:
  https://github.com/jeffs/winit/blob/hide-cursor/examples/hide_cursor.rs#L25

**Comment by madsmtm** [comment]
Closing as per discussion in https://github.com/rust-windowing/winit/issues/3267#issuecomment-1859193822.
