### ISSUE TITLE
`EventLoop::run_on_demand` stuck in "exiting" when rerun

### ISSUE THREAD

**Issue by alexheretic** [rust-windowing/winit#3284]
After finishing a `EventLoop::run_on_demand` run by calling `elwt.exit()` subsequent runs immediately exit.

On subsequent `run_on_demand` calls `elwt.exiting()` is `true`. I would expect exiting to be false until `exit()` is called again.

I've reproduced this issue on Linux & Macos.

## Steps to reproduce
* Run `cargo run --example window_on_demand`
* Exit window
* It hangs forever because the example never actually calls `elwt.exit()`... This is an unrelated bug in the example.

## Steps to reproduce (2)
* Fix example to call `elwt.exit()` on `CloseRequested`.
```diff
diff --git a/examples/window_on_demand.rs b/examples/window_on_demand.rs
index ca9a448a..9945319c 100644
--- a/examples/window_on_demand.rs
+++ b/examples/window_on_demand.rs
@@ -41,6 +41,7 @@ fn main() -> Result<(), impl std::error::Error> {
                     } if window.id() == window_id => {
                         println!("--------------------------------------------------------- Window {idx} CloseRequested");
                         app.window = None;
+                        elwt.exit();
                     }
                     Event::AboutToWait => window.request_redraw(),
                     Event::WindowEvent {

```
* Run `cargo run --example window_on_demand`
* Exit window
* After 5 seconds a new window is created and immediately exited without input
```
...
--------------------------------------------------------- Window 1 CloseRequested
Run 1: AboutToWait
Run 1: LoopExiting
--------------------------------------------------------- Finished first loop
--------------------------------------------------------- Waiting 5 seconds
Run 2: NewEvents(Init)
Run 2: Resumed
DEBUG [sctk_adwaita::buttons] Ignoring "appmenu" button
Run 2: WindowEvent { window_id: WindowId(WindowId(94098374278864)), event: Resized(PhysicalSize { width: 128, height: 128 }) }
Run 2: WindowEvent { window_id: WindowId(WindowId(94098374278864)), event: RedrawRequested }
Run 2: AboutToWait
Run 2: LoopExiting
--------------------------------------------------------- Finished second loop
```

**Comment by notgull** [comment]
> I've reproduced this issue on Linux & Macos.

Are you using X11 or Wayland?

**Comment by alexheretic** [comment]
> Are you using X11 or Wayland?

The behaviour is the same on both.

**Comment by kchibisov** [comment]
Try https://github.com/rust-windowing/winit/pull/3285

**Comment by alexheretic** [comment]
@kchibisov yep that fixes it, nice one :+1:

**Comment by alexheretic** [comment]
The example works now thanks. However, when I tried this with Robo Instructus only wayland is working.

x11 fails on event_loop reuse with `GLXBadWindow` (so works fine initially, but fails when I try to build another window with the event-loop).
```
OsError { 
  line: 552,
  file: "/home/alex/.cargo/git/checkouts/winit-c2fdb27092aba5a7/c12c7b8/src/platform_impl/linux/x11/window.rs",
  error: XError(Xlib(XError { description: "GLXBadWindow", error_code: 170, request_code: 150, minor_code: 32 }))
}
```

The error is emitted from winit code. Shall I make another issue for this @kchibisov ?

**Comment by kchibisov** [comment]
>The error is emitted from winit code. Shall I make another issue for this @kchibisov ?

Which version of glutin are you using if it's even glutin? Winit can't emit glx errors.

**Comment by alexheretic** [comment]
I'm using latest glutin `0.31.2`

**Comment by kchibisov** [comment]
Hm, maybe some commands are enqueued and you get reply for them? Could you try spinning the loop for a while when exiting the first iteration?

**Comment by alexheretic** [comment]
> Could you try spinning the loop for a while when exiting the first iteration?

I'm not sure I understand what you mean. I can sleep a bit between exiting the run_on_demand and re-building the window. This has no effect though.

This error is returned by glutin-winit `DisplayBuilder::build` -> `finalize_window` -> winit `WindowBuilder::build`

**Comment by alexheretic** [comment]
Perhaps I can make a glutin run_on_demand example/test that reproduces this and we can use that to drive the fix?

**Comment by kchibisov** [comment]
I was suggesting to not sleep, but rather set to `Poll` and do like 10 iterations from `AboutToWait`.

>This error is returned by glutin-winit DisplayBuilder::build -> finalize_window -> winit WindowBuilder::build

Yeah, I know, but it could have error stuck from some previous command.

@alexheretic 

What you can try is to drain errors when we invoke `run_on_demand` again, so there's nothing stuck from previous iteration. 

```diff
diff --git a/src/platform_impl/linux/x11/mod.rs b/src/platform_impl/linux/x11/mod.rs
index fc3a6456..d61c5ddf 100644
--- a/src/platform_impl/linux/x11/mod.rs
+++ b/src/platform_impl/linux/x11/mod.rs
@@ -407,6 +407,10 @@ impl<T: 'static> EventLoop<T> {
             return Err(EventLoopError::AlreadyRunning);
         }
 
+        // Clear the errors from the previous iteration.
+        let window_target = get_xtarget(&self.target);
+        *window_target.xconn.latest_error.lock().unwrap() = None;
+
         let exit = loop {
             match self.pump_events(None, &mut event_handler) {
                 PumpStatus::Exit(0) => {
```

But I think it could be too early since you'll get this after the actual second run...

**Comment by kchibisov** [comment]
@alexheretic hm, in which order you're dropping Surface from glutin and the `Window` in winit? I'd assume you drop everything before the actual winit window?

**Comment by kchibisov** [comment]
Hm, no the patch I've sent shouldn't fix anything unless the error is set from GL thread in mesa somehow, since we clear the error and sync with the X server when leaving the `run_on_demand` call.

**Comment by alexheretic** [comment]
> hm, in which order you're dropping Surface from glutin and the Window in winit? 

Aha, yeah drop order seems to be the cause. All the glutin bits and window all get dropped before re-use happens though.

I was using a `move |event, elwt| ...` closure which moved window, surface and context. I'm not actually sure how the closure will decide drop order but yes it seems it was dropping the window before the gl bits.

If I ensure my Surface is dropped before the window all is well. Thanks for pointing me in the right direction mate! :tada:

**Comment by kchibisov** [comment]
>If I ensure my Surface is dropped before the window all is well. Thanks for pointing me in the right direction mate! 🎉

given that you drop window in _code_ and gl stuff is implicit, it'll be dropped right when you exit. But yeah, order will matter since the destructors won't work correctly and the error is a global state with GLX/X11.
