### ISSUE TITLE
`EventLoopWindowTarget::exit()` doesn't immediately stop the event loop

### ISSUE THREAD

**Issue by daxpedda** [rust-windowing/winit#3323]
<div type='discussions-op-text'>

<sup>Originally posted by **ItsSunnyMonster** December 26, 2023</sup>
I didn't file this as an issue because I don't know if I missed something or if this is the intended behaviour. When I call `EventLoopWindowTarget::exit()` in my event loop after all windows have been closed, on Windows, I would receive another bunch of events after that, including another `AboutToWait` event where I draw a frame. On macOS a `NewEvents(WaitCancelled)` event still gets emitted but that doesn't affect anything because I don't handle that event yet. Why is this?</div>

**Comment by daxpedda** [comment]
Which version of Winit are you using?

**Comment by ItsSunnyMonster** [comment]
I am using 0.29.5

**Comment by ItsSunnyMonster** [comment]
I have just updated to 0.29.6 and the same thing still happens

**Comment by kchibisov** [comment]
I don't think it's an issue though? it's true that we don't exit immediately because we could be in the middle of on-going event handling and to close cleanly it may require event processing to finish.

**Comment by daxpedda** [comment]
@ItsSunnyMonster is `LoopExiting` the last event you get?

**Comment by ItsSunnyMonster** [comment]
> @ItsSunnyMonster is `LoopExiting` the last event you get?

yes

**Comment by daxpedda** [comment]
I think generally speaking the documentation around this is poor, but as @kchibisov said: this works as intended, as long as `LoopExiting` is the last event.
