### ISSUE TITLE
How to use Wayland dmabuf + sync with winit?

### ISSUE THREAD

**Issue by gurchetansingh** [rust-windowing/winit#3326]
The Wayland API provides for a client to provide a dmabuf to the compositor.  Usually, you attach a dmabuf to a Wayland surface, which within winit is abstracted by the Window API.

In addition, the surface may be explicitly rather than implicitly synced:

https://lwn.net/Articles/814587/

I wonder how architecturally one would integrate:

- `linux-dmabuf-unstable-v1`
- `zwp_linux_explicit_synchronization_v1`

with Winit.  Or architecturally, would these be done outside Winit?  IIUC, Winit itself maintains a connection to the wl compositor.

CC: @rib @kchibisov @Osspial

**Comment by kchibisov** [comment]
see at mesa wsi on how to do so.

**Comment by gurchetansingh** [comment]
@kchibisov, just to confirm: then the recommended design would be winit just provided the surface, and the outside app/winit user attaching dma-buf + sync?

**Comment by kchibisov** [comment]
Yes, the same way winit already works with mesa (OpenGL, Vulkan, etc, it's all dmabufs).
