### ISSUE TITLE
window minimize not working on X11

### ISSUE THREAD

**Issue by acarl005** [rust-windowing/winit#3327]
I am running the `window_debug` example from the master branch.

```sh
cargo run --example window_debug
```

In a Wayland environment, pressing "m" correctly minimizes the window. However, in an X11 environment, nothing happens when "m" is pressed.

**Comment by notgull** [comment]
Verified that this issue is happening on my own machine.

On `winit` v0.28, I see this during the minimize:

```
000:<:0069: 24: Request(16): InternAtom only-if-exists=false(0x00) name='WM_CHANGE_STATE'
000:>:0069:32: Reply to InternAtom: atom=0x1df("WM_CHANGE_STATE")
000:<:006a: 44: Request(25): SendEvent propagate=false(0x00) destination=0x0000076e event-mask=SubstructureNotify,SubstructureRedirect ClientMessage(33) format=0x20 window=0x03e00001 type=0x1df("WM_CHANGE_STATE") data=0x03,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00;
```

I don't see this on `master`, which is probably the issue.

**Comment by acarl005** [comment]
Thanks for the quick fix!
