### ISSUE TITLE
send_event blocking or non-blocking?

### ISSUE THREAD

**Issue by DasLixou** [rust-windowing/winit#3334]
Hello!
Is `send_event` blocking or non-blocking? If it's not, is there a way to wait for it to be processed?

**Comment by madsmtm** [comment]
`send_event` is non-blocking.

Since you're the one processing the event, the easiest way would probably be to use a [`CondVar`](https://doc.rust-lang.org/nightly/std/sync/struct.Condvar.html) that tells the calling thread when you're done processing.

**Comment by DasLixou** [comment]
> `send_event` is non-blocking.
> 
> 
> 
> Since you're the one processing the event, the easiest way would probably be to use a [`CondVar`](https://doc.rust-lang.org/nightly/std/sync/struct.Condvar.html) that tells the calling thread when you're done processing.

Oh yeah CondVars... might be out of scope but is there any resource on how they work internally? Can just get as far as sys::CondVar

**Comment by madsmtm** [comment]
Hmm, [Mara Bos' book on atomics](https://marabos.nl/atomics/) has a pretty good section detailing how they work.

**Comment by DasLixou** [comment]
> `send_event` is non-blocking.
> 
> 
> 
> Since you're the one processing the event, the easiest way would probably be to use a [`CondVar`](https://doc.rust-lang.org/nightly/std/sync/struct.Condvar.html) that tells the calling thread when you're done processing.

Wait I think I am stupid.. I am trying to send an event inside the event loop, so what I want is handling an event completely before the current one continues, which shouldn't be possible, right? Gotta think about that...

**Comment by kchibisov** [comment]
yeah, you can't do that.
