### ISSUE TITLE
Abnormally slow startup for X11

### ISSUE THREAD

**Issue by notgull** [rust-windowing/winit#3335]
cc: https://github.com/alacritty/alacritty/issues/7472

It takes almost 3 seconds to create a window, which is frankly absurd.

**Comment by notgull** [comment]
https://github.com/rust-windowing/winit/blob/a857d3faacc62e26e49f129263bdc0a0ac2d85c2/src/platform_impl/linux/x11/window.rs#L138-L568

The following are all of the points where X11 requests are made:

- Getting the list of and information for all of the monitors (ideally a one-time thing).
- Querying the mouse to find out which monitor it's on.
- *Actually creating the window (with `CreateWindow`).*
- Getting the window attributes.
- *Setting window information (title, theme, decorations, DND properties)*
- *Mapping the window to the screen*
- Calling `XkbSetDetectableAutoRepeat`
- Setting up IME contexts.
- **Synchronizing with the server**

Italics are requests that don't block on `poll` and therefore shouldn't be a problem.

**Comment by notgull** [comment]
It looks like this is caused by conflicts with the Mesa GLX driver, at least the one for libMesa. Potentially AMD related.

**Comment by notgull** [comment]
Well, this has me stumped. It looks like fetching the list of monitors from the X server is what's taking so long. Not sure why it's locking up here when it didn't lock up in Xlib, nor why it seems to be GPU dependent.

@psychon By any chance do you have any insight here? I'm not well versed on the finer details of Xlib/XCB/Xkb interaction, so there might be something obvious I'm missing here.

**Comment by psychon** [comment]
> I'll also try to find the old xlib based code for this.

Commit bb9b629bc34c6db8fa1ebda24a03ce0ddbc1d51e added that call to `randr_query_version(0, 0)`. Before that, the code just did:
```rust
            let mut major = 0;
            let mut minor = 0;
            (self.xrandr.XRRQueryVersion)(self.display, &mut major, &mut minor);
```
This function actually ignores the passed-in numbers and always queries for the newest version supported by libxrandr. In my case that would be:
```
$ grep RANDR_M /usr/include/X11/extensions/randr.h
#define RANDR_MAJOR		1
#define RANDR_MINOR		6
```
So.... I think I'm done here and I should get back to bed and take more medicine. Sorry.
```diff
diff --git a/src/platform_impl/linux/x11/monitor.rs b/src/platform_impl/linux/x11/monitor.rs
index 09e42d66..e5859ac3 100644
--- a/src/platform_impl/linux/x11/monitor.rs
+++ b/src/platform_impl/linux/x11/monitor.rs
@@ -344,7 +344,7 @@ impl ScreenResources {
         conn: &impl x11rb::connection::Connection,
         root: &x11rb::protocol::xproto::Screen,
     ) -> Result<Self, X11Error> {
-        let version = conn.randr_query_version(0, 0)?.reply()?;
+        let version = conn.randr_query_version(1, 3)?.reply()?;
 
         if (version.major_version == 1 && version.minor_version >= 3) || version.major_version > 1 {
             let reply = conn
```
