### ISSUE TITLE
On Wayland, custom cursors don't respect alpha

### ISSUE THREAD

**Issue by eero-lehtinen** [rust-windowing/winit#3360]
I tested this gradient image
![gradient](https://github.com/rust-windowing/winit/assets/7013023/a451ed58-b49a-4ae8-b0fb-08ebaa2ef8a6)
as the cursor. It shows up perfectly fine on X11, but on Wayland, it shows up as just a red block with full opacity.

I don't really see anything wrong with the buffer creation. I'm not able to figure out what is wrong.

Here is my branch where I added the image to the example, but didn't get further https://github.com/eero-lehtinen/winit/tree/custom-cursor-gradient.

**Comment by kchibisov** [comment]
See https://github.com/rust-windowing/winit/pull/3445
