### ISSUE TITLE
Missing logo modifier enum in winit 0.29

### ISSUE THREAD

**Issue by erihsu** [rust-windowing/winit#3364]
The 0.28 version has logo enum in ModifiersChanged Event, but missing in 0.29
or how should I  map it in the latest version ?

**Comment by kchibisov** [comment]
it's called super now.

**Comment by erihsu** [comment]
> it's called super now.

Yes, I found it in KeyCode. Thanks

**Comment by kchibisov** [comment]
it's still on modifiers event, just called super and not logo.

**Comment by erihsu** [comment]
> it's still on modifiers event, just called super and not logo.

then CapitalLock not in modifiers event now ?

**Comment by kchibisov** [comment]
it was never there.
