### ISSUE TITLE
Add an owned display handle type

### ISSUE THREAD

**Issue by notgull** [rust-windowing/winit#3365]
It would be nice if there was an owned display handle that implemented `HasDisplayHandle` independent of `EventLoop` or `EventLoopWindowTarget`. It could keep this display alive.

It would be useful for `glutin` and potentially `wgpu`

**Comment by daxpedda** [comment]
Isn't this the same as #3317?

**Comment by notgull** [comment]
No, for graphics ecosystem cases a persistent window handle is necessary.

**Comment by daxpedda** [comment]
Ah, sorry, display vs window.
