### ISSUE TITLE
web: KeyEvent::text is None for backspace

### ISSUE THREAD

**Issue by rparrett** [rust-windowing/winit#3381]
Tested Winit 0.29 and bdeb2574dc2bd4e67893163c4a4dea8123194f61

MacOS produces `Some("\u{8}")`, and it looks like Windows is probably doing the same. Linux doesn't seem as clear and I'm unable to test.

It would be ideal if this behavior was the same on all platforms.

**Comment by kchibisov** [comment]
Use https://docs.rs/winit/latest/winit/keyboard/enum.NamedKey.html#method.to_text if you want text repr of `NamedKey`.

**Comment by rparrett** [comment]
Okay.

It looks like I may have misread the docs, and the behavior on MacOS is the (and I assume windows) is buggy? `KeyEvent::text` should only be `Some` for "real characters"?

My issue is that this behavior is not consistent across platforms.

**Comment by daxpedda** [comment]
I guess reopening because of platform inconsistencies.

**Comment by daxpedda** [comment]
On X11 it seems to be the same issue: pressing backspace returns `text: Some("\u{8}")`.
@kchibisov I'm unsure what the supposed behavior should be at this point, but it seems to me that your initial assessment is correct. Meaning this has to be fixed in apparently most backends.

**Comment by kchibisov** [comment]
>I guess reopening because of platform inconsistencies.

you can, it's just different issue to the originally reported one.

>@kchibisov I'm unsure what the supposed behavior should be at this point, but it seems to me that your initial assessment is correct. Meaning this has to be fixed in apparently most backends.

The issue is a bit more complicated since there's generally no control on how `NamedKey` values text is filled and the end caveats. Setting always `None` for it also won't work the way the current input is done, because named key could be at the end of compose input thus it'll have a valid input.

**Comment by rparrett** [comment]
Is there some documentation / standard you can point me to that is governing this behavior that you can point me to? The distinction between what `KeyCode::text` and `Key::to_text` seems arbitrary and confusing.

**Comment by kchibisov** [comment]
I'd at least remove `text` from events having `to_text`, but I'm not sure how I feel about remove `text` in general from `NamedKey` variants.
