### ISSUE TITLE
Ctrl sometimes gets "stuck" on X11

### ISSUE THREAD

**Issue by fredizzimo** [rust-windowing/winit#3388]
This was reported in

https://github.com/neovide/neovide/issues/2228

The [neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13800892/neovide_rCURRENT.log) is huge, by contains all key presses reported by Winit, and the modifier states. Search for `KeyEvent` and `ModifiersState` or filter by `[neovide::window::keyboard_manager]`

The key up event is received, but the modifier state is not updated. The modifiers are reported strange in other ways as well, for example shortly after, when super is pressed it alternates between super and no modifiers state.

I suspect this is some kind of timing issue, since it only happens on certain file types, and Neovide does not have any file type specific handling.

**Comment by kchibisov** [comment]
We pass modifiers from the xkb event. So there's either event or no event, but could be logic to send modifier lazily not work.

**Comment by fredizzimo** [comment]
@kchibisov, we just got a report of a very similar issue, but it was reported to happen on Wayland as well and we don't have any logs yet, so it might be a different but similar issue.

* https://github.com/neovide/neovide/issues/2358

But is it possible that this could affect Wayland too?

**Comment by kchibisov** [comment]
No, wayland having thing like that is not our bug.

**Comment by fredizzimo** [comment]
Thank you, I asked for that information as well. I will open a new issue if I can determine that it's a winit issue, and otherwise just resolve the issue in Neovide.
