### ISSUE TITLE
Associate received characters with key inputs

### ISSUE THREAD

**Issue by tomaka** [rust-windowing/winit#34]
Original: https://github.com/tomaka/glutin/issues/201

**Comment by tomaka** [comment]
Also: https://github.com/tomaka/glutin/issues/249

**Comment by francesca64** [comment]
The only thing preventing this is Windows. Supposedly Qt supports this, so I'll investigate how they handle it if I get a chance.

https://github.com/glfw/glfw/issues/1140#issuecomment-384166808

**Comment by Osspial** [comment]
Closing in favor of #753
