### ISSUE TITLE
Expose more DWM attributes on Windows.

### ISSUE THREAD

**Issue by sidit77** [rust-windowing/winit#3404]
Windows 11 added many [new dwm window attributes](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute) and it would be great to easily use them with winit.

For example:
* Window border color
* Window border thickness
* Window titlebar color
* Window titlebar text color
* Window corner preference
* Window backdrop (potential overlap with `Window::set_blur(bool)`; However Windows has several different blurs: Acryllic, Mica, and MicaAlt)

I'd be willing to work on this if this falls within winits scope.

**Comment by madsmtm** [comment]
Sounds like it's in-scope as a platform-specific extension

**Comment by msiglreith** [comment]
Backdrop implemented in https://github.com/rust-windowing/winit/pull/3257
