### ISSUE TITLE
On Mac, typing Fn+Delete should emit the delete character x7f but does nothing

### ISSUE THREAD

**Issue by coolbluewater** [rust-windowing/winit#3407]
On the mac, the way to enter the delete character is to type Fn+Delete. (Typing just Delete inserts backspace in macOS).
However, winit does not correctly translate this key combination. It only passes the physical key to the app.

**Comment by coolbluewater** [comment]
@madsmtm 
> Does text_with_all_modifiers resolve this for you?
Unfortunately not, there's no difference using this api.

**Comment by madsmtm** [comment]
Using the `window` example in this repo I'm able to get the following (note the `"\u{f728}"`), which seems to correspond to https://developer.apple.com/documentation/swiftui/keyequivalent/deleteforward.
```rust
KeyEvent { physical_key: Code(Delete), logical_key: Named(Delete), text: None, location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("\u{f728}"), key_without_modifiers: Named(Delete) } }
```

Can you give examples of why this doesn't work for your use-case? And maybe you can expand a bit on why you think it should be `\x7f`?

**Comment by kchibisov** [comment]
Maybe `\x7f` is a assumption you made based on the libxkbcommon? I don't think any of that is actually standard across platforms. We usually do have `\x8` for backspace, but that's about it.

winit may define extra mapping on `NamedKey` inside the `to_text` method, but I'm not sure why we should be doing so with such keys? Usually you bind the `logical_key` and perform some actual, and only terminals do care about such stuff. However, in terminals `Delete` is defined as an escape sequence and `\x7f` is usually a backspace, not delete.

**Comment by coolbluewater** [comment]
macOS treats "fn" + "delete" as delete, and treats "delete" by itself as backspace (somewhat confusingly.)
Winit correctly sets "text" to \x8 (backspace) when delete is pressed by itself, but, as reported here, does not set "text" to \x7f when "fn" + "delete" 
\x7f is delete in both ASCII and Unicode, see https://en.wikipedia.org/wiki/List_of_Unicode_characters.

**Comment by kchibisov** [comment]
it's not really a standard, even the pages say `usually` though? We just get text out of macOS input and it sets to that value, we could probably map it to `\x7f` in `to_text`, but that's about it?

**Comment by coolbluewater** [comment]
I see.  Going by the evolution of keyboard handling in winit it sure feels like a uniform api over the del key across all platforms is warranted. The web, for example does have a standard that seems to work, see https://www.geeksforgeeks.org/ways-to-capture-the-backspace-and-delete-on-the-onkeydown-event/ (I tested the first sample on the mac.)

**Comment by kchibisov** [comment]
For now we make guarantees only about the `logical_key` and you clearly get it, so you can properly detect it. We don't have the same for `text` attached, since I don't think there's a standard defining that?

Like I'm not sure what you want at the current state of things, since if your goal to detect whether `Delete` was pressed, it should be done via the `logical_key` and if you don't get a proper event, we should look on the actual cause why it happened and what our code on macOS lacks.

**Comment by coolbluewater** [comment]
Ah, you answered my question. I was using `physical_key` and `text`, but not `logical_key`. 
If `logical_key` correctly surfaces Del and Backspace across all keyboard layouts and platforms then I'm a happy camper.
If this is the case please feel free to close this issue.
