### ISSUE TITLE
Clarification on dead keys

### ISSUE THREAD

**Issue by k0nserv** [rust-windowing/winit#343]
I did some reasearch based on https://github.com/tomaka/winit/issues/263 using a simple macOS app that just logs keyDown events. With my layout(based on Swedish Pro) ^, ¨, ~ don't work correctly since they are dead keys. Handling dead keys involves quite a bit more [work](https://stackoverflow.com/questions/33203020/get-the-char-accent-in-nsevent) that needs to be done in winit. I'm curious if handling dead keys is considered in scope for winit or if that's something that you expect applications themselves to deal with.

Also see https://github.com/jwilm/alacritty/issues/682

**Comment by vberger** [comment]
For comparison, the wayland platforms automatically handles dead keys. By that I mean that for example:

- User presses `^` key (which is a dead key on my azerty keyboard)
- winit generates a `KeyPressed` event for key `^` but no `ReceivedCharacter` event
- User then presses `e` key
- winit generates a `KeyPressed` event for key `e`, then a `ReceivedCharacted('ê')`

**Comment by tomaka** [comment]
What @vberger described is what should happen IMO. That's also currently the behaviour on Windows.
