### ISSUE TITLE
Unexpected Logical Key Value

### ISSUE THREAD

**Issue by Shute052** [rust-windowing/winit#3453]
Reported in Bevy issue #11689, the problem arises with the winit dependency at version 0.29.2. As a newcomer to winit, I'm struggling to create a reproduction case for it, which is quite unfortunate.

I've included the Bevy converter below, designed to transform winit Keys into their owns:

```rust
pub fn convert_logical_key(logical_key_code: &winit::keyboard::Key) -> bevy_input::keyboard::Key {
    match logical_key_code {
        winit::keyboard::Key::Character(s) => bevy_input::keyboard::Key::Character(s.clone()),
        // Other cases are also straightforward one-to-one mappings
    }
}
```

From my perspective, a logical key should remain consistent regardless of external factors.
However, the situation is that the 'W' key reporting a lowercase 'w' normally and an uppercase 'W' when CapsLock is activated or Shift is pressed.

**Comment by kchibisov** [comment]
it's called logical key for a reason and that's how it's usually done, the winit key input is modeled around w3c key event, and it also has them like that. 

if you want unmodified, there's `key_without_modifier` or physical key.

**Comment by Shute052** [comment]
Ahh, this is helpful, thanks! It seems to should keep discussion in Bevy parts since games always need shortcuts.
