### ISSUE TITLE
with_always_on_top and set_always_on_top no longer seem to exist

### ISSUE THREAD

**Issue by MHanak1** [rust-windowing/winit#3454]
those functions (implemented around 2018) exist in the documentation but no longer seem to exist in the code.

https://docs.rs/tauri-winit/latest/winit/window/struct.Window.html#method.set_always_on_top

```
error[E0599]: no method named `set_always_on_top` found for struct `Rc<Window>` in the current scope
  --> src/main.rs:41:9
   |
41 |     window.set_always_on_top(true);
   |            ^^^^^^^^^^^^^^^^^ method not found in `Rc<Window>`
```

**Comment by msiglreith** [comment]
It has been replaced by [`Window::set_window_level`](https://docs.rs/winit/latest/winit/window/struct.Window.html#method.set_window_level)
