### ISSUE TITLE
AtomicU64 not available on all platforms

### ISSUE THREAD

**Issue by jamessan** [rust-windowing/winit#3456]
https://github.com/rust-windowing/winit/pull/2955 added the use of `AtomicU64`, however as the [portability](https://doc.rust-lang.org/std/sync/atomic/index.html#portability) docs note

> PowerPC and MIPS platforms with 32-bit pointers do not have `AtomicU64` or `AtomicI64` types.

Looks like this is also the case for armv5te.

Now, these are all tier 2 or 3 platforms (from rustc perspective), so I'd understand if that's not a priority.  Just wanted to raise the issue, since the did regress from previous winit releases.

**Comment by kchibisov** [comment]
`AtomicUsize` is fine, right?

**Comment by jamessan** [comment]
I'd think so, but the book isn't optimistic. :)

> `AtomicUsize` and `AtomicIsize` are generally the most portable, but even then they’re not available everywhere.

**Comment by kchibisov** [comment]
Well, it'll resolve to `AtomicU32` which will mean that there's no atomics at all, and we kind of require atomics.
