### ISSUE TITLE
Wayland availability detection does not check for WAYLAND_SOCKET

### ISSUE THREAD

**Issue by mstoeckl** [rust-windowing/winit#3459]
Wayland clients have two methods of connecting to the compositor. If the environment variable WAYLAND_DISPLAY is set, they can connect() to the Unix socket at a path indicated by WAYLAND_DISPLAY. A much rarer case is when the environment variable  WAYLAND_SOCKET is set; then the compositor will have provided one end of a socket pair through file descriptor inheritance, and  the value of WAYLAND_SOCKET will indicate the file descriptor ID.

Currently, `winit` when autodetecting which backend to use only checks for WAYLAND_DISPLAY, not WAYLAND_SOCKET. (The code that does this check is in [src/platform_impl/linux/mod.rs](https://github.com/rust-windowing/winit/blob/4d4d6e5052877d9578bac73f52eaf323e9089998/src/platform_impl/linux/mod.rs#L752C13-L754C35) .) It should consider the Wayland backend to be usable if either of WAYLAND_DISPLAY or WAYLAND_SOCKET is available.

To test this, run a program using winit under a compositor or tool that provides a Wayland connection using WAYLAND_SOCKET. (The way I ran into this issue was with the command [`waypipe`](https://gitlab.freedesktop.org/mstoeckl/waypipe/)` --oneshot ssh localhost `[`alacritty`](https://github.com/alacritty/alacritty).)

**Comment by kchibisov** [comment]
https://github.com/rust-windowing/winit/pull/3460

**Comment by kchibisov** [comment]
I have a feeling that if you set `WAYLAND_DISPLAY` to some garbage value it'll workaround the issue.

**Comment by kchibisov** [comment]
While I was testing it, I've discovered that empty `WAYLAND_SOCKET` prevents from running as will if you have e.g. `WAYLAND_DISPLAY` set https://github.com/Smithay/wayland-rs/pull/697

The logic in wayland-rs follows the `libwayland` here, hence do you happen to know why it's like that there?

**Comment by kchibisov** [comment]
opened upstream https://gitlab.freedesktop.org/wayland/wayland/-/issues/438
