### ISSUE TITLE
`v0.30.0` release planning

### ISSUE THREAD

**Issue by madsmtm** [rust-windowing/winit#3476]
Winit is moving towards [a trait-based API](https://github.com/rust-windowing/winit/issues/3432), users can submit feedback on their migration [here](https://github.com/rust-windowing/winit/issues/3626).

To this end, we will use Winit `v0.30` as a migration step, where both the trait-based and the current closure-based APIs will be available, such that we can solicit feedback from users, and hopefully make the transition less painful.

Check out [the milestone](https://github.com/rust-windowing/winit/milestone/11) for the current schedule.

**Comment by madsmtm** [comment]
I'd like to move forwards with the `v0.30` release soon, looking at [the milestone](https://github.com/rust-windowing/winit/milestone/11) I'm unsure of what blockers there are except for https://github.com/rust-windowing/winit/issues/3477?

**Comment by madsmtm** [comment]
Might also want to block on https://github.com/rust-windowing/winit/pull/3590, it's somewhat related to the migration entries.

**Comment by daxpedda** [comment]
I would only block on #3477.

**Comment by daxpedda** [comment]
Lets not forget https://github.com/rust-windowing/winit/pull/2325.

**Comment by torokati44** [comment]
Is there going to be a `0.30` alpha/beta/RC release before final, so users can more easily (and sooner) experiment with the migration?

**Comment by madsmtm** [comment]
I don't think we were planning to do so

**Comment by torokati44** [comment]
I see, thank you!

**Comment by kchibisov** [comment]
Old APIs are deprecated and not yet removed, so you don't have rc, etc, because they are still there, you'll just get a warning for them.

Some were changed, but preserving semantics, so it's not really a breaking change either.

**Comment by madsmtm** [comment]
We decided today to wait for the `ndk` update to `0.9`, at the very latest release Winit 0.30 at next week's meeting

**Comment by kchibisov** [comment]
Release done.
