### ISSUE TITLE
The window returns the original size after resize on Wayland

### ISSUE THREAD

**Issue by alberand** [rust-windowing/winit#3485]
Hi,
Thank you for your work on this great project. 

I did the following change to the `examples/resizable.rs`
```
diff --git a/examples/resizable.rs b/examples/resizable.rs
index 3bfc4b59..33ed87e9 100644
--- a/examples/resizable.rs
+++ b/examples/resizable.rs
@@ -43,6 +43,7 @@ fn main() -> Result<(), impl std::error::Error> {
                     resizable = !resizable;
                     println!("Resizable: {resizable}");
                     window.set_resizable(resizable);
+                    let _ = window.request_inner_size(LogicalSize::new(500.0, 500.0));
                 }
                 WindowEvent::RedrawRequested => {
                     fill::fill_window(&window);
```
Pressing **space** causes the window to resize to the  [500.0, 500.0] size. However, this window stays in this *new* size until it's unfocused. After focus is lost, the window gets back to its original size `LogicalSize::new(600.0, 300.0)`.

I debugged this a little, and it looks like that `winit` correctly handles `request_inner_size()` and resizes the window. However, the moment when `WindowState.configure()` is called (unfocus event), the `WindowConfigure.new_size` is still set to [600, 300] and `self.inner_size()` is [500, 500]. Therefore, the window gets resized back to the `new_size` [600, 300].

By doing switch to fullscreen and back to normal before unfocusing window, fixes the problem and window stays in the new requested size.

*My speculation is that `request_inner_size()` doesn't change the frame size? Or it's not properly communicated to wayland server?*

Platform:
Wayland Version: 1.22.0
Sway Version: 1.8.1
winit latest origin/master 4d4d6e5052877d9578bac73f52eaf323e9089998

On **space**:
```
Resizable: true
[ 104934.034]  -> xdg_toplevel@24.set_min_size(600, 300)
[ 104934.045]  -> xdg_toplevel@24.set_max_size(600, 300)
[ 104934.064]  -> wl_compositor@3.create_region(new id wl_region@33)
[ 104934.080]  -> wl_region@33.add(0, 0, 2147483647, 2147483647)
[ 104934.092]  -> wl_surface@22.set_opaque_region(wl_region@33)
[ 104934.098]  -> wl_region@33.destroy()
[ 104934.111]  -> xdg_surface@23.set_window_geometry(0, 0, 500, 500)
[ 104934.118]  -> wl_surface@22.commit()
[ 104934.144]  -> wl_buffer@31.destroy()
[ 104934.162]  -> wl_shm_pool@30.create_buffer(new id wl_buffer@34, 0, 500, 500, 2000, 1)
[ 104935.695] wl_buffer@29.release()
[ 104935.711]  -> wl_surface@22.attach(wl_buffer@34, 0, 0)
[ 104935.718]  -> wl_surface@22.damage_buffer(0, 0, 500, 500)
[ 104935.723]  -> wl_surface@22.commit()
```

On unfocus:
```
[ 107020.196]  -> wl_compositor@3.create_region(new id wl_region@31)
[ 107020.213]  -> wl_region@31.add(0, 0, 2147483647, 2147483647)
[ 107020.224]  -> wl_surface@22.set_opaque_region(wl_region@31)
[ 107020.230]  -> wl_region@31.destroy()
[ 107020.241]  -> xdg_surface@23.set_window_geometry(0, 0, 600, 300)
[ 107021.282] wl_buffer@34.release()
[ 107021.301]  -> wl_surface@22.attach(wl_buffer@29, 0, 0)
[ 107021.310]  -> wl_surface@22.damage_buffer(0, 0, 600, 300)
[ 107021.315]  -> wl_surface@22.commit()
[ 107021.446] wl_display@1.delete_id(31)
```

**Comment by kchibisov** [comment]
Could post full logs actually? Truncated logs are useless.

**Comment by kchibisov** [comment]
maybe that what sway wants?

```
diff --git a/src/platform_impl/linux/wayland/window/state.rs b/src/platform_impl/linux/wayland/window/state.rs
index 4a59a074..b36fa501 100644
--- a/src/platform_impl/linux/wayland/window/state.rs
+++ b/src/platform_impl/linux/wayland/window/state.rs
@@ -658,6 +658,11 @@ impl WindowState {
         // Update the stateless size.
         if Some(true) == self.last_configure.as_ref().map(Self::is_stateless) {
             self.stateless_size = inner_size;
+
+            if !self.resizable {
+                self.set_min_inner_size(Some(self.stateless_size));
+                self.set_max_inner_size(Some(self.stateless_size));
+            }
         }

         // Update the inner frame.

```

**Comment by alberand** [comment]
Sure, here's the full log with `export WAYLAND_DEBUG=1`
[resizable.log](https://github.com/rust-windowing/winit/files/14232026/resizable.log)

The patch you suggested didn't make a difference.

**Comment by kchibisov** [comment]
The log was without the patch applied? For now it seems like sway bug to me.

**Comment by kchibisov** [comment]
When you resize it like that the window is `resizable`, right?

**Comment by alberand** [comment]
All the logs above is for `window.set_resizable(true)`. But it behaves the same way if set to false.

Here is the log for `window.set_resizable(false)`
[resizable-with-patch-no-resizable.log](https://github.com/rust-windowing/winit/files/14232443/resizable-with-patch-no-resizable.log)

**Comment by kchibisov** [comment]
in non-resizable the log looks more or less how I'd expect, but sway resizes you back. In resizable I think it's on user to update min/max sizes to ensure that their window can actually resize to that size.

```
[2968015.913]  -> xdg_toplevel@24.set_min_size(500, 500)
[2968015.921]  -> xdg_toplevel@24.set_max_size(500, 500)
[2968015.930]  -> wl_compositor@3.create_region(new id wl_region@33)
[2968015.941]  -> wl_region@33.add(0, 0, 2147483647, 2147483647)
[2968015.948]  -> wl_surface@22.set_opaque_region(wl_region@33)
[2968015.951]  -> wl_region@33.destroy()
[2968015.961]  -> xdg_surface@23.set_window_geometry(0, 0, 500, 500)
[2968015.979]  -> wl_buffer@31.destroy()
[2968015.991]  -> wl_shm_pool@30.create_buffer(new id wl_buffer@34, 0, 500, 500, 2000, 1)
[2968017.480] wl_buffer@29.release()
[2968017.493]  -> wl_surface@22.attach(wl_buffer@34, 0, 0)
[2968017.500]  -> wl_surface@22.damage_buffer(0, 0, 500, 500)
[2968017.504]  -> wl_surface@22.commit()
[2969377.883] zwp_relative_pointer_v1@21.relative_motion(80, 1989271320, -4.44921875, 0.00000000, -4.00000000, 0.00000000)
[2969377.894] wl_keyboard@17.leave(203311, wl_surface@22)
[2969377.901] wl_pointer@20.leave(203316, wl_surface@22)
[2969377.906] wl_pointer@20.frame()
[2969377.909] xdg_toplevel@24.configure(600, 300, array[0])
[2969377.915] xdg_surface@23.configure(203312)
```

but in general, there's nothing we can really do other having an option to ignore compositor suggested sizes, which may crash you with some compositors.

**Comment by kchibisov** [comment]
maybe sway from git doesn't have this bug with non-resizable? could you try it?

**Comment by alberand** [comment]
hmm no success yet on building the latest sway, but I've tried with 1.17.0, and it works the same way. The https://github.com/swaywm/sway/issues/7489 seems to describe the same issue. Looks like it's the way sway treats floating windows. 

The `swaymsg resize set 504px 504px` (4px border) on kitty terminal resizes the window and seems to produce similar logs (line 521)
[swaymsg-resize.log](https://github.com/rust-windowing/winit/files/14232982/swaymsg-resize.log)

Do you know how `swaymsg resize` performs resize?

**Comment by kchibisov** [comment]
The issue is that sway still thinks that the size is 600x300 in that case, even though we resized to something else.

`swaymsg` is a sway IPC command telling sway to change the size of the given window, so ofc it works.

On Wayland, size is entirely controlled by the user, however winit obeys to the resizes sway gives us, while we can ignore them and prefer user size, I'm not sure if that's the right way, especially given that certain sizes you can't ignore (fullscreen/maximize).

So it just seems not really a winit issue in the first place, at least in the way it's formulated.
