### ISSUE TITLE
How do I deal with the scroll wheel value from platform to platform?

### ISSUE THREAD

**Issue by Speykious** [rust-windowing/winit#3493]
The scroll wheel value I get from `MouseScrollDelta::LineDelta` when I scroll with the mouse is different on Linux and web.

Here are the values I obtain per increment on the things I've tested:

| Native | Firefox | Chromium |
| --- | --- | --- |
| ±12.0 | ±132.0 | ±120.0 |

Between the two browsers, there might be a config difference maybe... But between browser and native, it's a whole order of magnitude of difference, and it's making it impossible to implement a consistent cross-platform scroll behavior.

The documentation says:
> ```rs
> LineDelta(f32, f32)
> ```
> 
> Amount **in lines or rows** to scroll in the horizontal and vertical directions.
> 
> Positive values indicate that the content that is being scrolled should move right and down (revealing more content left and up).

What kind of scale do "lines or rows" represent? For `PixelDelta` it's clear, it's pixels, which makes it easy, but I have no clue how the `LineDelta` numbers scale. And I don't scroll 10 times faster on web compared to native, that's for sure. So is there something I can do about it?

(For context, I'm on Arch Linux with KDE X11 and I tested this on both Firefox and Chrome.)

**Comment by kchibisov** [comment]
Line delta is basically a discrete amount in terms of mouse wheel _clicks_. How much you discrete is up to you, it could be one line in your editor or e.g. 5 lines, you just know that it actually _clicked_ once.
