### ISSUE TITLE
X11: Mouse motion events sometimes contain garbage

### ISSUE THREAD

**Issue by valaphee** [rust-windowing/winit#3500]
While printing out events on X11, I noticed that sometimes (not always), the motion events are invalid:
```
DeviceEvent { device_id: DeviceId(X(DeviceId(2))), event: Motion { axis: 0, value: -1.0 } }
DeviceEvent { device_id: DeviceId(X(DeviceId(2))), event: Motion { axis: 1, value: 7.1e-322 } }
DeviceEvent { device_id: DeviceId(X(DeviceId(2))), event: MouseMotion { delta: (-1.0, 7.1e-322) } }
```
Only one axis gets reported and the second axis is just an unrelated value (most likely smth not belonging to the event).
```
for i in 0..xev.valuators.mask_len * 8 {
    if !xinput2::XIMaskIsSet(mask, i) {
        continue;
    }
    let x = unsafe { *value };
```

The easiest way I found to reproduce this is just moving the cursor between two monitors. It might also just be a x11 problem.

I'm running natively latest Arch Linux with Gnome using X11.

**Comment by notgull** [comment]
`7.1e-322` is really close to zero, which makes me think this is an error in interpreting the data from the X11 server.

Can you reproduce this issue while running `xtrace`, then attach the logs?

**Comment by valaphee** [comment]
XIRawEvent raw_values are used instead of XIRawEvent valuators values: https://github.com/rust-windowing/winit/blob/e61a7320a277ecfdafd978ea0276df2f0c64aeda/src/platform_impl/linux/x11/event_processor.rs#L1418

Replacing raw values with values yields way higher precision, (raw values only indicate if a value is zero, positive or negative at least with a mouse device) and doesn't has this problem.

I'll try to get a trace.
