### ISSUE TITLE
Allow user to opt out of setting WM_NORMAL_HINTS

### ISSUE THREAD

**Issue by acarl005** [rust-windowing/winit#3508]
## Problem

When I launch my app in a desktop environment with a Wayland tiling window manager, e.g. Hyprland or Sway, my app's windows are by default treated as floating windows instead of tiled windows.

We're forcing the use of X11 on the client by `WAYLAND_DISPLAY=""`. This is necessary for GPU compatibility reasons, among others.

## Cause

It looks like the cause is unconditionally setting `WM_NORMAL_HINTS` [here](https://github.com/rust-windowing/winit/blob/a8c7109e8966a7f6bfbb4ce3531bd30d9dbbbaa4/src/platform_impl/linux/x11/window.rs#L469-L495). Digging into the Hyprland source code for example, it uses the presence of the x11 size hint as a heuristic to make the window a floating window, [here](https://github.com/hyprwm/Hyprland/blob/13d985489788fa5349b3457d6eb1c19bad8f37e9/src/managers/XWaylandManager.cpp#L242-L243).

Interestingly, I tried to modify the winit code to set `WmSizeHints.size` to `None`, but this wasn't enough. I had to totally remove the call to `WmSizeHints::set`. Doing so fixed the issue and my app's windows were being correctly tiled in Hyprland.

## Proposed Solution

I would be nice if there was a way in the WindowBuilder API to opt out of setting this hint altogether.

**Comment by kchibisov** [comment]
So does alacritty `float` for you automatically as well when you force it to run on X11? It just sounds like you pass something to builder that does that, since I've never seen it float on sway.

Usually if you set `min/max` inner size it could happen? Idk.

**Comment by acarl005** [comment]
> does alacritty float for you automatically as well when you force it to run on X11?

Yes, it does. Only if X11 is forced.

![PXL_20240222_013545082 MP](https://github.com/rust-windowing/winit/assets/8334252/ffbca9a4-8ac2-4b33-8537-81b15be0b706)

Sorry for the photo. I don't have screenshots set up on this device. In this case, I ran the following from `kitty`:

```
nix-shell -p alacritty
WAYLAND_DISPLAY="" alacritty
```

Then, alacritty opens with a floating window. This is in a Hyprland session. Just to doublecheck I also verified this with `hyprctl clients`

```
Window 3815060 -> Alacritty:
	mapped: 1
	hidden: 0
	at: 320,150
	size: 800,600
	workspace: 1 (1)
	floating: 1
	monitor: 0
	class: Alacritty
	title: Alacritty
	initialClass: Alacritty
	initialTitle: Alacritty
	pid: 7934
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 0
```

**Comment by kchibisov** [comment]
Could you test sway, because on i3/dwm/bspwm it's clearly not a problem, so it sounds like just a yet another hyperland bug.

**Comment by acarl005** [comment]
It turns out things behave as expected on Sway. Alacritty windows are tiled as expected on Sway, even through Xwayland. My app is also behaving as expected, though I had to remove a min size constraint.

This appears to be a quirk of Hyprland. IIUC, [this line](https://github.com/hyprwm/Hyprland/blob/13d985489788fa5349b3457d6eb1c19bad8f37e9/src/managers/XWaylandManager.cpp#L243C69-L243C89) just needs another condition to ensure `SIZEHINTS->min_width != 0` and also min_height. I'll open an issue with them.

Thanks for your attention on the issue.
