### ISSUE TITLE
0.29.10 locked once_cell to 1.18.0 on M1 macOS 

### ISSUE THREAD

**Issue by erihsu** [rust-windowing/winit#3515]
I have a crate depends on winit(0.29.10) and wgpu-hal(0.19) which both require once_cell. For wgpu-hal, it requires once_cell 1.19, while winit requires 1.12. The cargo can resolve version on ```x86_64-unknown-linux-gnu``` target. But on M1 macOS, it shows
```
  previously selected package `once_cell v1.18.0`
    ... which satisfies dependency `once_cell = "^1.12"` (locked to 1.18.0) of package `winit v0.29.10`
```

I am not sure whether it's a bug that winit  not support ```aarch64-apple-darwin``` target

**Comment by kchibisov** [comment]
`cargo update -p once_cell`.
