### ISSUE TITLE
[Feature Request]: cargo-3ds support

### ISSUE THREAD

**Issue by lexi-the-cute** [rust-windowing/winit#3522]
One of the dependencies of winit cannot compile under cargo-3ds. I can't remember which one it is off the top of my head, so I'll have to try to rebuild again either tonight after work or tomorrow. I asked about it on the Nintendo Homebrew Discord (https://discord.gg/C29hYvh), but I'm not sure that have experience with Rust and Winit

I'll send more info after I test again

**Comment by lexi-the-cute** [comment]
The crate is rustix

[compile-log.txt](https://github.com/rust-windowing/winit/files/14394508/feature-request.txt)

**Comment by notgull** [comment]
The 3DS uses raw frame buffers, which has been decided to be out-of-scope for winit.

**Comment by lexi-the-cute** [comment]
what do you propose i should use instead? preferably something that's interchangeable with existing winit code so it can be easily swapped between it and winit depending on the target?

**Comment by notgull** [comment]
At one point we were talking about setting up a crate to deal with raw framebuffers. This also comes up when dealing with DRM/KMS on Linux, for instance. Then `winit` could have a backend that uses that crate to simulate a single-window environment (like a kiosk).

Admittedly this is pretty low-priority for us on the roadmap, as there are more pressing items to look into as well as very few people on the `winit` team who are experienced in dealing with raw framebuffers. If there is a lot of community interest then we can expedite this.
