### ISSUE TITLE
[Research] Can we use GPUI in the winit library?

### ISSUE THREAD

**Issue by kacperpaczos** [rust-windowing/winit#3535]
> Built like a video game
> Zed’s breakthrough performance starts with our GPUI framework, a new way to build 2D user interfaces. GPUI rasterizes the entire window on the GPU, just like a 3D video game. The result? Fast, reliable, and smooth delivery of pixels on every frame.

https://github.com/rust-windowing/winit/assets/23406555/79ebb634-6389-47b6-bf71-2c1d0de21811

**What does it mean**: GPUI rasterizes the entire window on the GPU, just like a 3D video game. The result? Fast, reliable, and smooth delivery of pixels on every frame

And can we use this in the winit library?

**Comment by jgcodes2020** [comment]
Winit is a _windowing_ library, not a UI library. That means it only manages windows and routes events. GPUI currently uses its own windowing library, though I don't know if the Zed team wishes to make it possible to use with `raw_window_handle`. That would be cool though.
