### ISSUE TITLE
Mouse events regression in 0.29.12+ on X11

### ISSUE THREAD

**Issue by rafalh** [rust-windowing/winit#3558]
Testing new the Bevy version 0.13 on Linux I encountered a mouse-look camera regression. I tracked it down to release 0.29.12 of `winit`.
On both videos I am trying to move my mouse horizontally and the only difference is `winit` version. 

winit 0.29.12
https://github.com/rust-windowing/winit/assets/160391/4962b5ef-d626-4464-8911-70332a6c4cb3
winit 0.29.11
https://github.com/rust-windowing/winit/assets/160391/83ca6774-8234-4981-986e-8f3e616d96d9

In the first one horizontal movement is very slow and generally mouse moves in a diagonal motion. In the second it works as expected.
I think it may have been caused by https://github.com/rust-windowing/winit/commit/3d4c53459a7e9a616df9673610a2e6bb48205e4f

Likely related to https://github.com/bevyengine/bevy/issues/12198

**Comment by irate-devil** [comment]
I left a comment on the specific lines I think are causing the issue: https://github.com/rust-windowing/winit/pull/3523#discussion_r1510018941
