### ISSUE TITLE
Handle Keyboard input on Android

### ISSUE THREAD

**Issue by DrSloth** [rust-windowing/winit#3598]
### Description

Hello there, i am currently trying to implement an android app using egui and winit. As it seems Keyboard Input is currently not supported on Android. I already got the keyboard to open up using jni in my app. 

However the "text" field of the `KeyEvents` seems to be empty and non ascii chars don't seem to be supported.

I am already investigating this and would absolutely love some pointers to implementing this and hopefully getting this into a release version of winit to support egui on android. 

### Relevant platforms

Android

**Comment by kchibisov** [comment]
See https://github.com/rust-windowing/winit/pull/2993

If you feel like making to work on it, comment on this PR.
