### ISSUE TITLE
Getting `NotSupported(NotSupportedError)` when creating an EventLoop under X11

### ISSUE THREAD

**Issue by StealthyKamereon** [rust-windowing/winit#3603]
### Description

I'm trying to run an application that uses winit. When I launch it it crashes on the following line :
```rust
let event_loop = EventLoop::new().unwrap();
```

I then made a dummy Rust package with only this line and sure enough I have the same crash.

### OS and window mananger

I am on Nixos and using Plasma 5.

### Winit version

0.29.15

**Comment by notgull** [comment]
> NixOS

Please ensure that all of the following libraries are installed: 

- libx11-dev
- libxcursor-dev
- libxcb1-dev
- libxi-dev
- libxkbcommon-dev
- libxkbcommon-x11-dev

**Comment by StealthyKamereon** [comment]
It is indeed the problem.
Being on Nixos, dynamically loaded libraries are a bit of a hassle.

I'm closing this ticket as it's not really a bug of winit but rather its underlying lib: x11-rs
I'll write the solution here later when / if I find it for future people that come across this problem.

Thanks

**Comment by StealthyKamereon** [comment]
The correct way to do this in Nixos to my understanding is to use [nix-ld](https://github.com/nix-community/nix-ld-rs/tree/main).

Adding this snippet should enable nix-ld to provide path to the required libs :
```nix
programs.nix-ld.enable = true;
programs.nix-ld.libraries = with pkgs; [
    xorg.libX11
    xorg.libXcursor
    xorg.libxcb
    xorg.libXi
    libxkbcommon
];
```

Unfortunately, it still doesn't work for some reason (see https://github.com/nix-community/nix-ld-rs/issues/26).
The current workaround I found is to set the content of `LD_LIBRARY_PATH` manually before running the binary:
```bash
export LD_LIBRARY_PATH=$NIX_LD_LIBRARY_PATH
```

I am still looking for a better solution.

**Comment by nuxeh** [comment]
For what it's worth, I got a similar app with the same error to work using a modification of the nix shell here https://discourse.nixos.org/t/could-not-find-system-library-x11-required-by-the-x11-crate/33751

**Comment by freddycansic** [comment]
My solution was to include a `build.rs` in the root directory of the cargo project.

```rust
fn main() {
    println!(
        "cargo:rustc-link-search={}",
        std::env::var("NIX_LD_LIBRARY_PATH").unwrap_or(String::new())
    );
}
```

This adds `NIX_LD_LIBRARY_PATH` to the rustc linker library search paths.

Still, it would be nice to use a Nix specific solution.

Reference: https://doc.rust-lang.org/cargo/reference/build-scripts.html

**Comment by kchibisov** [comment]
just export `LD_LIBRARY_PATH` from the nix expression, it has an option to populate this variable. Or you fhs.

**Comment by jowi-dev** [comment]
Just wanted to come by and drop this - this is how I get Bevy working on my nixos machine.
```
        devShells.default = pkgs.mkShell {
          buildInputs = buildInputs ++  [ pkgs.valgrind ];
            LD_LIBRARY_PATH = "$LD_LIBRARY_PATH:${
              with pkgs;
              pkgs.lib.makeLibraryPath [
                xorg.libX11 
                xorg.libXcursor 
                xorg.libXi 
                libxkbcommon 
                xorg.libxcb  
                pkgs.vulkan-loader
                pkgs.glfw
              ]
            }";
        };
```

```
      buildInputs = with pkgs; [ 
        xorg.libX11 
        xorg.libXcursor 
        xorg.libXi 
        libxkbcommon 
        xorg.libxcb  
        alsa-lib 
        libudev-zero 
        openssl 
        llvm 
        pkg-config 
        gcc 
        sqlite] 
```
