### ISSUE TITLE
[Features Request] Drag & dropping text/images

### ISSUE THREAD

**Issue by couleurm** [rust-windowing/winit#3631]
### Description

Hello, I'm making an egui project and was wondering if this was implemented in winit before even asking emilk, thank you for winit

### Relevant platforms

Windows, macOS, Wayland, X11, Web

**Comment by hannesojala** [comment]
Have you tried https://docs.rs/winit/latest/winit/event/enum.WindowEvent.html#variant.DroppedFile?

**Comment by couleurm** [comment]
Does [egui example file_dialog](https://github.com/emilk/egui/tree/master/examples/file_dialog) use this? If so it does not work with dragging in text

**Comment by daxpedda** [comment]
This is being tracked in https://github.com/rust-windowing/winit/issues/720.

I don't know the implementation status, but Web isn't implemented for sure.
