### ISSUE TITLE
Set the cursor to be inherited or any other global value

### ISSUE THREAD

**Issue by beoboo** [rust-windowing/winit#3647]
### Description

When changing the cursor icon, it's not possible to set global values (e.g. inherited - see full list [here](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)).

### Relevant platforms

Web

**Comment by daxpedda** [comment]
What would you want Winit to do here?
You can use `!important` to overwrite Winit, after all Winit itself isn't doing anything special, just adding CSS directly to the element.

I'm going  to close this as not really actionable, but please feel free to make a suggestion here if you have one.

**Comment by beoboo** [comment]
I think one of these 2 solutions could really help: 
* it's modifying the DOM adding a style property, but it's not allowing to remove it (something like "reset_cursor_icon" or "remove_cursor_icon")
* it's missing some possible values, so adding them could work as well.

Even if we can set `!important` on the parent, this doesn't seem the proper solution. 

IMHO implementing both the above missing parts would be the perfect and more robust solution.

NB: I can help, but I don't know the main vision so I don't want to implement something that's not going to be accepted (especially since the new 0.30 revamp).

**Comment by daxpedda** [comment]
> * it's modifying the DOM adding a style property, but it's not allowing to remove it (something like "reset_cursor_icon" or "remove_cursor_icon")

Making [`CursorIcon::Default`](https://docs.rs/winit/0.30.0/winit/window/enum.CursorIcon.html#variant.Default) remove the cursor style is probably the way to go. Though it would be best if we can figure out how to make this behave the same cross-platform, e.g. does `Default` fall back to the default cursor on other backends as well? If it does, shouldn't we add a `Cursor` one as well then?

I will ask around and then open a separate issue.

> * it's missing some possible values, so adding them could work as well.

It would be best if you point out exactly what you are missing so we can figure out if its covered by other backends as well or if its a Web-only thing.

> NB: I can help, but I don't know the main vision so I don't want to implement something that's not going to be accepted (especially since the new 0.30 revamp).

We have to figure out first how we want to proceed before doing any implementation.
