### ISSUE TITLE
Minimal window example

### ISSUE THREAD

**Issue by doonv** [rust-windowing/winit#3659]
The `window` example shows a lot of stuff that isn't needed for a winit application. This can be useful, but for someone who is just starting out with the library, it can be overwhelming. So I'd like an example that only shows the bare minimum to create a window, and only handle basic events like resizing.

**Comment by kchibisov** [comment]
Bare minimum is what you see on the `cargo doc` page as a first thing.

**Comment by doonv** [comment]
> Bare minimum is what you see on the `cargo doc` page as a first thing.

Why isn't that example included in the examples folder?
