### ISSUE TITLE
Reintroduce ability to query use of X11 or Wayland as backend on raw `EventLoop`

### ISSUE THREAD

**Issue by vorporeal** [rust-windowing/winit#3670]
### Description

Pre 0.30, `EventLoopWindowTargetExtX11` enabled users to invoke `is_x11` on an `EventLoop`, as an `EventLoop` could be coerced into an `EventLoopWindowTarget`.

With the 0.30 API changes that replaced `EventLoopWindowTarget` with `ActiveEventLoop`, there is no longer a way to perform this check without doing something indirect/awkward like doing a match on `event_loop.owned_display_handle().raw_display_handle()`.

This functionality was used in our application to determine whether to invoke `winit::platform::x11::register_xlib_error_hook` before starting the event loop.  While we could set up our error hook callback as part of the init event, we'd prefer to do it before starting the event loop for maximum "coverage".

### Relevant platforms

X11

**Comment by kchibisov** [comment]
Yeah, probably was just forgotten. Using `raw-window-handle` and `matches!` should be fine as well.

Though, in the future such identity may go away anyway when the backends could be plugged/etc.
