### ISSUE TITLE
Rapid cursor movement causes frame loss

### ISSUE THREAD

**Issue by AuracleTech** [rust-windowing/winit#3689]
### Description

Faster cursor moves, the less framerate

No render load :
- no cursor movement : ~4500 draw/s
- rapid cursor movement : ~300  draw/s

Heavy render load :
- no cursor movement : ~20 draw/s
- rapid cursor movement : ~5 draw/s

Tried this [pull request for high polling rate fix](https://github.com/rust-windowing/winit/pull/3609), didn't work
Note that I do not even utilize inputs yet

[my event loop source](https://github.com/AuracleTech/nhope/blob/084a2c1c82211f181ce0e7bd7d756724dc8d7e72/examples/example.rs)

`Green` = framerate with no cursor movement
`Red` = framerate with rapid cursor movements

![image](https://github.com/rust-windowing/winit/assets/40531871/3fd9c6b0-4d4b-4fca-b1d1-4f218140ac00)

### Windows version

```shell
Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
```

### Winit version

0.29.15

**Comment by AuracleTech** [comment]
Seems like a strange issue. When recording, the bug is less visible. Tried changing Razer Synapse between 125hz and 8000hz, losing frames mostly at 8000hz. When OBS records I only lose 3-4 frames at 8000hz. Thinking it might be a Windows problem rather than winit. Profiling needed for confirmation.

**Comment by AuracleTech** [comment]
The issue appears to happen even without using `winit` so this is a Microsoft Windows issue...

# flamegraph
Note : function name are cryptic because they aren't from rust but from the Windows OS itself

![image](https://github.com/rust-windowing/winit/assets/40531871/903e346c-ef74-4d7b-a19c-6187967012c0)

# Windows performance analyzer
#### No cursor movement : 
- 33 000 `Thread: CSwitch`
- almost zero `QueueNullPostMessage`
![image](https://github.com/rust-windowing/winit/assets/40531871/0be9eddc-6fb0-400f-b794-1904a6050d41)

#### Cursor movement :
- 225 000 `Thread: CSwitch`
- 4000 `QueueNullPostMessage` which are the same length as the `Thread: CSwitch` so they must be related somehow
![image](https://github.com/rust-windowing/winit/assets/40531871/6943ca12-7cec-469c-8ba0-e8a826b2755e)

Hot spot can be found in `winit/src/platform_impl/windows/event_loop.rs` line ~`460` where a `loop` iterates.
If you stopwatch, the whole `loop` takes `100` nanoseconds with the cursor at rest.
But with rapid cursor movements it ramps up to `50` to `150` **milliseconds**, this is a *massive* performance hit.

Temporary fix 1 : Reduce polling rate of cursor to 1000hz or under. (Simple)
Temporary fix 2 : Multithread the renderer and do not rely on `WindowEvent::RedrawRequested` due to events timing influence

Hopefully this helps

**Comment by madsmtm** [comment]
> polling rate of cursor

Actually, I remember reading a very good article about this before, probably from Hacker News or something, can't seem to find it now. But a quick Google search does indeed suggest that this is a more general problem on Windows.

**Comment by AuracleTech** [comment]
I am closing this issue considering its a windows issue and there's nothing we can do except point fingers at @Microsoft

**Comment by madsmtm** [comment]
I read a related blog post about this today, see https://ph3at.github.io/posts/Windows-Input/
