### ISSUE TITLE
Cross-platform inconsistency in `ApplicationHandler::resumed()`

### ISSUE THREAD

**Issue by daxpedda** [rust-windowing/winit#3699]
Currently Android requires the surface to be recreated in `resumed()`, but this isn't the case for Web and iOS (I think), where the surface does not need to be recreated on `resumed()`.

I'm unsure what the solution here might be, maybe it would be best to split this into two different methods, or maybe we can tell the user somehow that the `Window` is invalid now.

Related: https://github.com/rust-windowing/winit/issues/3695.

**Comment by kchibisov** [comment]
We use `Occluded` for stuff like that on iOS iirc, not sure about the web, but generally if you don't need to do anything you could just use `Occluded` as well.

Unless the state is something different than what `Occluded(true)` is.

**Comment by daxpedda** [comment]
No, this is not related to `Occluded`.
Speaking for Web: on `suspended()` the application will actually not be running until `resumed()` is fired.

**Comment by MarijnS95** [comment]
@daxpedda this sounds like the original misunderstanding that "suspended" and "resumed" have anything to do with the Android lifecycle, which they also do not. This is merely supposed to be a callback on the `Surface` when it (dis)appears. There are separate events, that are not handled in `winit` currently, that signify when an app stops/starts or pauses/unpauses (more closely related to being in focus or "occluded").

If web doesn't actually need to recreate a window, `resumed()` is the wrong event for this. As proposed longer ago, we should perhaps provide users with such events, and rename the existing events to "surface created" and "surface removed"?
