### ISSUE TITLE
doc: pre_present_notify feature is not documented in FEATURES.md

### ISSUE THREAD

**Issue by filnet** [rust-windowing/winit#3703]
So it is hard to know on which platforms it is supported.

**Comment by kchibisov** [comment]
It should say so in the docs instead like all other APIs.

`FEATURES.md` should be removed anyway since it serves no real purpose anymore.

**Comment by filnet** [comment]
There is documentation https://github.com/rust-windowing/winit/blob/fff6788c12826e15631f32c1176ff679a3b1983c/src/window.rs#L633 but it is not clear which platforms actually support it. Reads like all platforms do.

**Comment by kchibisov** [comment]
it's only wayland, it should be documented that nothing other than wayland supports it.

**Comment by filnet** [comment]
Note that when creating a PR you are asked if `FEATURES.md` was updated...
