### ISSUE TITLE
How to get primary monitor size with `EventLoop::primary_monitor` gone in winit 0.30

### ISSUE THREAD

**Issue by alexheretic** [rust-windowing/winit#3723]
I used the primary monitor size to inform setting up of `WindowAttributes` (previously `WindowBuilder` in 0.29). This no longer seems possible in 0.30 as these methods were moved out of `EventLoop`.

Is it possible to access this info before building the window with 0.30?

```rust
let primary_monitor = event_loop // EventLoop<()>
    .primary_monitor()
    .or_else(|| event_loop.available_monitors().next())
    .expect("No monitors found to render on");
let (win_width, win_height): (u32, _) = primary_monitor.size().into();

let mut window_attrs = Window::default_attributes();
// ... use win_width & win_height to setup

// build window

// run loop
```

**Comment by kchibisov** [comment]
Building window outside of event loop is deprecated. Inside of event loop everything is still there as before.

**Comment by alexheretic** [comment]
`WindowAttributes::with_inner_size` etc don't seem deprecated. It's just that I can no longer query the primary monitor info any more to use that dynamically.

I haven't migrated to the new trait yet. So I guess this can only be done now with that now. Just seems a bit of an odd limitation.

**Comment by kchibisov** [comment]
`ActiveEventLoop` has `primary_monitor` and that's the type you work with inside the loop. The limitation is because you need loop running to get such information in general.

The API was not that reliable before and primary monitor as a concept is not a great thing either.

**Comment by alexheretic** [comment]
Ok thanks for the info
