### ISSUE TITLE
`RequestRedraw` not firing if `Window` is not visible

### ISSUE THREAD

**Issue by Bromles** [rust-windowing/winit#3782]
### Description
When I use `with_visible(false)` during `Window` creation or `set_visible(false)` on actual `Window`, all subsequent `RequestRedraw` events are missing. Neither `ControlFlow::Poll` nor manual `window.request_redraw()` cause `RequestRedraw` event processing

---
minimal reproduction

```rust
use winit::application::ApplicationHandler;
use winit::event::WindowEvent;
use winit::event_loop::{ActiveEventLoop, ControlFlow, EventLoop};
use winit::window::{Window, WindowAttributes, WindowId};

fn main() {
    let event_loop = EventLoop::new().unwrap();
    let mut app = App::Loading;

    event_loop.run_app(&mut app).unwrap();
}

enum App {
    Loading,
    Ready {
        window: Window
    },
}

impl ApplicationHandler for App {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        if let Self::Loading = self {
            let window_attributes = WindowAttributes::default().with_visible(false);

            let window = event_loop.create_window(window_attributes).unwrap();
            
            event_loop.set_control_flow(ControlFlow::Poll);
            
            *self = Self::Ready { window };

            let Self::Ready {window, ..} = self else {
                return;
            };

            window.request_redraw();
        }
    }

    fn window_event(&mut self, event_loop: &ActiveEventLoop, _window_id: WindowId, event: WindowEvent) {
        let Self::Ready {
            window,
        } = self
        else {
            return;
        };

        match event {
            WindowEvent::CloseRequested => event_loop.exit(),
            WindowEvent::RedrawRequested => {
                println!("RedrawRequested");
                window.set_visible(true);
            }
            WindowEvent::Resized(_) => {
                println!("Resized");
            }
            _ => {}
        }
    }
}
```

With this code, I observe only one "Resized" line in the output

If I change `with_visible(false)` to `with_visible(true)`, there are 3 "Resized" lines in the output and then one "RedrawRequested". 

It seems like `Window` is not receiving `RequestRedraw` events if it is not visible. I think this is either a bug or an undocumented behavior

---
### Platform: 
WIndows 11 Enterprise, Version 23H2, OS build 22631.3737

### Winit version:
0.30.3

**Comment by kchibisov** [comment]
The documentation clearly says so https://docs.rs/winit/latest/winit/window/struct.Window.html#method.request_redraw though, that there's no guarantee when it'll arrive, the thing it that it'll.

I think if you toggle `set_visible` after a while it'll make you receive it.

**Comment by Bromles** [comment]
It works fine if I just call `window.set_visible(true)` from another thread with arbitrary delay after `resumed` (i.e. after 2 seconds)

But my initial intention was to create an invisible window, wait for first render in `RedrawRequested` and make it visible right after that. All of this was to avoid showing pure white window to users before first render, just like advised in this section of the docs: https://docs.rs/winit/latest/winit/index.html#drawing-on-the-window

But this workaround with delayed `set_visible` seem too fragile and arbitrary, I'd prefer to use actual lifecycle events that Winit provides

**Comment by Bromles** [comment]
Also seems like my call to `window.request_redraw()` is put into queue but not handled until window is visible, since I can see "RedrawRequested" in the output when `window.set_visible(true)` is triggered after delay

**Comment by kchibisov** [comment]
>Also seems like my call to window.request_redraw() is put into queue but not handled until window is visible, since I can see "RedrawRequested" in the output when window.set_visible(true) is triggered after delay

That what docs say, that your request will arrive eventually, because that how windows want you to draw since it doesn't think that your window should be drawn, because it's not visible.

I'd suggest to just fill the window with color and then make it visible following the normal loop.

**Comment by Bromles** [comment]
I solved it by rendering the first frame right in `resumed` and making the window visible after that. I think that issue can be closed, thank you for clarification
