### ISSUE TITLE
Crash on 0.30.1+ when creating immediate child viewports

### ISSUE THREAD

**Issue by ArthurBrussee** [rust-windowing/winit#3800]
### Description

Hiya! I've been doing some work for a winit upgrade for egui (https://github.com/emilk/egui/pull/4849), but, it seems that [this ](https://github.com/rust-windowing/winit/pull/3684) commit has introduced a crash on macOS. The multiple_viewports example spawns a immediate child viewport, but on macOS this crashes with:

`Segmentation fault: 11`

It seems some precondition of retain is violated (though it's a safe function? Is `objc2` wrong? Really above my paygrade I'm afraid!) 

<img width="1171" alt="Screenshot 2024-07-19 at 01 04 30" src="https://github.com/user-attachments/assets/919dbc65-4a91-467d-bf41-9753947251ee">

This might already be fixed in 0.31.0 as I think the code in that area has changed a bit, but either way wanted to let you know.

### macOS version

```shell
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79
```

### Winit version

0.30.0 works, 0.30.1+ crashes

**Comment by ArthurBrussee** [comment]
Update: It seems like this was a false alarm and caused by unsafe undefined behaviour in egui. Waiting a bit for the winit upgrade PR to be fully tested & landed, and will close this then. Apologies for the noise!

**Comment by ArthurBrussee** [comment]
Oh strange! In egui the cause was some bad unsafe code. Specifically around these bits:

https://github.com/emilk/egui/commit/6f2f006885a6d81eb7a6f8ef5ae36b97ee3fb145#diff-31986c1b45795fe76fd65d559692c61cb9fac99582526da317a37598d1b97d22L321

I can't 100% remember but it was trying to pass the event_loop to child windows, but the claimed lifetime guarantees there weren't right at all.  That was solved with an "EventLoopGaurd" https://github.com/emilk/egui/commit/6f2f006885a6d81eb7a6f8ef5ae36b97ee3fb145#diff-61057fd82c6983a59c1045857b33f20b6d20ed7836019c46f6f842ac3e974505R1

I find it hard to say what exactly changed in winit that triggered this and how the crash relates, as it all might just be lottery of undefined behaviour, but if you have some unsafe code around event loops, I guess check those!

**Comment by jdm** [comment]
That sounds extremely similar to what we're doing in Servo, complete with lifetime shenanigans around event loops. Thanks for the pointers!
