### ISSUE TITLE
`WindowEvent::KeyInput` lags on gnome X11, but not on i3

### ISSUE THREAD

**Issue by cfagot** [rust-windowing/winit#3815]
### Description

This issue most prominently displays itself in games when holding a key down for an action and repeat rate is faster than the frame rate. In that case when you stop pressing the key you will immediately get a device event for the key release, but the WindowEvent::KeyboardInput will continue for some time before the release event arrives. I haven't seen this on wayland, windows, or x11+i3, which is all I've tested on. But I have seen it on 2 ubuntu+gnome+x11 installs, and Johhn-Nagle saw it on same.

Note that nothing like this happens with mouse events even though they are generated at a much higher frequency, so has nothing to do with the app not draining events fast enough.

The following app demonstrates this and can be used to test on different platforms (visually with the animated triangles and also in the console output where you can see what events arrive between new_events and about_to_wait:

https://github.com/cfagot/test_winit_event

Even though this is most easily seen with repeat events, this also happens with any key events that happen in clumps, which is typical typing behavior. I test by just mashing on the keyboard which I find strangely satisfying.
 
**Also important to note that when run with i3 instead of gnome, this does not happen.**

Note: a lot of the details can be found in [this](https://github.com/rust-windowing/winit/discussions/3373) thread (start after John-Nagle starts posting).

### OS and window mananger

Ubuntu 22.04 LTS/Gnome. But as mentioned in the description, I tested with i3 and the issue does not occur there.

### Winit version

0.30.3, but have also seen the same issue on 0.29.*

**Comment by John-Nagle** [comment]
Thanks. I have a program that sometimes runs at low frame rates, and key events can get way behind. If key repeat is 15Hz and frame rate is 12Hz, and you hold down an arrow key, you can build up a huge backlog.

(Use case: I'm working on improving performance, and sometimes run in debug mode, which is why I hit this.)

**Comment by kchibisov** [comment]
Just for the clarity.

Repeat can not be disabled per application level on X11. If your app is not draining the loop you're out of luck, so don't stall the connection and do batching, whatever.

`single_iteration` drains all the events from the X queue. If you read it, you'll see `drain_events` which has `while` loop over all the events inside the connection. If they are not there means that we haven't received them from the X server yet.

However on the _gnome_ vs _i3_ is a completely different issue and is related to how input method works.

**Comment by cfagot** [comment]
I understand what drain is doing, which is why I mention that mouse events don't have the same issue. So for whatever reason that key events arrive one per single_iteration call, it's surely not ideal (and also seems to be unique to x11 with gnome).

**Comment by John-Nagle** [comment]
Right, mouse events are fine. Only keyboard events have this problem. I see it on x11, but don't have other platforms for testing.

**Comment by kchibisov** [comment]
As I said, they arrive normally, it's just they go through the input method and `SendEvent` one more time. The solution would probably to just straight disable this forwarding.

**Comment by cfagot** [comment]
Sure thing. It might not be till tomorrow but I'll get to it.

Thanks for the fix.

**Comment by cfagot** [comment]
I couldn't fully apply to 0.32 (the version I am using) because ime is not
defined on ActiveEventLoop. Needed for this line
in src/platform_impl/linux/x11/event_processor.rs:

let ime = self.target.ime.as_ref();

But I tested by just setting forward_to_ime to false and it fixes the
problem. I think that's the only thing you need me to test.

Anyway, yes, I think this is the fix for what John and I were seeing.
Thanks!

clark

**Comment by SUPERCILEX** [comment]
This caused a bug in egui, see https://github.com/rust-windowing/winit/issues/4048

**Comment by Knar33** [comment]
I am still seeing this issue in Bevy which uses winit version 0.30.6 - it propagates an ime_allowed property to set_ime_allowed() and even when I set it to false I still get this issue - when I release a key I get a released event then an extra pressed event followed by another released event (which comes much later if my framerate is low). 

maybe it's related to this? https://github.com/rust-windowing/winit/issues/3092

**Comment by kchibisov** [comment]
You should try `0.30.7`, if IME disable doesn't work (we don't even init it at this point), then I'm not entirely sure how to solve this, since you literally have nothing in between and winit just forwards.

**Comment by Knar33** [comment]
That got rid of the extra release + press but the only release I get now is the one that is delayed. In 0.30.6 I got a release as soon as I released the key, followed immediately by a press, then a delay and another release.

**Comment by kchibisov** [comment]
If you were getting extra events that meant that you haven't disabled IME? Like the issue was only present when IME was around, without it it was not the case.

**Comment by Knar33** [comment]
I just double checked in both 0.30.6 and 0.30.7 to be sure, it seems like having ime enabled/disabled makes no difference. Maybe Bevy sets it incorrectly (winit_window is just a Window object) https://github.com/bevyengine/bevy/blob/8d9a00f5483b2ba28f40081759bd3d6f8b8a686d/crates/bevy_winit/src/system.rs#L516 

In 0.30.6 releasing a key would give me an immediate release event followed by a press event, then a delay and a second release event 

In 0.30.7 releasing a key gives just has a delay then a single release event.

**Comment by kchibisov** [comment]
Test with the `--example window` in winit to check, but I don't see why it wouldn't work.

**Comment by kchibisov** [comment]
idk, you can try https://github.com/rust-windowing/winit/pull/4056, but I'm not adding a new patch release just for that, since I have no idea if it's really how it should be.

On other compositors it seems that the current code works just fine.

**Comment by Knar33** [comment]
> idk, you can try #4056, but I'm not adding a new patch release just for that, since I have no idea if it's really how it should be.
> 
> On other compositors it seems that the current code works just fine.

This patch fixes my issue! I ran into some trouble patching because the cargo.toml in #4056 is a bit different from 0.30.x but I figured it out.

I did try `--example window` and got no delay for key releases, even when I revert to 0.30.5. I'm not sure if that means bevy configures the window incorrectly or consumes events in a weird way, but either way #4056 makes the issue go away.

**Comment by John-Nagle** [comment]
I may have the same problem, as mentioned at https://github.com/rust-windowing/winit/issues/4048

Is #4056 planned to go into a future winit release, or is that branch test-only pending further info?

**Comment by kchibisov** [comment]
Should go, but needs a review.

**Comment by John-Nagle** [comment]
I'd appreciate a release off of 0.30.x, or at least a branch, which has this fix, but not all the breaking changes that are in unreleased trunk. 

- 0.30.7 is too sluggish for games because of this. Avatars controlled by arrow keys can barely walk around. Driving is hopeless. My Sharpview project can't release.
- Building against trunk Winit breaks Egui and its friends. I tried.
- Going back to an earlier version of Winit breaks recent changes in Egui, Wgpu, and their friends.
- A full update cycle for everything that depends on Winit takes 1-2 months as all the other projects advance, and won't start until Winit 0.31.x appears. So there won't be a solid stack again until spring. 
- I can fork Winit if I have to, but then things start to diverge.

Thanks.

**Comment by madsmtm** [comment]
See https://github.com/rust-windowing/winit/pull/4072

**Comment by John-Nagle** [comment]
All fixed! I'm happily driving around the virtual world on Winit 0.30.8. Thanks.
