### ISSUE TITLE
WindowEvent::ReceivedCharacter(char) returns empty char when Ctrl is pressed

### ISSUE THREAD

**Issue by markusmoenig** [rust-windowing/winit#3817]
I am using v0.28 as this is the last version pixels uses. I cannot get the char of the currently pressed key when Ctrl is down. This happens on all OSes. Any workaround ? I do not need a code, but the character of the key itself.

I do not know if this is a bug or for some reason the correct behavior.

Thanks

**Comment by kchibisov** [comment]
`text_with_all_modifiers`.

**Comment by markusmoenig** [comment]
And how do I get access to it in your cryptic API ?
