### ISSUE TITLE
Missing "key_binding" example

### ISSUE THREAD

**Issue by markusmoenig** [rust-windowing/winit#3821]
As I try to find out how to use 'key_without_modifiers' I found the following comment in the *control_flow.rs* example:

// WARNING: Consider using `key_without_modifiers()` if available on your platform.
// See the `key_binding` example

But there is no *key_binding* example ...

**Comment by kchibisov** [comment]
https://github.com/rust-windowing/winit/blob/master/examples/window.rs#L414

It all depends on what/how you want to do things.
