### ISSUE TITLE
Cursor icon doesn't follow system cursor theme

### ISSUE THREAD

**Issue by HaoliangXu** [rust-windowing/winit#3863]
### Description

This is the theme showing on a winit window:
![Screenshot from 2024-08-13 16-09-56](https://github.com/user-attachments/assets/bc181bc8-901f-4603-8b33-4afe0ca6241a)

This is the cursor theme(Yaru on Ubuntu) showing on another application:
![Screenshot from 2024-08-13 16-12-36](https://github.com/user-attachments/assets/7c8d222f-e740-406d-a9b7-72fb1f7873cf)

It's inconsistent experience for an end user, especially for "resize" icons.

### Window isn't shown unless you draw

- [X] I understand that windows aren't shown on Wayland unless I draw and present to them.

### Winit version

0.30.5

**Comment by kchibisov** [comment]
Set `XCURSOR_THEME` to the cursor you're using.

You're likely setting your from the dbus.

**Comment by HaoliangXu** [comment]
I actually did this before the post. It works. I know it can be made permanently. But other applications, even the ones made all by rust, don't need to set this variable. Like what I said, to the end users, who may not know how to set it, it's not a good experience.

**Comment by kchibisov** [comment]
We use the `default` theme when the variable is missing and also use the cursor-shape-v1 protocol.

If the rust app is using dbus it won't have this issue.

Nothing winit can do about it, since it tries to look for default theme and you have nothing set as default in _traditional_ way of setting it(~/.icons/default).

**Comment by HaoliangXu** [comment]
Thank you for the reply, I think I understand now.
Do you mean the variable is missing and "not" using cursor-shape-v1 protocol?
So the way to solve it is to use dbus in addition with winit in the application.

**Comment by kchibisov** [comment]
cursor-shape-v1 means that compositor sets the cursor, so it's not used, likely because your system is too lod.

The way to solve it is to set the theme in your configuration. _You certainly can_ use dbus to get the GTK variable, but it's _GTK_ specific.
