### ISSUE TITLE
Docs.rs build failure on v0.30.5

### ISSUE THREAD

**Issue by eidloi** [rust-windowing/winit#3881]
Ahoy! I released a crate (`sickle_ui`) that builds on `bevy`, which in turn has a dependency on `winit`. The build went fine, but someone noted that the docs could not be built on `docs.rs`.

The error: 

```
[INFO] [stderr]     Checking winit v0.30.5
[INFO] [stderr] error: The platform you're compiling for is not supported by winit
[INFO] [stderr]   --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/mod.rs:78:1
[INFO] [stderr]    |
[INFO] [stderr] 78 | compile_error!("The platform you're compiling for is not supported by winit");
[INFO] [stderr]    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The logs can be checked here: https://docs.rs/crate/sickle_ui/0.2.3/builds/1327978/x86_64-unknown-linux-gnu.txt

NOTE: The previous build I did about an hour prior to this built fine with v0.30.4: https://docs.rs/crate/sickle_ui/0.2.2/source/Cargo.lock#4214

**Comment by daxpedda** [comment]
I assume this is https://github.com/rust-windowing/winit/issues/3174.
You depend on `bevy` with `default-features = false`, but Winit needs at least one backend enable to allow compilation.

**Comment by eidloi** [comment]
> I assume this is #3174. You depend on `bevy` with `default-features = false`, but Winit needs at least one backend enable to allow compilation.

aahhhh that makes sense. I didn't consider this thanks!
