### ISSUE TITLE
When using multiple windows on webgl, an error is displayed

### ISSUE THREAD

**Issue by zhuliang198754** [rust-windowing/winit#3916]
### Description

When using multiple windows on the WEBGL platform, the rendering position of the non-main window is displayed incorrectly, but WEBGPU is normal

                 let second_window = commands
                    .spawn((
                        Window {
                            title: "xxx".to_owned(),
                            canvas: Some(canvas_id),
                            transparent: true,
                            composite_alpha_mode: if adapter.backend == wgpu_types::Backend::Gl
                            {
                                bevy::window::CompositeAlphaMode::default()
                            } else {
                                bevy::window::CompositeAlphaMode::PreMultiplied
                            },
                            fit_canvas_to_parent: false,
                            ..default()
                        },
                    ))
                    .id();

                let second_window_camera = commands
                    .spawn((
                        Camera3dBundle {
                            tonemapping: Tonemapping::None,
                            camera: Camera {
                                target: RenderTarget::Window(WindowRef::Entity(second_window)),
                                ..default()
                            },
                            ..default()
                        },
                    ))
                    .id();

![365890434-b860fe14-aec7-41f5-ac24-b7bdcaf55f69](https://github.com/user-attachments/assets/ffcb047c-d414-431a-9503-c9a1da814e42)

### Tested browsers

Chrome, Microsoft Edge

### Tested devices

windows

### Winit version

0.30

**Comment by zhuliang198754** [comment]
I haven't found the problem yet, does anyone know the reason?

**Comment by daxpedda** [comment]
I'm unable to understand the bug report:
- Where is the second "window" in the screenshot?
- This is not the Bevy repository, it is Winit. However if a minimal reproducible example (even with Bevy) is given I'm willing to take a look.
- "the rendering position of the non-main window is displayed incorrectly" what does that mean?
  - Do you mean its not rendered at the correct position?
  - How did you determine or set the position?
  - How is it incorrect?

I'm gonna go ahead and close this, but please tell us if you have any answers to these questions!

**Comment by zhuliang198754** [comment]
When more than two windows are instantiated and all windows are associated with canvas, the problem of displaying the image not being at the canvas position occurs.

**Comment by zhuliang198754** [comment]
> I'm unable to understand the bug report:
> 
> * Where is the second "window" in the screenshot?
> * This is not the Bevy repository, it is Winit. However if a minimal reproducible example (even with Bevy) is given I'm willing to take a look.
> * "the rendering position of the non-main window is displayed incorrectly" what does that mean?
>   
>   * Do you mean its not rendered at the correct position?
>   * How did you determine or set the position?
>   * How is it incorrect?
> 
> I'm gonna go ahead and close this, but please tell us if you have any answers to these questions!

@daxpedda 

When more than two windows are instantiated and all windows are associated with canvas, the problem of displaying the image not being at the canvas position occurs.

**Comment by zhuliang198754** [comment]
@daxpedda   Only webgl is wrong

**Comment by daxpedda** [comment]
> the problem of display not being at the canvas position occurs.

What is a "display"?
Are you saying that what you draw is not drawn at the position of the canvas?

---

It would help if you try to answer the questions directly.

I did try this locally and everything seems to work correctly.
It might be an issue in Wgpu, see https://github.com/gfx-rs/wgpu/issues/2343, I didn't try with Wgpu yet, but I will when I get to it.

**Comment by zhuliang198754** [comment]
> > the problem of display not being at the canvas position occurs.
> 
> What is a "display"? Are you saying that what you draw is not drawn at the position of the canvas?
> 
> It would help if you try to answer the questions directly.
> 
> I did try this locally and everything seems to work correctly. It might be an issue in Wgpu, see [gfx-rs/wgpu#2343](https://github.com/gfx-rs/wgpu/issues/2343), I didn't try with Wgpu yet, but I will when I get to it.

Thank you so much。It's the same situation https://github.com/gfx-rs/wgpu/issues/2343
