### ISSUE TITLE
Keyboard event text is reported incorrectly for multi-key sequences (e.g. üïêéè) on X11

### ISSUE THREAD

**Issue by rikusalminen** [rust-windowing/winit#3917]
### Description

Winit is reporting incorrect text on X11 for keyboard events when typing characters that need multiple keypresses. I am using fi/se keyboard layout, but this is common on many European keyboard layouts.

As an example, to type the character `ü`, there are two keypresses needed: first, press the umlaut key `"` followed by pressing the `u` key.

Winit reports the following events for this keypress sequence:
```
KeyboardInput {
    device_id: DeviceId(
        X(
            DeviceId(
                3,
            ),
        ),
    ),
    event: KeyEvent {
        physical_key: Code(
            BracketRight,
        ),
        logical_key: Unidentified(
            Xkb(
                0xFE57,
            ),
        ),
        text: None,
        location: Standard,
        state: Released,
        repeat: false,
        platform_specific: KeyEventExtra {
            text_with_all_modifiers: None,
            key_without_modifiers: Unidentified(
                Xkb(
                    0xFE57,
                ),
            ),
        },
    },
    is_synthetic: false,
}
KeyboardInput {
    device_id: DeviceId(
        X(
            DeviceId(
                3,
            ),
        ),
    ),
    event: KeyEvent {
        physical_key: Code(
            KeyU,
        ),
        logical_key: Character(
            "u",
        ),
        text: Some(
            "u",
        ),
        location: Standard,
        state: Pressed,
        repeat: false,
        platform_specific: KeyEventExtra {
            text_with_all_modifiers: Some(
                "u",
            ),
            key_without_modifiers: Character(
                "u",
            ),
        },
    },
    is_synthetic: false,
}
KeyboardInput {
    device_id: DeviceId(
        X(
            DeviceId(
                3,
            ),
        ),
    ),
    event: KeyEvent {
        physical_key: Code(
            KeyU,
        ),
        logical_key: Character(
            "u",
        ),
        text: Some(
            "u",
        ),
        location: Standard,
        state: Released,
        repeat: false,
        platform_specific: KeyEventExtra {
            text_with_all_modifiers: Some(
                "u",
            ),
            key_without_modifiers: Character(
                "u",
            ),
        },
    },
    is_synthetic: false,
}
```

In the log above, the keypresses report `text`, `text_with_all_modifiers` and `key_without_modifiers` as `u`, not `ü`. This is incorrect.

The keypress event for the `u` key should return `ü` in the `text` field as reported by `XFilterEvent` / `Xutf8LookupString`.

Without `window.set_ime_allowed()`, the only IME event that occurs is `Ime(Disabled)`.
With `window.set_ime_allowed(true)`, these IME events are produced:
```
Ime(
    Preedit(
        "",
        None,
    ),
)
Ime(
    Commit(
        "ü",
    ),
)
```

The pre-edit event string is empty, it should probably be `"`. With IME there's no key press event for the u character.

In my opinion it would be more useful if character input events were separate from key press events as they do not have a 1:1 mapping. This is a common pattern in other APIs in this domain (SDL, GLFW, etc). This would simplify the winit codebase, especially on platforms where the text input events are separate from keyboard events (e.g. Windows `WM_CHAR` and `WM_SYSCHAR` and Android's `ReceivedCharacter` #2305).

### OS and window mananger

Linux, OpenBox

### Winit version

0.30.5

**Comment by rikusalminen** [comment]
Never mind, the behaviour with `window.set_ime_enabled(true)` is acceptable. Maybe this should be the default?

It would still make sense to have separate text input events to key events.

**Comment by kchibisov** [comment]
@rikusalminen it really depends where they'll go depending on the IME on X11, on Wayland, they are inside the `KeyInput` and you have `Dead`, etc events, on X11 with XIM you have issues like that.
