### ISSUE TITLE
Very high CPU usage on Wayland due to constant RedrawRequested events

### ISSUE THREAD

**Issue by vladh** [rust-windowing/winit#3933]
### Description

I'm using iced and encountering very high GPU usage in all use cases, on Wayland only. (https://github.com/iced-rs/iced/issues/2558)

I'm testing whether winit is the cause of the issue. I'm using the following Hello World program:

```rust
use winit::application::ApplicationHandler;
use winit::event::WindowEvent;
use winit::event_loop::{ActiveEventLoop, ControlFlow, EventLoop};
use winit::window::{Window, WindowId};

#[derive(Default)]
struct App {
    window: Option<Window>,
}

impl ApplicationHandler for App {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        self.window = Some(event_loop.create_window(Window::default_attributes()).unwrap());
    }

    fn window_event(&mut self, event_loop: &ActiveEventLoop, _id: WindowId, event: WindowEvent) {
        match event {
            WindowEvent::CloseRequested => {
                event_loop.exit();
            },
            WindowEvent::RedrawRequested => {
                self.window.as_ref().unwrap().request_redraw();
            }
            _ => (),
        }
    }
}

fn main() {
    let event_loop = EventLoop::new().unwrap();
    event_loop.set_control_flow(ControlFlow::Wait);
    let mut app = App::default();
    let _ = event_loop.run_app(&mut app);
}
```

Running this on my system causes very high CPU usage:

![2024-09-28-18-46-01](https://github.com/user-attachments/assets/8e9a295a-3da3-42eb-ac38-62cfe17c1513)

My understanding is that this shouldn't happen with `ControlFlow::Wait`.

The CPU usage drops to ~0% if I remove this line:

```rust
self.window.as_ref().unwrap().request_redraw();
```

Printing the events received shows constant `RedrawRequested` events — 76,000 events per second.

Do you have any pointers about how I might continue debugging this? I'm happy to put in more work, but am a bit stumped right now.

### Window isn't shown unless you draw

- [X] I understand that windows aren't shown on Wayland unless I draw and present to them.

### Winit version

0.30.5

**Comment by kchibisov** [comment]
you ask to draw as fast as you can so everything works as expected. If you want to throttle drawing, use `pre_present_notify`(all of that is mentioned in docs).

**Comment by kchibisov** [comment]
Keep in mind here, the `pre_present_notify` will only work if you do the drawing, if you don't ever do that it's pretty much useless and won't change anything.

The default `window.rs` example does things pretty much as they should and draws with the display refresh rate, etc, etc.
