### ISSUE TITLE
Bring back the nice examples back in v0.29.x

### ISSUE THREAD

**Issue by Nekomaru-PKU** [rust-windowing/winit#3935]
### Description

I've noticed that back in `v0.29.x`, we have up to 39 examples under `examples/` demonstrating various usages of `winit`, but after the huge API change in v0.30, we have only 6 in current `master`. I'm more than willing to help with bringing the lost examples back, which may help newcomers to get familiar with this outstanding crate more smoothly.

I'm mainly a Windows developer with a MacBook aside, so I'll check on these two platforms before appending any commit to a pull request. However I may need help to make sure the examples that I rewrite are error-free on other platforms.

**Comment by kchibisov** [comment]
half of them were broken, part moved to docs, and whatever left shows conceptually different aspects, like run methods, etc. Having example for each window method call made no sense and they were never updated, so they are all in window.rs now.

I'd accept a rename of `window.rs` to `app.rs` and adding `window.rs` which is like in docs for lib.rs + softbuffer basic drawing, but that's about it.

**Comment by Nekomaru-PKU** [comment]
That sounds reasonable. I'll close this issue. Thanks for your comment!

**Comment by Nekomaru-PKU** [comment]
That sounds reasonable. I'll close this issue. Thanks for your comment!
