### ISSUE TITLE
Device events for keyboard not arriving, focused or not.

### ISSUE THREAD

**Issue by yanchith** [rust-windowing/winit#3937]
### Description

Hi all,

Recently ran into the issue, that there's no key device events on macOS, whether the window is focused or not.

```rust
    fn device_event(
        &mut self,
        _event_loop: &winit::event_loop::ActiveEventLoop,
        _device_id: winit::event::DeviceId,
        event: winit::event::DeviceEvent,
    ) {
        match event {
            winit::event::DeviceEvent::Key(key) => {
                println!("key    {key:?}"); // This never happens
            }

            _ => (),
        }
    }
```

Window events for keyboard input arrive just fine.

### macOS version

```shell
ProductName:		macOS
ProductVersion:		14.1.2
BuildVersion:		23B2091
```

### Winit version

0.30.5

**Comment by kchibisov** [comment]
Device events are not guaranteed. They also never send on Wayland since it's how platform works. macOS is close to it there.
