### ISSUE TITLE
Add support in web for showing virtual keyboard

### ISSUE THREAD

**Issue by will-hart** [rust-windowing/winit#3938]
### Description

When using winit in a mobile web browser in web builds, I don't have a way to pop up the virtual keyboard, which means I can't use (most) custom GUI libraries for text input.

I came across this via [`bevy_simple_text_input`](https://github.com/rparrett/bevy_simple_text_input/issues/75). egui supports keyboard inputs by using a [hidden input field](https://github.com/emilk/egui/pull/253/files) but ideally winit would provide a way to do this.

This is possibly a duplicate of #1823 and #2260.

### Relevant platforms

web with a mobile device (tablet/phone)

**Comment by daxpedda** [comment]
Closing in favor of #1823.
