### ISSUE TITLE
Locking the cursor, but detecting movement as well?

### ISSUE THREAD

**Issue by jjant** [rust-windowing/winit#3945]
Hi, I want to be able to lock the cursor in position when holding the left button on the window, and detect mouse movement while the cursor is locked. The use case is to support game-engine style camera panning.

I tried using `window.set_cursor_grab(Locked);` but after locking the cursor, all `CursorMoved` events return the same position, so I can't calculate a delta (which I need). How/can this be done with Winit?

I'm on OSX btw.

**Comment by kchibisov** [comment]
https://docs.rs/winit/latest/winit/event/enum.DeviceEvent.html#variant.MouseMotion
