### ISSUE TITLE
Window doesn't open and prints error instead.

### ISSUE THREAD

**Issue by vol8** [rust-windowing/winit#4012]
### Description

*Note: I issued this at the egui repo and they told me that it's a winit problem and I should report the issue here.*

I created a basic window that only has a "Hello World" label. I made in in eframe.
It builds successfully but when I run the program, it prints this error:

```
Error: WinitEventLoop(Os(OsError { line: 81, file: "/home/vol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoWaylandLib)) }))
```

The window doesn't open and just prints this error on the screen.

I am on NixOS using Hyprland as my WM.

### Debugging output

```shell
No debugging output
```

### Window isn't shown unless you draw

- [X] I understand that windows aren't shown on Wayland unless I draw and present to them.

### Winit version

0.30.5, tho I am not sure because I am not using winit directly.

**Comment by kchibisov** [comment]
install `libwayland`.

**Comment by vol8** [comment]
> install `libwayland` ( as it says that there's no lib found).

How do I install `libwayland` on nixos? There's no package entry.

![image](https://github.com/user-attachments/assets/1d1d5736-29ed-4dfd-9557-cbe7de973938)
