### ISSUE TITLE
Winit 0.30.6 triggers two key press events instead of one

### ISSUE THREAD

**Issue by PPakalns** [rust-windowing/winit#4048]
### Description

Problem found while using popular egui library with winit 0.30.6.  winit 0.30.5 works correctly.

Text edit field registers two key press events instead of one.  

If you believe that it is fault of egui integration and the new behavior is correct, feel free to close this issue. Wanted to report it just in case!

### OS and window mananger

Ubuntu 24.04.1 LTS
i3 4.24

### Winit version

0.30.6

**Comment by SUPERCILEX** [comment]
Can confirm this is a winit bug, traced back to 107bf91a2d9ce628a1f5d9fee2f2c6bc1e82d4ce.

**Comment by SUPERCILEX** [comment]
Though looking at the commit, maybe this means egui needs to handle things differently?

**Comment by PPakalns** [comment]
This broke bevy_egui integration too. It retrieves events from bevy, which exposes partially processed events and some winit event data. 

https://github.com/vladbat00/bevy_egui/blob/main/src/systems.rs

It is possible that more than one integration is broken due to this.

**Comment by kchibisov** [comment]
https://github.com/rust-windowing/winit/pull/4049

**Comment by John-Nagle** [comment]
See: https://github.com/emilk/egui/issues/5509

Works in winit 0.30.5, fails in 0.30.6. Repro available.

**Comment by John-Nagle** [comment]
Nice. When will this reach crates.io? Thanks.

**Comment by PPakalns** [comment]
winit 0.30.7 resolves the issue!

Thank you all!

**Comment by John-Nagle** [comment]
Indeed it does. My 3D world viewer is running nicely now. Thanks, and have a good holiday!

**Comment by John-Nagle** [comment]
Uh oh. I'm only getting one key press event in 0.30.7, but it seems to be queued for too long. If I hold down an arrow key while the frame rate is low, I can build up a backlog of key events that play back for seconds after releasing the arrow key.
 
This was a problem some time back, but was fixed. Did this new fix re-create the old problem?

Winit 0.30.7, Linux, X-windows, Ubuntu.

**Comment by kchibisov** [comment]
See https://github.com/rust-windowing/winit/issues/3815#issuecomment-2563204546 , gnome would need one extra patch to workaround things.
