### ISSUE TITLE
Example code doesn't seem to be working

### ISSUE THREAD

**Issue by Sl-L** [rust-windowing/winit#4053]
I just cloned the repository and tried running `cargo run --example child_window` and while it does compile, the console logging works and it doesn't crash, no child window is being rendered. The `Child window created with id: xxxxxxxx` message appears on the terminal but nothing new appears, am I misinterpreting what the code should be doing or is this not working properly?

Steps to reproduce:
- `$git clone https://github.com/rust-windowing/winit`
- `$cd winit`
- `cargo run --example child_window`
- press [any] key to create new child window

Current behavior: Terminal log message `Child window created with id: xxxxxxxx` appears and nothing, visibly, changes on the parent window

Expected behavior: A new window appears inside the parent window

System:  
 - Kernel: 6.8.0-51-generic arch: x86_64 bits: 64 compiler: gcc v: 13.3.0 clocksource: tsc
 - Desktop: Cinnamon v: 6.2.9 tk: GTK v: 3.24.41 wm: Muffin v: 6.2.0 vt: 7 dm: LightDM v: 1.30.
 - Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble

**Comment by kchibisov** [comment]
How does it look?

**Comment by Sl-L** [comment]
Can't take a screenshot right now (writing this from my phone) but first blank (as in, nothing except the background color and the title bar) window appears titled "parent window", after pressing a key the "child window created" message gets printer on the terminal, the window remains unchanged and no new windows appear. Maybe I should check if the processes that get created for the child windows are actually working on the background and not getting killed to narrow down the issue?

**Comment by kchibisov** [comment]
everything is in the same process. I think the issue could be that all windows are drawn with the same color, so you don't notice that. You can modify example to draw different color for each window.

**Comment by Sl-L** [comment]
So the child windows created don't have a border, title, closing button or anything? Because I tried putting the parent window on full screen and still nothing seemed to change

**Comment by kchibisov** [comment]
child window here is just a slice of the parent window, it's not a modal dialog or anything like that.

**Comment by Sl-L** [comment]
Does the method with_decorations on the window attributes of the child window do anything then? Cause I tried that just now and had the same result

**Comment by kchibisov** [comment]
No, nothing affects them, I'd suggest to tune the `fill_window` to see them.

**Comment by Sl-L** [comment]
I got it to work, the example is currently filling all windows with the same color so the only way to tell spaces apart is using the messages in terminal.
Can I make a pull request tomorrow with an edit of the example or will it just be ignored?

**Comment by kchibisov** [comment]
Sure.
