### ISSUE TITLE
windows: Use of `MsgWaitForMultipleObjects` breaks accessibility

### ISSUE THREAD

**Issue by mwcampbell** [rust-windowing/winit#4055]
Accessibility on Windows is severely broken. The assistive technology (e.g. screen reader) can't consistently obtain UI Automation objects from the window, which means that basically nothing works.

Because the `MsgWaitForMultipleObjects` call uses `QS_ALLEVENTS`, which doesn't include `QS_SENDMESSAGE`, the event loop isn't awakened for blocking accessibility messages like `WM_GETOBJECT`. This was introduced by #3950, which was backported to winit v0.30.x and recently released in v0.30.6 and v0.30.7.

**Comment by kchibisov** [comment]
cc @AngelicosPhosphoros

**Comment by kchibisov** [comment]
I'd note that without it waiting doesn't really work at all, so we should find a way to have both working, otherwise users won't have a way to basically use anything on windows related to timers.
