### ISSUE TITLE
Description: cant compile cargo run --release -p egui_demo_app under fedora 41

### ISSUE THREAD

**Issue by commitcompanion** [rust-windowing/winit#4063]
Description:

I encountered an error while compiling a Rust project using winit version 0.30.7. The error message indicates that the platform is not supported by winit. Here is the error log:

error: The platform you're compiling for is not supported by winit
  --> /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.7/src/platform_impl/mod.rs:78:1
   |
78 | compile_error!("The platform you're compiling for is not supported by winit...
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0432]: unresolved import `self::platform`
  --> /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.7/src/platform_impl/mod.rs:34:15
   |
34 | pub use self::platform::*;
   |               ^^^^^^^^ could not find `platform` in `self`

error[E0432]: unresolved imports `crate::platform_impl::PlatformCustomCursor`, `crate::platform_impl::PlatformCustomCursorSource`
 --> /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.7/src/cursor.rs:8:28
  |
8 | ...::{PlatformCustomCursor, PlatformCustomCursorSourc...
  |       ^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PlatformCustomCursorSource` in `platform_impl`
  |       |
  |       no `PlatformCustomCursor` in `platform_impl`

error[E0432]: unresolved import `crate::platform_impl::PlatformIcon`
 --> /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.7/src/icon.rs:1:5
  |
1 | use crate::platform_impl::PlatformIc...
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PlatformIcon` in `platform_impl`

error[E0432]: unresolved import `crate::platform_impl::PlatformSpecificWindowAttributes`
 --> /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.7/src/window.rs:7:34
  |
7 | ...f, PlatformSpecificWindowAttribute...
  |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PlatformSpecificWindowAttributes` in `platform_impl`

error[E0369]: binary operation `==` cannot be applied to type `&std::option::Option<MonitorHandle>`
    --> /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.7/src/window.rs:1751:16
     |
1746 | ...ne, Debug, PartialEq, Eq)]
     |               --------- in this derive macro expansion
...
1751 | ...ss(Option<MonitorHandle>),
     |       ^^^^^^^^^^^^^^^^^^^^^
     |
     = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

Steps to Reproduce:

    Clone the repository and navigate to the project directory.
    Run the command: cargo run --release -p egui_demo_app.
    Observe the compilation error as described above.

Expected Behavior:

The project should compile successfully without any platform-related errors.
Additional Information:

    Rust Version: 1.80.0
    winit Version: 0.30.7
    Operating System: Linux

_Originally posted by @commitcompanion in https://github.com/rust-windowing/winit/issues/3174#issuecomment-2563512854_

**Comment by kchibisov** [comment]
specify feature you want to build(x11/wayland) and don't spam issue tracker with the same thing in like 3 places, thanks.

**Comment by madsmtm** [comment]
Might also be useful to provide the output from running the command `rustc -vV`
