### ISSUE TITLE
X11 grab mode changes silently

### ISSUE THREAD

**Issue by StarStarJ** [rust-windowing/winit#4064]
### Description

The following scenario bugs out for me on X11:

- At the start of my program I set the mouse to confined, works
- At some point I try to set the mouse to `lock`, which as the doc says is unsupported, the library correctly responds with an unsupported error.
- After this `lock` call the mouse however is not confined anymore. calling `set_cursor_grab` with confined, directly after the error call from the `lock` call, does _not_ throw an error, but `Ok()` instead without confining the mouse to the window.

At this point the state is invalid.
Especially that the last point does not return an error is a problem for me, else I could recover from it.

### OS and window mananger

Linux debian 12
KDE plasma 6.2.4

However this bug was initially reported by a person with i3 WM on arch linux

### Winit version

0.30.7

**Comment by kchibisov** [comment]
Try https://github.com/rust-windowing/winit/pull/4065

**Comment by StarStarJ** [comment]
Seems to work returning an error.

Would there be smth wrong with simply ignoring the whole call if `CursorGrabMode` is `Locked`? Because that seems to be what the windows version does and would make winit more consistent over different backends

**Comment by kchibisov** [comment]
We can, though, the fix I've submitted will be needed anyway.
