### ISSUE TITLE
Wayland set_icon

### ISSUE THREAD

**Issue by Its-Just-Nans** [rust-windowing/winit#4066]
### Description

Hello

Currently `set_window_icon` on Wayland is doing nothing

https://github.com/rust-windowing/winit/blob/5ea81efc74ebaa04a7cb4621ec522bce14d700e5/src/platform_impl/linux/wayland/window/mod.rs#L498

Since https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/269 is merged, shouldn't we able to change `set_window_icon` for wayland ?

I guess something like

```rust
use wayland_protocols::xdg::toplevel_icon::v1::client::xdg_toplevel_icon_manager_v1;

fn set_window_icon(&self, window_icon: Option<crate::window::Icon>) {
    if let Some(icon) = window_icon {
        let icon = xdg_toplevel_icon_manager_v1::XdgToplevelIconManagerV1::create_icon(self.xdg_toplevel_icon_manager_v1, &queue, icon);
        let buffer = xdg_toplevel_icon_manager_v1::XdgToplevelIconManagerV1::set_icon(
            &self.xdg_toplevel_icon_manager_v1,
            icon,
        );
    }
}
```

using https://github.com/Smithay/wayland-rs/blob/c65ff18c6babb67e52fe55f213d263ee7713e7f8/wayland-protocols/src/xdg.rs#L215

Is that planned ?
Thanks

**Comment by Its-Just-Nans** [comment]
@kchibisov I can't find the duplicate, where is it ?

Thanks

**Comment by kchibisov** [comment]
I've said that it's a duplicate, I'm not sure how you're unable to find it.

**Comment by kchibisov** [comment]
https://github.com/rust-windowing/winit/issues/3859

**Comment by Its-Just-Nans** [comment]
> I think it's the same as #2810, it was closed as intentionally unsupported.
> 
> But @kchibisov, could you detail why the proposed solution of using the newer API is not possible/desirable?

- It wasn't possible at the time of #2810 but will be possible with #3859
