### ISSUE TITLE
How do I build a new window inside run_forever or poll_events?

### ISSUE THREAD

**Issue by wez** [rust-windowing/winit#413]
I'd like to be able to spawn a new window in response to user input.

Since the event loop is borrowed mutably by `run_forever` and `poll_events`, there doesn't appear to be a way to spawn new windows in response to input events.

This may be another facet of https://github.com/tomaka/winit/issues/231

**Comment by jwilm** [comment]
One option is to simply break out of the event loop in that case:

```rust
loop {
    let mut flag = false;
    events.run_forever(|event| {
        match event {
            // Event you care about
            flag = true;
            return ControlFlow::Break;
        }
    });
    if flag {
        windows.push(Window::new(&events));
    }
}
```

**Comment by wez** [comment]
Sure, but that's not inside the callback :-p
I'm using `run_forever` for maximum idle reasons, so if I have to break out of the loop its now on me to find a way to efficiently sleep without lagging on processing events per all of the discussion in #231.

**Comment by wez** [comment]
oh, I misread your comment; I didn't really notice that you could call run forever again

**Comment by Osspial** [comment]
This should be fixed by the EventLoop 2.0 API rework, when that gets merged.

**Comment by MendyBerger** [comment]
Now you'd use the [EventLoopWindowTarget](https://docs.rs/winit-gtk/latest/winit/event_loop/struct.EventLoopWindowTarget.html) that you get in the [run](https://docs.rs/winit-gtk/0.28.2/winit/event_loop/struct.EventLoop.html#method.run) method, right?

**Comment by daxpedda** [comment]
Yes, new windows are created with [`Window::new()` ](https://docs.rs/winit/0.29.15/winit/window/struct.Window.html#method.new), which takes a [`EventLoopWindowTarget`](https://docs.rs/winit/0.29.15/winit/event_loop/struct.EventLoopWindowTarget.html).
