### ISSUE TITLE
Noob Question on Menus etc

### ISSUE THREAD

**Issue by andymans** [rust-windowing/winit#427]
First - winit looks excellent. I'd like to use it to deliver a desktop app; but I need to be able to:
a) add native Menu support to the application
b) have those menus localized based on the User's OS language settings

Is this something I can do in winit, or do I need to extend it in some way?

Thx.

**Comment by Osspial** [comment]
Winit currently doesn't have an explicit API for handling window menus. On Windows, you can use [the `CreateMenu` and `SetMenu` APIs on `HWND`s](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646977(v=vs.85).aspx), and on Mac you can use [application menus](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/MenuList/Articles/HowMenusWork.html). You can get the data you need to handle those with the [platform-specific `os` modules](https://docs.rs/winit/0.11.3/winit/os/index.html).

I have no idea how you'd handle menus on Linux, as I *think* that's handled by non-native widget APIs like GTK+ or Qt. There may be some way to set window menus that doesn't rely on a specific API, but I'm not all that familiar with Linux desktop development.

**Comment by pearzl** [comment]
hi，I want to add  menus for a window. But I can't get `HWND` from the an  `window`, because it's not `pub`. so Is there some method to access the `HWND` ?
thanks

**Comment by Osspial** [comment]
Closing this, since we've decided that this is out of scope for Winit.

**Comment by timtom-dev** [comment]
> Winit currently doesn't have an explicit API for handling window menus. On Windows, you can use [the `CreateMenu` and `SetMenu` APIs on `HWND`s](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646977(v=vs.85).aspx), and on Mac you can use [application menus](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/MenuList/Articles/HowMenusWork.html). You can get the data you need to handle those with the [platform-specific `os` modules](https://docs.rs/winit/0.11.3/winit/os/index.html).

Hey @Osspial Sorry if I'm misunderstanding something, I'm not yet familiar with the Cocoa API. I'm also trying to create a menu, and it looks like I need a reference to an `NSApplication` object, but I don't see a winit function that exposes one from the macOS module. Do you have an example I could look at?

**Comment by maroider** [comment]
If it's not exposed in the `platform::macos` module, then it's not exposed anywhere at all.
I've gone ahead and opened #1855 so that manipulating the menu bar actually becomes possible.
