### ISSUE TITLE
Native Widget Handling

### ISSUE THREAD

**Issue by Osspial** [rust-windowing/winit#446]
There are several OS-specific widgets that are extremely useful when creating desktop applications, which could be provided in some platform-agnostic way. This issue isn't demanding that they be implemented by winit directly, but there should be some official way to create them, either in winit itself or some associated downstream crate. How should we handle this?

Widgets that could be provided:
* File save/open dialogs
* Confirmation dialogs (e.g. *Do you want to save before closing* dialogs)
* Menu bars
* Right-click menus
* Taskbar/Dock menus (the right-click menu when you click on a window's taskbar icon)

#403 #427

**Comment by francesca64** [comment]
I think this is something that should definitely be handled by a separate crate. I'd put these under the broader classification of *GUI primitives*, which is outside of winit's scope. That's not to mention that X11 requires us to draw all of these ourselves, making it quite an undertaking (especially if we want them to look native).

As for the specifics of how to handle this, the best approach is just to start making such a library so we can get a better understanding of the problem. We'll then know what it makes sense for winit to expose (in X11's case, it's probably just a `WindowBuilderExt` method for setting hints).

If you'd be interested in trying to tackle this together, I should have time to work on it after the `Closed` API change is finished.
