### ISSUE TITLE
windows - support for other messages

### ISSUE THREAD

**Issue by chrde** [rust-windowing/winit#450]
It seems that messages not handled in the event_loop  e.g: `WM_NOTIFY` go to the default handler. Is there a way to provide a callback to handle such cases?

**Comment by francesca64** [comment]
There's not presently any API for that. The simplest change would be to allow you to provide a fall-through callback, but that would mean that any time a new event handler were added to winit, it would be a breaking change. What sort of API would you like for this?

**Comment by chrde** [comment]
what if the new callback has precedence over the existing loop? It could return a `Handled/Not handled`, and in the second case, just run the existing wnd_proc. This way we prevent future breaking changes because of `winit` handling new events

**Comment by Osspial** [comment]
This behavior should be supported by the [Window Subclassing API](https://docs.microsoft.com/en-us/windows/desktop/Controls/subclassing-overview#subclassing_v6). As such, I don't think we need to add an equivalent API into Winit.
