### ISSUE TITLE
Added support for fullscreen options and proper fullscreen behaviors in macos

### ISSUE THREAD

**Issue by edwin0cheng** [rust-windowing/winit#473]
This is  a tracking issue for improvements of PR https://github.com/tomaka/winit/pull/465 :

- Currently disregards whatever monitor is passed for setting fullscreen, always using whichever monitor has the keyboard focus. `enterFullScreenMode` should work for this, but it appears to be absent from core-foundation.
- Similarly, get_current_monitor always returns the currently focused monitor, rather than the monitor the window is on. `CGGetDisplaysWithRect` could be used to find the monitor that the majority of the window is on. But it is absent from core-foundation too. 
- We should let user to control the FullScreen Options by expose it in `WindowBuilderExt`. 

Here is the related PR for in core-foundation:

- [x] PR for CGGetDisplaysWithRect https://github.com/servo/core-foundation-rs/pull/207
- [x] PR for Fullscreen options: https://github.com/servo/core-foundation-rs/pull/204
- [x] PR for enterFullScreenMode related: https://github.com/servo/core-foundation-rs/pull/208

And related discussion: https://github.com/tomaka/winit/issues/460#issuecomment-382212377

**Comment by francesca64** [comment]
Is anything else blocking this? If you don't have time at the moment, I'd be happy to implement this.

**Comment by francesca64** [comment]
I've only addressed `get_current_monitor`. #521 

`enterFullScreenMode` works pretty differently from `toggleFullScreen`. It pops our view out into a "private" fullscreen window, which not only means our window delegate's `windowDidEnterFullScreen`/etc. isn't triggered, but we also don't get events at all. If you fullscreen to a different screen than the window is on, then the window remains visible where it was in addition to having the fullscreen view.

Getting that to work correctly seems like it will be involved, so I'm not presently up to pursuing this further.

**Comment by edwin0cheng** [comment]
Thanks for your help !!

- The main problem is, i found that i do not have another screen to let me implement/test these features.   Have to wait until i come back home next month. 😅

- Actuallly i did not know how `enterFullScreenMode` works, but would it involve [willUseFullScreenPresentationOptions:](https://developer.apple.com/documentation/appkit/nswindowdelegate/1419144-window?language=objc)? If so, we can set the bookkeeping data there too. On the other hand, if using `enterFullScreenMode` is that complicated, do we have any other way to do it ? The goal here is choosing which monitor to go to fullscreen. Although google-fu failed to find any information about it, would it possible to move the NSWindow to another screen first, and call `toggleFullScreen` ?

**Comment by francesca64** [comment]
You can supply the same options to `enterFullScreenMode` (and more). It should work fine to just move the window and `toggleFullScreen`, and it's at least better than nothing.

Optimistically, `enterFullScreenMode` isn't that complicated to work with, and I'm just not very familiar with Cocoa yet. It does have some advantages, i.e. it fullscreens without the transition animation.

**Comment by madsmtm** [comment]
It seems like this issue has been long fixed, please reopen if that's not the case
