### ISSUE TITLE
Don't panic on failure to create the EventsLoop

### ISSUE THREAD

**Issue by elinorbgr** [rust-windowing/winit#500]
On Linux, the creation of EventsLoop panics if neither Wayland nor X11 could be initialized. Most of the time this is okay, but for some apps (eg [smithay](https://github.com/smithay/smithay)), it would be desirable to gracefully handle a failure to initialize winit.

Would it be acceptable to either:

- make EventsLoop::new() return a `Result` (breaking change) ? (not sure if it makes sense for non-linux platforms)
- add a platform-specific API for Linux, trying to create an EventsLoop and returning a `Result` ?

**Comment by francesca64** [comment]
> not sure if it makes sense for non-linux platforms

macOS and Windows don't look like they really have much in the way of opportunities for failure. At the same time, even on Linux most people would just call `expect` on that `Result` (and the docs would probably suggest as much), so it wouldn't be an ergonomic issue, and it would be good to have the added flexibility (along with consistency with `Window::new`).

What do you have in mind? `Result<EventsLoop, CreationError>`?

**Comment by vberger** [comment]
Something like that would do, yes. Unless maybe a better error enum can be designed for this?

**Comment by francesca64** [comment]
While I think our current reliance on `String` errors looks bad in terms of idiomatic Rust, I'm also not sure what we'd gain with a proper error enum. Internal errors from winit are generally exceptional and impossible for consumers to do anything about in their own code. Though, my main reason is honestly that designing and maintaining a stable API for that sounds like a hassle.

...I'm also noticing that `CreationError::NotSupported` has a "TODO: remove this" above it, so we could probably flatten the whole thing.

**Comment by Osspial** [comment]
We could probably just use [`std::io::Error`](https://doc.rust-lang.org/std/io/struct.Error.html), since that seems to be the standard way of handling OS errors in the standard library.
