### ISSUE TITLE
Add keep above/keep on top option

### ISSUE THREAD

**Issue by PlasmaPower** [rust-windowing/winit#522]
GTK has this feature, and it'd be very useful for overlays and such.

Moved from https://github.com/tomaka/glutin/issues/873

**Comment by francesca64** [comment]
The relevant hint is `_NET_WM_STATE_ABOVE`. I'm planning on adding more extensive hint support for X11 todayish, so I'll include that.

**Comment by francesca64** [comment]
...wait, I never asked you what platforms you wanted. This should probably be multiplat.

**Comment by francesca64** [comment]
Implemented on Windows, macOS, and X11: https://github.com/francesca64/winit/tree/always-on-top
