### ISSUE TITLE
Implement `Touch` events for OSX

### ISSUE THREAD

**Issue by tomaka** [rust-windowing/winit#54]
Original: https://github.com/tomaka/glutin/issues/592

**Comment by chances** [comment]
Has any progress been made on this front? If not, I'd be happy to contribute an initial draft. And to try to integrate other [gesture primitives](https://github.com/servo/cocoa-rs/blob/5b9a27e4cb1f8ec805da424cc0cdae7ff475fc8f/src/appkit.rs#L1966), too.

**Comment by adamnemecek** [comment]
What's the situation with this? I'm considering adding this functionality.

**Comment by goddessfreya** [comment]
You would have to ask @vbogaevsky.

**Comment by madsmtm** [comment]
I think the closest we're going to get to supporting touch events is https://github.com/rust-windowing/winit/pull/2157, which adds support for trackpad gestures.

At least, as far as I know, Apple doesn't (yet) support touch displays to any further extent than just simulating a cursor (the best alternative I know would be to use an iPad as an external display, called Sidecar, but that uses the trackpad gestures as well, it doesn't have true multi touch support).
