### ISSUE TITLE
Platform-specific default dimensions are unreachable

### ISSUE THREAD

**Issue by stblr** [rust-windowing/winit#569]
These platform-specific default dimensions are unreachable
https://github.com/tomaka/winit/blob/1b74822cfc0cb7fba4ed4940a3faae9499fcda95/src/platform/linux/x11/window.rs#L85-L87
https://github.com/tomaka/winit/blob/1b74822cfc0cb7fba4ed4940a3faae9499fcda95/src/platform/linux/wayland/window.rs#L27-L29
https://github.com/tomaka/winit/blob/1b74822cfc0cb7fba4ed4940a3faae9499fcda95/src/platform/windows/window.rs#L855-L857
https://github.com/tomaka/winit/blob/1b74822cfc0cb7fba4ed4940a3faae9499fcda95/src/platform/macos/window.rs#L758-L760
because `dimensions` is always  `Some`.
https://github.com/tomaka/winit/blob/1b74822cfc0cb7fba4ed4940a3faae9499fcda95/src/window.rs#L147-L155

**Comment by francesca64** [comment]
This doesn't seem like such a bad problem? The platform-specific values don't really have any special meaning, so it's probably better to be uniform.

@vberger I'm surprised I let that Wayland code pass review... what's up with 64x64?

**Comment by vberger** [comment]
Hmm, looks like something I've set up for testing and forgot about, this should definitely not have been merged.

**Comment by madsmtm** [comment]
The default window size was removed in https://github.com/rust-windowing/winit/pull/1013, so I'll close this.
