### ISSUE TITLE
XRandR extension not available

### ISSUE THREAD

**Issue by kvark** [rust-windowing/winit#576]
We are updating (https://github.com/gfx-rs/gfx/pull/2159) from 0.13 and 0.15 and seeing this error:
> thread 'main' panicked at '[winit] XRandR extension not available.', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.15.1/src/platform/linux/x11/monitor.rs:243:17

https://travis-ci.org/gfx-rs/gfx/jobs/394055523#L1175

**Comment by francesca64** [comment]
I'm guessing XRandR is absent from your Travis environment? Previously, not having that extension would only cause panics when calling monitor-related methods, but now we subscribe to display change/hotplug events upon `EventsLoop` creation.

**Comment by kvark** [comment]
@francesca64 that makes sense, thanks for the quick answer!
We do install "libxrandr-dev" here: https://github.com/gfx-rs/gfx/blob/eb8ba499f31317870bda8ce40d2790922e7a53e3/.travis.yml#L68

Is there anything extra we need to do?

**Comment by francesca64** [comment]
I'd assume that only installs the client library (which is why it doesn't panic when trying to load the `.so`), but doesn't give you the Xorg server extension.

**Comment by kvark** [comment]
Any idea how we should fix that? Maybe an example travis script to follow?

**Comment by francesca64** [comment]
No, I have no experience with using CI for headless testing. I'm also out of the house today, so I can't dig any deeper.

**Comment by Osspial** [comment]
@kvark was a solution ever found for this? If so, I'd like to close this.

**Comment by kvark** [comment]
I don't have the context of the problem in my head any more. Will re-open if hit this again.
