### ISSUE TITLE
Support keypress events with non-ascii chars

### ISSUE THREAD

**Issue by tomaka** [rust-windowing/winit#59]
Original: https://github.com/tomaka/glutin/issues/625

**Comment by francesca64** [comment]
I'm not really sure what's wanted here. The use case of the person who made the issue originally seems to be best solved using scancodes.

**Comment by est31** [comment]
Scancodes are hardware dependent. You got no way of printing a name for the key or anything. If you shouldn't use keycodes, why do they exist in the first place?

**Comment by tomaka** [comment]
The "name of the key" is supposed to be the virtual key code which is reported alongside with the scancode in every event.

**Comment by Ralith** [comment]
It would be useful to support querying a human-readable key name from the OS for a given scancode. This would reduce the demand for ridiculously many virtual key codes, and be more convenient/correct for UI purposes besides.

**Comment by Osspial** [comment]
Closing in favor of #753 and #812
