### ISSUE TITLE
Create window with physical dimensions

### ISSUE THREAD

**Issue by spearman** [rust-windowing/winit#615]
With the change to LogicalSize there's no way to create a window with desired physical dimensions without checking DPI and resizing after it's created.

**Comment by Unmoving** [comment]
Is this what is causing my window to behave so strangely on my UHD screen? I always have to resize the window to get my conrod gui be resized accordingly, but ONLY on the uhd screen. The fhd is working just fine all the time :(

**Comment by francesca64** [comment]
Sorry I never addressed this! There's already some discussion on this here: https://github.com/tomaka/winit/issues/591#issuecomment-403113701

**Comment by jojolepro** [comment]
Here's a small piece of code I just wrote for amethyst which does just that. 
```rs
let hidpi = self.events.get_primary_monitor().get_hidpi_factor();

if let Some(dimensions) = self.config.dimensions {
    wb = wb.with_dimensions(LogicalSize::from_physical(dimensions, hidpi));
}
```
get_primary_monitor() returns MonitorId.
wb is winit's WindowBuilder.

**Comment by Osspial** [comment]
Closing in favor of #837
