### ISSUE TITLE
Enable/Disable screensaver toggle

### ISSUE THREAD

**Issue by rukai** [rust-windowing/winit#616]
I need a method on the window to disable/enable the screensaver.
When the window is closed the screensaver should be automatically reset to its previous state.
From memory resetting the screensaver state is normally handled by the os screensaver toggling api which takes a handle to the window and automatically resets when the window is closed closed.

I am somewhat familiar with the dolphin implementation of this https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/UICommon/UICommon.cpp#L365 and am happy to implement it for winit some time (windows + linux only), although I wont be free to do so in a long while, so I thought I'd post here in case anyone wanted to pick this up.

**Comment by Osspial** [comment]
Is there any reason this can't be implemented outside of Winit? My gut feeling is to close this as *out of scope*.

**Comment by n1ght-hunter** [comment]
this should be closed as out of scope.
https://github.com/rust-windowing/winit/pull/695#issuecomment-437620383

**Comment by madsmtm** [comment]
Indeed, this is out of scope of Winit, and just from [a quick search](https://lib.rs/search?q=awake) I found the [`keepawake`](https://docs.rs/keepawake/) crate, which seems to do exactly what you need?

(If for some reason parts of this cannot be cleanly implemented outside of Winit, then feel free to ask, we're open to adding extension points to allow doing so).

**Comment by kchibisov** [comment]
It's not, see https://github.com/rust-windowing/winit/issues/3351 the reasoning is for apps to indicate that they show something that doesn't require user input, like media players.

**Comment by kchibisov** [comment]
Anyway, I'll keep the more recent issue opened since it lists all the APIs which should be used to handle that.
