### ISSUE TITLE
crash on suspend/resume on laptop

### ISSUE THREAD

**Issue by chutz** [rust-windowing/winit#705]
Found via https://github.com/jwilm/alacritty/ occurs in the example program as well, when I suspend and resume my laptop, winit based programs crash with the following message:
```
thread 'main' panicked at '[winit] Failed to find any monitors using XRandR.', libcore/option.rs:989:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by vberger** [comment]
Given the error message, this can only have been generated at either of these two places:

https://github.com/tomaka/winit/blob/2f7321a07628f24f26b7c368e9b4be20b3ff4dfc/src/platform/linux/x11/monitor.rs#L107-L111

or

https://github.com/tomaka/winit/blob/2f7321a07628f24f26b7c368e9b4be20b3ff4dfc/src/platform/linux/x11/monitor.rs#L220-L225

which means that `self.get_available_monitors()` has either returned an empty list or that the list did not contain a monitor marked primary.

A proper backtrace with debug symbols would indeed help.

**Comment by francesca64** [comment]
> or that the list did not contain a monitor marked primary.

I should've included a comment in `get_primary_monitor` explaining this, but if no monitors are reported as primary, we always mark the first one:
https://github.com/tomaka/winit/blob/8dcd5143935cedcefeef5f08e17d5b076dcfbfbf/src/platform/linux/x11/monitor.rs#L191-L197

So this can only be the result of the monitor list being empty. Since winit is aware of any changes to what monitors are connected (something added in recent versions), it's likely that resuming has us receive a state update before the hardware is available again, resulting in an empty list.

**Comment by chutz** [comment]
That sounds like a pretty reasonable theory, often the GPUs take longer to come back than the CPU, so it is pretty probable that the monitor list could be empty for a period of time while the GPU is brought back up.

I am at a conference at the moment, so rebuilding with debug symbols is a little difficult. I am happy to test patches etc though if you have a theoretical fix.

**Comment by francesca64** [comment]
I unfortunately can't reproduce this on my desktop.

> so rebuilding with debug symbols is a little difficult

I doubt debug symbols would help anyway, so no worries.

The most straightforward fix would be to make the monitor check more lenient, i.e. not to panic until the monitor data would actually need to be accessed. I do have some concerns over the correctness of doing that, but at the same time, I doubt the protocol gives us any real way to deal with this problem.

**Comment by jonpas** [comment]
Can also consistently reproduce on switching monitors around with xrandr (or mons wrapper). Switching from extended (2 monitors side-by-side) to one of them works fine. Switching from one to extended causes panic.

**Comment by haarp** [comment]
For me suffices to close my laptop's lid to make all Alacritty windwows suicide. I'd be fine if the process blocks until monitor data is available again.

**Comment by chrisduerr** [comment]
It looks like this issue can be reproduced on Wayland (though with a different error):
https://github.com/jwilm/alacritty/issues/2156

It might be good to create a separate issue though, since they affect separate platforms and might be caused by different issues?

**Comment by Osspial** [comment]
@murarth Would you able to tackle this? It looks like the cause for this is fairly simple (see https://github.com/rust-windowing/winit/issues/1007#issuecomment-508813712), so it shouldn't be too difficult to fix.

**Comment by Osspial** [comment]
Can someone test to see if #1158 fixes this?
