### ISSUE TITLE
Enable `Less` and `Greater` Keys on X11

### ISSUE THREAD

**Issue by tomaka** [rust-windowing/winit#71]
Original: https://github.com/tomaka/glutin/issues/775

**Comment by francesca64** [comment]
This would be trivial to implement, but since `Less` and `Greater` aren't members of `VirtualKeyCode`, it's really a question of API design.

How extensive is `VirtualKeyCode` supposed to be?

**Comment by tomaka** [comment]
@francesca64 `VirtualKeyCode` was initially just a list of keyboard keys provided by Microsoft Windows and was slightly tweaked over time. It didn't get any real deep thought.

**Comment by Osspial** [comment]
Closing in favor of #753 and #812
