### ISSUE TITLE
Window example stops responding after short keyboard input

### ISSUE THREAD

**Issue by pault-t-canva** [rust-windowing/winit#714]
I originally opened https://github.com/jwilm/alacritty/issues/1803 to alacritty, but it was shown that this is most likely a winit issue. 

### Environment
Mac OS 10.13.6
Running on a built in display. 15.4 inch (2880 x 1800)

### Reproduction steps:

* `cargo run --example window > out.log`
* Once window is focused. Type `asdfasdf`
  * A weird point here. If i type slowly, everything is okay. If i type fewer characters it's fine. It seems to start failing once a certain amount of keyboard inputs are received in a small amount of time.
* Then the log shows the `ReceivedCharacter` even looping over and over even though i've stopped providing any input.

Attached is the log 
[out.log](https://github.com/tomaka/winit/files/2593211/out.log)

**Comment by pault-t-canva** [comment]
This appears to not be an issue on Mojave. Specifically 10.14.2

**Comment by andradei** [comment]
It seems to be an issue on Catalina 10.15.2

**Comment by madsmtm** [comment]
Our event handling internals has changed a lot in the past three years, especially relating to keyboard input, so I'm going to close this as "hoping fixed".

I know, not really satisfying, but there's just too little information here for me to do much more. If you find that the issue still persists, please do say so / reopen, your input is valued, _especially_ with weird issues like these!
