### ISSUE TITLE
HiDPI not fully supported on Android

### ISSUE THREAD

**Issue by Osspial** [rust-windowing/winit#721]
On Android, `get_hidpi_factor` currently always returns `1.0`. According to @francesca64 this is blocked on tomaka/android-rs-glue#116.

**Comment by francesca64** [comment]
This looks like the right way to get the DPI: https://stackoverflow.com/a/3166582/5435443

AFAIK, we don't have access to that or any other Java API. I'd really like to see progress on tomaka/android-rs-glue#116 (or alternatives), but I don't really have the time to do something like that in the near future.
