### ISSUE TITLE
Wayland: Blurry cursor when using HiDPI scaling

### ISSUE THREAD

**Issue by trobjo** [rust-windowing/winit#727]
Perhaps this should be added to the "Wayland metabug" report?

Anyway, I use HiDPI scaling on Linux+Wayland+Sway, and alacritty's cursor it blurry. It has the correct size though, and the rest of the window (i.e. text rendering) is sharp enough. 

It doesn't happen, when I turn scaling off. 

I know QT apps had the same bug until version 5.12, so I'm quite certain it's a bug in winit. 

The fix in QT can be found  here: https://codereview.qt-project.org/#/c/225465/

**Comment by vberger** [comment]
This is actually an issue with SCTK, but it'll likely require some work in winit too.

blocked on https://github.com/Smithay/client-toolkit/issues/47

**Comment by illiliti** [comment]
https://github.com/Smithay/client-toolkit/commit/d61c5517ff23b97d802927f7630452d4cff6a808

**Comment by goddessfreya** [comment]
Is this still a issue?

**Comment by illiliti** [comment]
> Is this still a issue?

I can reproduce this on sway 1.4, alacritty 0.4.1

**Comment by kchibisov** [comment]
@goddessfreya this is an issue and I'm working on it right now. During more extensive testing with winit I've found out a very strange bug with HiDPI cursors. So I'm investigating right now.

So it'll likely be blocked until https://github.com/Smithay/client-toolkit/pull/97 will be answered and new 0.6.x release will arrive.

**Comment by vberger** [comment]
> [Smithay/client-toolkit@d61c551](https://github.com/Smithay/client-toolkit/commit/d61c5517ff23b97d802927f7630452d4cff6a808)

Note that this commit is only on SCTK `0.7.0`, which significantly changed the API of the lib. Winit will need some work to be updated to this new version. I'll probably do it at some point when I get the time to unless someones attacks it before me.
