### ISSUE TITLE
Improving Scan Code and General Keyboard Layout Handling

### ISSUE THREAD

**Issue by Osspial** [rust-windowing/winit#732]
Right now, we don't provide any way to convert `ScanCode`s to or from `VirtualKeyCode`s. Providing that is useful for storing layout-independent keymaps, but displaying the actual key to the user in a GUI.

What's more, because we're (usually) reporting the raw scan code provided by the OS there seems to be some inconsistency what key corresponds to what on different platforms. From my testing on Windows and Linux the letter/punctuation keys, number keys, function keys, and escape, space, shift, enter, tab, backspace, and caps keys are all identical across both platforms, but various other keys (such as arrow keys) weren't consistent. That makes it impossible to use scan codes to portably store keyboard layouts.

**Comment by Imberflur** [comment]
https://github.com/rust-windowing/winit/issues/2678 seems related
