### ISSUE TITLE
Possible input lag on Linux?

### ISSUE THREAD

**Issue by newpavlov** [rust-windowing/winit#733]
In this [application](https://github.com/SkoltechRobotics/cam-vis) I get a noticeable input lag when moving image using mouse (if you don't have video cam, you can use `dummy` branch), in other words try to drag image corner and you will notice that rectangle lags behind mouse cursor.

Lag may originate on `vulkano` side,  but it's unlikely, since app can give hundreds of FPS on Intel integrated card. Moving `events_loop.poll_events(..)` does not help. The lag was reported on both X11 and Wayland.

UPD: I've wrote a [simpler app](https://github.com/newpavlov/lag-test) which does not require a camera and computationally simpler.

**Comment by rukai** [comment]
Vulkano is kind of weird, I wouldn't be too surprised if it was its fault. Does the same issue occur with glium?

**Comment by mitchmindtree** [comment]
I personally haven't noticed any input lag on Linux, can you post more info about the specifics of your system? (Distro, linux version, desktop).

> Lag may originate on vulkano side, but it's unlikely, since app can give hundreds of FPS on Intel integrated card.

The FPS is not necessariliy related to input lag. Are you sure that you're not queuing to many images at once? The reason I suggest this is that the vulkan spec in general does not guarantee whether or not acquiring the next image from the swapchain will block - it may differ between hardware implementations. I think I remember reading that this has caused some users an issue where on some systems latency slowly increases over  time as the buffer of images for presentation slowly increases over time. I could be way off though, and I'm not sure if this is the case for all presentat modes. What present mode is this issue happening with? Can you try a different one and see if the issue persists?

Similarly it might be worth checking that, if you use some sort of queue to submit your graphics, you're not inserting into it faster than you're pulling from it.

**Comment by newpavlov** [comment]
>Does the same issue occur with glium?

I don't have an analogous application written with glium, so I can't check. Do you know any suitable applications?

>can you post more info about the specifics of your system

It's a laptop with i7-6500U CPU, Debian Unstable and Gnome on Wayland. As I've wrote earlier I am using integrated GPU right now. Input lag is noticeable for me in both FIFO and mailbox presentation modes. (immediate and relaxed modes are not supported in my case)

>The FPS is not necessariliy related to input lag.

Yes, I understand. I've mentioned it to show that application is relatively simple.

I will try to check it with different setups to see if problem persists.

**Comment by icefoxen** [comment]
I was working from the opener's repo, this commit: https://github.com/SkoltechRobotics/cam-vis/commit/582efb1ec33d66ec715489ed0c78e6fae55c4dcb

Like I said, it's hard to come up with a better measurement besides "it feels wrong".  I'll see if I can come up with something.

**Comment by newpavlov** [comment]
I've wrote a [simpler app](https://github.com/newpavlov/lag-test) for testing input lag. It has a simple crosshair which follows mouse pointer. Ideally crosshair and mouse pointer should be always aligned, but in reality I get the following result:
![screen](https://user-images.githubusercontent.com/329626/50299974-0f4ebc80-0494-11e9-8e76-47eacb2e289e.png)

**Comment by mitchmindtree** [comment]
@newpavlov ahh thanks for linking this.

Yes when using the default FIFO mode I also notice a bit of lag, however using both immediate and mailbox modes (via e.g. `cargo run --release -- -m mailbox`) I don't see any lag at all. I guess this is kind of expected as FIFO is a queue of `min_image_count` pending images, while in mailbox mode the most "recently presented" image is always selected and immediate doesn't have any wait for vsync at all.

**Comment by newpavlov** [comment]
I was getting lag even with the immediate mode on integrated Intel GPU + Wayland, when I've retested the application on a discrete GPU + X11, immediate mode produced a significantly smaller (although noticeable if you look carefully) lag.

I guess this issue can be closed, as it looks like the lag can be mostly attributed to the graphical part of the application.

**Comment by icefoxen** [comment]
Thanks for the test app, @newpavlov !  Like mitchmindtree, in mailbox and immediate mode I see no lag at all, while in FIFO mode it's small but definitely present.  Again, Intel integrated graphics, Linux on X11.

**Comment by spearman** [comment]
> Thanks for the test app, @newpavlov ! Like mitchmindtree, in mailbox and immediate mode I see no lag at all, while in FIFO mode it's small but definitely present. Again, Intel integrated graphics, Linux on X11.

What is immediate mode? I have a glium application and when I implemented a software cursor I found that it lags behind the hardware cursor by 2 frames or so. Hardware cursor starts moving on frame 1, by frame 2 the software cursor has not seen the update, and finally by frame 3 the software cursor is now where the hardware cursor was on frame 1.

**Comment by kchibisov** [comment]
Immediate mode is basically tearing and such. Not available anywhere for example.

**Comment by kchibisov** [comment]
The real world benchmarks showed that there's no such issue.
