### ISSUE TITLE
set_cursor doesn't work after show() and on Focused

### ISSUE THREAD

**Issue by paulrouget** [rust-windowing/winit#735]
`set_cursor` is not working if called immediately after `window.show()` or if called on `Focused` event.

**Comment by paulrouget** [comment]
At least on Mac. Also possibly on Wayland: https://github.com/jwilm/alacritty/issues/1750

**Comment by vberger** [comment]
Cursor setting on wayland is simply not implemented yet, so this is not linked to the Mac issue.

**Comment by francesca64** [comment]
Does this problem still exist on #740?

**Comment by Osspial** [comment]
@paulrouget Checking back in on this. Is this still an issue?

**Comment by paulrouget** [comment]
Appears to work now.
