### ISSUE TITLE
Linux X11: Slow window creation

### ISSUE THREAD

**Issue by kimsnj** [rust-windowing/winit#751]
I am experiencing a very slow window creation on a linux laptop.
I used following snippet to test it:
``` rust
extern crate winit;

fn main() {
    let events_loop = winit::EventsLoop::new();

    let _window = winit::WindowBuilder::new()
        .with_title("A fantastic window!")
        .build(&events_loop)
        .unwrap();
}
```

And as a result of `time`:
```
> time target/release/examples/open

real	0m2.269s
user	0m0.005s
sys	0m0.005s
```

My laptop is running Ubuntu Gnome 16.04 with X11.
It has an Intel i7-4810MQ and is using the integrated GPU.

I created a flamegraph [here](https://gist.github.com/kimsnj/caea6dffd56ff2b3665f9380faf3fa2e) (doesn't seem to be possible to include directly the svg as attachement).

Any clue on where the issue might come from / how to dig deeper ?
Thanks in advance for your help.

**Comment by francesca64** [comment]
Thanks for reporting this!

Before looking into this more, 2 things:
1. What version of winit are you using?
2. Could you try generating the flamegraph from a debug build? I assume there'd be more symbol names that way.

**Comment by kimsnj** [comment]
I reported the issue after cloning from `master` directly.
I since bisected git history to see if previous versions had the same issue. 
It appears that the slowdown was introduced between v0.15.1 and v0.16.1 and more specifically by commit [DPI for everyone](https://github.com/tomaka/winit/commit/1b74822cfc0cb7fba4ed4940a3faae9499fcda95)

Time before: 40ms
Time after: 2s
I'v added flamegraphs before / after in this [gist](https://gist.github.com/kimsnj/caea6dffd56ff2b3665f9380faf3fa2e)

**Comment by chrisduerr** [comment]
Possible duplicate of https://github.com/tomaka/winit/issues/682?

**Comment by kimsnj** [comment]
The issue occurs for me even with a single monitor.
But looking at the latest comment from @ti-mo in above issue. I tried:

```
> time xrandr > /dev/null

real	0m1.956s
user	0m0.000s
sys	0m0.004s
```

So I guess it does share the same root cause.

**Comment by ZeGentzy** [comment]
@kimsnj The flame graph doesn't list fn names for a lot of things...

Can I get `valgrind --tool=callgrind --dump-instr=yes --collect-jumps=yes --simulate-cache=yes` instead?

**Comment by Osspial** [comment]
Now that #801's been merged, is this still an issue?

**Comment by kimsnj** [comment]
Hi,

I don't have access anymore to my previous work laptop that demonstrated the behavior.
On the current one (and with the latest version), running `alacritty -e false` takes ~100ms.

So I guess this issue can be closed as I cannot provide more leads as to what happened on the other setup.
