### ISSUE TITLE
xrandr reports width_mm is zero bug

### ISSUE THREAD

**Issue by dannyfritz** [rust-windowing/winit#769]
I'm pretty sure this is a bug: https://github.com/tomaka/winit/blob/3c59283b3fbf409353413c0c0d7d39ae85287e60/src/platform/linux/x11/util/randr.rs#L26

But I'm unsure if the answer is `width_px` or `height_mm`. So that is why this is an issue and not a PR. Easy fix regardless. :)

**Comment by Osspial** [comment]
Hey, thanks for reporting this! Sorry it took so long to get back on it.

You'd want to change that to `height_mm`. You're right that that's a fairly simple fix, though.

**Comment by ZeGentzy** [comment]
Needs to be fixed on evlpv2 branch :/

**Comment by ZeGentzy** [comment]
Fix monitor width & height sanity check #861
