### ISSUE TITLE
how to ignore backsapce key event on input method?

### ISSUE THREAD

**Issue by coderhwz** [rust-windowing/winit#773]
According to this issue  https://github.com/jwilm/alacritty/issues/1606, I try look into Alacritty source code,and I found out that Alacritty accpet KeyboardInput directly. I want to know how to ignore backspace KeyboardInput event on input method OR how to recognize the event has been caputure by  input method ? thanks

**Comment by xieyunzi** [comment]
I think the step is:

1. get current input source
1. if input source is some input method, ignore input key event
1. loop above step

step 1 is os depended

**Comment by lvht** [comment]
@coderhwz is there any progress for this issue?

**Comment by Osspial** [comment]
I've got a WIP branch (on Windows, at least) for dispatching all the keyboard and IME events in a single event struct, which should allow this. IME support hasn't been completed on that, though.

**Comment by kchibisov** [comment]
This was resolved with IME input a year ago or so. When using IME the keyboard events are not sent to the application.
