### ISSUE TITLE
Could Wayland support be optional?

### ISSUE THREAD

**Issue by neonmoe** [rust-windowing/winit#774]
Could the Wayland part of winit be made into its own feature? I'm asking this because it bothers me that the Wayland parts make up a considerable part of the dependencies of this crate, yet it's so wip that I currently manually force x11 in all my projects which use winit. I'm ready to contribute myself as well, I'd just like to hear if this is in any way feasible.

**Comment by vberger** [comment]
I personally think it would make sense to have both `x11` and `wayland` be cargo features (both enabled by default). Apps that are only sensible in a wayland-only or x11-only context (because they use platform specific logic) but still want to use winit for the convenience it provides would be users of such flags.

Though, as I understand your initial concern is not that. What do you mean that "wayland support is so wip" exactly? A lot of progress has been done in the recent releases.

**Comment by neonmoe** [comment]
It seems the last time I tested, I was on an old version of winit! Very sorry about that, it seems that the problems I was having (resizing and the window decorations being weird) have indeed been fixed.

That said, I think that splitting x11 and wayland into features would indeed be a good idea, for the reasons provided, and because I find joy in minimizing dependencies, being able to have different builds for x11 and wayland instead of bundling them up in one sounds very good.

**Comment by vberger** [comment]
This would be pretty easy to implement overall, it's mainly a matter of scattering a few `#[cfg(...)]` in the right places. I suggest adding the two cargo features `platform_x11` and `platform_wayland`, which would be in the default feature set, and would only have an effect when compiling for unix platforms.

**Comment by neonmoe** [comment]
I had a go at this today, and I have a working version of the `platform_x11` feature now working (ie. it can be disabled and nothing breaks, except for a few warnings I didn't clean up yet).

However, I would like some guidance on a few points:
1. It seems that target-specific features are somewhat WIP (https://github.com/rust-lang/cargo/issues/1197), so afaik, it isn't possible to make a specific target's dependencies optional, and then enable them as default features for that target. Of course, it's still possible to just make the `platform_x11` and `platform_wayland` features, and just leave the dependencies in. Removing the then-useless dependencies based on features should probably have it's own issue after this one is resolved, which would have to wait until Cargo is capable of this.
2. Glutin is very coupled to winit in this area, so it needs similar features. Those features should always be enabled in sync with winit (if winit has `platform_x11` enabled and glutin doesn't, glutin doesn't compile), and I'm not sure how that should be done. Just documentation (if so, where?), or is there a way to tell this to Cargo?
3. On Glutin again, is these some kind of synchronization between winit and glutin I should be aware of, when making the PRs?
4. Currently, I've gated off quite a bit of functionality with the cfgs, including modifying public API, such as WindowBuilderExtUnix. Should the features be this invasive, or should those functions just be no-ops, or something else? It could be hard to gate off functionality gracefully, as functions might have types provided by the optional dependencies in their signatures.

Here's the commits for my current progress on [winit](https://github.com/neonmoe/winit/commit/81797cbf14a0c469794da837355a4eb4036b40c1) and [glutin](https://github.com/neonmoe/glutin/commit/ef2eb03f964c1a3936c87886834c24ccc0272d47).

**Comment by Evrey** [comment]
To keep the discussion fresh:

I, too, would like Wayland support to be optional. I'm building an application using Vulkan (`ash`) for rendering. Something Wayland has no support for. So in effect `winit` currently pulls in a huge amount of — for me — useless dependencies, blowing up initial compile times, etc. Am initialising the event loop with a special `cfg!(unix)` and `new_x11()`.

I like the `platform_wayland`/`platform_x11` feature flag duality.

@neonmoe Quite a promising set of changes you made.

**Comment by vberger** [comment]
> I'm building an application using Vulkan (`ash`) for rendering. Something Wayland has no support for.

Independently of the question of cargo features, nothing is blocking the use of Vulkan on Wayland. See for example that [vulkano supports it](https://github.com/vulkano-rs/vulkano/blob/dc73b1f4697838ed6447e8e21af347c95ccc72a0/vulkano/src/swapchain/surface.rs#L251-L259).

**Comment by Evrey** [comment]
@vberger Huh, 'tseems my info on that is quite out of date. Thanks!
