### ISSUE TITLE
Build fails with stable-i686-apple-darwin

### ISSUE THREAD

**Issue by tomaka** [rust-windowing/winit#78]
Original: https://github.com/tomaka/glutin/issues/803

**Comment by Osspial** [comment]
@ryanisaacg pinging you since I know you can test on macOS - is this still an issue? If not, I'll close it, but I'm preparing a list of issues for new contributors and I don't know if this should go in it.

**Comment by ryanisaacg** [comment]
I think my Mac is 64 bit? I'm not sure how to build for 32 bit, and I think 32 bit Apple platforms are very much legacy.

**Comment by Osspial** [comment]
I think you can build for 32-bit by installing the `stable-i686-apple-darwin` target with rustup. If they're super legacy though, I'd be fine with just closing this - looking into this further, this may be a downstream issue anyway.

**Comment by ryanisaacg** [comment]
iOS no longer permits 32 bit applications, and the current macOS version puts a warning modal before any 32 bit application. Apple has no published timeline for when 32 bit apps will be entirely disallowed but it's my understanding it's in the pretty near future. I think closing this is pretty safe.
