### ISSUE TITLE
Use XIMPreeditPosition if sending xim spot

### ISSUE THREAD

**Issue by pickfire** [rust-windowing/winit#788]
When setting xim spot with `set_spot`, `XIMPreeditPosition` should be used instead of `XIMPreeditNothing` in https://github.com/tomaka/winit/blob/c91dfdd6fe8763811f72d6a8a268d10d29b3dc77/src/platform/linux/x11/ime/context.rs#L65-L72.

I got that from http://csweb.cs.wfu.edu/~torgerse/Kokua/Irix_6.5.21_doc_cd/usr/share/Insight/library/SGI_bookshelves/SGI_Developer/books/XLib_PG/sgi_html/ch11.html and https://dev-files.blender.org/file/data/obyhbxfvb5tw6sh6ztfk/PHID-FILE-ufb42ktbze7hiyhj6sac/D1570.id8908.diff.

**Comment by kchibisov** [comment]
I think this is sort of resolved.
