### ISSUE TITLE
OpenBSD: Need to bump wayland-client and smithay-client-toolkit version numbers

### ISSUE THREAD

**Issue by rennis250** [rust-windowing/winit#825]
Hello,

I found out today that winit no longer builds on OpenBSD, since it uses an older version of wayland-client (v0.21) and an older version of smithay-client-toolkit (v0.4.3) that both depend on an older nix crate (v0.12) that does not compile on OpenBSD. Bumping wayland-client to v0.23.1 and smithay-client-toolkit to v0.6.0 fixes this issue for me.

Thanks,
Rob

**Comment by rennis250** [comment]
Sorry! I spoke too soon. wayland-client v0.23.1 does not build. I'm determining a solution...

**Comment by rennis250** [comment]
Ok, the problem goes deeper than that. Nix needs to be v0.13 everywhere (including in the wayland-rs crates), but the newest wayland-client (v0.23.1) also tries to use a nix feature that is not available on OpenBSD (it tries to check for an EPROTO errno). My temporary fix is to use an older glium version (0.20) that still compiles. Will open an issue at wayland-rs.

**Comment by rennis250** [comment]
Issue opened: https://github.com/Smithay/wayland-rs/issues/259

**Comment by Osspial** [comment]
Work has been done to upgrade the Wayland dependencies to the newest versions, but the changes are currently sitting on the [eventloop-2.0](https://github.com/tomaka/winit/tree/eventloop-2.0) branch while we get the macOS and X11 backends ready for the [corresponding API rework](https://github.com/tomaka/winit/issues/459). Work is ongoing on for X11, but the person who's been managing macOS's backend hasn't been able to work on it. I've been talking with her about it though, and hopefully we should be able to get someone else to finish said backend up and finally get that branch onto master, which would allow us to push the Wayland dependency updates to crates.io.

**Comment by rennis250** [comment]
Ok, no rush. Just wanted to notify. Things are working fine for now with a slightly older version of glutin.

**Comment by vberger** [comment]
FYI wayland-client-0.21.12 has been released including the update to nix 0.13, and it does not attempt to use EPROTO in winit.

**Comment by rennis250** [comment]
Ok, thanks. Actually, I was wrong about the whole EPROTO thing and need to correct the misinformation I spread. It turns out EPROTO and other new errnos have been available in OpenBSD since 6.2. Nix master was recently upgraded to account for that: https://github.com/nix-rust/nix/pull/1036

**Comment by Azyrael** [comment]
Just wanted to check if the upcoming update fixes wayland entirely? because it builds for me, but when i create a window it does not show up, somehow? creation succeeds, but the window does not show up on the screen. the os shows a window existing (as in an icon in the taskbar shows up), but it does not display anything and the event loop is not triggered in any way. all functions accessing the window after creation return option::none, so the window is immediately destroyed after creation, apparently.

**Comment by vberger** [comment]
> all functions accessing the window after creation return option::none

Which functions are your referring to exactly?

The Wayland platform has a particularity that a window will not show up (or exist at all really) until its contents has been drawn at least once. Meaning a winit-only code is not enough to display a window, given winit does not provide any drawing facility.
