### ISSUE TITLE
CI is borked

### ISSUE THREAD

**Issue by ZeGentzy** [rust-windowing/winit#844]
Hey @Osspial, the CI is borked for both glutin and winit since we changed to `rust-windowing`. I've sent an authorization request for travis-ci and appveyor. Please accept it.

**Comment by Osspial** [comment]
Thanks for letting me know! I've granted them both organization access.

**Comment by ZeGentzy** [comment]
Appveyor is still non functional, at least for glutin. Don't know why

**Comment by Osspial** [comment]
Looks like I needed to create new Appveyor projects for Winit and Glutin for the auto-build to work. Should be functional now, though!
