### ISSUE TITLE
List of related projects

### ISSUE THREAD

**Issue by felixrabe** [rust-windowing/winit#846]
I've skimmed [FEATURES.md](https://github.com/rust-windowing/winit/blob/master/FEATURES.md) and thought about making a list of features (and projects) outside the scope of winit – features that newcomers to winit might expect to be provided by winit itself, and/or projects that are a natural fit to use together with winit.

Some that come to mind:

-   Use winit with OpenGL – **glutin** ([GitHub](https://github.com/rust-windowing/glutin)・[crates.io](https://crates.io/crates/glutin)・[lib.rs](https://lib.rs/crates/glutin)).
-   Use winit with Vulkan – **vulkano-win** ([GitHub](https://github.com/vulkano-rs/vulkano/tree/master/vulkano-win)・[crates.io](https://crates.io/crates/vulkano-win)・[lib.rs](https://lib.rs/crates/vulkano-win)・[website](https://vulkano.rs/)) and **gfx-backend-vulkan** ([GitHub](https://github.com/gfx-rs/gfx/tree/master/src/backend/vulkan)・[GitHub (gfx-rs)](https://github.com/gfx-rs/gfx)・[crates.io](https://crates.io/crates/gfx-backend-vulkan)・[lib.rs](https://lib.rs/crates/gfx-backend-vulkan)・[blog](https://gfx-rs.github.io/)).
-   Platform-native file dialogs – **tinyfiledialogs** ([GitHub](https://github.com/jdm/tinyfiledialogs-rs)・[crates.io](https://crates.io/crates/tinyfiledialogs)・[lib.rs](https://lib.rs/crates/tinyfiledialogs)).
-   Features omitted from winit 1.0 that might make candidates for inclusion in later releases, e.g. system tray / notification area / notifications – ??? (something like a winit-contrib or winit-extras crate - or there might already exist crates for that).

I think a good place to put such a list might be a Wiki page on GitHub. This might also serve as a list of suggestions to the community of what pieces of the Rust GUI story are still missing.

Other lists related Rust GUI programming:

-   Crates in category "GUI" on [crates.io](https://crates.io/categories/gui) and [lib.rs](https://lib.rs/gui).
-   Crates using keyword "GUI" on [crates.io](https://crates.io/keywords/gui) and [lib.rs](https://lib.rs/keywords/gui).
-   https://github.com/rust-unofficial/awesome-rust/blob/master/README.md#gui.
-   https://areweguiyet.com/ – does not list winit and glutin yet.
-   https://rust-lang-nursery.github.io/rust-cookbook/  – has no GUI programming section yet.

**Comment by jdm** [comment]
For platform-native file dialogs, https://github.com/jdm/tinyfiledialogs-rs/ is one option.

**Comment by felixrabe** [comment]
Yes, I think that was the one.

**Comment by vberger** [comment]
For vulkan, there are [vulkano-win](https://crates.io/crates/vulkano-win) and [gfx-backend-vulkan](https://github.com/gfx-rs/gfx/tree/master/src/backend/vulkan)

**Comment by ZeGentzy** [comment]
Both have winit support:
https://github.com/PistonDevelopers/conrod
https://github.com/Gekkio/imgui-rs

**Comment by Osspial** [comment]
I've enabled the wiki for this project - go nuts! A PR linking that page on the root page of Winit's documentation would be really helpful too, once the page is in place.

**Comment by felixrabe** [comment]
I'm on it, should have a cleaned up wiki version of this by tomorrow.

**Comment by felixrabe** [comment]
https://github.com/rust-windowing/winit/wiki/Missing-features-provided-by-other-crates

**Comment by felixrabe** [comment]
Updated https://github.com/rust-windowing/winit/wiki/Missing-features-provided-by-other-crates. Working on #854 now.
