### ISSUE TITLE
List of applications built with winit

### ISSUE THREAD

**Issue by felixrabe** [rust-windowing/winit#849]
Similar to #846 ([wiki](https://github.com/rust-windowing/winit/wiki/Missing-features-provided-by-other-crates)), I find it useful to somewhere have a list of applications built with winit, as https://crates.io/crates/winit/reverse_dependencies does not list them (as it probably makes no sense to publish them on crates.io in the first place).

Some I know of:

-   Alacritty (via glutin – [GitHub](https://github.com/jwilm/alacritty))
-   Servo (via glutin – [GitHub](https://github.com/servo/servo), see [/ports/servo/Cargo.toml](https://github.com/servo/servo/blob/master/ports/servo/Cargo.toml))

**Comment by mitchmindtree** [comment]
My company [MindBuffer](https://mindbuffer.net) has been using it for all of our creative commercial projects over the past couple years including:

- [Spatial Audio Server](https://www.mindbuffer.net/#/spatial-audio-server/) ([open source](https://github.com/museumsvictoria/spatial_audio_server)).
- [JEN](https://www.mindbuffer.net/#/jen/) - generative music engine (closed source).

We recently finished a multi-screen projection installation and a magic mirror installation, both using winit alongside vulkano via nannou - we're currently just waiting on Museums Victoria's legal team to sign off on the open source license before we can publish them. We're also just finishing off some laser control software that uses winit that we'll likely open source under a copy-left license in the next week or two.

**Comment by felixrabe** [comment]
Nice example of such a list: https://github.com/ocornut/imgui/wiki/Software-using-dear-imgui

**Comment by felixrabe** [comment]
It might make sense to re-use the style of the ["missing features" wiki page](https://github.com/rust-windowing/winit/wiki/Missing-features-provided-by-other-crates).

**Comment by felixrabe** [comment]
@mitchmindtree What is the license of https://github.com/museumsvictoria/spatial_audio_server? (Added issue about this: museumsvictoria/spatial_audio_server#187.)

**Comment by felixrabe** [comment]
https://github.com/rust-windowing/winit/wiki/Software-that-uses-winit

Feel free to add / update stuff :)
