### ISSUE TITLE
Tracking issue: Sizing(&mut PhysicalSize) event

### ISSUE THREAD

**Issue by Osspial** [rust-windowing/winit#850]
As discussed in https://github.com/rust-windowing/winit/pull/695#issuecomment-450692378. This will address #584 and allow window resize increments (useful for text editors).

Any PR that implements this should expose the client area's size, not the external window size.

**Comment by vberger** [comment]
Might be worth thinking if / how it should fit with the optional suggested size of the `HiDPIFactorChanged` event I suggested in https://github.com/rust-windowing/winit/issues/837#issuecomment-485924649 maybe?

**Comment by ZeGentzy** [comment]
@Osspial Is this still relevant?

**Comment by Osspial** [comment]
@ZeGentzy Yeah, this was the original version of #949. I'd rather use this issue, since it's more specific about the sort of design we're looking for.

**Comment by LoganDark** [comment]
Any progress / news on this? It's been over a year, and this would be very useful. Right now you can only set the resize increment once and only on specific platforms.

**Comment by madsmtm** [comment]
Since https://github.com/rust-windowing/winit/pull/2411 we now have `Window::set_resize_increments`, and it works with the client area's size.

While that doesn't fully address the original suggestion (having a callback on resize that the user can then respond to), I think it should solve the primary use-case? If not, feel free to reopen.

**Comment by LoganDark** [comment]
@madsmtm Does winit already fill the other use cases for a resize callback, such as aspect ratio constraints?

**Comment by madsmtm** [comment]
I don't think so, but perhaps that use-case (aspect ratio constraints) is more appropriately tracked in https://github.com/rust-windowing/winit/issues/584?
