### ISSUE TITLE
Request for slightly better event overview documentation

### ISSUE THREAD

**Issue by AlterionX** [rust-windowing/winit#855]
The current docs leave something to be desired in differentiating the many different types of `Event`s in the system.

There are two primary inputs (`DeviceEvent` and `WindowEvent`) but the there's no higher level documentation to differentiate the two. If you go into the docs and read each individual class's documentation it becomes rather obvious, but it's confusing at first, so I think it should get (at least briefly) mentioned when explaining the event loop.

Additionally, it's slightly confusing that certain events are duplicated, as this phrase: "Once a window has been created, it will generate events. For example whenever the user moves the window, resizes the window, moves the mouse, etc. an event is generated." makes it seem like there is one and exactly one event being created where there are, in fact, multiple.

I ended up writing an abstraction for the entire input loop to filter out events like these, but it was a bit frustrating working with the thing before I got used to it.

**Comment by alasher** [comment]
@AlterionX Check out my pull request and see if it's close to what you were thinking. I'm new to the project so feel free to clarify anything that may be misleading or incorrect. Thanks!

**Comment by AlterionX** [comment]
@alasher Someone else got there before I did! But what they said is what I'm thinking as well.

A mouse movement or keyboard press is also duplicated through the `WindowEvent` interface through this: https://docs.rs/winit/0.20.0-alpha1/winit/event/enum.WindowEvent.html#variant.KeyboardInput or other variants of `WindowEvent`.

**Comment by AlterionX** [comment]
Merged with #976
