### ISSUE TITLE
EventLoop 2.0 hitting unreachable code during resize on Windows

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#867]
When resizing a window on Windows, the following `unreachable!()` statement is hit:
https://github.com/rust-windowing/winit/blob/eventloop-2.0/src/platform_impl/windows/event_loop.rs#L412

This causes the program to immediately panic without any chance for recovery.

This was tested using the `run_return` event loop method. It was suggested to me that it would freeze and act like `run` during resize on Windows, but apparently there are some more severe issues?

**Comment by Osspial** [comment]
If all's working properly, it *should* freeze. Looks like this should be fairly simple to fix, though - I'll get a PR up soon.

**Comment by Osspial** [comment]
If all's working properly, it *should* freeze. Looks like this should be fairly simple to fix, though - I'll get a PR up soon.
