### ISSUE TITLE
Support for WASI

### ISSUE THREAD

**Issue by skyne98** [rust-windowing/winit#869]
Hey there, everyone!

I have seen some discussion here related to support of WebAssembly through `wasm32-unknown-unknown` target. @tomaka has mentioned, that we cannot make assumptions about the environment, which was true.

However, now we have a `wasm32-wasi` target for both rustc and clang. Is it possible to create a working backend for winit to run as a wasi webassembly binary?

Thanks!

**Comment by vberger** [comment]
Is there some possibility of unification with the works of https://github.com/rust-windowing/winit/pull/845 and https://github.com/rust-windowing/winit/pull/797 ?

**Comment by skyne98** [comment]
@vberger, I guess it will make sense. However, as far as I understand, WASI version of Winit should work more or less the same way the Linux one does, except for some minor limitations (no locks, no threads)?

**Comment by vberger** [comment]
I was just trying to bring up things that might or might now be relevant. I know pretty much nothing about WASI.

Does WASI exposes its own system windowing API, or would a WASI client have to connect to a regular x11 / wayland socket? In the latter case, does that mean that the system libraries (libwayland / libx11 / mesa / ...) would need to be compiled to the `wasm32-wasi` target as well?

**Comment by skyne98** [comment]
It is definitely the latter. Also, yes, it means the all of those libraries will have to be compiled to this target as well.

**Comment by vberger** [comment]
In that case, Wayland support would be pretty easy to get (thanks to the pure-rust implementation in wayland-rs), but I cannot speak at all for the other platforms, nor about opengl / vulkan.

It'd be great to have some idea of what the general plans are for windowing / opengl / vulkan with WASI in general, unrelatedly of winit.

**Comment by skyne98** [comment]
In the end it should still come down to making system calls, right? In that case, it's just a matter of extending the set of supported system calls to encompass required functionality.

**Comment by vberger** [comment]
What I mean is: winit supporting this is dependent on the required system libs being ported to WASI. This is not a small feat, and winit cannot really do anything until it is done.

**Comment by skyne98** [comment]
But I think that, in theory, this can be done in a more gradual manner. Maybe starting with Wayland, because of already existing wayland-rs? This way we should be able to get some way of GUI up and running while learning on its experiences to extend the functionality.

**Comment by vberger** [comment]
Yes, absolutely. I guess the first step would then to get [wayland-rs](https://github.com/Smithay/wayland-rs) and then [SCTK](https://github.com/Smithay/client-toolkit) to compile to `wasm32-wasi`.

**Comment by skyne98** [comment]
@vberger, I guess that it won't yet be possible without proper IPC support, right?

**Comment by vberger** [comment]
Oh good point, the wayland protocol requires being able to send and receive file descriptors though an unix socket.
