### ISSUE TITLE
eventloop-2.0 branch breaks compiling for emscripten target

### ISSUE THREAD

**Issue by iceiix** [rust-windowing/winit#874]
`cargo build --target wasm32-unknown-emscripten` works on the `master` branch (compiles, although it fails at runtime for other reasons: https://github.com/rust-windowing/winit/issues/760 https://github.com/rust-windowing/winit/pull/767) but fails on the `eventloop-2.0` branch:

**snip**

Would ultimately like to use the wasm32-unknown-unknown backend once/if it is supported by https://github.com/rust-windowing/winit/issues/395 https://github.com/rust-windowing/winit/pull/845, I had a temporary workaround in https://github.com/iceiix/winit/pull/2 to compile (but not run) for wasm32-unknown-unknown by reusing the emscripten backend, attempted to port to eventloop-2.0 in https://github.com/iceiix/winit/pull/3 but found it was failing to build even without my changes.

**Comment by ZeGentzy** [comment]
If your going to post a error log that long, paste bin it please. I've snipped it out.

The emscripten backend has yet to be ported to evlpv2.

**Comment by iceiix** [comment]
Full error log: https://gist.github.com/iceiix/9819a9d148b5aeaec72babfdf123dbf4

**Comment by ryanisaacg** [comment]
Emscripten support has been dropped in favor of wasm, which is now out on master.
