### ISSUE TITLE
Support listing available video modes for a monitor

### ISSUE THREAD

**Issue by ZeGentzy** [rust-windowing/winit#877]
https://github.com/rust-windowing/glutin/issues/742

Should be trivial to implement.

**Comment by JamesHinshelwood** [comment]
Seems like this is implemented in `0.20.0`, [`video_modes`](https://docs.rs/winit/0.20.0-alpha1/winit/monitor/struct.MonitorHandle.html)

**Comment by Osspial** [comment]
Looks like it. #896 was tagged as closing this so I'm not entirely sure why this hasn't been closed already.
