### ISSUE TITLE
Fails to build on DragonFly

### ISSUE THREAD

**Issue by jbeich** [rust-windowing/winit#878]
Probably similar to #815. I don't have DragonFly VM to confirm. CC @t6
```rust
src/platform/linux/x11/mod.rs:241:33
    |
241 |                 let errno_ptr = __errno_location();
    |                                 ^^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to previous error
```
http://muscles.dragonflybsd.org/synth/logs/x11___alacritty.log

**Comment by t6** [comment]
AFAICT DragonFly does not have an `__errno_location()` or similar function and the only way to get at it is via something like what https://github.com/mneumann/errno-dragonfly-rs does.

**Comment by murarth** [comment]
`__errno_location` no longer appears anywhere in `winit`, so I believe this issue can be closed.

**Comment by ZeGentzy** [comment]
I think this got fixed cause openbsd had a similar problem or something. Whoooooo!
