### ISSUE TITLE
Is ControlFlow supposed to be sticky? (eventloop-2.0)

### ISSUE THREAD

**Issue by aloucks** [rust-windowing/winit#891]
Based on the doc comment, I would believe that it is intended to be sticky. However, the x11 and wayland implementations are resetting it per loop iteration. It doesn't look like Windows is doing this.

https://github.com/rust-windowing/winit/blob/0df436901a4835b47c1daf58a5260b839cf9dd6a/src/event_loop.rs#L65-L69

https://github.com/rust-windowing/winit/blob/0df436901a4835b47c1daf58a5260b839cf9dd6a/src/platform_impl/linux/x11/mod.rs#L283-L286

https://github.com/rust-windowing/winit/blob/0df436901a4835b47c1daf58a5260b839cf9dd6a/src/platform_impl/linux/x11/mod.rs#L289-L291

https://github.com/rust-windowing/winit/blob/0df436901a4835b47c1daf58a5260b839cf9dd6a/src/platform_impl/linux/x11/mod.rs#L301-L306

**Comment by Osspial** [comment]
It is indeed intended to be sticky.

**Comment by vberger** [comment]
Ah, ok. I assumed it was only supposed to be sticky during a run of the event loop, rather than forever.

**Comment by aloucks** [comment]
> I assumed it was only supposed to be sticky during a run of the event loop, rather than forever.

Yes, that's how I understand it; Control flow is sticky for the duration of `run_return` and reset in between calls to that. The current implementation resets the control flow on each tick of the loop.

This part is correct:

https://github.com/rust-windowing/winit/blob/0df436901a4835b47c1daf58a5260b839cf9dd6a/src/platform_impl/linux/x11/mod.rs#L226-L229

**Comment by vberger** [comment]
Well, the fix is simple enough, I just don't have the time to work on it for now.
