### ISSUE TITLE
Add support for set_always_on_top for Wayland

### ISSUE THREAD

**Issue by newpavlov** [rust-windowing/winit#899]
Right now `set_always_on_top` does [nothing](https://github.com/rust-windowing/winit/blob/8d6e8bb8d1bc49da251fe16a16ac1b3cb1636717/src/platform_impl/linux/mod.rs#L343) on Wayland.  IIUC according to this Gnome [issue](https://bugzilla.gnome.org/show_bug.cgi?id=710056) it should be possible to implement. (though it may be DE dependent)

**Comment by vberger** [comment]
Hmm, according to the gtk+ git history, the "always-on-top" was actually never really implemented, and I cannot find the current Gnome API to implement it. So it seems to me that it still cannot be implemented.

**Comment by newpavlov** [comment]
Hm, I wonder how in this case XWayland handles it... I use Gnome on Wayland and "always on top" works without any issues.

**Comment by vberger** [comment]
XWayland has a special relation with the Wayland compositor, and is not just a regular Wayland client. In particular it does not goes through the Wayland protocol to do window management.

**Comment by newpavlov** [comment]
[Here](https://www.reddit.com/r/gnome/comments/c3godh/does_wayland_support_always_on_top_functionality/) they write that Nautilus on Wayland does not use XWayland and it supports "always on top" functionality without issues. Though we still don't know how exactly this is done.

**Comment by kchibisov** [comment]
Always on top is not supported and there's no way to do that on Wayland.

The reason why you can do 'always on top' via right click on CSD under GNOME is because you can request compositor to show menu with various actions. And on GNOME this menu contains 'Always on top' as well as other things.

So this issue will track adding those on right click on CSD.

**Comment by kchibisov** [comment]
Actually, I'll open a new one to track this thing, so users will know that always on top is not supported by design on Wayland at least now.
