### ISSUE TITLE
Update to Rust 2018 Edition

### ISSUE THREAD

**Issue by Osspial** [rust-windowing/winit#912]
See #612, but in issue form.

**Comment by crlf0710** [comment]
One thing that previously mentioned but not yet done is migrating to 2018 module structure.

Tried to do the migration locally and filed https://github.com/rust-lang/rust/issues/61924 .

**Comment by felixrabe** [comment]
^ The issue created by @crlf0710 was marked as a duplicate of rust-lang/rust#59345.

**Comment by murarth** [comment]
Closed by #924
