### ISSUE TITLE
On Windows, Window size is set incorrectly on HiDPI displays

### ISSUE THREAD

**Issue by Osspial** [rust-windowing/winit#923]
On Windows 10, this can be replicated by setting the scaling ratio greater than 100% in Display settings and running the following example:

```rust
extern crate winit;
use winit::window::WindowBuilder;
use winit::event::{Event, WindowEvent};
use winit::event_loop::{EventLoop, ControlFlow};

fn main() {
    let event_loop = EventLoop::new();

    let window = WindowBuilder::new()
        .with_title("A fantastic window!")
        .with_inner_size(winit::dpi::LogicalSize::new(128.0, 128.0))
        .build(&event_loop)
        .unwrap();
    println!("{:?}", window.inner_size());

    event_loop.run(|event, _, control_flow| {
        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => *control_flow = ControlFlow::Exit,
            _ => *control_flow = ControlFlow::Wait,
        }
    });
}
```

With 150% scaling, the window gets created with a size of `LogicalSize { width: 124.0, height: 116.66666666666667 }`, instead of the expected `LogicalSize { width: 128.0, height: 128.0 }`.

**Comment by Osspial** [comment]
This happens because, in order to create a window with a specified inner size on Windows, you must calculate the window's outer size (that is, the size of the window including decorations) and pass *that* size along to the window sizing functions. Unfortunately, we aren't quite doing this correctly: we're using the [`AdjustWindowRectEx`](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-adjustwindowrectex) function instead of [`AdjustWindowRectExForDpi`](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-adjustwindowrectexfordpi), which properly accounts for the screen's scale factor.

Fixing this should be a matter of doing some additional DPI tracking internally and calling the correct function.

**Comment by SuperiorJT** [comment]
I'm looking into this task and wasn't able to duplicate this behavior on my machine. Maybe I'm doing something incorrectly, but setting my dpi to 150% gives me the expected output of `LogicalSize { width: 128.0, height: 128.0 }`. One thing I noticed in my testing the logical size would change when dragging the window to another monitor that has a different dpi. Is this intended? It kinda makes makes sense to me since we are using the RECT that Windows gives us on the dpi change event. I just wanted to make sure.

**Comment by Osspial** [comment]
@SuperiorJT Hmm, that's odd - I just ran that example to double-check, and it repros on my machine. If it only happens on some configurations, I guess it makes sense for me to go ahead and fix it myself, since I can easily reproduce it.

Also, the `LogicalSize` changing shouldn't happen, and I believe is caused by this issue.
