### ISSUE TITLE
Incorrect HighDPI setting on Mac.

### ISSUE THREAD

**Issue by mooman219** [rust-windowing/winit#927]
Relevant [Apple docs](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/EnablingOpenGLforHighResolution/EnablingOpenGLforHighResolution.html#//apple_ref/doc/uid/TP40001987-CH1001-SW4)

It looks like `setWantsBestResolutionOpenGLSurface` is not being set to true on mac. This results in the program being provided a 1-pixel-per-point framebuffer regardless of the backing scale factor for the display the view occupies. This means that glViewport is implicitly called for you, and calling it yourself will almost certainly result in an incorrect famebuffer size. To match how DPI scaling works on other systems (Windows and Linux), `setWantsBestResolutionOpenGLSurface` should be set to true on Mac. This forces the view to perform the correct conversions between view units (points) and pixel units as needed.

This is probably a breaking change.

**Comment by ZeGentzy** [comment]
Related: #821

**Comment by madsmtm** [comment]
Closing, I believe @goddessfreya answered this, and https://github.com/rust-windowing/winit/pull/1073 even added a switch for changing this behaviour.

Feel free to reopen if you're still having problems with this, @mooman219.
