### ISSUE TITLE
Invisible window takes focus from existing window

### ISSUE THREAD

**Issue by chichid** [rust-windowing/winit#936]
Consider this code, where I'm creating an invisible window, after a visible window. Should the first window appear disabled (the second window takes focus from it)? 

``
let el = winit::EventsLoop::new();
let win = winit::WindowBuilder::new().with_visibility(true).build(&el).unwrap();
let win = winit::WindowBuilder::new().with_visibility(false).build(&el).unwrap();    
``

I tried this on Windows 10, and it results in a disabled window. I would expect an invisible window not to take focus from any other windows.

**Comment by Osspial** [comment]
Hi, and thanks for the bug report!

I can confirm that this is undesirable behavior. My best guess as to what's causing it is one of the direct or indirect calls to [`set_window_flags`](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/windows/window_state.rs#L116-L128) in the [this part of the window `init` function](https://github.com/rust-windowing/winit/blob/06244dd4929d1acf1f4650ecb38ca73c1ec22743/src/platform_impl/windows/window.rs#L722-L754). I'd be up for tackling this at some point, but this should also be a good first issue to investigate if anyone would be interested.

**Comment by chichid** [comment]
I'm interested, and already investigating it, I haven't done Win32 in ages though.

**Comment by chichid** [comment]
PR created
