### ISSUE TITLE
Unnecessary usage of thread-local storage on Windows

### ISSUE THREAD

**Issue by Osspial** [rust-windowing/winit#94]
Currently, the win32 window callback relies on thread-local storage to stash data for the callback function. This isn't necessary - by using the [win32 subclassing API](https://msdn.microsoft.com/en-us/library/windows/desktop/bb773183(v=vs.85).aspx), it is possible to pass a user-defined pointer into the window function with the `dwRefData` parameter in a subclass. By boxing up the callback data and freeing it when the window is destroyed, the use of the `thread_local` macro can be avoided.

**Comment by ZeGentzy** [comment]
Did this get solved or was it decided against? The commit that references this issue doesn't appear at a glance to solve it.

**Comment by Osspial** [comment]
This was fixed by the EventLoop 2.0 rework.
