### ISSUE TITLE
No mouse events when unfocused on macOS

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#942]
This has been reported to Alacritty in https://github.com/jwilm/alacritty/issues/2475.

It looks like winit does not report mouse movements inside the window if it is currently unfocused. This makes it difficult to track mouse click positions since the mouse can "teleport" into position without being able to track it.

If this is an intentional design decision, I think that there's no way around reporting mouse position on click events, since a click might come in without any previous motion events at all.

This could be resolved with https://github.com/rust-windowing/winit/issues/883, but it might still make sense to report motions above the unfocused window, since I'm pretty sure other platforms do that?

**Comment by Osspial** [comment]
I'm pretty sure this is unintentional. Windows, at least, does indeed report mouse motion above unfocused windows.

**Comment by ZeGentzy** [comment]
And X11 reports everything, including keyboard events to other programs (RIP security).

**Comment by SergeevPavel** [comment]
What if I want to change something in my window after just mouse move? E.g. highlight item on hover. It will work on unfocused window on linux but will not on macos. So I think this issue need more general fix.

**Comment by chrisduerr** [comment]
I don't think there's any intention to report mouse reports on unfocused windows on all platforms.

In fact, some platforms like Wayland will do their best to prevent you from getting that information.

If you want the user to interact with the window in any way, it has to be focused.
