### ISSUE TITLE
Input method for wayland

### ISSUE THREAD

**Issue by quininer** [rust-windowing/winit#952]
The [text-input v3 protocol](https://github.com/wayland-project/wayland-protocols/commit/db152d7c6f53adb60db8dfc046604a487002d927) has been around for a while and is supported in [Gtk](https://gitlab.gnome.org/GNOME/gtk/merge_requests/272) and [wlroots](https://github.com/swaywm/wlroots/pull/1203), KDE also has an [patch](https://phabricator.kde.org/D16735).

**Comment by vberger** [comment]
This will depend on https://github.com/Smithay/client-toolkit/issues/43
