### ISSUE TITLE
Consider replacing `mpsc` with `crossbeam_channel`

### ISSUE THREAD

**Issue by felixrabe** [rust-windowing/winit#954]
`mpsc::Receiver::recv_timeout()` contains a bug: https://doc.rust-lang.org/nightly/std/sync/mpsc/struct.Receiver.html#method.recv_timeout

I'm not 100% sure about the relative stability of `mpsc` vs `crossbeam_channel`, but decided to prefer `crossbeam_channel` for my own code. The API is compatible: https://docs.rs/crossbeam-channel

Maybe someone else has more insight into this?

**Comment by felixrabe** [comment]
A quick `rg recv_timeout` on 8d6e8bb8d did not reveal any usage of that function.

**Comment by felixrabe** [comment]
See https://stjepang.github.io/2019/01/29/lock-free-rust-crossbeam-in-2019.html for a writeup from January 2019 on the history of `crossbeam` and `crossbeam-channel`. Some highlights:

> This year might be a good time to publish version 1.0 since I don’t expect API changes anymore.

> Servo switched from mpsc to crossbeam-channel, which removed a bunch of unsafe code and the dependence on the unstable mpsc_select feature. That was an important milestone because it proved crossbeam-channel is mature and reliable enough for such a big project.

**Comment by notgull** [comment]
Now that the `mpsc` implementation of `libstd` just uses `crossbeam`'s implementation, this issue has effectively been solved for us.
