### ISSUE TITLE
Forward porting from winit-legacy (tracking issue)

### ISSUE THREAD

**Issue by felixrabe** [rust-windowing/winit#961]
(Edit: Working on this in PR #966.)

I just looked at the Git history more closely and noticed that some (all?) of the changes on the [winit-legacy](https://github.com/rust-windowing/winit/tree/winit-legacy) branch have not been ported to EL2.

My [forward-porting](https://github.com/felixrabe/winit/tree/forward-porting) branch contains some of my commits that I've noticed are lacking on current (EL2) master. If I get to it, I might expand it to more forward-portable stuff.

**Comment by ZeGentzy** [comment]
Yeah, some changes probably slipped through the cracks. Open a PR with the cherrypicked changes, not a tracking issue. There's hardly anything to track: either it's merged, or it's not (which in that case, merge it).

**Comment by felixrabe** [comment]
Can we keep this open until the PR closes this issue?
