### ISSUE TITLE
Wrong XRandR check regarding 0mm display size

### ISSUE THREAD

**Issue by Abendstolz** [rust-windowing/winit#963]
In [x11/util/randr.rs ](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/linux/x11/util/randr.rs#L25) there is a bug as the check should read:

`if width_mm == 0 || height_mm == 0`

All credits go to https://github.com/rust-lang/rust-clippy

**Comment by ZeGentzy** [comment]
Duplicate: #769
