### ISSUE TITLE
Windows window without decoration not rendering properly

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#979]
This has been reported to Alacritty in https://github.com/jwilm/alacritty/issues/2564.

It seems like `with_decorations(false)` causes the rendering on Windows to break. In the glutin example, this results in a white window. If transparency is enabled, this will just lead to a completely transparent window.

**Comment by ZeGentzy** [comment]
dupe https://github.com/rust-windowing/winit/issues/851 ?

**Comment by chrisduerr** [comment]
This is indeed a dupe of #851 and has been fixed.
