### ISSUE TITLE
MacOS minimize support

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#983]
This has been reported to Alacritty in https://github.com/jwilm/alacritty/issues/2534.

Currently winit exposes an API on all platforms to set the window visibility using the `set_visible` method. If this is called on macOS, the window is hidden without adding it to the dock, this is working as intended.

However, on macOS a different method of hiding windows exists too, this is called `miniaturize` [in their docs](https://developer.apple.com/documentation/appkit/nswindow/1419426-miniaturize?language=objc)  which makes the window invisible and adds it to the dock. I believe this is what happens when the minimize button is clicked in the window decorations, but as far as I can tell there's no way to call this explicitly from winit.

The generated cocoa-rs bindings provide [this method](https://github.com/servo/cocoa-rs/blob/ea0667fdd2cffbdc442e50bbf6a2977ba7c2d322/src/appkit.rs#L1018) on `NsWindow`. So I think it should be relatively trivial to implement this using the [`WindowsExtMacOS`](https://github.com/rust-windowing/winit/blob/master/src/platform/macos.rs#L12), since I don't think it's available in this fashion on any other platform.

Alternatively, this could be declared as out of scope, so downstream consumers would have to use the [`ns_window`](https://github.com/rust-windowing/winit/blob/master/src/platform/macos.rs#L16) call instead to do this themselves.

**Comment by felixrabe** [comment]
I think that's perfectly in scope. I just looked at https://docs.rs/winit/0.20.0-alpha1/winit/window/struct.Window.html because I wondered whether this could not be handled by some platform-independent `set_minimized` method. Turns out, there isn't one.

**Comment by felixrabe** [comment]
Related: #783 (Minimizing window on Windows causes WindowEvent::Resized(size=0) event)

**Comment by felixrabe** [comment]
Opened #985 (Add `Window::set_minimized` method) about the missing method.

**Comment by kchibisov** [comment]
I guess this bug should be closed now.
