### ISSUE TITLE
Test cases for platforms

### ISSUE THREAD

**Issue by arthrp** [rust-windowing/winit#986]
In the [request for help](https://users.rust-lang.org/t/winit-0-20-the-state-of-windowing-in-rust-and-a-request-for-help/29485) it was mentioned that some platforms are basically not tested at all. I'd be interested to help - with testing and possibly some code contributions.
 Thus, a question - is there any test set defined for the platforms (especially those in need of testers - like webassembly)? If not, maybe defining some basic test set will help with current situation?

**Comment by ZeGentzy** [comment]
Currently, you add yourself to this list then we ping you when we got changes that need testing: https://github.com/rust-windowing/winit/wiki/Testers-and-Contributors

Alas, their is not exactly a set list of things for people to test. There was some discussion somewhere about writing an interactive test suit, but no ones gotten around to it.

**Comment by ZeGentzy** [comment]
https://github.com/rust-windowing/winit/issues/251

**Comment by daxpedda** [comment]
Closing in favor of #2866.
