### ISSUE TITLE
Redraw Requested not issued for glutin examples (winit examples too?) until at least one other event has been issued.

### ISSUE THREAD

**Issue by goddessfreya** [rust-windowing/winit#987]
The glutin examples for some reason don't draw until you've moved the mouse or pressed a key at least once. I suspect this is a winit bug. Found while testing out #925 .

**Comment by felixrabe** [comment]
This is probably related to an issue I see in EL 2.0 on macOS (legacy examples work fine in that regard):

Returning `ControlFlow::Exit` seems to only work after another event has been received. (I.e.: I press the window's close button - nothing happens - I move the mouse slightly - window closes.)

**Comment by murarth** [comment]
Is this running on winit master? Because it sounds like the kind of bug I expected from #982, but didn't show up for me in testing.

**Comment by ZeGentzy** [comment]
Yes, was done against master.

**Comment by felixrabe** [comment]
@ZeGentzy On what platform(s)?

If Linux/X11, did #982 cause this (i.e. commit 29e2481) or is the issue also visible with the commit before (3555de1)?

**Comment by ZeGentzy** [comment]
Issue was present before #982, on x11. I'm afraid I lack time to git bisect this issue.

**Comment by sumit0190** [comment]
I only discovered this after setting `Poll` to `Wait` in my logic.

I thought manually calling `request_redraw` after catching it from an `EventsCleared` event would work, but turns out it doesn't (for `Wait`; `Poll` has been working correctly for me with that approach).

**Comment by Osspial** [comment]
Have any of the various bugfixes we've made in the past six months or so addressed this?

**Comment by kettle11** [comment]
I ran into this issue today when experimenting with Glutin examples.

**Comment by kchibisov** [comment]
I think this is fixed in some form.

Though, it'll be fixed once #2900 lands.
