### ISSUE TITLE
When event loop control flow is Poll, it doesn't receive CloseRequested event

### ISSUE THREAD

**Issue by VioletasTheThird** [rust-windowing/winit#995]
Hey, so I tried running the following code https://gist.github.com/ca2df08aa9adfe44dae2dd1568f27ac9. I decided to use `ControlFlow::Poll`, due to the fact that I would like to re-render on every frame (I know there isn't much right now, but eventually that would be needed I imagine). However, when I do have it as `Poll`, it doesn't receive `WindowEvent::CloseRequested` when i attempt to close the window. I do get the event if i set the control flow to `Wait`, however that doesn't have the desired outcome.

OS: Linux 5.1.10_1
Display Server: xorg
Window Manager: i3wm
(If you need any more info, ask me, I don't know exactly what to put)

Thank you in advance, and sorry if this is intended and I just couldn't find it in the docs.

**Comment by ZeGentzy** [comment]
Can you try this code against winit master? #982 might have fixed this.

**Comment by VioletasTheThird** [comment]
Ah yea, it seems to work on winit master. Should have probably tested with that in the first place, sorry!
